import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {test,expect,type Page} from '@playwright/test';
const fixture=JSON.parse(readFileSync('.ci-connected.json','utf8'));assert.equal(process.env.CI,'true');assert.equal(fixture.project,process.env.COMPOSE_PROJECT_NAME);assert.match(fixture.project,/^getlancer-ci-[0-9]+$/);
async function login(page:Page,actor:'builder'|'client'){const account=fixture.accounts['ci-'+actor+'@example.test'];await page.goto('/login');await page.getByLabel('Email address',{exact:true}).fill(account.email);await page.getByLabel('Password',{exact:true}).fill(account.password);await page.getByRole('button',{name:'Log in',exact:true}).click();await expect(page).toHaveURL(/\/workspace$/);}
const call=(page:Page,path:string,body?:unknown)=>page.request.fetch('/api/v1'+path,{method:body?'POST':'GET',data:body,headers:{Origin:'http://localhost:3000','X-Requested-With':'getlancer'}});
async function reflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width+1);}
test('connected care has real current-party consent, disabled merchant billing and no sample/provider fallback',async({page,browser},info)=>{
 const engagement=fixture.maintenance[info.project.name];const buyerContext=await browser.newContext({viewport:info.project.use.viewport,isMobile:info.project.use.isMobile,hasTouch:info.project.use.hasTouch,baseURL:'http://localhost:3000'}),buyer=await buyerContext.newPage(),network:string[]=[],errors:string[]=[];
 for(const p of [page,buyer]){p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(new URL(r.url()).hostname.endsWith('razorpay.com'))network.push(r.url());});}
 try{
  await login(page,'builder');await page.goto('/workspace/maintenance?engagementId='+engagement.id);await expect(page.getByRole('heading',{name:'Maintenance & support',exact:true})).toBeVisible();await expect(page.getByText('Sample data only',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Create support offer',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Completed engagement',{exact:true})).toBeFocused();await dialog.getByLabel('Care plan title',{exact:true}).fill('CI connected care '+info.project.name);await dialog.getByLabel('Included work',{exact:true}).fill('Bug fixes and small improvements for the delivered synthetic approval workflow.');await dialog.getByLabel('Terms & exclusions',{exact:true}).fill('Includes three requests each paid period. New features need a new agreement; future billing can be cancelled.');await dialog.getByLabel('Monthly price (INR)',{exact:true}).fill('1500.25');await dialog.getByRole('button',{name:'Create maintenance draft',exact:true}).click();await expect(dialog).not.toBeVisible();await page.getByRole('button',{name:'Review & send terms',exact:true}).click();await expect(dialog.getByRole('checkbox')).not.toBeChecked();await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Consent & send offer',exact:true}).click();await expect(dialog).not.toBeVisible();await reflow(page);
  await login(buyer,'client');await buyer.goto('/preview/maintenance');await expect(buyer).toHaveURL(/\/workspace\/maintenance$/);await buyer.goto('/workspace/maintenance?engagementId='+engagement.id);await buyer.getByRole('button',{name:'Review & accept terms',exact:true}).click();const terms=buyer.getByRole('dialog');await expect(terms.getByRole('checkbox')).not.toBeChecked();await terms.getByRole('checkbox').check();await terms.getByRole('button',{name:'Accept these terms',exact:true}).click();await expect(terms).not.toBeVisible();await expect(buyer.getByRole('button',{name:'Authorize recurring billing',exact:true})).toBeDisabled();await expect(buyer.getByText('Support unavailable',{exact:true})).toBeVisible();await expect(buyer.getByRole('button',{name:'New support request',exact:true})).toHaveCount(0);await expect(buyer.getByText('Maintenance billing is not enabled. Contact the workspace operator.',{exact:true})).toBeVisible();await buyer.getByRole('tab',{name:'Terms & consent',exact:true}).click();await expect(buyer.getByText('Not recorded',{exact:true})).toHaveCount(0);await reflow(buyer);await buyer.evaluate(()=>window.scrollTo(0,0));await buyer.screenshot({path:info.outputPath('connected-maintenance-consent.png'),fullPage:true});
  const offers=await (await call(page,'/maintenance?engagementId='+engagement.id)).json(),offer=offers.items[0];expect(offer.status).toBe('ACCEPTED');expect((await call(page,'/maintenance/'+offer.id+'/accept',{consent:true,digest:offer.digest})).status()).toBe(403);expect(network).toEqual([]);expect(errors).toEqual([]);
  // Revoked session must clear private dialog fields and must not announce successful save.
  await page.getByRole('button',{name:'Create support offer',exact:true}).click();await dialog.getByLabel('Care plan title',{exact:true}).fill('Private care text that must clear');await dialog.getByLabel('Included work',{exact:true}).fill('A private draft with enough detail to satisfy validation.');await dialog.getByLabel('Terms & exclusions',{exact:true}).fill('Private agreed monthly draft text should not stay visible after the owner session is revoked.');await dialog.getByLabel('Monthly price (INR)',{exact:true}).fill('50');expect((await call(page,'/auth/logout',{})).ok()).toBeTruthy();await dialog.getByRole('button',{name:'Create maintenance draft',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('heading',{name:'Sign in to your maintenance workspace',exact:true})).toBeVisible();await expect(page.getByLabel('Care plan title',{exact:true})).toHaveCount(0);await expect(page.getByText('Maintenance draft created. Review the terms before sending.',{exact:true})).toHaveCount(0);
 }finally{await buyerContext.close();}
});
