import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
const recipes=JSON.parse(readFileSync('backend/src/main/resources/catalog/components.json','utf8'));
async function reflow(page:import('@playwright/test').Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width+1);}
test('compact component discovery has real search, empty and honest backend states',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/components');await expect(page.getByRole('heading',{name:/Build your next/})).toBeVisible();await expect(page.locator('.kit-grid>.kit-card')).toHaveCount(6);await reflow(page);
 await page.getByLabel('Component category',{exact:true}).selectOption('AUTH');await page.getByRole('button',{name:'Search',exact:true}).click();await expect(page.locator('.kit-grid>.kit-card')).toHaveCount(1);await expect(page.getByRole('heading',{name:'Quiet sign-in',exact:true})).toBeVisible();await reflow(page);
 await page.getByLabel('Search components',{exact:true}).fill('none-that-exists');await page.getByRole('button',{name:'Search',exact:true}).click();await expect(page.getByRole('heading',{name:'No components found.',exact:true})).toBeVisible();
 await page.goto('/components?kind=BACKEND');await expect(page.getByText(/no live backend runtime is available yet/)).toBeVisible();expect(errors).toEqual([]);
});
test('all six curated previews run their actual controls inside an opaque sandbox',async({page})=>{
 const errors:string[]=[],upstream:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:3000')&&!r.url().startsWith('about:'))upstream.push(r.url());});
 for(const c of recipes){await page.goto('/components/'+c.slug);await expect(page.getByRole('heading',{name:c.title,exact:true})).toBeVisible();const iframe=page.locator('.kit-preview-stage iframe'),frame=page.frameLocator('.kit-preview-stage iframe');await expect(iframe).toHaveAttribute('sandbox','allow-scripts allow-forms');
  if(c.category==='NAVBAR'){await frame.getByRole('button',{name:'Menu +',exact:true}).click();await frame.getByRole('link',{name:'About',exact:true}).click();await expect(frame.locator('output')).toContainText('About selected');}
  if(c.category==='SIDEBAR'){await frame.getByRole('button',{name:'Projects',exact:true}).click();await expect(frame.getByRole('heading',{name:'Projects',exact:true})).toBeVisible();await frame.getByRole('button',{name:'Hide sidebar',exact:true}).click();await expect(frame.getByRole('button',{name:'Show sidebar',exact:true})).toHaveAttribute('aria-expanded','false');}
  if(c.category==='FORM'){await frame.getByLabel('Project name',{exact:true}).fill('Sample garden');await frame.getByLabel('What should it solve?',{exact:true}).fill('Coordinate the neighbourhood garden.');await frame.getByRole('button',{name:'Save brief',exact:true}).click();await expect(frame.locator('output')).toContainText('Brief saved');}
  if(c.category==='CARD'){await frame.getByRole('button',{name:'Save project',exact:true}).click();await expect(frame.getByRole('button',{name:'Saved ✓',exact:true})).toHaveAttribute('aria-pressed','true');}
  if(c.category==='AUTH'){await frame.getByRole('button',{name:'Show password',exact:true}).click();await expect(frame.getByLabel('Demo password',{exact:true})).toHaveAttribute('type','text');await frame.getByRole('button',{name:'Try sign-in',exact:true}).click();await expect(frame.locator('output')).toContainText('Demo signed in');}
  if(c.category==='DASHBOARD'){await frame.getByLabel('Filter projects',{exact:true}).selectOption('Active');await expect(frame.locator('tbody tr')).toHaveCount(2);await frame.getByRole('button',{name:'Sort by task count',exact:true}).click();await expect(frame.locator('tbody tr').first()).toContainText('Research portal');}
  const isolated=await iframe.evaluate((element:HTMLIFrameElement)=>{try{return element.contentWindow!.document.body.textContent}catch{return 'opaque';}});expect(isolated).toBe('opaque');await reflow(page);
 }
 expect(errors).toEqual([]);expect(upstream).toEqual([]);
});
test('preview viewport, keyboard tabs and anonymous free download preserve working source integrity',async({page},info)=>{
 await page.goto('/components/quiet-sign-in');await page.getByRole('button',{name:'Phone',exact:true}).click();expect((await page.locator('.kit-preview-stage iframe').boundingBox())!.width).toBeLessThanOrEqual(377);await reflow(page);
 await page.getByRole('tab',{name:'Source',exact:true}).click();await expect(page.getByRole('button',{name:'README.md',exact:true})).toBeVisible();await page.getByRole('button',{name:'README.md',exact:true}).click();await expect(page.getByRole('region',{name:'README.md source'}).or(page.locator('pre[aria-label="README.md source"]'))).toContainText('No packages');
 await page.getByRole('tab',{name:'Source',exact:true}).focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await expect(page.getByRole('tab',{name:'Setup & licence',exact:true})).toHaveAttribute('aria-selected','true');await reflow(page);
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Download source',exact:true}).click();const download=await downloadEvent,bytes=readFileSync((await download.path())!);expect(download.suggestedFilename()).toBe('quiet-sign-in-1.0.0.zip');const files=JSON.parse(execFileSync('python3',['-c',"import sys,io,zipfile,json; z=zipfile.ZipFile(io.BytesIO(sys.stdin.buffer.read())); assert z.testzip() is None; print(json.dumps({n:z.read(n).decode() for n in z.namelist()}))"],{input:bytes,encoding:'utf8'}));expect(Object.keys(files).sort()).toEqual(['LICENSE','README.md','index.html']);expect(createHash('sha256').update(files['index.html']).digest('hex')).toBe(recipes.find((c:any)=>c.slug==='quiet-sign-in').sha256);
 await page.goto('/components');await page.screenshot({path:info.outputPath('component-catalogue.png'),fullPage:true});
});
test('sample creator and college forms stay compact and never manufacture a purchase',async({page})=>{
 const gateway:string[]=[];page.on('request',r=>{if(r.url().includes('razorpay.com'))gateway.push(r.url());});await page.goto('/preview/components');await expect(page.getByText('3 / 3',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Review price & buy one slot',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'New component',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Component title',{exact:true}).fill('Sample navigation remix');await dialog.getByLabel('Summary',{exact:true}).fill('A curated navigation for a small studio.');await dialog.getByLabel('Your contribution & intended use',{exact:true}).fill('I selected this original recipe to explain a studio navigation use case.');await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Save component draft',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('heading',{name:'Sample navigation remix',exact:true})).toBeVisible();await reflow(page);
 await page.goto('/preview/college-projects');await page.getByRole('button',{name:'Add college context',exact:true}).click();await page.getByLabel('Coding language / framework',{exact:true}).fill('Python / FastAPI');await page.getByLabel('Problem you solved',{exact:true}).fill('Make a synthetic dataset easier to understand.');await page.getByLabel('Outcome & supporting evidence',{exact:true}).fill('A reproducible example explaining how the data changes.');await page.getByLabel('Prerequisites / local setup',{exact:true}).fill('Python fundamentals and local setup.');await page.getByLabel('Your individual contribution',{exact:true}).fill('I implemented the data cleaning and presentation modules.');await page.getByRole('checkbox',{name:/I have permission/}).check();await page.getByRole('button',{name:'Save context for review',exact:true}).click();await expect(page.getByText('Python / FastAPI · Academic details private')).toBeVisible();await reflow(page);expect(gateway).toEqual([]);
 await page.goto('/college-projects');await page.getByLabel('Project category',{exact:true}).selectOption('AI_ML');await page.getByRole('button',{name:'Search',exact:true}).click();await expect(page.locator('.kit-grid>.kit-card')).toHaveCount(1);await reflow(page);
});
