import {test,expect,type Page,type Route} from '@playwright/test';
import {createHostingPreview,hostingLimits} from '../../lib/hosting';

async function noOverflow(page:Page){await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width+1);}
async function actor(page:Page,value:'BUILDER'|'OPERATOR'){const controls=page.locator('.studio-preview');if(!await controls.evaluate(node=>(node as HTMLDetailsElement).open))await page.getByText('Hosted frontend sample',{exact:true}).click();await page.getByLabel('Sample actor',{exact:true}).selectOption(value);await expect(page.getByText('Loading frontend packages…',{exact:true})).not.toBeVisible();}
async function submit(page:Page){await page.getByRole('button',{name:'Review rights & submit',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('checkbox')).not.toBeChecked();await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Submit sample for review',exact:true}).click();await expect(dialog).not.toBeVisible();}
async function approve(page:Page){await actor(page,'OPERATOR');await page.getByRole('button',{name:'Simulate operator review',exact:true}).click();const dialog=page.getByRole('dialog');for(const checkbox of await dialog.getByRole('checkbox').all()){await expect(checkbox).not.toBeChecked();await checkbox.check();}await dialog.getByLabel('Sample review reason',{exact:true}).fill('Inspected the bundled sample manifest and recorded rights consent.');await dialog.getByRole('button',{name:'Record simulated review',exact:true}).click();await expect(dialog).not.toBeVisible();await actor(page,'BUILDER');}

test('bundled sample separates unchecked consent, operator review, publication and withdrawal without network',async({page},info)=>{
  const network:string[]=[];page.on('request',request=>{const url=new URL(request.url());if(url.pathname.startsWith('/api/')||(url.hostname!=='127.0.0.1'&&url.hostname!=='localhost'))network.push(request.url());});
  await page.goto('/preview/hosting');await expect(page.getByRole('heading',{name:'Hosted frontend demos',exact:true})).toBeVisible();await expect(page.getByText('Sample data only',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Simulate publication',exact:true})).toHaveCount(0);await noOverflow(page);
  const open=page.getByRole('button',{name:'Review rights & submit',exact:true});await open.click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('checkbox')).not.toBeChecked();await dialog.getByRole('button',{name:'Submit sample for review',exact:true}).click();await expect(dialog).toBeVisible();await expect(dialog.getByRole('checkbox')).toBeFocused();await page.keyboard.press('Escape');await expect(open).toBeFocused();await submit(page);await expect(page.getByText('Waiting for operator review',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Simulate publication',exact:true})).toHaveCount(0);
  await approve(page);await page.getByRole('button',{name:'Simulate publication',exact:true}).click();await expect(page.getByText('Simulated publication ready',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Open hosted demo',exact:true})).toHaveCount(0);await page.getByText('File manifest (4)',{exact:true}).click();await expect(page.getByText('index.html',{exact:true})).toBeVisible();await noOverflow(page);await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:info.outputPath('hosting-sample-reviewed-publication.png'),fullPage:true});
  await page.getByRole('button',{name:'Withdraw frontend',exact:true}).click();await dialog.getByRole('button',{name:'Withdraw sample',exact:true}).click();await expect(page.getByText('Withdrawal completed',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Simulate publication',exact:true})).toHaveCount(0);await noOverflow(page);expect(network).toEqual([]);
});

test('interrupted sample publication and delayed withdrawal keep one fixed identity through recovery',async({page})=>{
  await page.goto('/preview/hosting');await submit(page);await approve(page);await page.getByRole('button',{name:'Simulate interrupted publication',exact:true}).click();await expect(page.getByText('Recovery needs attention',{exact:true})).toBeVisible();const id=await page.locator('.hosting-reference').innerText();await expect(page.getByRole('button',{name:'Simulate publication',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Simulate reconciliation',exact:true}).click();await expect(page.getByText('Simulated publication ready',{exact:true})).toBeVisible();await expect(page.locator('.hosting-reference')).toHaveText(id);await page.getByRole('button',{name:'Simulate delayed withdrawal',exact:true}).click();await expect(page.getByText('Delete pending',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Open hosted demo',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Simulate reconciliation',exact:true}).click();await expect(page.getByText('Withdrawal completed',{exact:true})).toBeVisible();await expect(page.locator('.hosting-reference')).toHaveText(id);await page.getByRole('button',{name:'Reset sample',exact:true}).click();await expect(page.getByText('Draft',{exact:true})).toBeVisible();await expect(page.locator('.hosting-reference')).toHaveCount(0);await noOverflow(page);
});

test('sample package dialog uses readable controls, consent stays unchecked and Escape restores focus',async({page},info)=>{
  await page.goto('/preview/hosting');const create=page.getByRole('button',{name:'Copy bundled sample',exact:true});await create.click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Current public proof',{exact:true})).toBeFocused();for(const label of ['Current public proof','Frontend title','Package version']){const field=dialog.getByLabel(label,{exact:true});expect(await field.evaluate(node=>parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(16);await expect.poll(async()=>(await field.boundingBox())?.height||0).toBeGreaterThanOrEqual(44);}await expect(dialog.getByRole('checkbox')).not.toBeChecked();await noOverflow(page);await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:info.outputPath('hosting-sample-package-dialog.png'),fullPage:true});await page.keyboard.press('Escape');await expect(create).toBeFocused();await create.click();await expect(dialog.getByRole('checkbox')).not.toBeChecked();await dialog.getByLabel('Current public proof',{exact:true}).selectOption('sample-approved-proof');await dialog.getByLabel('Package version',{exact:true}).fill('../private');await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Copy sample draft',exact:true}).click();await expect(dialog.getByLabel('Package version',{exact:true})).toHaveAttribute('aria-invalid','true');await expect(dialog.getByLabel('Package version',{exact:true})).toBeFocused();await dialog.getByLabel('Package version',{exact:true}).fill('1.0.1');await dialog.getByRole('button',{name:'Copy sample draft',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByText('2 / 10 retained',{exact:true})).toBeVisible();await noOverflow(page);
});

test('connected source pagination and real multipart body work; denied refresh clears private forms without a success claim',async({page})=>{
  const sample=createHostingPreview(),record=sample.list()[0];let deny=false,uploaded=false;
  const list=(items:unknown[],number=0,hasMore=false)=>({items,page:number,size:12,hasMore,totalItems:items.length,totalPages:hasMore?2:1});
  await page.route('**/api/v1/**',async route=>{const url=new URL(route.request().url()),path=url.pathname.replace('/api/v1','');if(path==='/hosting/config')return route.fulfill({json:{enabled:true,reason:'',...hostingLimits}});if(path==='/me/hosting/sources')return route.fulfill({json:Number(url.searchParams.get('page')||0)===0?list([],0,true):list([{id:'later-proof',title:'Later approved public proof'}],1)});if(path==='/me/hosting'&&route.request().method()==='POST'){const headers=route.request().headers(),body=route.request().postData()||'';expect(headers['content-type']).toContain('multipart/form-data; boundary=');expect(headers['x-requested-with']).toBe('getlancer');for(const text of ['name="file"','filename="frontend.zip"','name="productId"','later-proof','name="rightsConsent"','true'])expect(body).toContain(text);uploaded=true;deny=true;return route.fulfill({json:{...record,id:'uploaded-frontend'}});}if(path==='/me/hosting')return route.fulfill(deny?{status:403,json:{error:{code:'FORBIDDEN',message:'Hosting access was revoked.'}}}:{json:list([record])});if(path==='/me/hosting/'+record.id)return route.fulfill({json:record});return route.fulfill({status:404,json:{error:{code:'NOT_FOUND',message:'Unexpected controlled request.'}}});});
  await page.goto('/workspace/hosting');await expect(page.getByRole('heading',{name:record.title,exact:true})).toBeVisible();await page.getByRole('button',{name:'Upload frontend ZIP',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Next proof sources',exact:true}).click();await expect(dialog.getByLabel('Current public proof',{exact:true}).locator('option[value="later-proof"]')).toHaveCount(1);await dialog.getByLabel('Current public proof',{exact:true}).selectOption('later-proof');await dialog.getByLabel('Frontend title',{exact:true}).fill('Uploaded static frontend');await dialog.getByLabel('Package version',{exact:true}).fill('1.0.0');await dialog.getByLabel('Built frontend ZIP',{exact:true}).setInputFiles({name:'frontend.zip',mimeType:'application/zip',buffer:Buffer.from('PK controlled interface bytes; ZIP safety is enforced on the server')});await expect(dialog.getByRole('checkbox')).not.toBeChecked();await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Upload immutable package',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('heading',{name:'Connect to your hosting workspace',exact:true})).toBeVisible();await expect(page.getByRole('navigation',{name:'Frontend packages',exact:true})).toHaveCount(0);await expect(page.getByText('Immutable package uploaded as a draft. Submit it for a separate operator review.',{exact:true})).toHaveCount(0);expect(uploaded).toBe(true);await noOverflow(page);
});

test('operator review downloads actual bytes, keeps both checks unchecked and clears review data after denied refresh',async({page})=>{
  const sample=createHostingPreview(),id=sample.list()[0].id;sample.submit(id,true);const record=sample.detail(id);let deny=false,reviews=0,downloadCalls=0;let lateDownload:Route|null=null;
  const empty={items:[],page:0,size:12,hasMore:false,totalItems:0,totalPages:0};
  await page.route('**/api/v1/**',async route=>{const url=new URL(route.request().url()),path=url.pathname.replace('/api/v1','');if(path==='/me')return route.fulfill({json:{email:'operator-interface@example.test',displayName:'Operator interface',roles:['ADMIN'],emailVerified:true,profile:{approval_status:'APPROVED'},activeSlotLimit:3}});if(path==='/admin/metrics')return route.fulfill({json:{weekly:[],sources:[],reportedValues:[]}});if(path==='/developer/analytics')return route.fulfill({json:{}});if(path==='/admin/hosting/'+id+'/package'){downloadCalls++;if(downloadCalls===1){lateDownload=route;return;}return route.fulfill({contentType:'application/zip',body:Buffer.from('PK controlled actual download bytes; server archive checks are tested separately')});}if(path==='/admin/hosting/'+id+'/review'){reviews++;expect(route.request().postDataJSON()).toEqual({action:'APPROVE',reason:'Inspected downloaded immutable package and its recorded rights consent.',rightsReviewed:true,packageReviewed:true});deny=true;return route.fulfill({json:{...record,status:'APPROVED'}});}if(path==='/admin/hosting')return route.fulfill(deny?{status:403,json:{error:{code:'FORBIDDEN',message:'Operator MFA access was revoked.'}}}:{json:{...empty,items:[record],totalItems:1,totalPages:1}});return route.fulfill({json:{...empty,totalOwned:0,activeCount:0}});});
  await page.goto('/workspace');const operations=page.locator('.hosting-operations');await operations.locator('summary').click();await expect(operations.getByRole('heading',{name:record.title,exact:true})).toBeVisible();const review=operations.getByRole('button',{name:'Review package & rights',exact:true});await expect(review).toBeDisabled();await operations.getByRole('button',{name:'Download actual ZIP',exact:true}).click();await expect.poll(()=>lateDownload!==null).toBe(true);await operations.locator('summary').click();await expect(operations.getByRole('button',{name:'Refresh hosting operations',exact:true})).not.toBeVisible();await operations.locator('summary').click();await expect(operations.getByRole('button',{name:'Refresh hosting operations',exact:true})).toBeEnabled();const lateResponse=page.waitForResponse(response=>response.url().endsWith('/admin/hosting/'+id+'/package'));await lateDownload!.fulfill({contentType:'application/zip',body:Buffer.from('PK stale controlled download bytes')});await (await lateResponse).finished();await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await expect(review).toBeDisabled();await expect(operations.getByText('ZIP downloaded for '+record.title+'. Inspect the actual archive and rights before recording review checks.',{exact:true})).toHaveCount(0);const pending=page.waitForEvent('download');await operations.getByRole('button',{name:'Download actual ZIP',exact:true}).click();const download=await pending;expect(download.suggestedFilename()).toBe('review-frontend-'+id+'.zip');await expect(review).toBeEnabled();await review.click();const dialog=page.getByRole('dialog');for(const checkbox of await dialog.getByRole('checkbox').all())await expect(checkbox).not.toBeChecked();await page.keyboard.press('Escape');await expect(review).toBeFocused();await review.click();await dialog.getByLabel('Hosting evidence & decision reason',{exact:true}).fill('Inspected downloaded immutable package and its recorded rights consent.');await dialog.getByRole('button',{name:'Record operator decision',exact:true}).click();expect(reviews).toBe(0);for(const checkbox of await dialog.getByRole('checkbox').all())await checkbox.check();await dialog.getByRole('button',{name:'Record operator decision',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(operations.getByRole('heading',{name:record.title,exact:true})).toHaveCount(0);await expect(operations.getByRole('alert')).toContainText('Operator MFA access was revoked.');await expect(operations.getByText('Operator review recorded and current hosting state refreshed.',{exact:true})).toHaveCount(0);expect(reviews).toBe(1);await noOverflow(page);
});

test('failed 502/503 publisher responses refresh the same record into recovery and hide a withdrawn URL without a false success',async({page})=>{
  const sample=createHostingPreview(),id=sample.list()[0].id;sample.submit(id,true);sample.setActor('OPERATOR');sample.review(id,{action:'APPROVE',reason:'Reviewed controlled interface package and consent.',rightsReviewed:true,packageReviewed:true});sample.setActor('BUILDER');let record=sample.detail(id),deployCalls=0,withdrawCalls=0;
  const list=(items:unknown[])=>({items,page:0,size:12,hasMore:false,totalItems:items.length,totalPages:items.length?1:0});
  await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/api/v1','');if(path==='/hosting/config')return route.fulfill({json:{enabled:true,reason:'',...hostingLimits}});if(path==='/me/hosting/sources')return route.fulfill({json:list(sample.sources())});if(path==='/me/hosting')return route.fulfill({json:list([record])});if(path==='/me/hosting/'+id)return route.fulfill({json:record});if(path==='/me/hosting/'+id+'/deploy'){deployCalls++;sample.publish(id,true);record=sample.detail(id);return route.fulfill({status:502,json:{error:{code:'DEPLOYMENT_UNCONFIRMED',message:'Publication response was not confirmed.'}}});}if(path==='/me/hosting/'+id+'/reconcile'){sample.reconcile(id);record={...sample.detail(id),url:'https://controlled-static.example.test/'};return route.fulfill({json:record});}if(path==='/me/hosting/'+id+'/withdraw'){withdrawCalls++;sample.withdraw(id,true);record=sample.detail(id);return route.fulfill({status:503,json:{error:{code:'DELETE_UNCONFIRMED',message:'Withdrawal is committed; deletion needs reconciliation.'}}});}return route.fulfill({json:{items:[]}});});
  await page.goto('/workspace/hosting');await page.getByRole('button',{name:'Publish reviewed frontend',exact:true}).click();await expect(page.getByText('Recovery needs attention',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Publish reviewed frontend',exact:true})).toHaveCount(0);await expect(page.getByRole('alert')).toContainText('Publication response was not confirmed.');await page.getByRole('button',{name:'Reconcile deployment',exact:true}).click();await expect(page.getByRole('link',{name:'Open hosted demo',exact:true})).toBeVisible();await page.getByRole('button',{name:'Withdraw frontend',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirm withdrawal',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('link',{name:'Open hosted demo',exact:true})).toHaveCount(0);await expect(page.getByText('Withdrawal recorded. Public access is denied; check the deployment state for deletion confirmation.',{exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Reconcile deployment',exact:true})).toBeVisible();expect(deployCalls).toBe(1);expect(withdrawCalls).toBe(1);await noOverflow(page);
});

for(const action of ['REJECT','CHANGES_REQUESTED','withdraw'])test('operator '+action+' returns keyboard focus to the stable panel title when its opener disappears',async({page})=>{
  const sample=createHostingPreview(),id=sample.list()[0].id;sample.submit(id,true);let record=sample.detail(id),writes=0;
  const empty={items:[],page:0,size:12,hasMore:false,totalItems:0,totalPages:0};
  await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname.replace('/api/v1','');if(path==='/me')return route.fulfill({json:{email:'operator-interface@example.test',displayName:'Operator interface',roles:['ADMIN'],emailVerified:true,profile:{approval_status:'APPROVED'},activeSlotLimit:3}});if(path==='/admin/metrics')return route.fulfill({json:{weekly:[],sources:[],reportedValues:[]}});if(path==='/developer/analytics')return route.fulfill({json:{}});if(path==='/admin/hosting/'+id+'/package')return route.fulfill({contentType:'application/zip',body:Buffer.from('PK controlled immutable archive bytes')});if(path==='/admin/hosting/'+id+'/'+(action==='withdraw'?'withdraw':'review')){writes++;const data=route.request().postDataJSON();expect(data.reason).toBe('Inspected the exact package and recorded operator evidence.');if(action==='withdraw'){expect(data).toEqual({reason:data.reason});record={...record,deploymentState:'DELETED',desiredState:'WITHDRAWN'};}else{expect(data).toEqual({action,reason:data.reason,rightsReviewed:true,packageReviewed:true});record={...record,status:action as typeof record.status};}return route.fulfill({json:record});}if(path==='/admin/hosting')return route.fulfill({json:{...empty,items:[record],totalItems:1,totalPages:1}});return route.fulfill({json:{...empty,totalOwned:0,activeCount:0}});});
  await page.goto('/workspace');const operations=page.locator('.hosting-operations'),title=operations.locator('summary');await title.click();await expect(operations.getByRole('heading',{name:record.title,exact:true})).toBeVisible();
  if(action!=='withdraw'){const pending=page.waitForEvent('download');await operations.getByRole('button',{name:'Download actual ZIP',exact:true}).click();await pending;}
  const opener=operations.getByRole('button',{name:action==='withdraw'?'Withdraw hosted frontend':'Review package & rights',exact:true});await expect(opener).toBeEnabled();await opener.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();if(action!=='withdraw'){await dialog.getByLabel('Hosting review decision',{exact:true}).selectOption(action);for(const checkbox of await dialog.getByRole('checkbox').all())await checkbox.check();}await dialog.getByLabel('Hosting evidence & decision reason',{exact:true}).fill('Inspected the exact package and recorded operator evidence.');await dialog.getByRole('button',{name:'Record operator decision',exact:true}).click();
  await expect(dialog).not.toBeVisible();await expect(opener).toHaveCount(0);await expect(title).toBeFocused();expect(writes).toBe(1);await noOverflow(page);
});
