import {test,expect,type Page} from '@playwright/test';
import {createMaintenancePreview} from '../../lib/maintenance';

// Browser-only HTTP/SDK controls exercise adverse interface timing, never real provider effects.
async function controlledWorkspace(page:Page){
 const sample=createMaintenancePreview();sample.offerAction('preview-care','send',true);sample.setSide('BUYER');sample.offerAction('preview-care','accept',true);
 const first=sample.detail('preview-care'),second={...structuredClone(first),id:'care-second',title:'Second care agreement'};
 const records=[first,second];let denyDetail=0,confirmCalls=0,billingFailure=false,refreshFailure=false,denyAfterWrite=0,billingCalls=0,refreshCalls=0,loseRequestResponse=false,failedAction='',actionCalls=0,accountId='account-interface-fixture';const billingKeys:string[]=[],detailReads:string[]=[],requestKeys:string[]=[],requestWrites=new Map<string,{offerId:string;title:string;description:string;id:string}>();
 const list=(items:unknown[],number=0,hasMore=false)=>({items,page:number,size:12,hasMore,totalItems:items.length,totalPages:hasMore?2:1});
 await page.addInitScript(()=>{
  const state=window as unknown as {careGateways:{options:Record<string,unknown>;handlers:Record<string,()=>void>;closed:boolean}[];Razorpay:unknown};state.careGateways=[];
  state.Razorpay=class{record:{options:Record<string,unknown>;handlers:Record<string,()=>void>;closed:boolean};constructor(options:Record<string,unknown>){this.record={options,handlers:{},closed:false};state.careGateways.push(this.record);}open(){}close(){this.record.closed=true;}on(event:string,handler:()=>void){this.record.handlers[event]=handler;}};
 });
 await page.route('**/api/v1/**',async route=>{
  const url=new URL(route.request().url()),path=url.pathname.replace('/api/v1',''),method=route.request().method();
  if(path==='/me')return route.fulfill({json:{id:accountId,email:'interface-fixture@example.test',roles:['CLIENT'],displayName:'Interface fixture'}});
  if(path==='/maintenance/config')return route.fulfill({json:{enabled:true,keyId:'rzp_live_interface_fixture',mode:'live',reason:''}});
  if(path==='/maintenance/sources'){const number=Number(url.searchParams.get('page')||0);return route.fulfill({json:number===0?list([],0,true):list([{id:'later-source',title:'Later eligible delivery',side:'SELLER'}],1)});}
  if(path==='/maintenance')return route.fulfill({json:list(records)});
  const record=records.find(item=>path==='/maintenance/'+item.id||path.startsWith('/maintenance/'+item.id+'/'));
  if(record&&method==='GET'){detailReads.push(record.id);return route.fulfill(denyDetail?{status:denyDetail,json:{error:{code:denyDetail===403?'FORBIDDEN':'UNAVAILABLE',message:denyDetail===403?'Workspace access was revoked.':'Current agreement detail is unavailable.'}}}:{json:record});}
  if(record&&path.endsWith('/billing/confirm')){confirmCalls++;return route.fulfill({json:{status:'ACTIVE'}});}
  if(record&&path.endsWith('/billing')){billingCalls++;billingKeys.push(route.request().headers()['idempotency-key']);if(billingFailure){record.billing={id:'billing-reserved-fixture',status:'UNKNOWN',mode:'live',creationStep:'SUBSCRIPTION',attentionReason:'Provider response is uncertain; reconcile this reserved subscription.',cancelRequested:false,cancelConfirmed:false,createdAt:new Date().toISOString()};if(denyAfterWrite)denyDetail=denyAfterWrite;return route.fulfill({status:502,json:{error:{code:'BILLING_UNCONFIRMED',message:'Billing reservation was saved; the provider response was not confirmed.'}}});}return route.fulfill({json:{id:'billing-fixture',providerSubscriptionId:'sub_interfacefixture',keyId:'rzp_live_interface_fixture',mode:'live',status:'CREATED'}});}
  if(record&&path.endsWith('/billing/refresh')){refreshCalls++;if(refreshFailure){record.entitlement={...record.entitlement,available:false,remainingRequests:0,reason:'Financial state is stale. Reconciliation is required before opening a support request.'};if(denyAfterWrite)denyDetail=denyAfterWrite;return route.fulfill({status:503,json:{error:{code:'FINANCIAL_REFRESH_FAILED',message:'The provider financial refresh could not be completed.'}}});}return route.fulfill({json:{status:'ACTIVE'}});}
  if(record&&method==='POST'&&path.endsWith('/requests')){const key=route.request().headers()['idempotency-key'],body=route.request().postDataJSON(),previous=requestWrites.get(key);requestKeys.push(key);if(previous){if(previous.offerId!==record.id||previous.title!==body.title||previous.description!==body.description)return route.fulfill({status:409,json:{error:{code:'IDEMPOTENCY_CONFLICT',message:'Request key belongs to different support content.'}}});return route.fulfill({json:{id:previous.id}});}const id='request-fixture-'+requestWrites.size,now=new Date();requestWrites.set(key,{offerId:record.id,title:body.title,description:body.description,id});record.requests.push({id,invoiceId:'period-fixture',title:body.title,description:body.description,status:'OPEN',createdAt:now.toISOString(),responseDueAt:new Date(now.getTime()+86400000).toISOString()});record.entitlement.usedRequests++;record.entitlement.remainingRequests--;if(loseRequestResponse){loseRequestResponse=false;denyDetail=503;return route.abort('connectionreset');}return route.fulfill({json:{id}});}
  if(record&&method==='POST'&&['send','accept','withdraw','reject'].includes(path.split('/').pop()||'')){const action=path.split('/').pop()!;actionCalls++;record.status=({send:'OFFERED',accept:'ACCEPTED',withdraw:'WITHDRAWN',reject:'REJECTED'} as Record<string,string>)[action];if(action===failedAction)return route.fulfill({status:502,json:{error:{code:'ACTION_UNCONFIRMED',message:'The agreement action was committed; its response was not confirmed.'}}});return route.fulfill({json:{id:record.id,status:record.status}});}
  if(record&&method==='POST'&&path.endsWith('/billing/cancel')&&record.billing){actionCalls++;record.billing.cancelRequested=true;if(failedAction==='cancel-billing')return route.fulfill({status:503,json:{error:{code:'CANCELLATION_UNCONFIRMED',message:'Cancellation intent was committed; provider confirmation is unavailable.'}}});record.billing.cancelConfirmed=true;record.billing.status='CANCELLED';return route.fulfill({json:{id:record.id}});}
  return route.fulfill({status:404,json:{error:{code:'NOT_FOUND',message:'Unexpected controlled request.'}}});
 });
 await page.goto('/workspace/maintenance');await expect(page.getByRole('heading',{name:'Portal care',exact:true})).toBeVisible();
 return {records,setDeny:()=>{denyDetail=403;},failBilling:(deny=false)=>{billingFailure=true;denyAfterWrite=deny?403:0;},failRefresh:(deny=false)=>{refreshFailure=true;denyAfterWrite=deny?503:0;},loseRequestResponse:()=>{loseRequestResponse=true;},failAction:(action:string)=>{failedAction=action;},reconnect:()=>{denyDetail=0;},changeAccount:()=>{accountId='different-account-interface-fixture';},confirmCalls:()=>confirmCalls,billingCalls:()=>billingCalls,refreshCalls:()=>refreshCalls,actionCalls:()=>actionCalls,billingKeys,detailReads,requestKeys};
}
test('hostile maintenance query identifiers cannot select application routes or replace detail query parameters',async({page})=>{
 const fixture=await controlledWorkspace(page),requests:string[]=[];
 page.on('request',request=>{const url=new URL(request.url());if(url.pathname.startsWith('/api/v1/maintenance/')&&!['/api/v1/maintenance/config','/api/v1/maintenance/sources'].includes(url.pathname))requests.push(url.pathname+url.search);});
 for(const id of ['../maintenance/care-second','../../auth/providers','preview-care?page=999','..','https://outside.example.test/private']){
  requests.length=0;fixture.detailReads.length=0;
  await page.goto('/workspace/maintenance?maintenanceId='+encodeURIComponent(id));
  await expect(page.getByRole('heading',{name:'Portal care',exact:true})).toBeVisible();
  await expect.poll(()=>fixture.detailReads).toEqual(['preview-care']);
  expect(requests).toEqual(['/api/v1/maintenance/preview-care?page=0&size=12']);
 }
});

test('a valid maintenance UUID deep link still opens its authorized agreement',async({page})=>{
 const fixture=await controlledWorkspace(page),id='11111111-1111-4111-8111-111111111111';
 fixture.records[1].id=id;fixture.detailReads.length=0;
 await page.goto('/workspace/maintenance?maintenanceId='+id);
 await expect(page.getByRole('heading',{name:'Second care agreement',exact:true})).toBeVisible();
 await expect.poll(()=>fixture.detailReads.at(-1)).toBe(id);
});

async function openCheckout(page:Page){await page.getByRole('button',{name:'Authorize recurring billing',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Continue to Razorpay',exact:true}).click();await expect(dialog).not.toBeVisible();}

test('a previous checkout cannot overwrite another agreement and a payment failure stays visible',async({page})=>{
 const fixture=await controlledWorkspace(page);await openCheckout(page);
 await page.getByRole('navigation',{name:'Care agreements',exact:true}).getByRole('button',{name:/Second care agreement/}).click();await expect(page.getByRole('heading',{name:'Second care agreement',exact:true})).toBeVisible();
 await page.evaluate(()=>{const state=window as unknown as {careGateways:{options:{handler:(body:unknown)=>void;modal:{ondismiss:()=>void}};handlers:Record<string,()=>void>;closed:boolean}[]};const gateway=state.careGateways[0];if(!gateway.closed)throw Error('Previous checkout did not close');gateway.options.handler({razorpay_payment_id:'pay_latefixture'});gateway.options.modal.ondismiss();gateway.handlers['payment.failed']();});
 await expect(page.getByRole('heading',{name:'Second care agreement',exact:true})).toBeVisible();expect(fixture.confirmCalls()).toBe(0);await expect(page.getByRole('alert')).toHaveCount(0);
 await page.getByRole('navigation',{name:'Care agreements',exact:true}).getByRole('button',{name:/Portal care/}).click();await openCheckout(page);await page.evaluate(()=>{const state=window as unknown as {careGateways:{handlers:Record<string,()=>void>}[]};state.careGateways[1].handlers['payment.failed']();});await expect(page.getByRole('alert')).toContainText('Billing authorization was not confirmed. Refresh billing before trying again.');
});

test('later source pages remain reachable and a saved action with denied refresh clears private forms without success',async({page})=>{
 const fixture=await controlledWorkspace(page);await page.getByRole('button',{name:'Create support offer',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('navigation',{name:'Completed work pages',exact:true}).getByRole('button',{name:'Next',exact:true}).click();await expect(dialog.getByLabel('Completed engagement',{exact:true}).locator('option[value="later-source"]')).toHaveCount(1);await page.keyboard.press('Escape');
 fixture.records[0].side='SELLER';fixture.records[0].status='DRAFT';await page.getByRole('navigation',{name:'Care agreements',exact:true}).getByRole('button',{name:/Portal care/}).click();await page.getByRole('button',{name:'Review & send terms',exact:true}).click();await dialog.getByRole('checkbox').check();fixture.setDeny();await dialog.getByRole('button',{name:'Consent & send offer',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('heading',{name:'Sign in to your maintenance workspace',exact:true})).toBeVisible();await expect(page.getByRole('navigation',{name:'Care agreements',exact:true})).toHaveCount(0);await expect(page.getByText('Agreement Send recorded.',{exact:true})).toHaveCount(0);
});

test('failed billing authorization reloads its committed reservation and keeps the original error',async({page})=>{
 const fixture=await controlledWorkspace(page);fixture.failBilling();const reads=fixture.detailReads.length;
 await page.getByRole('button',{name:'Authorize recurring billing',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Continue to Razorpay',exact:true}).click();
 await expect(dialog).not.toBeVisible();await expect(page.locator('.care-notice.error')).toContainText('Billing reservation was saved; the provider response was not confirmed.');await expect(page.getByText('live · Unknown',{exact:true})).toBeVisible();await expect(page.getByText(/Provider response is uncertain; reconcile this reserved subscription/)).toBeVisible();await expect(page.getByRole('button',{name:'Refresh billing',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Cancel future billing',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Authorize recurring billing',exact:true})).toHaveCount(0);await expect(page.getByText('No billing authorization',{exact:true})).toHaveCount(0);
 expect(fixture.detailReads.slice(reads)).toEqual(['preview-care']);expect(fixture.billingCalls()).toBe(1);expect(fixture.billingKeys[0]).toMatch(/^[0-9a-f-]{36}$/);expect(await page.evaluate(()=>(window as unknown as {careGateways:unknown[]}).careGateways.length)).toBe(0);
});

for(const deny of [false,true])test('failed financial refresh '+(deny?'clears private state when its GET is unavailable':'reloads stale entitlement and removes support access'),async({page})=>{
 const fixture=await controlledWorkspace(page),record=fixture.records[0];record.billing={id:'active-billing-fixture',status:'ACTIVE',mode:'live',cancelRequested:false,cancelConfirmed:false,createdAt:new Date().toISOString()};record.entitlement={available:true,reason:'Provider verified current paid period.',usedRequests:0,remainingRequests:3,requestLimit:3};fixture.failRefresh(deny);
 await page.getByRole('navigation',{name:'Care agreements',exact:true}).getByRole('button',{name:/Portal care/}).click();await expect(page.getByRole('button',{name:'New support request',exact:true})).toBeVisible();const reads=fixture.detailReads.length;
 await page.getByRole('button',{name:'Refresh billing',exact:true}).click();await expect(page.locator('.care-notice.error')).toContainText('The provider financial refresh could not be completed.');await expect(page.getByRole('button',{name:'New support request',exact:true})).toHaveCount(0);await expect(page.getByText('Paid period available',{exact:true})).toHaveCount(0);await expect(page.getByText('Billing and financial status refreshed.',{exact:true})).toHaveCount(0);
 if(deny){await expect(page.getByRole('heading',{name:'Sign in to your maintenance workspace',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Portal care',exact:true})).toHaveCount(0);await expect(page.getByRole('navigation',{name:'Care agreements',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Refresh billing',exact:true})).toHaveCount(0);}
 else{await expect(page.getByText('Support unavailable',{exact:true})).toBeVisible();await expect(page.getByText('Financial state is stale. Reconciliation is required before opening a support request.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Refresh billing',exact:true})).toBeEnabled();}
 expect(fixture.detailReads.slice(reads)).toEqual(['preview-care']);expect(fixture.refreshCalls()).toBe(1);
});

test('a failed authorization followed by denied detail clears the private dialog and retains the mutation error',async({page})=>{
 const fixture=await controlledWorkspace(page);fixture.failBilling(true);await page.getByRole('button',{name:'Authorize recurring billing',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:'Continue to Razorpay',exact:true}).click();
 await expect(dialog).not.toBeVisible();await expect(page.locator('.care-notice.error')).toContainText('Billing reservation was saved; the provider response was not confirmed.');await expect(page.getByRole('heading',{name:'Sign in to your maintenance workspace',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Portal care',exact:true})).toHaveCount(0);await expect(page.getByRole('navigation',{name:'Care agreements',exact:true})).toHaveCount(0);expect(fixture.billingCalls()).toBe(1);
});

for(const edit of ['none','title','description'])test('lost support request response and unavailable recovery preserves its '+(edit==='none'?'retry key and consumes one slot':edit+' draft while edited content gets a fresh key'),async({page})=>{
 const fixture=await controlledWorkspace(page),record=fixture.records[0];record.billing={id:'active-billing-fixture',status:'ACTIVE',mode:'live',cancelRequested:false,cancelConfirmed:false,createdAt:new Date().toISOString()};record.entitlement={available:true,reason:'Provider verified current paid period.',usedRequests:0,remainingRequests:3,requestLimit:3};await page.getByRole('navigation',{name:'Care agreements',exact:true}).getByRole('button',{name:/Portal care/}).click();fixture.loseRequestResponse();
 await page.getByRole('button',{name:'New support request',exact:true}).click();const dialog=page.getByRole('dialog'),title='Repair the approval workflow',description='The approval workflow needs a verified fix for the delivered project.';await dialog.getByLabel('Request title',{exact:true}).fill(title);await dialog.getByLabel('What needs attention?',{exact:true}).fill(description);await dialog.getByRole('button',{name:'Open support request',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('heading',{name:'Sign in to your maintenance workspace',exact:true})).toBeVisible();await expect(page.getByRole('navigation',{name:'Care agreements',exact:true})).toHaveCount(0);expect(record.requests).toHaveLength(1);
 fixture.reconnect();await page.getByRole('button',{name:'Retry connection',exact:true}).click();await expect(page.getByRole('heading',{name:'Portal care',exact:true})).toBeVisible();await page.getByRole('button',{name:'New support request',exact:true}).click();await expect(dialog.getByLabel('Request title',{exact:true})).toHaveValue(title);await expect(dialog.getByLabel('What needs attention?',{exact:true})).toHaveValue(description);await expect(dialog.getByText('A previous submission is awaiting confirmation. Retry these details to check the same request; changing them starts a new request.',{exact:true})).toBeVisible();if(edit==='title')await dialog.getByLabel('Request title',{exact:true}).fill('Repair a different approval workflow');if(edit==='description')await dialog.getByLabel('What needs attention?',{exact:true}).fill('The approval workflow has a separate newly identified issue to repair.');await dialog.getByRole('button',{name:'Open support request',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByText('Support request opened. One slot in this paid period was used.',{exact:true})).toBeVisible();expect(fixture.requestKeys).toHaveLength(2);expect(fixture.requestKeys[0]).toMatch(/^[0-9a-f-]{36}$/);
 if(edit==='none'){expect(fixture.requestKeys[1]).toBe(fixture.requestKeys[0]);expect(record.requests).toHaveLength(1);await expect(page.getByText('1 of 3 requests used',{exact:true})).toBeVisible();}else{expect(fixture.requestKeys[1]).not.toBe(fixture.requestKeys[0]);expect(record.requests).toHaveLength(2);await expect(page.getByText('2 of 3 requests used',{exact:true})).toBeVisible();}
});

for(const action of ['send','accept','withdraw','reject','cancel-billing'])test('committed '+action+' with an uncertain response closes its ineligible confirmation and retains the original error',async({page})=>{
 const fixture=await controlledWorkspace(page),record=fixture.records[0];record.side=['send','withdraw'].includes(action)?'SELLER':'BUYER';record.status=['send','withdraw'].includes(action)?'DRAFT':action==='cancel-billing'?'ACCEPTED':'OFFERED';if(action==='cancel-billing')record.billing={id:'active-billing-fixture',status:'ACTIVE',mode:'live',cancelRequested:false,cancelConfirmed:false,createdAt:new Date().toISOString()};fixture.failAction(action);await page.getByRole('navigation',{name:'Care agreements',exact:true}).getByRole('button',{name:/Portal care/}).click();
 const labels:Record<string,[string,string]>={send:['Review & send terms','Consent & send offer'],accept:['Review & accept terms','Accept these terms'],withdraw:['Withdraw offer','Confirm withdraw'],reject:['Reject offer','Confirm reject'],'cancel-billing':['Cancel future billing','Confirm billing cancellation']};await page.getByRole('button',{name:labels[action][0],exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();if(['send','accept'].includes(action))await dialog.getByRole('checkbox').check();const reads=fixture.detailReads.length;await dialog.getByRole('button',{name:labels[action][1],exact:true}).click();
 await expect(dialog).not.toBeVisible();await expect(page.locator('.care-notice.error')).toContainText(action==='cancel-billing'?'Cancellation intent was committed; provider confirmation is unavailable.':'The agreement action was committed; its response was not confirmed.');await expect(page.getByRole('button',{name:labels[action][0],exact:true})).toHaveCount(0);expect(fixture.detailReads.slice(reads)).toEqual(['preview-care']);expect(fixture.actionCalls()).toBe(1);await expect(page.getByText(/^Agreement (Send|Accept|Withdraw|Reject) recorded\.$/)).toHaveCount(0);await expect(page.getByText('Cancellation status updated. Check provider confirmation above.',{exact:true})).toHaveCount(0);if(action==='cancel-billing')await expect(page.getByText('Cancellation requested; the provider has not confirmed billing stopped. Refresh or contact the operator.',{exact:true})).toBeVisible();else await expect(page.locator('.care-current [data-slot="badge"]').filter({hasText:({send:'Offered',accept:'Accepted',withdraw:'Withdrawn',reject:'Rejected'} as Record<string,string>)[action]})).toBeVisible();
});

test('reconnecting as another verified account clears the previous account pending request draft and key',async({page})=>{
 const fixture=await controlledWorkspace(page),record=fixture.records[0];record.billing={id:'active-billing-fixture',status:'ACTIVE',mode:'live',cancelRequested:false,cancelConfirmed:false,createdAt:new Date().toISOString()};record.entitlement={available:true,reason:'Provider verified current paid period.',usedRequests:0,remainingRequests:3,requestLimit:3};await page.getByRole('navigation',{name:'Care agreements',exact:true}).getByRole('button',{name:/Portal care/}).click();fixture.loseRequestResponse();await page.getByRole('button',{name:'New support request',exact:true}).click();const dialog=page.getByRole('dialog'),title='Private first account request',description='A support request written privately by the previous verified account.';await dialog.getByLabel('Request title',{exact:true}).fill(title);await dialog.getByLabel('What needs attention?',{exact:true}).fill(description);await dialog.getByRole('button',{name:'Open support request',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('button',{name:'Retry connection',exact:true})).toBeVisible();fixture.changeAccount();fixture.reconnect();await page.getByRole('button',{name:'Retry connection',exact:true}).click();await expect(page.getByRole('heading',{name:'Portal care',exact:true})).toBeVisible();await page.getByRole('button',{name:'New support request',exact:true}).click();await expect(dialog.getByLabel('Request title',{exact:true})).toHaveValue('');await expect(dialog.getByLabel('What needs attention?',{exact:true})).toHaveValue('');await expect(dialog.getByText('A previous submission is awaiting confirmation. Retry these details to check the same request; changing them starts a new request.',{exact:true})).toHaveCount(0);await dialog.getByLabel('Request title',{exact:true}).fill(title);await dialog.getByLabel('What needs attention?',{exact:true}).fill(description);await dialog.getByRole('button',{name:'Open support request',exact:true}).click();await expect(dialog).not.toBeVisible();expect(fixture.requestKeys).toHaveLength(2);expect(fixture.requestKeys[1]).not.toBe(fixture.requestKeys[0]);
});
