import {test,expect,type Page} from '@playwright/test';
async function switchActor(page:Page,value:string){const controls=page.locator('.studio-preview');if(!await controls.evaluate(node=>(node as HTMLDetailsElement).open))await page.getByText('Maintenance sample',{exact:true}).click();await page.getByLabel('Sample actor',{exact:true}).selectOption(value);await expect(page.getByText('Loading maintenance records…',{exact:true})).not.toBeVisible();}
async function consent(page:Page,button:string){const dialog=page.getByRole('dialog');await dialog.getByRole('checkbox').check();await dialog.getByRole('button',{name:button,exact:true}).click();await expect(dialog).not.toBeVisible();}
async function noOverflow(page:Page){await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width+1);}
test('maintenance sample separates consent and billing, enforces support lifecycle and preserves cancelled paid period without network',async({page},info)=>{
 const network:string[]=[];page.on('request',request=>{const url=new URL(request.url());if(url.pathname.startsWith('/api/v1/')||url.hostname==='razorpay.com'||url.hostname.endsWith('.razorpay.com'))network.push(request.url());});
 await page.goto('/preview/maintenance');await expect(page.getByRole('heading',{name:'Maintenance & support',exact:true})).toBeVisible();await expect(page.getByText('Sample data only',{exact:true})).toBeVisible();await noOverflow(page);
 const send=page.getByRole('button',{name:'Review & send terms',exact:true});await send.click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('checkbox')).not.toBeChecked();await page.keyboard.press('Escape');await expect(send).toBeFocused();await send.click();await consent(page,'Consent & send offer');
 await switchActor(page,'BUYER');await page.getByRole('button',{name:'Review & accept terms',exact:true}).click();await expect(dialog.getByRole('checkbox')).not.toBeChecked();await consent(page,'Accept these terms');await expect(page.getByText('Support unavailable',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Simulate billing & paid period',exact:true}).click();await expect(dialog.getByRole('checkbox')).not.toBeChecked();await consent(page,'Simulate authorized paid period');await expect(page.getByText('Simulated paid period',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'New support request',exact:true}).click();await dialog.getByLabel('Request title',{exact:true}).fill('Correct the approval notification');await dialog.getByLabel('What needs attention?',{exact:true}).fill('The second approval reviewer needs a notification when the request is ready.');await dialog.getByRole('button',{name:'Open support request',exact:true}).click();await expect(dialog).not.toBeVisible();await page.getByRole('tab',{name:'Requests',exact:true}).click();await expect(page.getByText('2 remaining',{exact:true})).toBeVisible();
 await switchActor(page,'SELLER');await page.getByRole('button',{name:'Start request',exact:true}).click();await dialog.getByRole('button',{name:'Confirm request action',exact:true}).click();await page.getByRole('button',{name:'Submit resolution',exact:true}).click();await dialog.getByLabel('Resolution details',{exact:true}).fill('Corrected the approval notification and verified the second reviewer.');await dialog.getByLabel('Delivery URL',{exact:true}).fill('https://example.test/changes');await dialog.getByRole('button',{name:'Submit resolution',exact:true}).click();await expect(dialog).not.toBeVisible();
 await switchActor(page,'BUYER');await page.getByRole('button',{name:'Request revision',exact:true}).click();await dialog.getByLabel('What needs revision?',{exact:true}).fill('Please also include the third approval reviewer in this notification.');await dialog.getByRole('button',{name:'Record revision request',exact:true}).click();await switchActor(page,'SELLER');await page.getByRole('button',{name:'Start request',exact:true}).click();await dialog.getByRole('button',{name:'Confirm request action',exact:true}).click();await page.getByRole('button',{name:'Submit resolution',exact:true}).click();await dialog.getByLabel('Resolution details',{exact:true}).fill('Included the third reviewer and verified all notification recipients.');await dialog.getByRole('button',{name:'Submit resolution',exact:true}).click();await switchActor(page,'BUYER');await page.getByRole('button',{name:'Accept resolution',exact:true}).click();await dialog.getByRole('button',{name:'Confirm request action',exact:true}).click();await expect(page.getByText('Resolved',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Cancel future billing',exact:true}).click();await dialog.getByRole('button',{name:'Confirm billing cancellation',exact:true}).click();await expect(page.getByText('Future billing stopped. An eligible paid period remains available until its end.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'New support request',exact:true})).toBeEnabled();await expect(page.getByText('2 remaining',{exact:true})).toBeVisible();await noOverflow(page);await page.screenshot({path:info.outputPath('maintenance-current-plan-and-request.png'),fullPage:true});await page.getByRole('tab',{name:'Billing',exact:true}).click();await expect(page.getByText('Local sample invoice',{exact:true})).toBeVisible();await noOverflow(page);expect(network).toEqual([]);await expect(page.locator('script[src*="razorpay.com"]')).toHaveCount(0);
});
test('maintenance offer dialog has readable fields, validates paise and returns focus at every viewport',async({page},info)=>{
 await page.goto('/preview/maintenance');const create=page.getByRole('button',{name:'Create support offer',exact:true});await create.click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Completed engagement',{exact:true})).toBeFocused();for(const label of ['Monthly price (INR)','Requests per paid period','First response (elapsed hours)','Maximum billing cycles']){const field=dialog.getByLabel(label,{exact:true});expect(await field.evaluate(node=>parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(16);expect((await field.boundingBox())!.height).toBeGreaterThanOrEqual(44);}
 await page.screenshot({path:info.outputPath('maintenance-offer-dialog.png'),fullPage:true});await page.keyboard.press('Escape');await expect(create).toBeFocused();await page.getByRole('button',{name:'Withdraw offer',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirm withdraw',exact:true}).click();await create.click();await dialog.getByLabel('Completed engagement',{exact:true}).selectOption('preview-completed-project');await dialog.getByLabel('Care plan title',{exact:true}).fill('Portal support');await dialog.getByLabel('Included work',{exact:true}).fill('Bug fixes and small improvements for the delivered portal.');await dialog.getByLabel('Terms & exclusions',{exact:true}).fill('Includes bounded maintenance. New features need a separate agreement and future billing can be cancelled.');await dialog.getByLabel('Monthly price (INR)',{exact:true}).fill('1500.001');await dialog.getByRole('button',{name:'Create maintenance draft',exact:true}).click();await expect(dialog.getByLabel('Monthly price (INR)',{exact:true})).toHaveAttribute('aria-invalid','true');await expect(dialog.getByLabel('Monthly price (INR)',{exact:true})).toBeFocused();await noOverflow(page);await dialog.getByLabel('Monthly price (INR)',{exact:true}).fill('1500.25');await dialog.getByRole('button',{name:'Create maintenance draft',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('heading',{name:'Portal support',exact:true})).toBeVisible();await noOverflow(page);
});
