import {test,expect,type Page} from '@playwright/test';
async function noOverflow(page:Page){await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width+1);}
async function actor(page:Page,value:string){const controls=page.locator('.studio-preview');if(!await controls.evaluate(node=>(node as HTMLDetailsElement).open))await page.getByText('Interactive source marketplace preview',{exact:true}).click();await page.getByLabel('Preview actor',{exact:true}).selectOption(value);}

test('source preview requires license consent, retains its snapshot and disables real archives without provider requests',async({page},info)=>{
 const requests:string[]=[];page.on('request',request=>{if(request.url().includes('/api/v1/')||request.url().includes('razorpay.com'))requests.push(request.url());});await page.goto('/preview/templates?tab=purchases');await expect(page.getByRole('heading',{name:'Purchased source',exact:true})).toBeVisible();await page.getByRole('button',{name:'Review sample license',exact:true}).click();const dialog=page.getByRole('dialog'),confirm=dialog.getByRole('button',{name:'Accept sample license & simulate capture',exact:true});await expect(confirm).toBeDisabled();await dialog.getByRole('checkbox').check();await confirm.click();await expect(dialog).not.toBeVisible();const purchase=page.getByTestId('template-purchase');await expect(purchase.getByText('Captured',{exact:true})).toBeVisible();await expect(purchase.getByRole('button',{name:'Download purchased source',exact:true})).toBeDisabled();await purchase.getByText('Purchased license terms',{exact:true}).click();await expect(purchase.getByText('One commercial end product.',{exact:false}).first()).toBeVisible();await purchase.getByRole('button',{name:'Raise a purchase concern',exact:true}).click();await dialog.getByLabel('Describe the purchase concern',{exact:true}).fill('The sample documentation needs a clearer setup section.');await dialog.getByRole('button',{name:'Record purchase concern',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(purchase.getByText('Disputed',{exact:true})).toBeVisible();await expect(purchase.getByText('₹0.00',{exact:true})).toBeVisible();await noOverflow(page);await page.screenshot({path:info.outputPath('source-license-history.png'),fullPage:true});expect(requests).toEqual([]);await expect(page.locator('script[src*="checkout.razorpay.com"]')).toHaveCount(0);
});
test('seller preview uploads metadata, records rights consent and exposes a separate operator review',async({page})=>{
 const requests:string[]=[];page.on('request',request=>{if(request.url().includes('/api/v1/')||request.url().includes('razorpay.com'))requests.push(request.url());});await page.goto('/preview/templates');await expect(page.getByRole('heading',{name:'Your template releases',exact:true})).toBeVisible();await page.getByLabel('Version number',{exact:true}).fill('1.1.0');await page.getByLabel('Release notes',{exact:true}).fill('Improved keyboard navigation and release documentation.');await page.getByRole('checkbox',{name:'I have the rights to distribute this source and its dependencies under my license. The package includes the required notices.',exact:true}).check();await page.getByRole('button',{name:'Simulate private version upload',exact:true}).click();const release=page.locator('.commerce-version').filter({has:page.getByRole('heading',{name:'Version 1.1.0',exact:true})});await expect(release.getByText('Draft',{exact:true})).toBeVisible();await release.getByRole('button',{name:'Submit version for review',exact:true}).click();const dialog=page.getByRole('dialog'),confirm=dialog.getByRole('button',{name:'Confirm rights & submit version',exact:true});await expect(confirm).toBeDisabled();await dialog.getByRole('checkbox').check();await confirm.click();await expect(dialog).not.toBeVisible();await expect(release.getByText('Pending',{exact:true})).toBeVisible();await actor(page,'OPERATOR');const review=page.locator('.commerce-version').filter({has:page.getByRole('heading',{name:'Version 1.1.0',exact:true})});await review.getByLabel('Decision for version 1.1.0',{exact:true}).selectOption('APPROVE');await review.getByLabel('Review reason for version 1.1.0',{exact:true}).fill('Ownership evidence, license notices and source package reviewed.');await review.getByRole('checkbox').nth(0).check();await review.getByRole('checkbox').nth(1).check();await review.getByRole('button',{name:'Record package review',exact:true}).click();await expect(review.getByText('Approved',{exact:true})).toBeVisible();await actor(page,'SELLER');await expect(page.getByRole('heading',{name:'Version 1.1.0',exact:true})).toBeVisible();await noOverflow(page);expect(requests).toEqual([]);
});
test('public source catalog and license detail reflow with clear sample labels and return keyboard focus',async({page})=>{
 await page.goto('/templates');await expect(page.getByRole('heading',{name:'A head start, with the source.',exact:true})).toBeVisible();await expect(page.getByText('Frontend preview · Sample listings and license flows.',{exact:false})).toBeVisible();await noOverflow(page);await page.getByRole('link',{name:'Approval portal starter',exact:true}).click();await expect(page.getByRole('heading',{name:'Your license',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Review license & buy',exact:true})).toHaveCount(0);await noOverflow(page);await page.goto('/preview/templates');const create=page.getByRole('button',{name:'Create template',exact:true});await create.click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Approved public proof project',{exact:true})).toBeFocused();await dialog.getByLabel('Template title',{exact:true}).fill('Source tools');await dialog.getByLabel('Short summary',{exact:true}).fill('A clear and accessible template starter.');await dialog.getByLabel('What is included?',{exact:true}).fill('A release with useful source files and detailed setup notes.');await dialog.getByLabel('Approved public proof project',{exact:true}).selectOption('sample-proof');await dialog.getByLabel('License terms',{exact:true}).fill('One commercial end product; modification is allowed and template redistribution is prohibited.');await dialog.getByLabel('Price (INR)',{exact:true}).fill('5.001');await dialog.getByRole('button',{name:'Create template draft',exact:true}).click();await expect(dialog.getByLabel('Price (INR)',{exact:true})).toHaveAttribute('aria-invalid','true');await expect(dialog.getByLabel('Price (INR)',{exact:true})).toBeFocused();await noOverflow(page);await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(create).toBeFocused();
});
