import {test,expect,type Page,type Route} from '@playwright/test';
const id='11111111-1111-4111-8111-111111111111';
const manifest={id:'fixture-manifest',title:'Protocol fixture lab',summary:'Browser fixture for control-plane behavior, not hosted execution evidence.',language:'Java',framework:'HTTP',sourceUrl:'https://github.com/example/free-source',setup:'Read the source README and configure your own environment.',executionMode:'ISOLATED',scenarios:[{id:'inspect',title:'Inspect bounded fixture',description:'Browser protocol fixture only.',inputs:[{name:'count',label:'Record count',type:'INTEGER',required:true,maxLength:2,min:1,max:10,choices:[]}],operations:[{id:'inspect',label:'Inspect records'}]}]};
const runtime={enabled:true,reason:'Browser protocol fixture: admission for this test only.'};
const quota={dailyLimit:5,remaining:5,resetAt:'2026-10-10T00:00:00Z',activeRunId:null as string|null,runtime};
const run=(status='QUEUED',verified=false,expiresAt=new Date(Date.now()+300000).toISOString())=>({id,manifestId:manifest.id,scenarioId:'inspect',status,executionMode:'ISOLATED',verified,requestedAt:new Date().toISOString(),expiresAt,reason:'Browser protocol fixture status; not provider evidence.',eventsUrl:'/api/v1/lab-runs/'+id+'/events'});
const json=(route:Route,body:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
async function catalogue(page:Page,currentQuota=quota,enabled=runtime){await page.route('**/api/v1/lab-manifests',route=>json(route,{items:[manifest],runtime:enabled}));await page.route('**/api/v1/lab-quota',route=>json(route,currentQuota));}
async function events(page:Page,status='QUEUED'){await page.route('**/api/v1/lab-runs/'+id+'/events',route=>route.fulfill({status:200,contentType:'text/event-stream',body:'id: 1\ndata: '+JSON.stringify({runId:id,sequence:1,type:'STATE',recordedAt:new Date().toISOString(),data:{status,reason:'Browser protocol fixture event only.'}})+'\n\n'}));}
async function reflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}

test('empty unavailable catalogue starts no runs and keeps an honest free source fallback',async({page})=>{
 let mutations=0;await page.route('**/api/v1/lab-manifests',route=>json(route,{items:[],runtime:{enabled:false,reason:'Operator admission evidence is not yet available.'}}));await page.route('**/api/v1/lab-quota',route=>json(route,{error:{code:'UNAUTHENTICATED',message:'Sign in.'}},401));await page.route('**/api/v1/lab-runs',route=>{mutations++;return json(route,{});});
 await page.goto('/labs');await expect(page.getByRole('heading',{name:'No certified labs yet',exact:true})).toBeVisible();await expect(page.getByText('Live execution is unavailable',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Open component library',exact:true})).toHaveAttribute('href','/components');await expect(page.getByRole('button',{name:'Run isolated lab',exact:true})).toHaveCount(0);expect(mutations).toBe(0);await reflow(page);
});
test('disabled or exhausted execution retains editable inputs and freely available setup',async({page})=>{
 const disabled={enabled:false,reason:'Isolation admission is not complete.'};await catalogue(page,{...quota,remaining:0,runtime:disabled},disabled);await page.goto('/labs');await page.getByLabel('Record count',{exact:true}).fill('4');await expect(page.getByRole('button',{name:'Run isolated lab',exact:true})).toBeDisabled();await expect(page.getByLabel('Record count',{exact:true})).toHaveValue('4');await expect(page.getByRole('link',{name:'Free source & setup',exact:true})).toHaveAttribute('href',manifest.sourceUrl);await expect(page.getByText(manifest.setup,{exact:true})).toBeVisible();await reflow(page);
});
test('ambiguous start retries exactly one identity and queued cancellation is truthful',async({page})=>{
 await catalogue(page);await events(page);const requests:{key:string;body:unknown}[]=[];
 await page.route('**/api/v1/lab-runs',async route=>{requests.push({key:route.request().headers()['idempotency-key'],body:route.request().postDataJSON()});if(requests.length===1)return route.abort('failed');if(requests.length===2)return json(route,{error:{code:'RATE_LIMITED',message:'Retry temporarily limited.'}},429);return json(route,run());});
 await page.route('**/api/v1/lab-runs/'+id+'/stop',route=>json(route,run('CANCELLED')));
 await page.goto('/labs');await page.getByLabel('Record count',{exact:true}).fill('3');await page.getByRole('button',{name:'Run isolated lab',exact:true}).click();await expect(page.getByRole('alert')).toContainText('result is uncertain');await expect(page.getByLabel('Record count',{exact:true})).toHaveValue('3');await expect(page.getByLabel('Record count',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Retry same run request',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Retry temporarily limited');await expect(page.getByLabel('Record count',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Retry same run request',exact:true}).click();await expect(page.getByText('Execution not yet verified',{exact:true})).toBeVisible();expect(requests).toHaveLength(3);expect(requests[1]).toEqual(requests[0]);expect(requests[2]).toEqual(requests[0]);await page.getByRole('button',{name:'Stop current run',exact:true}).click();await expect(page.getByText('Cancelled',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Send certified request',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Stop current run',exact:true})).toHaveCount(0);await reflow(page);
});
test('an uncertain operation retains its original identity through a rate-limited retry',async({page})=>{
 await catalogue(page);await events(page,'RUNNING');await page.route('**/api/v1/lab-runs',route=>json(route,run('RUNNING',true)));const requests:{key:string;body:unknown}[]=[];
 await page.route('**/api/v1/lab-runs/'+id+'/requests',route=>{requests.push({key:route.request().headers()['idempotency-key'],body:route.request().postDataJSON()});if(requests.length===1)return route.abort('failed');if(requests.length===2)return json(route,{error:{code:'RATE_LIMITED',message:'Operation retry temporarily limited.'}},429);return json(route,{output:'Recovered original operation',summary:'Browser protocol fixture only.'});});
 await page.goto('/labs');await page.getByLabel('Record count',{exact:true}).fill('3');await page.getByRole('button',{name:'Run isolated lab',exact:true}).click();await expect(page.getByText('Isolated execution verified',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Send certified request',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Retry the same operation');await page.getByRole('button',{name:'Retry same operation',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Operation retry temporarily limited');await expect(page.getByLabel('Record count',{exact:true}).nth(1)).toBeDisabled();await page.getByRole('button',{name:'Retry same operation',exact:true}).click();await expect(page.getByText(/Recovered original operation/)).toBeVisible();expect(requests).toHaveLength(3);expect(requests[1]).toEqual(requests[0]);expect(requests[2]).toEqual(requests[0]);await reflow(page);
});
test('a revoked operation clears run activity and preserves the operation input',async({page})=>{
 await catalogue(page);await events(page,'RUNNING');await page.route('**/api/v1/lab-runs',route=>json(route,run('RUNNING',true)));let operations=0;await page.route('**/api/v1/lab-runs/'+id+'/requests',route=>{operations++;return operations===1?json(route,{output:'Private result fixture',summary:'Synthetic operation response'}):json(route,{error:{code:'LAB_AUTHORITY_REVOKED',message:'Current source authority was revoked.'}},403);});
 await page.goto('/labs');await page.getByLabel('Record count',{exact:true}).fill('2');await page.getByRole('button',{name:'Run isolated lab',exact:true}).click();await expect(page.getByText('Isolated execution verified',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Send certified request',exact:true}).click();await expect(page.getByText(/Private result fixture/)).toBeVisible();await page.getByLabel('Record count',{exact:true}).nth(1).fill('5');await page.getByRole('button',{name:'Send certified request',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Current source authority was revoked');await expect(page.getByText(/Private result fixture/)).toHaveCount(0);await expect(page.getByRole('heading',{name:'No run has been started here',exact:true})).toBeVisible();await expect(page.getByText('Browser protocol fixture event only.',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Send certified request',exact:true})).toHaveCount(0);await expect(page.getByLabel('Retained count',{exact:true})).toHaveValue('5');await reflow(page);
});
test('a recovered expired run cannot send operations or manufacture a new terminal status',async({page})=>{
 await catalogue(page,{...quota,activeRunId:id});await page.route('**/api/v1/lab-runs/'+id,route=>json(route,run('RUNNING',true,new Date(Date.now()-60000).toISOString())));await page.goto('/labs');await expect(page.getByText('This run has expired. Requests are unavailable.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Send certified request',exact:true})).toBeDisabled();await expect(page.getByText('Running',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Run isolated lab',exact:true})).toBeDisabled();await reflow(page);
});
test('operator MFA denial renders no fabricated resource counts or admission controls',async({page})=>{
 await page.route('**/api/v1/admin/labs',route=>json(route,{error:{code:'ADMIN_MFA_REQUIRED',message:'Current administrator MFA is required.'}},403));await page.goto('/workspace/labs');await expect(page.getByRole('heading',{name:'Operator access required',exact:true})).toBeVisible();await expect(page.getByRole('alert')).toContainText('administrator MFA');await expect(page.getByRole('button',{name:'Pause new admissions',exact:true})).toHaveCount(0);await expect(page.getByText('Reserved memory',{exact:true})).toHaveCount(0);await reflow(page);
});

test('operator reasons follow the same 500-character contract as the server',async({page})=>{
 let mutations=0,paused=false;const record=()=>({runtime,paused,pauseReason:'Fixture reason',queued:0,starting:0,running:0,cancelling:0,attention:0,activeReservations:0,memoryReservedMiB:0,dailyReservedMicros:0,monthlyReservedMicros:0});
 await page.route('**/api/v1/admin/labs',route=>json(route,record()));await page.route('**/api/v1/admin/labs/pause-admissions',route=>{mutations++;expect(route.request().postDataJSON().reason.length).toBe(500);paused=true;return json(route,record());});
 await page.goto('/workspace/labs');await expect(page.getByRole('heading',{name:'Current admission',exact:true})).toBeVisible();await expect(page.getByLabel('Decision reason',{exact:true})).toHaveAttribute('maxlength','500');await page.getByLabel('Decision reason',{exact:true}).fill('short');await page.getByRole('button',{name:'Pause new admissions',exact:true}).click();await expect(page.getByRole('alert')).toBeFocused();expect(mutations).toBe(0);await page.getByLabel('Decision reason',{exact:true}).fill('x'.repeat(500));await page.getByRole('button',{name:'Pause new admissions',exact:true}).click();await expect(page.getByRole('status')).toContainText('Admission pause recorded');expect(mutations).toBe(1);await reflow(page);
});
