package com.getlancer.maintenance;

import com.getlancer.shared.ApiError;
import com.getlancer.shared.Pages;
import jakarta.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class MaintenanceRepository {
  private final JdbcTemplate db;
  private static final String OFFER="SELECT o.id,o.engagement_id,o.revision,o.status,o.title,o.scope,o.terms,o.amount_minor,o.currency,o.requests_per_cycle,o.response_hours,o.total_cycles,o.seller_id,o.seller_consented_at,o.buyer_id,o.buyer_consented_at,o.digest,o.created_at,e.title AS engagement_title FROM maintenance_offers o JOIN delivery_engagements e ON e.id=o.engagement_id ";
  // Current membership determines visibility. Final action checks use DeliveryRepository and shared party locks.
  private static final String MEMBER="(e.buyer_user_id=? OR e.builder_user_id=? OR EXISTS(SELECT 1 FROM business_members m WHERE m.business_id=e.business_id AND m.user_id=? AND m.role IN ('OWNER','HIRING_MANAGER')) OR EXISTS(SELECT 1 FROM team_members m WHERE m.team_id=e.team_id AND m.user_id=? AND m.role IN ('OWNER','BUSINESS_MANAGER') AND (m.expires_at IS NULL OR m.expires_at>now())))";
  public MaintenanceRepository(JdbcTemplate db) { this.db=db; }
  private Map<String,Object> one(String sql,Object...args) { var rows=db.queryForList(sql,args); if(rows.isEmpty()) throw new ApiError(404,"NOT_FOUND","Maintenance record not found."); return rows.get(0); }
  public void advisory(String key) { db.queryForObject("SELECT pg_advisory_xact_lock(hashtextextended(?,0))",Object.class,key); }
  public void lockActor(UUID actor) {
    var active=db.queryForList("SELECT id FROM users WHERE id=? AND account_status='ACTIVE' AND email_verified_at IS NOT NULL FOR SHARE",actor);
    if(active.isEmpty()) throw new ApiError(403,"FORBIDDEN","An active verified account is required.");
    db.queryForList("SELECT user_id FROM developer_profiles WHERE user_id=? FOR SHARE",actor);
    db.queryForList("SELECT user_id FROM user_roles WHERE user_id=? ORDER BY role FOR SHARE",actor);
  }
  public Map<String,Object> offer(UUID id,boolean lock) { return one(OFFER+"WHERE o.id=?"+(lock?" FOR UPDATE OF o":""),id); }
  public Map<String,Object> billing(UUID id,boolean lock) { return one("SELECT id,engagement_id,offer_id,payer_id,request_key,amount_minor,currency,requests_per_cycle,response_hours,total_cycles,digest,account_id,mode,status,creation_step,plan_state,subscription_state,provider_plan_id,provider_subscription_id,attention_reason,local_hold,reconcile_generation,reconciled_at,cancel_requested,cancel_confirmed,cancel_state,billing_consented_at,created_at,updated_at,last_reconcile_attempt_at FROM maintenance_subscriptions WHERE id=?"+(lock?" FOR UPDATE":""),id); }
  public Map<String,Object> forOffer(UUID offer,boolean lock) { var rows=db.queryForList("SELECT id,engagement_id,offer_id,payer_id,request_key,amount_minor,currency,requests_per_cycle,response_hours,total_cycles,digest,account_id,mode,status,creation_step,plan_state,subscription_state,provider_plan_id,provider_subscription_id,attention_reason,local_hold,reconcile_generation,reconciled_at,cancel_requested,cancel_confirmed,cancel_state,billing_consented_at,created_at,updated_at,last_reconcile_attempt_at FROM maintenance_subscriptions WHERE offer_id=?"+(lock?" FOR UPDATE":""),offer); return rows.isEmpty()?null:rows.get(0); }
  public Map<String,Object> period(UUID id,boolean lock) { return one("SELECT id,subscription_id,provider_invoice_id,payment_id,order_id,amount_minor,currency,period_start,period_end,status,refunded_minor,pending_refund,transfer_key,transfer_state,transfer_id,reversed_minor,transfer_status,dispute_status,attention_reason,reconciled_at,created_at FROM maintenance_periods WHERE id=?"+(lock?" FOR UPDATE":""),id); }
  public Map<String,Object> request(UUID id,UUID subscription) { return one("SELECT id,subscription_id,period_id,actor_id,request_key,title,description,status,delivery_note,delivery_url,first_response_at,response_due_at,resolved_at,created_at FROM maintenance_requests WHERE id=? AND subscription_id=? FOR UPDATE",id,subscription); }
  public Map<String,Object> list(UUID actor,HttpServletRequest r) {var args=new ArrayList<Object>(List.of(actor,actor,actor,actor));String filter="";if(r.getParameter("engagementId")!=null){args.add(com.getlancer.shared.Support.uuid(r.getParameter("engagementId")));filter=" AND e.id=?";}return Pages.query(db,r,OFFER+"WHERE "+MEMBER+filter+" ORDER BY o.created_at DESC,o.id",args.toArray());}
  public Map<String,Object> sources(UUID actor,HttpServletRequest r) {var args=new ArrayList<Object>(List.of(actor,actor,actor,actor));String filter="";if(r.getParameter("engagementId")!=null){args.add(com.getlancer.shared.Support.uuid(r.getParameter("engagementId")));filter=" AND e.id=?";}return Pages.query(db,r,"SELECT e.id,e.title FROM delivery_engagements e WHERE e.status='COMPLETED' AND "+MEMBER+filter+" ORDER BY e.created_at DESC,e.id",args.toArray());}
  public boolean eligible(Map<String,Object> e,boolean lock) {
    if(lock) {
      if(e.get("businessId")!=null) db.queryForList("SELECT id FROM businesses WHERE id=? FOR SHARE",e.get("businessId"));
      if(e.get("teamId")!=null) db.queryForList("SELECT id FROM teams WHERE id=? FOR SHARE",e.get("teamId"));
      db.queryForList("SELECT u.id FROM users u WHERE u.id IN (?,?,(SELECT owner_id FROM teams WHERE id=?),(SELECT owner_id FROM businesses WHERE id=?)) ORDER BY u.id FOR SHARE",e.get("buyerUserId"),e.get("builderUserId"),e.get("teamId"),e.get("businessId"));
      db.queryForList("SELECT d.user_id FROM developer_profiles d WHERE d.user_id=? OR d.user_id=(SELECT owner_id FROM teams WHERE id=?) ORDER BY d.user_id FOR SHARE",e.get("builderUserId"),e.get("teamId"));
      db.queryForList("SELECT user_id FROM user_roles WHERE user_id IN (?,?,(SELECT owner_id FROM teams WHERE id=?)) ORDER BY user_id,role FOR SHARE",e.get("buyerUserId"),e.get("builderUserId"),e.get("teamId"));
    }
    return db.queryForObject("SELECT count(*) FROM delivery_engagements e WHERE e.id=? AND e.status='COMPLETED' AND ((e.buyer_user_id IS NOT NULL AND EXISTS(SELECT 1 FROM users u JOIN user_roles r ON r.user_id=u.id AND r.role='CLIENT' WHERE u.id=e.buyer_user_id AND u.account_status='ACTIVE' AND u.email_verified_at IS NOT NULL)) OR (e.business_id IS NOT NULL AND EXISTS(SELECT 1 FROM businesses b JOIN users u ON u.id=b.owner_id JOIN business_members m ON m.business_id=b.id AND m.user_id=u.id AND m.role='OWNER' WHERE b.id=e.business_id AND u.account_status='ACTIVE' AND u.email_verified_at IS NOT NULL))) AND EXISTS(SELECT 1 FROM users u JOIN developer_profiles d ON d.user_id=u.id JOIN user_roles r ON r.user_id=u.id AND r.role='DEVELOPER' WHERE (u.id=e.builder_user_id OR u.id=(SELECT owner_id FROM teams WHERE id=e.team_id AND status='ACTIVE')) AND u.account_status='ACTIVE' AND u.email_verified_at IS NOT NULL AND d.approval_status='APPROVED' AND (e.team_id IS NULL OR EXISTS(SELECT 1 FROM team_members m WHERE m.team_id=e.team_id AND m.user_id=u.id AND m.role='OWNER' AND (m.expires_at IS NULL OR m.expires_at>now())))) AND NOT EXISTS(SELECT 1 FROM delivery_disputes d WHERE d.engagement_id=e.id AND d.status='OPEN') AND NOT EXISTS(SELECT 1 FROM payment_attempts p JOIN delivery_milestones m ON m.id=p.milestone_id WHERE m.engagement_id=e.id AND p.status<>'REJECTED' AND (p.status<>'CAPTURED' OR p.refunded_minor>0 OR p.attention_reason IS NOT NULL OR p.transfer_status NOT IN ('CREATED','PENDING','PROCESSED') OR EXISTS(SELECT 1 FROM payment_provider_disputes d WHERE d.attempt_id=p.id AND (d.status<>'won' OR d.deducted_minor>0))))",Integer.class,e.get("id"))>0;
  }
  public void draft(UUID id,UUID engagement,Map<String,Object> terms) {
    db.update("INSERT INTO maintenance_offers(id,engagement_id,revision,title,scope,terms,amount_minor,requests_per_cycle,response_hours,total_cycles) SELECT ?,?,coalesce(max(revision),0)+1,?,?,?,?,?,?,? FROM maintenance_offers WHERE engagement_id=?",id,engagement,terms.get("title"),terms.get("scope"),terms.get("terms"),terms.get("amountMinor"),terms.get("requestsPerCycle"),terms.get("responseHours"),terms.get("totalCycles"),engagement);
  }
  public boolean openOffer(UUID engagement) { return db.queryForObject("SELECT count(*) FROM maintenance_offers WHERE engagement_id=? AND status IN ('DRAFT','OFFERED')",Integer.class,engagement)>0; }
  public boolean enrollmentExists(UUID engagement) { return db.queryForObject("SELECT count(*) FROM maintenance_subscriptions s WHERE s.engagement_id=? AND ((s.provider_subscription_id IS NULL AND NOT s.cancel_confirmed AND s.status<>'REJECTED') OR (s.provider_subscription_id IS NOT NULL AND s.status NOT IN ('CANCELLED','COMPLETED','EXPIRED')) OR EXISTS(SELECT 1 FROM maintenance_periods p WHERE p.subscription_id=s.id AND p.period_end>now()))",Integer.class,engagement)>0; }
  public void offerAction(UUID id,String status,UUID actor,String digest) {
    if(status.equals("OFFERED")) db.update("UPDATE maintenance_offers SET status=?,seller_id=?,seller_consented_at=now(),digest=? WHERE id=?",status,actor,digest,id);
    else if(status.equals("ACCEPTED")) db.update("UPDATE maintenance_offers SET status=?,buyer_id=?,buyer_consented_at=now() WHERE id=?",status,actor,id);
    else db.update("UPDATE maintenance_offers SET status=? WHERE id=?",status,id);
  }
  public void reserve(UUID id,Map<String,Object> o,UUID payer,UUID key,String account,String mode) { db.update("INSERT INTO maintenance_subscriptions(id,engagement_id,offer_id,payer_id,request_key,amount_minor,currency,requests_per_cycle,response_hours,total_cycles,digest,account_id,mode) VALUES(?,?,?,?,?,?,'INR',?,?,?,?,?,?)",id,o.get("engagement_id"),o.get("id"),payer,key,o.get("amount_minor"),o.get("requests_per_cycle"),o.get("response_hours"),o.get("total_cycles"),o.get("digest"),account,mode); }
  public Map<String,Object> key(UUID actor,UUID key) {var rows=db.queryForList("SELECT id,engagement_id,offer_id,payer_id,request_key,amount_minor,currency,requests_per_cycle,response_hours,total_cycles,digest,account_id,mode,status,creation_step,plan_state,subscription_state,provider_plan_id,provider_subscription_id,attention_reason,local_hold,reconcile_generation,reconciled_at,cancel_requested,cancel_confirmed,cancel_state,billing_consented_at,created_at,updated_at,last_reconcile_attempt_at FROM maintenance_subscriptions WHERE payer_id=? AND request_key=?",actor,key);return rows.isEmpty()?null:rows.get(0);}
  public boolean consentAuthority(UUID engagement,UUID actor,String side) {
    return db.queryForObject("SELECT count(*) FROM delivery_engagements e JOIN users u ON u.id=? AND u.account_status='ACTIVE' AND u.email_verified_at IS NOT NULL WHERE e.id=? AND "+(side.equals("BUYER")?"(e.buyer_user_id=u.id AND EXISTS(SELECT 1 FROM user_roles r WHERE r.user_id=u.id AND r.role='CLIENT') OR EXISTS(SELECT 1 FROM business_members m WHERE m.business_id=e.business_id AND m.user_id=u.id AND m.role IN ('OWNER','HIRING_MANAGER')))":"EXISTS(SELECT 1 FROM developer_profiles d JOIN user_roles r ON r.user_id=d.user_id AND r.role='DEVELOPER' WHERE d.user_id=u.id AND d.approval_status='APPROVED') AND (e.builder_user_id=u.id OR EXISTS(SELECT 1 FROM team_members m JOIN teams t ON t.id=m.team_id AND t.status='ACTIVE' WHERE m.team_id=e.team_id AND m.user_id=u.id AND m.role IN ('OWNER','BUSINESS_MANAGER') AND (m.expires_at IS NULL OR m.expires_at>now())))"),Integer.class,actor,engagement)>0;
  }
  public void lockConsentParties(UUID engagement,UUID buyer,UUID payer,UUID seller) {
    db.queryForList("SELECT b.id FROM businesses b JOIN delivery_engagements e ON e.business_id=b.id WHERE e.id=? FOR SHARE OF b",engagement);
    db.queryForList("SELECT t.id FROM teams t JOIN delivery_engagements e ON e.team_id=t.id WHERE e.id=? FOR SHARE OF t",engagement);
    db.queryForList("SELECT m.user_id FROM business_members m JOIN delivery_engagements e ON e.business_id=m.business_id WHERE e.id=? AND m.user_id IN (?,?,?) ORDER BY m.user_id FOR SHARE OF m",engagement,buyer,payer,seller);
    db.queryForList("SELECT m.user_id FROM team_members m JOIN delivery_engagements e ON e.team_id=m.team_id WHERE e.id=? AND m.user_id IN (?,?,?) ORDER BY m.user_id FOR SHARE OF m",engagement,buyer,payer,seller);
    db.queryForList("SELECT id FROM users WHERE id IN (?,?,?) ORDER BY id FOR SHARE",buyer,payer,seller);
    db.queryForList("SELECT user_id FROM developer_profiles WHERE user_id IN (?,?,?) ORDER BY user_id FOR SHARE",buyer,payer,seller);
    db.queryForList("SELECT user_id FROM user_roles WHERE user_id IN (?,?,?) ORDER BY user_id,role FOR SHARE",buyer,payer,seller);
  }
  public boolean bindPlan(UUID id,String plan) {return db.update("UPDATE maintenance_subscriptions SET provider_plan_id=?,plan_state='CONFIRMED',subscription_state='NOT_CREATED',creation_step='SUBSCRIPTION',status='CREATING',attention_reason=null,updated_at=now() WHERE id=? AND provider_plan_id IS NULL",plan,id)==1; }
  public void bindSubscription(UUID id,String subscription,String status) { db.update("UPDATE maintenance_subscriptions SET provider_subscription_id=?,subscription_state='CONFIRMED',creation_step='COMPLETE',status=?,attention_reason=null,updated_at=now() WHERE id=?",subscription,status,id); }
  public void creationFailed(UUID id,String step,boolean rejected) { String state=rejected?"REJECTED":"UNKNOWN"; if(step.equals("PLAN")) db.update("UPDATE maintenance_subscriptions SET plan_state=?,status=?,attention_reason=?,updated_at=now() WHERE id=? AND plan_state='CREATING'",state,state,"Plan creation needs operator verification before any new attempt.",id);else db.update("UPDATE maintenance_subscriptions SET subscription_state=?,status=?,attention_reason=?,updated_at=now() WHERE id=? AND subscription_state='CREATING'",state,state,"Subscription creation needs operator verification before any new attempt.",id); }
  public boolean unattempted(UUID id) {return db.update("UPDATE maintenance_subscriptions SET attention_reason='Plan confirmed; no subscription request was sent. An MFA operator may resume after current consent and eligibility checks.',updated_at=now() WHERE id=? AND subscription_state='NOT_CREATED'",id)==1;}
  public void status(UUID id,String status,boolean terminal) { db.update("UPDATE maintenance_subscriptions SET status=?,cancel_confirmed=cancel_confirmed OR ?,cancel_state=CASE WHEN ? THEN 'CONFIRMED' ELSE cancel_state END,updated_at=now() WHERE id=?",status,terminal,terminal,id); }
  public void fresh(UUID id,java.time.Instant started) { db.update("UPDATE maintenance_subscriptions s SET reconciled_at=now(),attention_reason=null,updated_at=now() WHERE s.id=? AND NOT EXISTS(SELECT 1 FROM maintenance_webhook_events w WHERE w.received_at>? AND w.processed_at IS NULL AND (w.subscription_id=s.provider_subscription_id OR w.payment_id IN (SELECT payment_id FROM maintenance_periods p WHERE p.subscription_id=s.id)))",id,java.sql.Timestamp.from(started)); }
  public void beginReconcile(UUID id) {db.update("UPDATE maintenance_subscriptions SET reconcile_generation=reconcile_generation+1,reconciled_at=null,attention_reason='Financial reconciliation is pending.' WHERE id=?",id);}
  public void stale(UUID id,String reason) { db.update("UPDATE maintenance_subscriptions SET reconciled_at=null,attention_reason=?,updated_at=now() WHERE id=?",reason,id); }
  public void hold(UUID id,boolean held) { db.update("UPDATE maintenance_subscriptions SET local_hold=?,updated_at=now() WHERE id=?",held,id); }
  public void subscriptionReserved(UUID id) {db.update("UPDATE maintenance_subscriptions SET subscription_state='CREATING' WHERE id=? AND subscription_state='NOT_CREATED'",id);}
  public void cancelIntent(UUID id) {db.update("UPDATE maintenance_subscriptions SET cancel_requested=true WHERE id=?",id);}
  public void noSubscriptionCancelled(UUID id) {db.update("UPDATE maintenance_subscriptions SET cancel_requested=true,cancel_confirmed=true,cancel_state='CONFIRMED',subscription_state='REJECTED',status='CANCELLED',attention_reason=null WHERE id=? AND provider_subscription_id IS NULL",id);}
  public void transferObserved(UUID id,String status,long reversed) {db.update("UPDATE maintenance_periods SET reversed_minor=greatest(reversed_minor,?),transfer_status=CASE WHEN greatest(reversed_minor,?)>0 THEN 'REVERSED' ELSE ? END,attention_reason='An unbound transfer was observed; MFA operator binding is required.' WHERE id=?",reversed,reversed,status,id);}
  public List<String> eventDisputes(String payment,java.time.Instant started) {return db.queryForList("SELECT DISTINCT dispute_id FROM maintenance_webhook_events WHERE payment_id=? AND dispute_id IS NOT NULL AND received_at<=? ORDER BY dispute_id LIMIT 501",String.class,payment,java.sql.Timestamp.from(started));}
  public List<String> eventRefunds(String payment,java.time.Instant started) {return db.queryForList("SELECT DISTINCT refund_id FROM maintenance_webhook_events WHERE payment_id=? AND refund_id IS NOT NULL AND received_at<=? ORDER BY refund_id LIMIT 501",String.class,payment,java.sql.Timestamp.from(started));}
  public List<String> knownRefunds(String payment) {return db.queryForList("SELECT r.id FROM maintenance_refunds r JOIN maintenance_periods p ON p.id=r.period_id WHERE p.payment_id=? ORDER BY r.id LIMIT 501",String.class,payment);}
  public List<String> subscriptionEventRefunds(UUID subscription,java.time.Instant started) {return db.queryForList("SELECT DISTINCT w.refund_id FROM maintenance_webhook_events w JOIN maintenance_subscriptions s ON s.id=? WHERE w.refund_id IS NOT NULL AND w.received_at<=? AND (w.subscription_id=s.provider_subscription_id OR w.payment_id IN (SELECT payment_id FROM maintenance_periods p WHERE p.subscription_id=s.id)) ORDER BY w.refund_id LIMIT 10001",String.class,subscription,java.sql.Timestamp.from(started));}
  public boolean unidentifiedRefundEvents(UUID subscription,java.time.Instant started) {return db.queryForObject("SELECT EXISTS(SELECT 1 FROM maintenance_webhook_events w JOIN maintenance_subscriptions s ON s.id=? WHERE w.refund_id IS NULL AND w.event_kind LIKE 'refund.%' AND w.received_at<=? AND (w.subscription_id=s.provider_subscription_id OR w.payment_id IN (SELECT payment_id FROM maintenance_periods p WHERE p.subscription_id=s.id)))",Boolean.class,subscription,java.sql.Timestamp.from(started));}
  public boolean unidentifiedPaymentRefundEvents(String payment,java.time.Instant started) {return db.queryForObject("SELECT EXISTS(SELECT 1 FROM maintenance_webhook_events WHERE payment_id=? AND refund_id IS NULL AND event_kind LIKE 'refund.%' AND received_at<=?)",Boolean.class,payment,java.sql.Timestamp.from(started));}
  public boolean routingEventsUnverified(UUID subscription,java.time.Instant started) {return db.queryForObject("SELECT EXISTS(SELECT 1 FROM maintenance_webhook_events w JOIN maintenance_subscriptions s ON s.id=? WHERE (w.processed_at IS NULL AND w.received_at>? OR w.refund_id IS NULL AND w.event_kind LIKE 'refund.%') AND (w.subscription_id=s.provider_subscription_id OR w.payment_id IN (SELECT payment_id FROM maintenance_periods p WHERE p.subscription_id=s.id)))",Boolean.class,subscription,java.sql.Timestamp.from(started));}
  public void cancelReserved(UUID id) { db.update("UPDATE maintenance_subscriptions SET cancel_requested=true,cancel_state='CREATING',updated_at=now() WHERE id=?",id); }
  public void cancelUnknown(UUID id) { db.update("UPDATE maintenance_subscriptions SET cancel_state='UNKNOWN',attention_reason='Future billing cancellation is not confirmed. Reconcile before retrying.',updated_at=now() WHERE id=? AND NOT cancel_confirmed AND cancel_state IN ('CREATING','UNKNOWN')",id); }
  public List<Map<String,Object>> periods(UUID billing) { return db.queryForList("SELECT id,subscription_id,provider_invoice_id,payment_id,order_id,amount_minor,currency,period_start,period_end,status,refunded_minor,pending_refund,transfer_key,transfer_state,transfer_id,reversed_minor,transfer_status,dispute_status,attention_reason,reconciled_at,created_at FROM maintenance_periods WHERE subscription_id=? ORDER BY period_start DESC,id",billing); }
  public Map<String,Object> byInvoice(String invoice) {var rows=db.queryForList("SELECT id,subscription_id,provider_invoice_id,payment_id,order_id,amount_minor,currency,period_start,period_end,status,refunded_minor,pending_refund,transfer_key,transfer_state,transfer_id,reversed_minor,transfer_status,dispute_status,attention_reason,reconciled_at,created_at FROM maintenance_periods WHERE provider_invoice_id=? FOR UPDATE",invoice);return rows.isEmpty()?null:rows.get(0);}
  public void addPeriod(UUID id,UUID billing,String invoice,String payment,String order,long amount,java.time.Instant start,java.time.Instant end) {db.update("INSERT INTO maintenance_periods(id,subscription_id,provider_invoice_id,payment_id,order_id,amount_minor,currency,period_start,period_end,transfer_key) VALUES(?,?,?,?,?,?,'INR',?,?,?)",id,billing,invoice,payment,order,amount,java.sql.Timestamp.from(start),java.sql.Timestamp.from(end),UUID.randomUUID());ledger(id,"capture:"+payment,"CAPTURE",amount);}
  public void financial(UUID id,long refunded,boolean pending) { var p=period(id,true);long previous=number(p,"refunded_minor"),total=Math.max(previous,refunded);db.update("UPDATE maintenance_periods SET refunded_minor=?,pending_refund=?,status=CASE WHEN ?>0 THEN 'REFUNDED' WHEN ? THEN 'HELD' ELSE 'PAID' END,reconciled_at=now() WHERE id=?",total,pending,total,pending,id);if(total>previous)ledger(id,"refund-total:"+total,"REFUND",total-previous); }
  public void refund(UUID period,String id,long amount,String state) {int changed=db.update("INSERT INTO maintenance_refunds(id,period_id,amount_minor,status) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=CASE WHEN maintenance_refunds.status='processed' THEN 'processed' ELSE excluded.status END,updated_at=now() WHERE maintenance_refunds.period_id=excluded.period_id AND maintenance_refunds.amount_minor=excluded.amount_minor",id,period,amount,state);if(changed!=1)throw mismatch();}
  public boolean pendingRefund(UUID period) {return db.queryForObject("SELECT count(*) FROM maintenance_refunds WHERE period_id=? AND status='pending'",Integer.class,period)>0;}
  public void dispute(UUID period,String id,String state,long deducted) {int n=db.update("INSERT INTO maintenance_provider_disputes(id,period_id,status,deducted_minor) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,deducted_minor=excluded.deducted_minor,updated_at=now() WHERE maintenance_provider_disputes.period_id=excluded.period_id",id,period,state,deducted);if(n!=1)throw mismatch();db.update("UPDATE maintenance_periods p SET dispute_status=CASE WHEN EXISTS(SELECT 1 FROM maintenance_provider_disputes d WHERE d.period_id=p.id AND (d.status<>'won' OR d.deducted_minor>0)) THEN 'HELD' ELSE 'WON' END WHERE id=?",period);}
  public List<String> knownDisputes(UUID period) {return db.queryForList("SELECT id FROM maintenance_provider_disputes WHERE period_id=? ORDER BY id LIMIT 501",String.class,period);}
  public void transferReserved(UUID id) {db.update("UPDATE maintenance_periods SET transfer_state='CREATING',attention_reason='Routing reservation committed; provider confirmation pending.' WHERE id=? AND transfer_state='NOT_CREATED'",id);}
  public void transferUnknown(UUID id,boolean rejected) {db.update("UPDATE maintenance_periods SET transfer_state=?,transfer_status='UNKNOWN',attention_reason='Payment routing requires operator verification. Do not repeat the transfer.' WHERE id=? AND transfer_id IS NULL",rejected?"REJECTED":"UNKNOWN",id);}
  public void transferBound(UUID id,String transfer,String status,long reversed) {db.update("UPDATE maintenance_periods SET transfer_id=?,transfer_state='CONFIRMED',reversed_minor=greatest(reversed_minor,?),transfer_status=CASE WHEN greatest(reversed_minor,?)>0 THEN 'REVERSED' ELSE ? END,attention_reason=CASE WHEN greatest(reversed_minor,?)=0 AND ? IN ('CREATED','PENDING','PROCESSED') THEN null ELSE 'Transfer is held, failed or reversed.' END WHERE id=?",transfer,reversed,reversed,status,reversed,status,id);if(Set.of("CREATED","PENDING","PROCESSED").contains(status)&&reversed==0)ledger(id,"transfer:"+transfer,"TRANSFER",number(period(id,false),"amount_minor"));}
  public Map<String,Object> currentPeriod(UUID billing) { var rows=db.queryForList("SELECT p.id,p.subscription_id,p.provider_invoice_id,p.payment_id,p.order_id,p.amount_minor,p.currency,p.period_start,p.period_end,p.status,p.refunded_minor,p.pending_refund,p.transfer_key,p.transfer_state,p.transfer_id,p.reversed_minor,p.transfer_status,p.dispute_status,p.attention_reason,p.reconciled_at,p.created_at,(SELECT count(*) FROM maintenance_requests r WHERE r.period_id=p.id) AS used_requests FROM maintenance_periods p WHERE p.subscription_id=? AND p.period_start<=now() AND p.period_end>now() ORDER BY p.period_start FOR UPDATE OF p",billing);return rows.size()==1?rows.get(0):null; }
  public boolean financiallyClear(Map<String,Object> p) {return number(p,"refunded_minor")==0&&!Boolean.TRUE.equals(p.get("pending_refund"))&&!"HELD".equals(p.get("dispute_status"))&&p.get("transfer_state").equals("CONFIRMED")&&Set.of("CREATED","PENDING","PROCESSED").contains(Objects.toString(p.get("transfer_status")))&&p.get("attention_reason")==null;}
  public boolean freshAndClear(Map<String,Object> s,Map<String,Object> p) {return financiallyClear(p)&&s.get("reconciled_at")!=null&&MaintenanceBillingService.instant(s.get("reconciled_at")).isAfter(java.time.Instant.now().minusSeconds(300))&&db.queryForObject("SELECT count(*) FROM maintenance_webhook_events w WHERE (w.processed_at IS NULL OR w.refund_id IS NULL AND w.event_kind LIKE 'refund.%') AND (w.subscription_id=? OR w.payment_id IN (SELECT payment_id FROM maintenance_periods WHERE subscription_id=?))",Integer.class,s.get("provider_subscription_id"),s.get("id"))==0;}
  public void request(UUID id,UUID billing,UUID period,UUID actor,UUID key,String title,String description,int responseHours) {db.update("INSERT INTO maintenance_requests(id,subscription_id,period_id,actor_id,request_key,title,description,response_due_at) VALUES(?,?,?,?,?,?,?,now()+make_interval(hours=>?))",id,billing,period,actor,key,title,description,responseHours);}
  public Map<String,Object> requestKey(UUID actor,UUID key) {var rows=db.queryForList("SELECT id,subscription_id,period_id,actor_id,request_key,title,description,status,delivery_note,delivery_url,first_response_at,response_due_at,resolved_at,created_at FROM maintenance_requests WHERE actor_id=? AND request_key=?",actor,key);return rows.isEmpty()?null:rows.get(0);}
  public void requestAction(UUID id,String state,String note,String url,boolean seller,boolean resolved) {db.update("UPDATE maintenance_requests SET status=?,delivery_note=coalesce(?,delivery_note),delivery_url=coalesce(?,delivery_url),first_response_at=CASE WHEN ? THEN coalesce(first_response_at,now()) ELSE first_response_at END,resolved_at=CASE WHEN ? THEN now() ELSE resolved_at END WHERE id=?",state,note,url,seller,resolved,id);}
  public Map<String,Object> requests(UUID billing,HttpServletRequest r) {return Pages.query(db,r,"SELECT id,period_id AS \"invoiceId\",title,description,status,delivery_note AS \"deliveryNote\",delivery_url AS \"deliveryUrl\",created_at AS \"createdAt\",first_response_at AS \"firstResponseAt\",response_due_at AS \"responseDueAt\",resolved_at AS \"resolvedAt\" FROM maintenance_requests WHERE subscription_id=? ORDER BY created_at DESC,id",billing);}
  public List<Map<String,Object>> activity(UUID offer) {return db.queryForList("SELECT id,kind,detail,created_at AS \"createdAt\" FROM maintenance_audit WHERE offer_id=? ORDER BY created_at DESC,id LIMIT 100",offer);}
  public void audit(UUID offer,UUID actor,String kind,String detail) {db.update("INSERT INTO maintenance_audit(id,offer_id,actor_id,kind,detail) VALUES(?,?,?,?,?)",UUID.randomUUID(),offer,actor,kind,detail);}
  public void ledger(UUID period,String key,String kind,long amount) {db.update("INSERT INTO maintenance_ledger(id,period_id,entry_key,kind,amount_minor) VALUES(?,?,?,?,?) ON CONFLICT(period_id,entry_key) DO NOTHING",UUID.randomUUID(),period,key,kind,amount);}
  public Map<String,Object> attention(HttpServletRequest r) {return Pages.query(db,r,"SELECT s.id,s.offer_id AS \"offerId\",s.status,s.mode,s.creation_step AS \"creationStep\",s.provider_plan_id AS \"providerPlanId\",s.provider_subscription_id AS \"providerSubscriptionId\",s.amount_minor AS \"amountMinor\",s.account_id AS \"accountId\",s.attention_reason AS \"attentionReason\",s.local_hold AS \"localHold\",s.cancel_state AS \"cancelState\" FROM maintenance_subscriptions s WHERE s.attention_reason IS NOT NULL OR s.local_hold OR (s.cancel_requested AND NOT s.cancel_confirmed) OR s.status IN ('CREATING','UNKNOWN','REJECTED') OR EXISTS(SELECT 1 FROM maintenance_periods p WHERE p.subscription_id=s.id AND (p.attention_reason IS NOT NULL OR p.pending_refund OR p.refunded_minor>0 OR p.dispute_status='HELD')) ORDER BY s.created_at,s.id");}
  public void event(String id,String hash,String kind,String subscription,String payment,String dispute,String refund) {
    advisory("maintenance-event:"+id);var rows=db.queryForList("SELECT event_id,payload_hash,event_kind,subscription_id,payment_id,dispute_id,processed_at,received_at,attempts,refund_id FROM maintenance_webhook_events WHERE event_id=?",id);
    if(!rows.isEmpty()){var old=rows.get(0);if(!Objects.equals(old.get("payload_hash"),hash)||!Objects.equals(old.get("event_kind"),kind)||!Objects.equals(old.get("subscription_id"),subscription)||!Objects.equals(old.get("payment_id"),payment)||!Objects.equals(old.get("dispute_id"),dispute)||old.get("refund_id")!=null&&!Objects.equals(old.get("refund_id"),refund))throw new ApiError(409,"WEBHOOK_CONFLICT","Event identifier has a different signed payload or provider reference.");if(old.get("refund_id")==null&&refund!=null)db.update("UPDATE maintenance_webhook_events SET refund_id=? WHERE event_id=? AND refund_id IS NULL",refund,id);return;}
    db.update("INSERT INTO maintenance_webhook_events(event_id,payload_hash,event_kind,subscription_id,payment_id,dispute_id,refund_id) VALUES(?,?,?,?,?,?,?)",id,hash,kind,subscription,payment,dispute,refund);
  }
  public void attempted(UUID id) {db.update("UPDATE maintenance_subscriptions SET last_reconcile_attempt_at=now() WHERE id=?",id);}
  public List<UUID> pending() {return db.queryForList("SELECT s.id FROM maintenance_subscriptions s WHERE s.provider_subscription_id IS NOT NULL AND (s.cancel_requested AND NOT s.cancel_confirmed OR s.reconciled_at IS NULL OR s.reconciled_at<now()-interval '5 minutes' OR EXISTS(SELECT 1 FROM maintenance_webhook_events w WHERE w.processed_at IS NULL AND (w.subscription_id=s.provider_subscription_id OR w.payment_id IN (SELECT payment_id FROM maintenance_periods p WHERE p.subscription_id=s.id)))) ORDER BY s.last_reconcile_attempt_at NULLS FIRST,s.updated_at,s.id LIMIT 5",UUID.class);}
  public void processed(UUID id,java.time.Instant started) {db.update("UPDATE maintenance_webhook_events SET processed_at=now(),attempts=attempts+1 WHERE processed_at IS NULL AND received_at<=? AND (subscription_id=(SELECT provider_subscription_id FROM maintenance_subscriptions WHERE id=?) OR payment_id IN (SELECT payment_id FROM maintenance_periods WHERE subscription_id=?))",java.sql.Timestamp.from(started),id,id);}
  public static long number(Map<String,Object> row,String key) {return ((Number)row.get(key)).longValue();}
  static ApiError mismatch() {return new ApiError(409,"PROVIDER_MISMATCH","Provider facts do not match the frozen maintenance agreement. Ask the operator to reconcile it.");}
}
