package com.getlancer.maintenance;

import static com.getlancer.maintenance.MaintenanceRepository.number;
import static com.getlancer.shared.Support.hash;
import static com.getlancer.shared.Support.id;
import static com.getlancer.shared.Support.text;
import static com.getlancer.shared.Support.uuid;

import com.getlancer.security.Security;
import com.getlancer.shared.ApiError;
import com.getlancer.shared.Pages;
import jakarta.servlet.http.HttpServletRequest;
import java.net.URI;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;
import java.util.function.Supplier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

@Service
public class MaintenanceService {
  private final MaintenanceRepository repo; private final MaintenanceAccess access; private final MaintenanceBillingService billing; private final Security security; private final TransactionTemplate transaction;
  public MaintenanceService(MaintenanceRepository repo,MaintenanceAccess access,MaintenanceBillingService billing,Security security,PlatformTransactionManager manager){this.repo=repo;this.access=access;this.billing=billing;this.security=security;transaction=new TransactionTemplate(manager);}
  private <T>T tx(Supplier<T> work){return transaction.execute(s->work.get());}
  public Map<String,Object> configuration(HttpServletRequest r){access.delivery.verified(r);return billing.configuration();}
  public Map<String,Object> list(HttpServletRequest r){return tx(()->{var page=repo.list(access.delivery.verified(r),r);var items=new ArrayList<Map<String,Object>>();var ordered=new ArrayList<>(Pages.items(page));ordered.sort(Comparator.comparing(o->o.get("engagement_id").toString()));for(var o:ordered){try{items.add(offerSummary(access.offer((UUID)o.get("id"),r,"ANY",false)));}catch(ApiError e){if(e.status!=404&&e.status!=403)throw e;}}items.sort(Comparator.comparing(o->Pages.items(page).stream().map(x->x.get("id")).toList().indexOf(o.get("id"))));page.put("items",items);return page;});}
  public Map<String,Object> sources(HttpServletRequest r){return tx(()->{var page=repo.sources(access.delivery.verified(r),r);var items=new ArrayList<Map<String,Object>>();var ordered=new ArrayList<>(Pages.items(page));ordered.sort(Comparator.comparing(o->o.get("id").toString()));for(var source:ordered){try{var e=access.delivery.lockEngagement((UUID)source.get("id"),r,"ANY");if(access.eligible(e))items.add(Map.of("id",e.get("id"),"title",e.get("title"),"side",e.get("side")));}catch(ApiError e){if(e.status!=404&&e.status!=403)throw e;}}page.put("items",items);return page;});}
  static long bounded(Map<String,Object> body,String key,long min,long max){Object value=body.get(key);if(!(value instanceof Number n)||!n.toString().matches("[0-9]+"))throw new ApiError(400,"VALIDATION_ERROR","Enter a whole number for "+key+".",Map.of(key,"Use a whole number between "+min+" and "+max+"."));long result;try{result=Long.parseLong(n.toString());}catch(NumberFormatException e){throw new ApiError(400,"VALIDATION_ERROR","Invalid "+key+".");}if(result<min||result>max)throw new ApiError(400,"VALIDATION_ERROR","Check "+key+".",Map.of(key,"Use a whole number between "+min+" and "+max+"."));return result;}
  public Map<String,Object> create(Map<String,Object> body,HttpServletRequest r){UUID engagement=uuid(body.get("engagementId"));var terms=new LinkedHashMap<String,Object>();terms.put("title",text(body,"title",3,100));terms.put("scope",text(body,"scope",20,4000));terms.put("terms",text(body,"terms",40,8000));terms.put("amountMinor",bounded(body,"amountMinor",100,1000000000));terms.put("requestsPerCycle",bounded(body,"requestsPerCycle",1,50));terms.put("responseHours",bounded(body,"responseHours",1,720));terms.put("totalCycles",bounded(body,"totalCycles",1,12));return tx(()->{var e=access.delivery.lockEngagement(engagement,r,"SELLER");repo.lockActor(security.user(r));e=access.delivery.lockEngagement(engagement,r,"SELLER");access.requireEligible(e);if(repo.openOffer(engagement)||repo.enrollmentExists(engagement))throw new ApiError(409,"MAINTENANCE_CONFLICT","An outstanding offer or existing enrollment must finish before new terms.");UUID id=UUID.randomUUID();repo.draft(id,engagement,terms);repo.audit(id,security.user(r),"OFFER_DRAFTED","Monthly maintenance terms drafted for completed work.");return Map.of("id",id);});}
  private static String digest(Map<String,Object> o){return hash(List.of(o.get("id"),o.get("engagement_id"),o.get("revision"),o.get("title"),o.get("scope"),o.get("terms"),o.get("amount_minor"),o.get("currency"),o.get("requests_per_cycle"),o.get("response_hours"),o.get("total_cycles")).stream().map(value->{String s=value.toString();return s.length()+":"+s;}).reduce("",String::concat));}
  public Map<String,Object> offerAction(UUID id,String action,Map<String,Object> body,HttpServletRequest r){return tx(()->{String side=Set.of("send","withdraw").contains(action)?"SELLER":"BUYER";var o=access.offer(id,r,side,Set.of("send","accept").contains(action));String status=o.get("status").toString(),next;
    switch(action){case "send"->{if(!status.equals("DRAFT"))throw conflict();consent(body);next="OFFERED";}case "accept"->{if(!status.equals("OFFERED"))throw conflict();consent(body);if(!Objects.equals(body.get("digest"),o.get("digest")))throw new ApiError(409,"TERMS_CHANGED","Reload and review the exact offered terms before accepting.");next="ACCEPTED";}case "withdraw"->{if(!Set.of("DRAFT","OFFERED").contains(status))throw conflict();next="WITHDRAWN";}case "reject"->{if(!status.equals("OFFERED"))throw conflict();next="REJECTED";}default->throw new ApiError(400,"VALIDATION_ERROR","Unknown maintenance offer action.");}
    repo.offerAction(id,next,security.user(r),digest(o));repo.audit(id,security.user(r),"OFFER_"+next,"Maintenance offer "+next.toLowerCase(Locale.ROOT)+" recorded against its immutable terms.");return offerSummary(access.offer(id,r,"ANY",false));});}
  private static void consent(Map<String,Object> body){if(!Boolean.TRUE.equals(body.get("consent")))throw new ApiError(400,"CONSENT_REQUIRED","Read and explicitly consent to these maintenance terms.");}
  private static ApiError conflict(){return new ApiError(409,"INVALID_STATE","This action is not available in the current state. Refresh the record.");}
  public Map<String,Object> detail(UUID id,HttpServletRequest r){return tx(()->{var o=access.offer(id,r,"ANY",false);var e=access.delivery.lockEngagement((UUID)o.get("engagement_id"),r,"ANY");var result=offerSummary(o);var s=repo.forOffer(id,true);result.put("billing",s==null?null:MaintenanceBillingService.summary(s));result.put("entitlement",entitlement(e,s));result.put("invoices",s==null?List.of():repo.periods((UUID)s.get("id")).stream().map(p->invoiceSummary(p,s)).toList());var requests=s==null?Map.of("items",List.of(),"page",0,"hasMore",false,"totalItems",0):repo.requests((UUID)s.get("id"),r);result.put("requests",requests.get("items"));result.put("requestPage",requests);result.put("activity",repo.activity(id));return result;});}
  private Map<String,Object> entitlement(Map<String,Object> e,Map<String,Object> s){var out=new LinkedHashMap<String,Object>();out.put("available",false);out.put("usedRequests",0);out.put("remainingRequests",0);out.put("requestLimit",s==null?0:s.get("requests_per_cycle"));String reason="Accept the agreement and authorize billing. A live paid invoice is required.";
    if(s!=null){var p=repo.currentPeriod((UUID)s.get("id"));boolean parties=access.eligible(e);reason=!parties?"The engagement or a party is ineligible; support is held.":!s.get("mode").equals("live")?"Test payments do not grant real support access.":Boolean.TRUE.equals(s.get("local_hold"))?"An operator hold prevents new support requests.":p==null?"No unique current paid invoice period is available.":!repo.freshAndClear(s,p)?"Financial reconciliation or routing requires review before new support.":"Live paid period verified.";
      boolean available=parties&&s.get("mode").equals("live")&&!Boolean.TRUE.equals(s.get("local_hold"))&&p!=null&&repo.freshAndClear(s,p);out.put("available",available);if(p!=null){long used=number(p,"used_requests"),limit=number(s,"requests_per_cycle");out.put("invoiceId",p.get("id"));out.put("periodStart",p.get("period_start"));out.put("periodEnd",p.get("period_end"));out.put("usedRequests",used);out.put("remainingRequests",available?Math.max(0,limit-used):0);}}
    out.put("reason",reason);return out;}
  public Map<String,Object> request(UUID offer,Map<String,Object> body,HttpServletRequest r){UUID key=uuid(r.getHeader("Idempotency-Key"));String title=text(body,"title",3,100),description=text(body,"description",20,4000);UUID billingId=tx(()->{access.offer(offer,r,"BUYER",true);var s=repo.forOffer(offer,true);if(s==null)throw new ApiError(409,"SUPPORT_NOT_ENTITLED","A paid billing period is required.");return (UUID)s.get("id");});billing.reconcile(billingId);
    return tx(()->{UUID actor=security.user(r);repo.advisory("maintenance-request:"+actor+":"+key);var o=access.offer(offer,r,"BUYER",true);var s=repo.forOffer(offer,true);var previous=repo.requestKey(actor,key);if(previous!=null){if(!previous.get("subscription_id").equals(s.get("id"))||!previous.get("title").equals(title)||!previous.get("description").equals(description))throw new ApiError(409,"IDEMPOTENCY_CONFLICT","Request key belongs to different support content.");return Map.of("id",previous.get("id"));}
      var e=access.delivery.lockEngagement((UUID)o.get("engagement_id"),r,"BUYER");var accessState=entitlement(e,s);if(!Boolean.TRUE.equals(accessState.get("available")))throw new ApiError(409,"SUPPORT_NOT_ENTITLED",accessState.get("reason").toString());if(((Number)accessState.get("remainingRequests")).intValue()<1)throw new ApiError(409,"SUPPORT_QUOTA_EXHAUSTED","All requests in this paid period have been used. Cancelled requests also count.");UUID id=UUID.randomUUID();repo.request(id,(UUID)s.get("id"),(UUID)accessState.get("invoiceId"),actor,key,title,description,(int)number(s,"response_hours"));repo.audit(offer,actor,"REQUEST_OPENED",title);return Map.of("id",id);});}
  public Map<String,Object> requestAction(UUID offer,UUID request,String action,Map<String,Object> body,HttpServletRequest r){UUID billingId=tx(()->{var o=access.offer(offer,r,Set.of("start","submit").contains(action)?"SELLER":"BUYER",true);var s=repo.forOffer((UUID)o.get("id"),true);if(s==null)throw new ApiError(409,"SUPPORT_HELD","No paid billing period is available.");repo.request(request,(UUID)s.get("id"));return (UUID)s.get("id");});billing.reconcile(billingId);return tx(()->{boolean seller=Set.of("start","submit").contains(action);var o=access.offer(offer,r,seller?"SELLER":"BUYER",true);var s=repo.forOffer(offer,true);if(s==null||Boolean.TRUE.equals(s.get("local_hold")))throw new ApiError(409,"SUPPORT_HELD","Support is held for operator review.");var item=repo.request(request,(UUID)s.get("id"));var period=repo.period((UUID)item.get("period_id"),true);if(!repo.freshAndClear(s,period))throw new ApiError(409,"SUPPORT_HELD","The request's paid period has a financial hold.");String status=item.get("status").toString(),next,note=null,url=null,detail=item.get("title").toString();
    switch(action){case "start"->{if(!Set.of("OPEN","REVISION_REQUESTED").contains(status))throw conflict();next="IN_PROGRESS";}case "submit"->{if(!status.equals("IN_PROGRESS"))throw conflict();next="SUBMITTED";note=text(body,"deliveryNote",10,4000);url=safeUrl(text(body,"deliveryUrl",0,500));detail=note;}case "accept"->{if(!status.equals("SUBMITTED"))throw conflict();next="RESOLVED";}case "request-revision"->{if(!status.equals("SUBMITTED"))throw conflict();next="REVISION_REQUESTED";detail=text(body,"reason",10,2000);}case "cancel"->{if(!Set.of("OPEN","REVISION_REQUESTED").contains(status))throw conflict();next="CANCELLED";}default->throw new ApiError(400,"VALIDATION_ERROR","Unknown support request action.");}
    repo.requestAction(request,next,note,url,seller,next.equals("RESOLVED"));repo.audit(offer,security.user(r),"REQUEST_"+next,detail.length()>2000?detail.substring(0,2000):detail);return Map.of("id",request,"status",next);});}
  private static String safeUrl(String value){if(value.isBlank())return null;try{URI u=URI.create(value);if(!"https".equalsIgnoreCase(u.getScheme())||u.getHost()==null||u.getUserInfo()!=null||(u.getPort()!=-1&&u.getPort()!=443))throw new IllegalArgumentException();return value;}catch(IllegalArgumentException e){throw new ApiError(400,"VALIDATION_ERROR","Use an HTTPS delivery URL without credentials.",Map.of("deliveryUrl","Use a public HTTPS URL."));}}
  static Map<String,Object> offerSummary(Map<String,Object> o){var out=new LinkedHashMap<String,Object>();for(String key:List.of("id","title","scope","terms","status","currency","digest","revision","side"))out.put(key,o.get(key));out.put("engagementId",o.get("engagement_id"));out.put("engagementTitle",o.get("engagement_title"));out.put("amountMinor",o.get("amount_minor"));out.put("requestsPerCycle",o.get("requests_per_cycle"));out.put("responseHours",o.get("response_hours"));out.put("totalCycles",o.get("total_cycles"));out.put("sellerConsentActorId",o.get("seller_id"));out.put("buyerConsentActorId",o.get("buyer_id"));out.put("sellerConsentedAt",o.get("seller_consented_at"));out.put("buyerConsentedAt",o.get("buyer_consented_at"));out.put("createdAt",o.get("created_at"));return out;}
  private static Map<String,Object> invoiceSummary(Map<String,Object> p,Map<String,Object> s){var out=new LinkedHashMap<String,Object>();for(String key:List.of("id","status","currency"))out.put(key,p.get(key));out.put("providerInvoiceId",p.get("provider_invoice_id"));out.put("amountMinor",p.get("amount_minor"));out.put("periodStart",p.get("period_start"));out.put("periodEnd",p.get("period_end"));out.put("refundedMinor",p.get("refunded_minor"));out.put("pendingRefund",p.get("pending_refund"));out.put("attentionReason",p.get("attention_reason"));out.put("transferStatus",p.get("transfer_status"));out.put("disputeStatus",p.get("dispute_status"));out.put("mode",s.get("mode"));return out;}
  public Map<String,Object> start(UUID id,Map<String,Object> b,HttpServletRequest r){return billing.start(id,b,r);}public Map<String,Object> confirm(UUID id,Map<String,Object>b,HttpServletRequest r){return billing.confirm(id,b,r);}public Map<String,Object> refresh(UUID id,HttpServletRequest r){billing.refresh(id,r);return detail(id,r);}public Map<String,Object> cancel(UUID id,HttpServletRequest r){billing.cancel(id,r);return detail(id,r);}public Map<String,Object> attention(HttpServletRequest r){return billing.attention(r);}public Map<String,Object> operator(UUID id,String action,Map<String,Object>b,HttpServletRequest r){return billing.operator(id,action,b,r);}public Map<String,Object> webhook(HttpServletRequest r){return billing.webhook(r);}
}
