'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Search,Bookmark,Layers,Inbox,Send,UserRound,ShieldCheck,RotateCcw,ArrowUpRight,Plus,CheckCircle2,Mail,FlaskConical,ChartNoAxesCombined} from 'lucide-react';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import Preview from '@/app/components/preview';
import WorkspaceOverview from '@/app/components/workspace-overview';
import ReviewFields from '@/app/components/review-fields';
import ProposalReport from '@/app/components/proposal-report';
import {categories,technologies,label,availabilityLabel} from '@/lib/catalog';
import {applyDemoAction,createDemoState,publicDemoProjects,builderSteps,DEMO_STORAGE_KEY,type DemoState,type DemoAction,type DemoProject,type DemoRequest} from '@/lib/demo-state';

type Modal={type:'project'|'inquire'|'draft'|'request'|'project-review'|'profile-review'|'review-review'|'report'|'report-review';id?:string};
const accountLabels:Record<string,string>={alex:'Client · Alex',leah:'Builder · Leah',daniel:'Builder · Daniel',sam:'Administrator · Sam'};
const budgets=['UNDER_1K','USD_1K_3K','USD_3K_10K','USD_10K_25K','USD_25K_PLUS','NEED_ESTIMATE'];
const timelines=['WITHIN_MONTH','ONE_TO_THREE_MONTHS','THREE_TO_SIX_MONTHS','FLEXIBLE'];
const titles:Record<string,string>={explore:'Find the software. Meet its builder.',saved:'Your shortlist, ready when you are.',showcases:'Make your best work visible.',inquiries:'Turn interest into your next project.',requests:'Your projects, from brief to delivery.',profile:'Let clients get to know you.',analytics:'Follow the work your showcases create.',admin:'Keep real work at the heart of getLancer.'};

export default function WorkspacePreview(){
 const [state,setState]=useState<DemoState>(createDemoState),[actorId,setActorId]=useState('alex'),[tab,setTab]=useState('explore');
 const [ready,setReady]=useState(false),[storageIssue,setStorageIssue]=useState(false),[reset,setReset]=useState(false);
 const [modal,setModal]=useState<Modal|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[technology,setTechnology]=useState(''),[projectType,setProjectType]=useState(''),[available,setAvailable]=useState(false),[sort,setSort]=useState('recent');
 const [lifecycle,setLifecycle]=useState('ACTIVE'),[requestFilter,setRequestFilter]=useState('');
 useEffect(()=>{
  try{const raw=sessionStorage.getItem(DEMO_STORAGE_KEY);if(raw){const saved=JSON.parse(raw);if(saved.state?.version===1&&saved.state.people?.length===4&&Array.isArray(saved.state.projects)&&Array.isArray(saved.state.requests)&&Array.isArray(saved.state.reports)&&Array.isArray(saved.state.audit)&&saved.state.saved){setState(saved.state);if(accountLabels[saved.actorId])setActorId(saved.actorId);if(Object.hasOwn(titles,saved.tab))setTab(saved.tab);}else setMessage('The previous demo was reset to the current sample data.');}}
  catch{setStorageIssue(true);}finally{setReady(true);}
 },[]);
 useEffect(()=>{if(ready)try{sessionStorage.setItem(DEMO_STORAGE_KEY,JSON.stringify({state,actorId,tab}));}catch{setStorageIssue(true);}},[state,actorId,tab,ready]);
 const me=state.people.find(p=>p.id===actorId)||state.people[0];
 const who=(id:string)=>state.people.find(p=>p.id===id)?.name||'Sample account';
 const own=state.projects.filter(p=>p.ownerId===me.id),active=own.filter(p=>p.lifecycleStatus==='ACTIVE').length;
 const received=state.requests.filter(r=>r.builderId===me.id&&r.status!=='CREATED_UNVERIFIED');
 const sent=state.requests.filter(r=>r.clientId===me.id);
 const pendingProjects=state.projects.filter(p=>p.approvalStatus==='PENDING_REVIEW'),pendingProfiles=state.people.filter(p=>p.profile==='PROFILE_PENDING');
 const pendingReviews=state.requests.filter(r=>r.review?.status==='PENDING'),openReports=state.reports.filter(r=>r.status==='OPEN');
 const selectedProject=state.projects.find(p=>p.id===modal?.id),selectedRequest=state.requests.find(r=>r.id===modal?.id);
 const selectedProfile=state.people.find(p=>p.id===modal?.id),selectedReport=state.reports.find(r=>r.id===modal?.id);
 function act(action:DemoAction,notice='Demo changes saved.'){
  try{setState(applyDemoAction(state,me.id,action));setError('');setMessage(notice);return true;}catch(e){setError((e as Error).message);return false;}
 }
 function open(value:Modal){setError('');setModal(value);}
 function changeAccount(id:string,nextTab?:string){setActorId(id);setTab(nextTab||(id==='sam'?'admin':id==='alex'?'explore':'showcases'));setModal(null);setMessage('');setError('');setRequestFilter('');}
 function submitDraft(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);if(act({type:'draft',id:modal?.id,title:String(data.get('title')),summary:String(data.get('summary')),description:String(data.get('description')),contribution:String(data.get('contribution')),category:String(data.get('category')),technology:String(data.get('technology')),projectType:String(data.get('projectType')),rightsConfirmed:data.get('rightsConfirmed')==='on'},'Draft saved. Add sample proof, then submit it for review.')){setModal(null);setLifecycle('DRAFT');setTab('showcases');}}
 const publicProjects=publicDemoProjects(state);
 const gallery=publicProjects.filter(p=>(tab!=='saved'||state.saved[me.id]?.includes(p.id))&&(!query||`${p.title} ${p.summary} ${p.builder} ${p.technology}`.toLowerCase().includes(query.toLowerCase().trim()))&&(!category||p.category===category)&&(!technology||p.technology===technology)&&(!projectType||p.projectType===projectType)&&(!available||['AVAILABLE_NOW','ONE_SLOT_LEFT','LIMITED'].includes(state.people.find(u=>u.id===p.ownerId)?.availability||''))).sort((a,b)=>sort==='name'?a.title.localeCompare(b.title):b.updatedAt.localeCompare(a.updatedAt));
 const showcaseItems=own.filter(p=>p.lifecycleStatus===lifecycle);
 const requestItems=(tab==='inquiries'?received:sent).filter(r=>!requestFilter||r.status===requestFilter);
 const actionHint=(r:DemoRequest)=>r.status==='CREATED_UNVERIFIED'?'Client: open the demo inbox and confirm the inquiry.':['HIRE_PENDING_CONFIRMATION','COMPLETION_PENDING_CONFIRMATION'].includes(r.status)?'Client: review and confirm the agreed outcome.':r.status==='COMPLETED'?(r.review?(r.review.status==='PENDING'?'Administrator: moderate the submitted review.':'Review moderation is complete.'):'Client: share your experience in a review.'):r.status==='NOT_HIRED'?'This request is closed.':`Builder: ${builderSteps[r.status]?.label.toLowerCase()||'review this inquiry'}.`;
 const nextActor=(r:DemoRequest)=>r.status==='CREATED_UNVERIFIED'||['HIRE_PENDING_CONFIRMATION','COMPLETION_PENDING_CONFIRMATION','COMPLETED'].includes(r.status)?r.status==='COMPLETED'&&r.review?.status==='PENDING'?'sam':r.clientId:r.builderId;
 function projectCard(p:DemoProject,index:number,management=false){const saved=state.saved[me.id]?.includes(p.id);return <article className="project demo-card" key={p.id}>
  <button className={'thumbnail tone-'+index%6} onClick={()=>open({type:'project',id:p.id})} aria-label={'Preview '+p.title}><Preview product={p}/></button>
  <div className="cardtitle"><h3>{p.title}</h3>{!management&&<button className="iconbutton" aria-label={(saved?'Unsave ':'Save ')+p.title} aria-pressed={!!saved} onClick={()=>act({type:'save',id:p.id},saved?'Removed from your demo shortlist.':'Saved to your demo shortlist.')}><Bookmark size={19} fill={saved?'currentColor':'none'}/></button>}</div>
  <p className="summary">{p.summary}</p><div className="tags"><span className="tag">{p.technology}</span><span className="tag">{label(p.projectType)}</span><span className="tag">{p.category}</span></div>
  {management?<><p className="demo-status">{label(p.approvalStatus)} · {label(p.lifecycleStatus)}</p>{p.moderationReason&&<p className="samplebar">{p.moderationReason}</p>}<div className="demo-actions">
   <button className="button" disabled={p.lifecycleStatus==='SUSPENDED'||p.approvalStatus==='PENDING_REVIEW'} onClick={()=>open({type:'draft',id:p.id})}>Edit showcase</button>
   {p.lifecycleStatus==='ACTIVE'?<button className="button" onClick={()=>act({type:'project',id:p.id,decision:'archive'},'Showcase archived. One active slot is now free.')}>Archive</button>:p.lifecycleStatus==='SUSPENDED'?<p>Restricted by moderation.</p>:p.approvalStatus==='APPROVED'?<button className="button primary" onClick={()=>act({type:'project',id:p.id,decision:'activate'},'Showcase is active in demo discovery.')}>Activate</button>:['DRAFT','CHANGES_REQUESTED'].includes(p.approvalStatus)?<><button className="button" disabled={p.proof} onClick={()=>act({type:'project',id:p.id,decision:'proof'},'Sample proof attached for this simulation. No file was uploaded.')}>{p.proof?'Sample proof attached':'Add sample proof'}</button><button className="button primary" onClick={()=>act({type:'project',id:p.id,decision:'submit'},'Submitted. Switch to Administrator · Sam to review it.')}>Submit for review</button></>:<button className="link" onClick={()=>changeAccount('sam')}>Review as administrator →</button>}
  </div></>:<div className="demo-byline"><span className="avatar">{p.builder.split(' ').map(v=>v[0]).join('')}</span><span>{p.builder}</span><button className="link" onClick={()=>open({type:'project',id:p.id})}>Preview ↗</button></div>}
 </article>}
 return <main id="main" className="wrap workspace-page demo-page">
  <section className="demo-toolbar" aria-label="Demo controls"><div><span className="demo-badge"><FlaskConical size={16}/>Interactive V1 demo</span><p>Fictional data. Actions stay in this tab; no real accounts, emails or uploads.</p></div><div className="demo-controls"><label htmlFor="demo-account">Test as</label><select id="demo-account" value={actorId} disabled={!ready} onChange={e=>changeAccount(e.target.value)}>{state.people.map(p=><option key={p.id} value={p.id}>{accountLabels[p.id]}</option>)}</select><button className="iconbutton" aria-label="Reset demo data" onClick={()=>setReset(true)}><RotateCcw size={18}/></button><Link className="link" href="/">Exit demo ↗</Link></div></section>
  {storageIssue&&<p className="samplebar" role="status">Browser storage is unavailable. You can keep testing, but refreshing may reset this demo.</p>}
  <div className="demo-heading"><div><p className="eyebrow">{me.admin?'Community administration':me.id==='alex'?'Client workspace':'Builder workspace'} · {me.name}</p><h1>{titles[tab]}</h1><p className="muted">One account can browse, commission work and publish its own showcases.</p></div>{tab!=='explore'&&<button className="button" onClick={()=>setTab('explore')}>Explore projects <ArrowUpRight size={16}/></button>}</div>
  {message&&<p className="success" role="status">{message}</p>}{error&&!modal&&<p className="error" role="alert">{error}</p>}
  {!ready&&<p role="status">Preparing your demo…</p>}
  {['showcases','inquiries','analytics','admin'].includes(tab)&&<WorkspaceOverview active={active} capacity={3} inquiries={received.length} completed={received.filter(r=>r.status==='COMPLETED').length} onSelect={setTab} moderation={me.admin?{projects:pendingProjects.length,profiles:pendingProfiles.length,reports:openReports.length}:undefined}/>}
  <Tabs className="workspace-layout demo-layout" orientation="vertical" value={tab} onValueChange={value=>{setTab(value);setError('');setRequestFilter('')}}>
   <TabsList className="workspace-tabs" variant="line"><TabsTrigger value="explore"><Search size={17}/>Explore projects</TabsTrigger><TabsTrigger value="saved"><Bookmark size={17}/>Saved ({state.saved[me.id]?.length||0})</TabsTrigger>{!me.admin&&<><TabsTrigger value="requests"><Send size={17}/>My requests ({sent.length})</TabsTrigger><TabsTrigger value="showcases"><Layers size={17}/>Showcases</TabsTrigger><TabsTrigger value="inquiries"><Inbox size={17}/>Received inquiries ({received.length})</TabsTrigger><TabsTrigger value="profile"><UserRound size={17}/>Profile</TabsTrigger><TabsTrigger value="analytics"><ChartNoAxesCombined size={17}/>Outcomes</TabsTrigger></>}{me.admin&&<TabsTrigger value="admin"><ShieldCheck size={17}/>Moderation ({pendingProjects.length+pendingProfiles.length+pendingReviews.length+openReports.length})</TabsTrigger>}</TabsList>
   {['explore','saved'].map(view=><TabsContent key={view} value={view}>
    <div className="search"><Search size={20}/><input aria-label="Search demo projects" placeholder="Search projects, builders or technology…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
    <div className="demo-filters"><label>Category<select aria-label="Business category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Technology<select aria-label="Technology" value={technology} onChange={e=>setTechnology(e.target.value)}><option value="">All technologies</option>{technologies.map(t=><option key={t}>{t}</option>)}</select></label><label>Project type<select aria-label="Project type" value={projectType} onChange={e=>setProjectType(e.target.value)}><option value="">All project types</option><option value="SAAS">SaaS</option><option value="CLIENT">Client work</option><option value="OPEN_SOURCE">Open source</option></select></label><label className="demo-availability"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/>Available for work</label></div>
    <div className="resultsbar"><span>{gallery.length} {view==='saved'?'saved ':''}projects · illustrative data</span><select aria-label="Sort projects" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Recently updated</option><option value="name">Name A–Z</option></select></div>
    {gallery.length?<div className="grid">{gallery.map((p,i)=>projectCard(p,i))}</div>:<div className="empty"><h2>{view==='saved'?'Your shortlist is empty.':'No projects match.'}</h2><p>{view==='saved'?'Save a project to find it here.':'Try another search or clear your filters.'}</p><button className="button" onClick={()=>{setQuery('');setCategory('');setTechnology('');setProjectType('');setAvailable(false);if(view==='saved')setTab('explore')}}>{view==='saved'?'Explore projects':'Clear search and filters'}</button></div>}
    <p className="samplebar"><strong>Try the client flow:</strong> Preview Stockroom → Build something similar → Send inquiry → confirm in the demo inbox. Templates and checkout belong to a later release.</p>
   </TabsContent>)}
   <TabsContent value="showcases"><div className="workspacehead demo-section-head"><div><h2>Your showcases</h2><p className="muted">{active} / 3 active · Unlimited drafts.</p></div><button className="button primary" disabled={me.profile!=='APPROVED'} onClick={()=>open({type:'draft'})}><Plus size={17}/>New draft</button></div>
    {me.profile!=='APPROVED'&&<p className="samplebar">Complete your profile and request approval before publishing. <button className="link" onClick={()=>setTab('profile')}>Open profile →</button></p>}
    <div className="demo-actions" aria-label="Showcase status">{['ACTIVE','DRAFT','ARCHIVED','SUSPENDED'].map(value=><button key={value} className={'button '+(lifecycle===value?'primary':'')} aria-pressed={lifecycle===value} onClick={()=>setLifecycle(value)}>{value==='DRAFT'?'Drafts & review':label(value)}</button>)}</div>
    {showcaseItems.length?<div className="grid demo-space">{showcaseItems.map((p,i)=>projectCard(p,i,true))}</div>:<div className="empty demo-space"><h2>No {label(lifecycle).toLowerCase()} showcases yet.</h2><p>Use New draft to add a project after your profile is approved.</p></div>}
    <p className="samplebar"><strong>Try publishing:</strong> Open Leah’s Customer portal under Drafts & review, add sample proof and submit. Approve as Sam, then return to Leah. Archive one active project before activating the fourth.</p>
   </TabsContent>
   {['requests','inquiries'].map(view=><TabsContent key={view} value={view}><div className="workspacehead demo-section-head"><div><h2>{view==='requests'?'My requests':'Qualified inquiries'}</h2><p className="muted">{view==='requests'?'Work you want another builder to create.':'Only email-confirmed inquiries reach the builder.'}</p></div><select aria-label="Filter requests by status" value={requestFilter} onChange={e=>setRequestFilter(e.target.value)}><option value="">All statuses</option>{['CREATED_UNVERIFIED','INQUIRY_RECEIVED','RESPONDED','DISCUSSION','PROPOSAL_SENT','HIRE_PENDING_CONFIRMATION','HIRED','IN_PROGRESS','COMPLETION_PENDING_CONFIRMATION','COMPLETED','NOT_HIRED'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div>
    {requestItems.length?requestItems.map(r=><article className="panel demo-request" key={r.id}><div className="workspacehead"><h3>{r.projectTitle} · {who(view==='requests'?r.builderId:r.clientId)}</h3><span className="tag">{label(r.status)}</span></div><p>{r.description}</p><p className="muted">{label(r.budgetBand)} · {label(r.timelineBand)}</p><p className="demo-next"><ArrowUpRight size={16}/>{actionHint(r)}</p><div className="demo-actions"><button className="button primary" onClick={()=>open({type:'request',id:r.id})}>{r.status==='CREATED_UNVERIFIED'?'Open demo inbox':'View request & next step'}</button>{nextActor(r)!==me.id&&<button className="button" onClick={()=>changeAccount(nextActor(r),nextActor(r)==='sam'?'admin':nextActor(r)===r.clientId?'requests':'inquiries')}>Continue as {who(nextActor(r))}</button>}</div></article>):<div className="empty"><Inbox size={28} style={{margin:'auto'}}/><h2>{view==='requests'?'Start with a project you like.':'No qualified inquiries yet.'}</h2><p>{view==='requests'?'Open a project preview and choose Build something similar.':'Send a request as a client and confirm it in the demo inbox.'}</p><button className="button" onClick={()=>view==='requests'?setTab('explore'):changeAccount('alex')}>{view==='requests'?'Explore projects':'Try the client view'}</button></div>}
   </TabsContent>)}
   <TabsContent value="profile"><section className="panel"><h2>{me.name}</h2><p className="tag">Profile: {label(me.profile)}</p>{me.reason&&<p className="samplebar">{me.reason}</p>}<form key={me.id+'-'+me.profile} className="form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);act({type:'profile',bio:String(d.get('bio')),availability:String(d.get('availability'))},'Profile draft saved. Submit it for administrator review.')}}><label htmlFor="demo-bio">About your work</label><textarea id="demo-bio" name="bio" defaultValue={me.bio} required minLength={20} maxLength={2000}/><label htmlFor="demo-availability">Availability for client work</label><select id="demo-availability" name="availability" defaultValue={me.availability}>{['AVAILABLE_NOW','ONE_SLOT_LEFT','LIMITED','NOT_ACCEPTING'].map(a=><option key={a} value={a}>{availabilityLabel(a)}</option>)}</select><p className="muted">Client availability is separate from your three active showcase slots. Bio changes require review; availability changes do not.</p><button className="button" disabled={me.profile==='PROFILE_PENDING'}>Save profile draft</button></form>{['DRAFT','CHANGES_REQUESTED'].includes(me.profile)&&<button className="button primary demo-space" onClick={()=>act({type:'submit-profile'},'Profile submitted. Switch to Sam to review it.')}>Submit profile for approval</button>}{me.profile==='PROFILE_PENDING'&&<button className="button demo-space" onClick={()=>changeAccount('sam')}>Review as administrator</button>}</section></TabsContent>
   <TabsContent value="analytics"><h2>Your demo outcomes</h2><div className="grid demo-space">{[['Qualified inquiries',received.length],['Client-confirmed hires',received.filter(r=>['HIRED','IN_PROGRESS','COMPLETION_PENDING_CONFIRMATION','COMPLETED'].includes(r.status)).length],['Completed engagements',received.filter(r=>r.status==='COMPLETED').length],['Published reviews',received.filter(r=>r.review?.status==='PUBLISHED').length]].map(([name,count])=><article className="panel" key={name}><p>{name}</p><strong className="demo-count">{count}</strong></article>)}</div><p className="samplebar">Calculated from your actions in this demo. No production analytics are recorded.</p></TabsContent>
   <TabsContent value="admin"><h2>Review queue</h2><p className="muted">Review evidence and record a reason for each decision.</p>
    {!pendingProjects.length&&!pendingProfiles.length&&!pendingReviews.length&&!openReports.length&&<div className="empty"><CheckCircle2 size={30} style={{margin:'auto'}}/><h3>You’re all caught up.</h3><p>Submit a profile, showcase, report or completed-engagement review to see it here.</p><button className="button" onClick={()=>changeAccount('leah','showcases')}>Try the builder flow</button></div>}
    {pendingProfiles.map(p=><article className="row" key={p.id}><div className="grow"><h3>{p.name}</h3><p>Builder profile · {p.bio}</p></div><button className="button" onClick={()=>open({type:'profile-review',id:p.id})}>Review profile</button></article>)}
    {pendingProjects.map(p=><article className="row" key={p.id}><div className="grow"><h3>{p.title}</h3><p>{p.builder} · Showcase review</p></div><button className="button" onClick={()=>open({type:'project-review',id:p.id})}>Review project</button></article>)}
    {pendingReviews.map(r=><article className="row" key={r.id}><div className="grow"><h3>{r.projectTitle} · {r.review?.rating} / 5</h3><p>{r.review?.reviewText}</p></div><button className="button" onClick={()=>open({type:'review-review',id:r.id})}>Moderate review</button></article>)}
    {openReports.map(r=><article className="row" key={r.id}><div className="grow"><h3>{label(r.reason)}</h3><p>{r.detail}</p></div><button className="button" onClick={()=>open({type:'report-review',id:r.id})}>Review report</button></article>)}
    <details className="panel demo-space"><summary>Decision history ({state.audit.length})</summary>{state.audit.map(a=><article key={a.id} className="row"><div><strong>{a.message}</strong><p className="muted">{a.actor} · {new Date(a.at).toLocaleString()}</p></div></article>)}{!state.audit.length&&<p>No decisions have been recorded in this demo.</p>}</details>
   </TabsContent>
  </Tabs>
  <Dialog open={!!modal} onOpenChange={value=>!value&&setModal(null)}><DialogContent className="demo-dialog"><DialogHeader><DialogTitle>{modal?.type==='draft'?(modal.id?'Edit showcase':'Create a showcase'):modal?.type==='inquire'?'Tell the builder what you need':modal?.type==='report'?'Report a concern':modal?.type?.endsWith('review')?'Moderation decision':modal?.type==='request'?selectedRequest?.projectTitle:selectedProject?.title}</DialogTitle><DialogDescription>Interactive demonstration. These actions only change the sample data in this tab.</DialogDescription></DialogHeader>
   {modal?.type==='project'&&selectedProject&&<><div className="thumbnail demo-detail-proof"><Preview product={selectedProject}/></div><p>{selectedProject.description}</p><h3>Builder’s contribution</h3><p>{selectedProject.contribution}</p><div className="panel"><h3>{selectedProject.builder}</h3><p>{state.people.find(p=>p.id===selectedProject.ownerId)?.bio}</p><p>{availabilityLabel(state.people.find(p=>p.id===selectedProject.ownerId)?.availability||'')}</p></div><div className="tags"><span className="tag">{selectedProject.technology}</span><span className="tag">{selectedProject.category}</span><span className="tag">{label(selectedProject.projectType)}</span></div><div className="demo-actions"><button className="button primary" disabled={me.admin||selectedProject.ownerId===me.id||!publicProjects.some(p=>p.id===selectedProject.id)} onClick={()=>open({type:'inquire',id:selectedProject.id})}>Build something similar</button><button className="button" onClick={()=>act({type:'save',id:selectedProject.id},'Demo shortlist updated.')}>{state.saved[me.id]?.includes(selectedProject.id)?'Unsave project':'Save project'}</button><button className="link" onClick={()=>open({type:'report',id:selectedProject.id})}>Report concern</button></div>{selectedProject.ownerId===me.id&&<p className="muted">This is your showcase. Choose another builder’s project to commission work.</p>}<h3>Client reviews</h3>{state.requests.filter(r=>r.builderId===selectedProject.ownerId&&r.review?.status==='PUBLISHED').map(r=><article className="panel" key={r.id}><strong>{r.review?.rating} / 5 · {r.review?.visibility==='NAMED'?who(r.clientId):'Verified client'}</strong><p>{r.review?.reviewText}</p><span className="muted">Simulated completed engagement</span></article>)}{!state.requests.some(r=>r.builderId===selectedProject.ownerId&&r.review?.status==='PUBLISHED')&&<p className="muted">No published demo reviews yet.</p>}<p className="samplebar">This proof is illustrative. Live external demos, downloads and checkout are not simulated.</p></>}
   {modal?.type==='inquire'&&selectedProject&&<form className="form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);if(act({type:'inquire',productId:selectedProject.id,description:String(data.get('description')),budgetBand:String(data.get('budget')),timelineBand:String(data.get('timeline'))},'Inquiry saved. Open the demo inbox in My requests to confirm it.')){setModal(null);setTab('requests');}}}><p className="samplebar">Inspired by {selectedProject.title} · {selectedProject.builder}</p><label htmlFor="demo-brief">Describe your project</label><textarea id="demo-brief" name="description" required minLength={20} maxLength={5000} placeholder="What should the software help you do?"/><label htmlFor="demo-budget">Budget</label><select id="demo-budget" name="budget" required defaultValue=""><option value="" disabled>Choose a budget</option>{budgets.map(b=><option key={b} value={b}>{label(b)}</option>)}</select><label htmlFor="demo-timeline">Timeline</label><select id="demo-timeline" name="timeline" required defaultValue=""><option value="" disabled>Choose a timeline</option>{timelines.map(t=><option key={t} value={t}>{label(t)}</option>)}</select><p>From {me.name} · {me.id}@example.test</p><p className="muted">Use a fictional brief. The demo uses the selected sample account and does not send email. Scope, contracts and payment are agreed directly with the builder.</p><button className="button primary">Send inquiry</button></form>}
   {modal?.type==='draft'&&<form className="form" onSubmit={submitDraft} key={modal.id||'new'}>{(['title','summary','description','contribution'] as const).map(name=><label key={name}>{label(name)}{['description','contribution'].includes(name)?<textarea name={name} defaultValue={selectedProject?.[name]||''} required minLength={name==='description'?20:10} maxLength={name==='description'?5000:2000}/>:<input name={name} defaultValue={selectedProject?.[name]||''} required minLength={name==='title'?3:10} maxLength={name==='title'?120:240}/>}</label>)}<label>Category<select name="category" defaultValue={selectedProject?.category||'Productivity'}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Technology<select name="technology" defaultValue={selectedProject?.technology||'React'}>{technologies.map(t=><option key={t}>{t}</option>)}</select></label><label>Project type<select name="projectType" defaultValue={selectedProject?.projectType||'SAAS'}><option value="SAAS">SaaS</option><option value="CLIENT">Client work</option><option value="OPEN_SOURCE">Open source</option></select></label><label className="filterlabel"><input type="checkbox" name="rightsConfirmed" defaultChecked={selectedProject?.rightsConfirmed||false}/>I have permission to showcase this work.</label><p className="muted">Editing returns the showcase to draft for review. Add sample proof after saving; files are not uploaded in this demo.</p><button className="button primary">Save draft</button></form>}
   {modal?.type==='request'&&selectedRequest&&<><span className="tag">{label(selectedRequest.status)}</span><p>{selectedRequest.description}</p><p className="muted">Client: {who(selectedRequest.clientId)} · Builder: {who(selectedRequest.builderId)}</p><p className="demo-next">{actionHint(selectedRequest)}</p>
    {selectedRequest.clientId===me.id&&selectedRequest.status==='CREATED_UNVERIFIED'&&<section className="demo-mail"><Mail size={24}/><h3>Demo inbox</h3><p>To: {me.id}@example.test</p><p>Confirm your inquiry about {selectedRequest.projectTitle} to send it to the builder. This message is simulated.</p><button className="button primary" onClick={()=>act({type:'request',id:selectedRequest.id,step:'confirm-email'},'Demo email confirmed. This inquiry now appears in the builder’s inbox.')}>Confirm inquiry email</button></section>}
    {selectedRequest.builderId===me.id&&builderSteps[selectedRequest.status]&&(selectedRequest.status==='DISCUSSION'?<ProposalReport disabled={false} onSubmit={async body=>act({type:'request',id:selectedRequest.id,step:'propose',reportedValue:body.reportedValue===undefined?undefined:Number(body.reportedValue),currency:String(body.currency||'USD').toUpperCase()},'Proposal recorded in the demo. Agreements and payments remain external.')}/>:<button className="button primary" onClick={()=>act({type:'request',id:selectedRequest.id,step:builderSteps[selectedRequest.status].step},'Demo request updated. Check the next step below.')}>{builderSteps[selectedRequest.status].label}</button>)}
    {selectedRequest.clientId===me.id&&['HIRE_PENDING_CONFIRMATION','COMPLETION_PENDING_CONFIRMATION'].includes(selectedRequest.status)&&<div className="demo-actions"><button className="button primary" onClick={()=>act({type:'request',id:selectedRequest.id,step:'accept'},'Client confirmation recorded in the demo.')}>{selectedRequest.status==='HIRE_PENDING_CONFIRMATION'?'Confirm hire':'Confirm completion'}</button><button className="button" onClick={()=>act({type:'request',id:selectedRequest.id,step:'reject'},'The request has returned to discussion or work in progress.')}>Not yet — continue the work</button></div>}
    {selectedRequest.clientId===me.id&&selectedRequest.status==='COMPLETED'&&!selectedRequest.review&&<form className="form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);act({type:'review',id:selectedRequest.id,rating:Number(d.get('rating')),reviewText:String(d.get('reviewText')),visibility:d.get('visibility')==='NAMED'?'NAMED':'ANONYMOUS'},'Review submitted. Sam must moderate it before publication.')}}><ReviewFields prefix="demo-review"/><button className="button primary">Submit review</button></form>}
    {selectedRequest.review&&<p className="samplebar">Review: {label(selectedRequest.review.status)} · {selectedRequest.review.rating} / 5</p>}
    {nextActor(selectedRequest)!==me.id&&selectedRequest.status!=='NOT_HIRED'&&<button className="button" onClick={()=>changeAccount(nextActor(selectedRequest),nextActor(selectedRequest)==='sam'?'admin':nextActor(selectedRequest)===selectedRequest.clientId?'requests':'inquiries')}>Continue as {who(nextActor(selectedRequest))} →</button>}
    {['INQUIRY_RECEIVED','RESPONDED','DISCUSSION','PROPOSAL_SENT'].includes(selectedRequest.status)&&<button className="link" onClick={()=>act({type:'request',id:selectedRequest.id,step:'close'},'This demo request is closed as not hired.')}>Close as not hired</button>}
    <h3>Request history</h3><ol className="demo-history">{selectedRequest.events.map((e,i)=><li key={i}><strong>{label(e.label)}</strong><span>{e.actor} · {new Date(e.at).toLocaleString()}</span></li>)}</ol>
   </>}
   {modal?.type==='report'&&selectedProject&&<form className="form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);if(act({type:'report',productId:selectedProject.id,reason:String(d.get('reason')),detail:String(d.get('detail'))},'Report saved in the demo moderation queue.'))setModal(null)}}><p>{selectedProject.title}</p><label>Reason<select name="reason">{['STOLEN_WORK','MISLEADING_CLAIM','CONFIDENTIAL_DATA','OTHER'].map(r=><option key={r} value={r}>{label(r)}</option>)}</select></label><label>What happened?<textarea name="detail" required minLength={10} maxLength={3000}/></label><button className="button primary">Submit report</button></form>}
   {modal?.type?.endsWith('review')&&<form className="form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget),approve=d.get('decision')==='approve',reason=String(d.get('reason'));let action:DemoAction;if(modal.type==='project-review')action={type:'project',id:modal.id!,decision:approve?'approve':'changes',reason};else if(modal.type==='profile-review')action={type:'moderate-profile',id:modal.id!,approve,reason};else if(modal.type==='review-review')action={type:'moderate-review',id:modal.id!,publish:approve,reason};else action={type:'resolve-report',id:modal.id!,hide:approve,reason};if(act(action,'Moderation decision recorded in the demo.'))setModal(null)}}>
    {selectedProject&&modal.type==='project-review'&&<><h3>{selectedProject.title}</h3><p>{selectedProject.description}</p><p><strong>Contribution:</strong> {selectedProject.contribution}</p><div className="thumbnail"><Preview product={selectedProject}/></div><p>Sample proof: {selectedProject.proof?'attached':'missing'} · Rights confirmed: {selectedProject.rightsConfirmed?'yes':'no'}</p><p className="muted">Approval activates the project if a slot is available. When all three slots are in use, it stays an approved draft.</p></>}
    {selectedProfile&&<><h3>{selectedProfile.name}</h3><p>{selectedProfile.bio}</p></>}
    {selectedRequest?.review&&<><h3>{selectedRequest.projectTitle}</h3><p>{selectedRequest.review.rating} / 5 · {selectedRequest.review.reviewText}</p><p>Engagement: {label(selectedRequest.status)} · Display: {selectedRequest.review.visibility==='ANONYMOUS'?'Verified client':who(selectedRequest.clientId)}</p></>}
    {selectedReport&&<><h3>{label(selectedReport.reason)}</h3><p>{selectedReport.detail}</p><p>{state.projects.find(p=>p.id===selectedReport.productId)?.title}</p></>}
    <label>Decision<select name="decision"><option value="approve">{modal.type==='review-review'?'Publish review':modal.type==='report-review'?'Restrict project':'Approve'}</option><option value="changes">{modal.type==='review-review'?'Hide review':modal.type==='report-review'?'Resolve without restriction':'Request changes'}</option></select></label><label>Reason<textarea name="reason" required minLength={3} maxLength={2000}/></label><button className="button primary">Record decision</button>
   </form>}
   {error&&<p className="error" role="alert">{error}</p>}
  </DialogContent></Dialog>
  <AlertDialog open={reset} onOpenChange={setReset}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reset this demo?</AlertDialogTitle><AlertDialogDescription>Your sample requests, saved projects and moderation decisions in this tab will be cleared. Real account data is unaffected.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep testing</AlertDialogCancel><AlertDialogAction onClick={()=>{setState(createDemoState());changeAccount('alex');setQuery('');setCategory('');setTechnology('');setProjectType('');setAvailable(false);setSort('recent');setLifecycle('ACTIVE');setMessage('Demo reset. Start again with any sample account.');}}>Reset demo</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}
