'use client';
import {useState} from 'react';
import WorkspaceOverview from '@/app/components/workspace-overview';
import Link from 'next/link';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Layers,Inbox,ArrowUpRight,Plus,CheckCircle2,UserRound,Send,ChartNoAxesCombined} from 'lucide-react';
import {examples} from '@/lib/catalog';
import Preview from '@/app/components/preview';
export default function WorkspacePreview(){const [tab,setTab]=useState('showcases');return <main id="main" className="wrap workspace-page">
  <div className="workspacehead workspace-welcome"><div><span className="eyebrow">Slate Atelier · Workspace preview</span><h1>Welcome, Leah.</h1><p className="muted">Your work, your inquiries, your next opportunity.</p></div><Link className="button" href="/">Explore projects <ArrowUpRight size={16}/></Link></div>
  <div className="samplebar">Fictional data for design review. These are examples of builder and client views; account actions are unavailable here.</div>
  <WorkspaceOverview active={3} capacity={3} inquiries={1} completed={0} onSelect={setTab}/><Tabs className="workspace-layout" orientation="vertical" value={tab} onValueChange={setTab}><TabsList className="workspace-tabs" variant="line"><TabsTrigger value="showcases"><Layers size={16}/>Showcases</TabsTrigger><TabsTrigger value="inquiries"><Inbox size={16}/>Received inquiries</TabsTrigger><TabsTrigger value="requests"><Send size={16}/>My requests</TabsTrigger><TabsTrigger value="profile"><UserRound size={16}/>Profile</TabsTrigger><TabsTrigger value="analytics"><ChartNoAxesCombined size={16}/>Outcomes</TabsTrigger></TabsList>
    <TabsContent value="showcases"><div className="workspacehead" style={{margin:'20px 0'}}><div><h2>Your work, on display.</h2><p className="muted">3 / 3 active · Archive one to publish another.</p></div><button className="button primary" disabled><Plus size={16}/>New draft</button></div><div className="grid">{examples.slice(0,3).map((p,n)=><article className="panel showcase-card" key={p.id}><div className={'thumbnail tone-'+n}><Preview product={p}/></div><h3 style={{fontSize:20,marginTop:18}}>{p.title}</h3><p className="showcase-status"><CheckCircle2 size={14}/>Approved · Active</p><div className="policy-links"><button className="button" disabled>Edit showcase</button><button className="button" disabled>Archive</button></div></article>)}</div><div className="panel" style={{marginTop:28}}><h2>Drafts & review</h2><p>Customer portal · Draft</p><p className="muted">Your fourth project can remain a draft while all three active slots are in use.</p></div></TabsContent>
    <TabsContent value="inquiries"><h2>Qualified inquiries</h2><p className="muted">Client requests for your work, delivered after email confirmation.</p><article className="panel" style={{marginTop:24}}><div className="workspacehead"><h3>Alex · Inventory system for five stores</h3><span className="tag">In discussion</span></div><p>We need stock transfers, purchase orders and alerts for our regional stores.</p><p className="muted">Inspired by Stockroom · USD 3,000–10,000 · 1–3 months</p><div className="policy-links"><button className="button" disabled>View history</button><button className="button primary" disabled>Mark proposal sent</button></div></article></TabsContent>
    <TabsContent value="requests"><div className="workspacehead"><div><h2>My requests</h2><p className="muted">Work you want another builder to create for you.</p></div><Link className="button" href="/">Find a builder</Link></div><article className="panel" style={{marginTop:24}}><div className="workspacehead"><h3>Booklane · Daniel Kim</h3><span className="tag">Hire pending confirmation</span></div><p>I need a booking experience for my consulting business, with appointment reminders and calendar integration.</p><p className="muted">USD 1,000–3,000 · Within a month</p><div className="samplebar">Daniel has asked you to confirm the hire. You decide whether the engagement is agreed.</div><div className="policy-links"><button className="button primary" disabled>Confirm hire</button><button className="button" disabled>Not yet — continue discussion</button></div></article><p className="muted" style={{marginTop:24}}>You keep the same account when commissioning work and publishing your own projects.</p></TabsContent>
    <TabsContent value="profile"><div className="panel form"><h2>Leah Morgan</h2><p>Independent software builder · React and Spring Boot</p><p><CheckCircle2 size={16} style={{display:'inline'}}/> Profile approved</p><p>Available for one new client project.</p><p className="muted">Availability for client work is separate from the three active showcase slots.</p><button className="button" disabled>Edit profile</button></div></TabsContent>
    <TabsContent value="analytics"><div className="panel"><span className="eyebrow">Your marketplace outcomes</span><h2>Every opportunity starts somewhere.</h2><p>1 qualified inquiry · 0 confirmed hires · 0 completed engagements</p><p className="muted">These figures are fictional. Only client-confirmed outcomes count toward your track record.</p></div></TabsContent>
  </Tabs>
 </main>}
