'use client';
import {useState,useEffect} from 'react';
import {api} from '@/lib/api';
import DeliveryOperations from './delivery-operations';
import PrivacyOperations from './privacy-operations';
import ReportTriage from './report-triage';
import ModerationWorkflow from './moderation-workflow';
import TeamModeration from './team-moderation';
import MoreRecords from './more-records';
export default function AdminTools(){
 const [metrics,setMetrics]=useState<any>(null);const [kind,setKind]=useState('categories'),[items,setItems]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[accounts,setAccounts]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{api('/admin/'+kind).then(r=>setItems(r.items)).catch(e=>setError(e.message));},[kind]);
 useEffect(()=>{api('/admin/metrics').then(setMetrics).catch(e=>setError(e.message))},[]);
 useEffect(()=>{api('/admin/audit').then(r=>setHistory(r.items)).catch(e=>setError(e.message));},[]);
 async function mutate(path:string,body:any){setBusy(true);setError('');try{await api(path,{method:'POST',body:JSON.stringify(body)});setMessage('Saved.');setHistory((await api('/admin/audit')).items);return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false)}}
 return <section style={{marginTop:40}}><h2>Community controls</h2>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}
 <details className="panel"><summary>Categories and technologies</summary><label htmlFor="taxonomy-kind">Manage</label><select id="taxonomy-kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="categories">Business categories</option><option value="technologies">Technologies</option></select>
 {items.map(item=><form key={kind+item.slug} className="row" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);if(await mutate('/admin/'+kind,{slug:item.slug,name:data.get('name'),active:data.get('active')==='on'}))setItems((await api('/admin/'+kind)).items);}}><label className="grow">{item.slug}<input name="name" aria-label={'Name for '+item.slug} defaultValue={item.name} required minLength={2} maxLength={100}/></label><label><input type="checkbox" name="active" defaultChecked={item.active}/> Active</label><button className="button" disabled={busy}>Save</button></form>)}
 <form className="form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;if(await mutate('/admin/'+kind,{...Object.fromEntries(new FormData(form)),active:true})){form.reset();setItems((await api('/admin/'+kind)).items);}}}><h3>Add a new option</h3><label htmlFor="taxonomy-slug">Permanent slug</label><input id="taxonomy-slug" name="slug" pattern="[a-z0-9-]+" minLength={2} maxLength={100} required/><label htmlFor="taxonomy-name">Display name</label><input id="taxonomy-name" name="name" minLength={2} maxLength={100} required/><button className="button" disabled={busy}>Add option</button></form></details>
 <details className="panel"><summary>Account enforcement</summary><form className="form" onSubmit={async e=>{e.preventDefault();setError('');try{setAccounts((await api('/admin/accounts?q='+encodeURIComponent(String(new FormData(e.currentTarget).get('q'))))).items)}catch(e){setError((e as Error).message)}}}><label htmlFor="account-search">Find by email</label><input id="account-search" name="q" type="email" required/><button className="button">Find account</button></form>{accounts.map(a=><form key={a.id} className="form panel" onSubmit={async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));if(await mutate('/admin/accounts/'+a.id+'/'+body.action,{reason:body.reason}))setAccounts([]);}}><h3>{a.email}</h3><p>{a.account_status} · {a.moderation_reason}</p><label htmlFor={'account-action-'+a.id}>Action</label><select id={'account-action-'+a.id} name="action"><option value="suspend">Suspend account and revoke sessions</option><option value="restore">Restore account access</option></select><label htmlFor={'account-reason-'+a.id}>Reason</label><textarea id={'account-reason-'+a.id} name="reason" required minLength={3} maxLength={2000}/><button className="button danger" disabled={busy}>Apply account decision</button></form>)}</details>
 <details className="panel"><summary>Inquiry restrictions</summary><form className="form" onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));await mutate('/admin/inquiries/'+encodeURIComponent(String(data.id))+'/'+data.action,{reason:data.reason})}}><label htmlFor="restricted-inquiry">Inquiry ID</label><input id="restricted-inquiry" name="id" required/><label htmlFor="inquiry-decision">Action</label><select id="inquiry-decision" name="action"><option value="quarantine">Quarantine for investigation</option><option value="block">Block confirmed abuse</option><option value="restore">Restore after review</option></select><label htmlFor="inquiry-reason">Reason</label><textarea id="inquiry-reason" name="reason" required minLength={3} maxLength={2000}/><button className="button" disabled={busy}>Record decision</button></form></details>
 {metrics&&<details className="panel"><summary>Weekly marketplace outcomes</summary><p>Failed email jobs needing attention: {metrics.failedEmails}</p><table><thead><tr><th>Week</th><th>Qualified inquiries</th><th>Confirmed hires</th><th>Completed</th></tr></thead><tbody>{metrics.weekly.map((w:any)=><tr key={w.week}><td>{new Date(w.week).toLocaleDateString()}</td><td>{w.qualified}</td><td>{w.hires}</td><td>{w.completed}</td></tr>)}</tbody></table>{metrics.sources?.length>0&&<><h3>Acquisition sources</h3>{metrics.sources.map((s:any)=><p key={s.source}>{s.source.replaceAll('_',' ')} · {s.qualified} qualified inquiries · {s.hires} confirmed hires</p>)}</>}{metrics.reportedValues?.length>0&&<><h3>Reported proposal values</h3><p>Self-reported, grouped by currency. These amounts are not processed payments.</p>{metrics.reportedValues.map((v:any)=><p key={v.currency}>{v.currency} {Number(v.total).toLocaleString()} · {v.proposals} proposals</p>)}</>}</details>}
 <DeliveryOperations/><TeamModeration/><PrivacyOperations/><ReportTriage/><ModerationWorkflow admin/><details className="panel"><summary>Moderation history</summary>{history.map(h=><article className="row" key={h.id}><div><strong>{h.target_type} · {h.action}</strong><p>{h.reason}</p><p className="muted">{new Date(h.created_at).toLocaleString()} · {h.target_id}</p></div></article>)}<MoreRecords path="/admin/audit" onItems={rows=>setHistory(old=>[...old,...rows.filter(r=>!old.some(x=>x.id===r.id))])}/></details></section>;
}
