'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import Link from 'next/link';
import {Building2,BriefcaseBusiness,Bookmark,Users,Plus,Search,ShieldCheck} from 'lucide-react';
import {api} from '@/lib/api';
import {createBusinessDemo} from '@/lib/business-demo';
import type {Business,Brief,BusinessRequest,BusinessWorkspaceData,Candidate,SavedCandidate,TalentList} from '@/lib/business';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {WorkspaceFrame,PreviewControls,WorkspaceMetrics} from './workspace-frame';
import {Field,TeamForm} from './workspace-form';
import './teams.css';
import './business.css';

const human=(v:string)=>v.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
function briefUpdate(brief:Brief,status:Brief['status']){const {title,description,category,technology,budget,timeline,availableOnly,repositoryVerifiedOnly}=brief;return {title,description,category,technology,budget,timeline,availableOnly,repositoryVerifiedOnly,status};}
type Index={items:Business[];invitations:{id:string;businessName:string;status:string}[]};
export default function BusinessWorkspace({demo=false}:{demo?:boolean}){
 const [adapter]=useState(()=>demo?createBusinessDemo():null),request:BusinessRequest=adapter?.request||api;
 const [actor,setActor]=useState('owner'),[me,setMe]=useState<{roles:string[]}|null>(null),[index,setIndex]=useState<Index>({items:[],invitations:[]}),[selected,setSelected]=useState(''),[workspace,setWorkspace]=useState<BusinessWorkspaceData|null>(null),[briefs,setBriefs]=useState<Brief[]>([]),[briefId,setBriefId]=useState(''),[lists,setLists]=useState<TalentList[]>([]),[listId,setListId]=useState(''),[saved,setSaved]=useState<SavedCandidate[]>([]),[shortlist,setShortlist]=useState<SavedCandidate[]>([]),[matches,setMatches]=useState<Candidate[]>([]),[tab,setTab]=useState('Requests'),[dialog,setDialog]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const dialogOpener=useRef<HTMLElement|null>(null);function showDialog(value:string){dialogOpener.current=document.activeElement as HTMLElement;setDialog(value)}
 const generation=useRef(0),brief=briefs.find(r=>r.id===briefId),base='/businesses/'+selected,owner=workspace?.myRole==='OWNER';
 async function load(businessId=selected,requestId=briefId,talentId=listId){const run=++generation.current;setLoading(true);setError('');try{const user=await request('/me'),idx:Index=await request('/businesses');let ws:BusinessWorkspaceData|null=null,rs:Brief[]=[],ls:TalentList[]=[],ss:SavedCandidate[]=[],sh:SavedCandidate[]=[],cs:Candidate[]=[];const b=idx.items.some(b=>b.id===businessId)?businessId:idx.items[0]?.id||'';let r='',l='';if(b){const root='/businesses/'+b;const result=await Promise.all([request(root),request(root+'/requests'),request(root+'/talent-lists')]);ws=result[0];rs=result[1].items;ls=result[2].items;r=rs.some(x=>x.id===requestId)?requestId:rs[0]?.id||'';l=ls.some(x=>x.id===talentId)?talentId:ls[0]?.id||'';if(r){sh=(await request(root+'/requests/'+r+'/shortlist')).items;if(rs.find(x=>x.id===r)?.status==='OPEN')cs=(await request(root+'/requests/'+r+'/matches')).items;}if(l)ss=(await request(root+'/talent-lists/'+l+'/entries')).items;}if(run!==generation.current)return;setMe(user);setIndex(idx);setSelected(b);setWorkspace(ws);setBriefs(rs);setBriefId(r);setLists(ls);setListId(l);setSaved(ss);setShortlist(sh);setMatches(cs);}catch(e){if(run===generation.current){setError((e as Error).message);setWorkspace(null);setBriefs([]);setMatches([]);setSaved([]);setShortlist([]);setMe(null);}}finally{if(run===generation.current)setLoading(false);}}
 useEffect(()=>{load('','','');return()=>{generation.current++}},[actor]);
 async function mutate(path:string,body:unknown={},method='POST'){setBusy(true);setError('');setMessage('');try{const result=await request(path,{method,body:JSON.stringify(body)});await load(path==='/businesses'?result.id:selected,path===base+'/requests'?result.id:briefId,path===base+'/talent-lists'?result.id:listId);setMessage('Changes saved.');return result;}catch(e){setError((e as Error).message);throw e;}finally{setBusy(false);}}
 const act=(path:string,body:unknown={},method='POST')=>{void mutate(path,body,method).catch(()=>{});};
 const closeAfter=(path:string,method='POST')=>async(data:unknown)=>{await mutate(path,data,method);setDialog('');};
 return <WorkspaceFrame section="business" preview={demo} className="business-page" title="Business hiring" description="Shape a private brief, find proven talent and keep your hiring team aligned." actions={workspace&&<button className="button primary" disabled={busy} onClick={()=>showDialog('request')}><Plus size={16} aria-hidden="true"/>New project request</button>}>
  {demo&&<PreviewControls title="Interactive business preview"><label className="team-field">Preview actor<select aria-label="Preview actor" value={actor} disabled={busy} onChange={e=>{adapter!.setActor(e.target.value);setActor(e.target.value);setTab('Requests');setDialog('');setMessage('');setWorkspace(null)}}>{adapter!.actors.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="button" disabled={busy} onClick={()=>{adapter!.reset();adapter!.setActor(actor);setMessage('Sample data reset.');load('','','')}}>Reset sample data</button></PreviewControls>}
  {error&&<p role="alert" className="team-error">{error}</p>}{message&&<p role="status" className="team-success">{message}</p>}
  {loading?<p role="status">Loading business workspace…</p>:!me?<Empty title="Sign in to your business workspace." description="Use a verified account to create or join a hiring workspace."><Link href="/login" className="button primary">Log in</Link><button className="button" onClick={()=>load()}>Retry</button></Empty>:<>
   {index.invitations.filter(i=>i.status==='PENDING').map(i=><section className="business-invitation" key={i.id}><div><strong>{i.businessName} invited you to join.</strong><p>You’ll have access to private project requests and shared talent lists.</p></div><div className="team-actions"><button disabled={busy} className="button primary" onClick={()=>act('/business-invitations/'+i.id+'/respond',{action:'ACCEPT'})}>Accept invitation</button><button disabled={busy} className="button" onClick={()=>act('/business-invitations/'+i.id+'/respond',{action:'DECLINE'})}>Decline</button></div></section>)}
   <div className="business-switcher">{index.items.length>0&&<label className="team-field">Business workspace<select aria-label="Business workspace" value={selected} disabled={busy} onChange={e=>{setWorkspace(null);setTab('Requests');load(e.target.value,'','')}}>{index.items.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>}<button className="button" disabled={busy} onClick={()=>showDialog('business')}><Building2 size={16} aria-hidden="true"/>Create business</button>{owner&&<button className="button" onClick={()=>showDialog('settings')}>Business settings</button>}</div>
   {me.roles.includes('ADMIN')&&<ConciergePanel request={request} demo={demo}/>}
   {!workspace?<Empty title="A shared place to hire." description="Create a business workspace or accept an invitation to collaborate on private briefs and talent lists."/>:<>
    <WorkspaceMetrics items={[{label:'Open requests',value:briefs.filter(r=>r.status==='OPEN').length,detail:'Ready for talent matching',Icon:BriefcaseBusiness},{label:'Draft briefs',value:briefs.filter(r=>r.status==='DRAFT').length,detail:'Visible to your hiring team',Icon:Building2},{label:'Talent lists',value:lists.length,detail:'Shared within this business',Icon:Bookmark},{label:'Hiring team',value:workspace.members.length,detail:human(workspace.myRole),Icon:Users}]}/>
    <Tabs value={tab} onValueChange={setTab} className="business-tabs studio-tabset"><TabsList className="studio-tabs" aria-label="Business workspace sections">{['Requests','Saved talent','Hiring team','Activity'].map(t=><TabsTrigger key={t} value={t}>{t}</TabsTrigger>)}</TabsList><TabsContent value={tab}>
    {tab==='Requests'&&(!briefs.length?<Empty title="Give your next project a clear start." description="Describe the problem, budget and timeline. Your brief stays private."/>:<div className="business-request-grid"><nav className="business-request-list" aria-label="Private project requests"><div className="business-list-heading"><h2>Project requests</h2><span>{briefs.length}</span></div>{briefs.map(r=><button key={r.id} type="button" aria-current={r.id===briefId?'true':undefined} className="business-brief-item" disabled={busy} onClick={()=>load(selected,r.id,listId)}><span className="team-badge">{human(r.status)}</span><strong>{r.title}</strong><span>{r.budget} · {r.timeline}</span></button>)}</nav>{brief&&<div className="business-request-detail"><section className="business-brief-panel"><div className="business-section-head"><div><span className="business-kicker">Private project request</span><h2>{brief.title}</h2></div><span className="team-badge">{human(brief.status)}</span></div><p className="business-brief-description">{brief.description}</p><dl className="business-brief-facts"><div><dt>Budget</dt><dd>{brief.budget}</dd></div><div><dt>Timeline</dt><dd>{brief.timeline}</dd></div><div><dt>Evidence needed</dt><dd>{[brief.category,brief.technology].filter(Boolean).join(' · ')}</dd></div></dl><div className="business-brief-actions">{brief.status!=='CLOSED'&&<button className="button" disabled={busy} onClick={()=>showDialog('edit')}>Edit brief</button>}{brief.status==='DRAFT'&&<button className="button primary" disabled={busy} onClick={()=>act(base+'/requests/'+brief.id,briefUpdate(brief,'OPEN'),'PUT')}>Open for matching</button>}{brief.status==='OPEN'&&<button className="button" disabled={busy} onClick={()=>showDialog('close')}>Close request</button>}<span><ShieldCheck size={15} aria-hidden="true"/>Private to your hiring team</span></div></section>
    <section className="business-candidate-section"><div className="business-section-head"><div><h2>{brief.status==='OPEN'?'Evidence that fits your brief':'Talent matching'}</h2><p>{brief.status==='OPEN'?'Suggestions use approved public work and your criteria.':'Open this request to find approved builders and teams.'}</p></div><Search size={20} aria-hidden="true"/></div>{brief.status==='OPEN'&&(matches.length?<div className="business-candidate-list">{matches.map(c=><CandidateCard key={c.kind+c.targetId} candidate={c} demo={demo}><Link className="button primary" href={(demo?'/preview':'/workspace')+'/delivery?businessRequestId='+brief.id+'&candidateKind='+c.kind+'&candidateId='+c.targetId}>Discuss a proposal</Link><button disabled={busy||shortlist.some(s=>s.kind===c.kind&&s.targetId===c.targetId)} className="button" onClick={()=>act(base+'/requests/'+brief.id+'/shortlist',{kind:c.kind,targetId:c.targetId,reason:'Selected for '+[brief.category,brief.technology].filter(Boolean).join(' and ')+' evidence'})}>{shortlist.some(s=>s.kind===c.kind&&s.targetId===c.targetId)?'Shortlisted':'Shortlist'}</button>{lists.length>0&&<label className="business-save-picker">Save to a talent list<select aria-label={'Save '+c.name+' to a talent list'} value="" disabled={busy} onChange={e=>act(base+'/talent-lists/'+e.target.value+'/entries',{kind:c.kind,targetId:c.targetId})}><option value="">Choose a list</option>{lists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}</CandidateCard>)}</div>:<Empty title="No eligible matches yet." description="Adjust your evidence criteria or request manual sourcing. We’ll never fill this list with sample talent."/>)}</section>
    <section className="business-shortlist"><div className="business-section-head"><h2>Request shortlist</h2><span>{shortlist.length}</span></div>{!shortlist.length?<p className="muted">Shortlist a candidate to compare the people behind the proof.</p>:shortlist.map(s=><CandidateCard key={s.id} candidate={s.candidate} demo={demo}><p>{s.reason}</p><span className="team-badge">{s.source==='CONCIERGE'?'Concierge recommendation':'Hiring team selection'}</span>{brief.status==='OPEN'&&<button className="button" disabled={busy} onClick={()=>act(base+'/requests/'+brief.id+'/shortlist/'+s.id,{},'DELETE')}>Remove</button>}</CandidateCard>)}</section>
    {brief.status==='OPEN'&&<section className="business-concierge-callout"><div><strong>Need a closer look?</strong><p>{brief.conciergeStatus?'Manual sourcing: '+human(brief.conciergeStatus):'Ask the platform administrator to review this brief and recommend proven talent.'}</p></div>{!brief.conciergeStatus&&<button className="button" disabled={busy} onClick={()=>showDialog('concierge')}>Request concierge sourcing</button>}</section>}
    </div>}</div>)}
    {tab==='Saved talent'&&<section className="business-section"><div className="business-section-head"><div><h2>A shortlist you can return to.</h2><p>Shared lists for this business. Saving talent does not contact or hire anyone.</p></div><button className="button" onClick={()=>showDialog('list')}><Plus size={16} aria-hidden="true"/>New talent list</button></div>{lists.length>0&&<label className="team-field business-list-select">Talent list<select aria-label="Talent list" value={listId} disabled={busy} onChange={e=>load(selected,briefId,e.target.value)}>{lists.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label>}{saved.length?saved.map(s=><CandidateCard key={s.id} candidate={s.candidate} demo={demo}><button disabled={busy} className="button" onClick={()=>act(base+'/talent-lists/'+listId+'/entries/'+s.id,{},'DELETE')}>Remove from list</button></CandidateCard>):<Empty title={lists.length?'Your list is ready.':'Keep the right people in view.'} description={lists.length?'Save builders or teams from an open request’s matching results.':'Create a talent list, then save candidates from matching results.'}/>}</section>}
    {tab==='Hiring team'&&<section className="business-section"><div className="business-section-head"><div><h2>Your hiring team</h2><p>Owners manage access. Hiring managers collaborate on briefs and talent lists.</p></div>{owner&&<button className="button" onClick={()=>showDialog('invite')}>Invite hiring manager</button>}</div>{workspace.members.map(m=><div className="business-member" key={m.userId}><span className="business-avatar">{m.name.slice(0,1)}</span><div><strong>{m.name}</strong><span>{human(m.role)}</span></div>{owner&&m.role!=='OWNER'&&<button className="button" disabled={busy} onClick={()=>showDialog('remove:'+m.userId)}>Remove access</button>}</div>)}{workspace.invitations.length>0&&<><h3>Invitations</h3>{workspace.invitations.map(i=><div className="business-member" key={i.id}><strong>{i.email}</strong><span className="team-badge">{human(i.status)}</span></div>)}</>}</section>}
    {tab==='Activity'&&<section className="business-section"><h2>Workspace activity</h2><ol className="business-activity">{workspace.activity.map(a=><li key={a.id}><div><strong>{human(a.action)}</strong><p>{a.detail}</p></div><time dateTime={a.createdAt}>{new Date(a.createdAt).toLocaleString()}</time></li>)}</ol></section>}
    </TabsContent></Tabs>
   </>}
  </>}
  <Dialog open={!!dialog} onOpenChange={v=>{if(!v&&!busy)setDialog('')}}><DialogContent className="workspace-dialog business-dialog" onCloseAutoFocus={e=>{e.preventDefault();dialogOpener.current?.focus()}}><DialogHeader><DialogTitle>{dialog==='request'?'New private project request':dialog==='edit'?'Edit private brief':dialog==='business'?'Create a business workspace':dialog==='settings'?'Business settings':dialog==='list'?'Create a talent list':dialog==='invite'?'Invite a hiring manager':dialog==='close'?'Close this project request?':dialog.startsWith('remove:')?'Remove hiring access?':'Request manual sourcing'}</DialogTitle><DialogDescription>{dialog==='concierge'?'This shares your private brief with the platform administrator. Candidates receive no automatic message.':dialog==='close'?'Closed requests remain in your history and cannot be reopened. Unfinished sourcing will be cancelled.':dialog.startsWith('remove:')?'This member will immediately lose access to private business records.':'Only authorized members of your business can access this information.'}</DialogDescription></DialogHeader>
   {(dialog==='request'||dialog==='edit')&&<BriefForm key={dialog+briefId} brief={dialog==='edit'?brief:undefined} busy={busy} onSave={async d=>{await mutate(base+'/requests'+(dialog==='edit'?'/'+brief!.id:''),d,dialog==='edit'?'PUT':'POST');setDialog('')}}/>}
   {(dialog==='business'||dialog==='settings')&&<TeamForm busy={busy} label={dialog==='business'?'Create workspace':'Save business settings'} onSave={closeAfter(dialog==='business'?'/businesses':base,dialog==='business'?'POST':'PUT')}><Field name="name" label="Business name" minLength={2} maxLength={120} value={dialog==='settings'?workspace?.business.name:''}/><Field name="summary" label="What does your business do?" type="textarea" minLength={10} maxLength={2000} value={dialog==='settings'?workspace?.business.summary:''}/></TeamForm>}
   {dialog==='list'&&<TeamForm busy={busy} label="Create talent list" onSave={closeAfter(base+'/talent-lists')}><Field name="name" label="List name" minLength={2} maxLength={120}/></TeamForm>}
   {dialog==='invite'&&<TeamForm busy={busy} label="Send invitation" onSave={closeAfter(base+'/invitations')}><Field name="email" label="Verified account email" type="email" maxLength={254}/><p>The recipient must accept before gaining access.</p></TeamForm>}
   {['close','concierge'].includes(dialog)&&<button className="button primary" disabled={busy} onClick={()=>{void mutate(base+'/requests/'+brief!.id+(dialog==='concierge'?'/concierge':''),dialog==='close'?briefUpdate(brief!,'CLOSED'):{},dialog==='close'?'PUT':'POST').then(()=>setDialog('')).catch(()=>{})}}>{busy?'Saving…':dialog==='close'?'Close request':'Share brief for sourcing'}</button>}
   {dialog.startsWith('remove:')&&<button className="button primary" disabled={busy} onClick={()=>{void mutate(base+'/members/'+dialog.split(':')[1],{},'DELETE').then(()=>setDialog('')).catch(()=>{})}}>Remove access</button>}
  </DialogContent></Dialog>
 </WorkspaceFrame>;
}

function Empty({title,description,children}:{title:string;description:string;children?:ReactNode}){return <div className="business-empty"><h3>{title}</h3><p>{description}</p>{children&&<div className="team-actions">{children}</div>}</div>;}
function CandidateCard({candidate:c,children,demo}:{candidate?:Candidate;children?:ReactNode;demo?:boolean}){return <article className="business-candidate"><div className="business-candidate-identity"><span className="business-avatar">{c?.kind==='TEAM'?<Users size={22} aria-hidden="true"/>:c?.name.slice(0,1)||'?'}</span><div><span className="business-kicker">{c?c.kind==='TEAM'?'Independent studio':'Independent builder':'Unavailable proof'}</span><h3>{c?.name||'Public proof no longer available'}</h3><p>{c?.summary||'You can remove this saved record. Private or withdrawn proof is never displayed.'}</p></div></div>{c&&<><ul className="business-match-reasons">{c.reasons.map(r=><li key={r}>{r}</li>)}</ul><p className="business-proof-count">{c.evidenceCount} eligible public showcase{c.evidenceCount!==1?'s':''}</p><Link className="link" href={demo&&c.kind==='TEAM'?'/preview/teams':c.url}>View {c.kind==='TEAM'?'team':'builder'} profile</Link></>}<div className="business-candidate-actions">{children}</div></article>;}
function BriefForm({brief,busy,onSave}:{brief?:Brief;busy:boolean;onSave:(d:Record<string,unknown>)=>Promise<void>}){return <TeamForm busy={busy} label={brief?'Save brief':'Create project request'} onSave={d=>onSave({...d,availableOnly:d.availableOnly==='on',repositoryVerifiedOnly:d.repositoryVerifiedOnly==='on'})}><div className="business-form-grid"><Field name="title" label="Project title" value={brief?.title} minLength={3} maxLength={120}/><Field name="description" label="Problem, users and essential requirements" type="textarea" value={brief?.description} minLength={20} maxLength={5000}/><Field name="category" label="Business category (optional if technology provided)" required={false} value={brief?.category} maxLength={100}/><Field name="technology" label="Technology (one, optional if category provided)" required={false} value={brief?.technology} maxLength={300}/><Field name="budget" label="Budget range" value={brief?.budget} maxLength={200}/><Field name="timeline" label="Timeline" value={brief?.timeline} maxLength={200}/><Field name="status" label="Request status" value={brief?.status||'DRAFT'} options={(brief?.status==='OPEN'?['OPEN']:['DRAFT','OPEN']).map(value=>({value,label:human(value)}))}/></div><div className="business-checks"><label><input type="checkbox" name="availableOnly" defaultChecked={brief?.availableOnly}/>Only available-now candidates</label><label><input type="checkbox" name="repositoryVerifiedOnly" defaultChecked={brief?.repositoryVerifiedOnly}/>Require manually reviewed repository evidence</label></div><p className="muted">Approved public showcases are required for every match. Repository evidence applies to the stated repository and does not verify identity or code quality.</p></TeamForm>;}

function ConciergePanel({request,demo}:{request:BusinessRequest;demo:boolean}){
 const [items,setItems]=useState<(Omit<Brief,'status'>&{id:string;requestId:string;businessName:string;status:string})[]>([]),[selected,setSelected]=useState(''),[matches,setMatches]=useState<Candidate[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[note,setNote]=useState('');const generation=useRef(0);
 async function load(){try{setItems((await request('/admin/concierge')).items);setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load();return()=>{generation.current++}},[]);
 async function select(id:string){const run=++generation.current;setSelected(id);setMatches([]);try{const result=await request('/admin/concierge/'+id+'/matches');if(run===generation.current)setMatches(result.items)}catch(e){if(run===generation.current)setError((e as Error).message)}}
 async function mutate(id:string,body:unknown,suffix='',method='PATCH'){setBusy(true);setError('');setNote('');try{await request('/admin/concierge/'+id+suffix,{method,body:JSON.stringify(body)});await load();setNote('Sourcing update saved.')}catch(e){setError((e as Error).message);throw e}finally{setBusy(false)}}
 return <section className="business-section business-concierge-admin"><div className="business-section-head"><div><span className="business-kicker">Administrator · manual sourcing</span><h2>Concierge requests</h2><p>Only briefs explicitly shared for sourcing appear here.</p></div><button className="button" disabled={busy} onClick={()=>load()}>Refresh queue</button></div>{error&&<p role="alert" className="team-error">{error}</p>}{note&&<p role="status" className="team-success">{note}</p>}{!items.length&&<Empty title="No sourcing requests yet." description="Businesses can opt in from an open private request."/>}{items.map(r=><article className="business-sourcing-record" key={r.id}><div className="business-section-head"><div><span className="business-kicker">{r.businessName}</span><h3>{r.title}</h3></div><span className="team-badge">{human(r.status)}</span></div><p>{r.description}</p><p>{r.budget} · {r.timeline} · {[r.category,r.technology].filter(Boolean).join(' · ')}</p><div className="team-actions">{r.status==='REQUESTED'&&<button className="button primary" disabled={busy} onClick={()=>{void mutate(r.id,{status:'IN_PROGRESS'}).catch(()=>{})}}>Start sourcing</button>}<button className="button" disabled={busy} onClick={()=>select(r.id)}>Review matching evidence</button>{r.status==='IN_PROGRESS'&&<button className="button" disabled={busy} onClick={()=>{void mutate(r.id,{status:'FULFILLED'}).catch(()=>{})}}>Mark fulfilled</button>}</div>{selected===r.id&&<div className="business-candidate-list">{!matches.length?<p>No eligible candidates for this brief.</p>:matches.map(c=><CandidateCard key={c.kind+c.targetId} candidate={c} demo={demo}>{r.status==='IN_PROGRESS'&&<TeamForm label="Recommend candidate" busy={busy} onSave={d=>mutate(r.id,{...d,kind:c.kind,targetId:c.targetId},'/shortlist','POST')}><Field name="reason" label="Client-visible recommendation reason" type="textarea" minLength={3} maxLength={2000}/></TeamForm>}</CandidateCard>)}</div>}</article>)}</section>;
}
