'use client';
import {useState} from 'react';
import ComponentSaveButton from './component-save-button';
import ComponentVersionHistory from './component-version-history';
import Link from 'next/link';
import {ArrowUpRight,Code2,Copy,Download,Monitor,Smartphone,Tablet,RotateCcw,Check} from 'lucide-react';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {componentLabel,componentSeeds,componentZip,type ComponentEntry} from '@/lib/components';

export function ComponentArtwork({item}:{item:ComponentEntry}){
 return <div className={'kit-art kit-art-'+item.category.toLowerCase()} aria-hidden="true"><div className="kit-mini-window"><div className="kit-mini-bar"><i/><i/><i/><span>studio / {componentLabel(item.category)}</span></div><div className="kit-mini-body">{item.category==='SIDEBAR'&&<div className="kit-mini-rail"><b/><b/><b/><b/></div>}<div className="kit-mini-main"><span className="kit-mini-kicker"/><strong>{item.category==='AUTH'?'Welcome back.':item.category==='FORM'?'Your next idea.':item.category==='DASHBOARD'?'Project pulse.':item.category==='CARD'?'Thoughtfully built.':'Make room for good work.'}</strong>{['AUTH','FORM'].includes(item.category)?<><div className="kit-mini-input"/><div className="kit-mini-input short"/><div className="kit-mini-button"/></>:item.category==='DASHBOARD'?<><div className="kit-mini-stats"><i/><i/></div><div className="kit-mini-line"/><div className="kit-mini-line"/><div className="kit-mini-line"/></>:<><div className="kit-mini-sculpture"><i/><b/></div><div className="kit-mini-line"/></>}</div></div></div></div>;
}
export function ComponentCard({item}:{item:ComponentEntry}){return <article className="kit-card"><Link href={'/components/'+item.slug} className="kit-card-preview" aria-label={'Try '+item.title}><ComponentArtwork item={item}/><span className="kit-preview-link">Try component <ArrowUpRight size={15}/></span></Link><div className="kit-card-copy"><div className="kit-card-meta"><span>{componentLabel(item.category)}</span><span className="kit-free">Free · MIT</span></div><h2><Link href={'/components/'+item.slug}>{item.title}</Link></h2><p>{item.summary}</p><div className="kit-card-foot"><span>{item.creator}</span><span>HTML / CSS / JS</span></div></div></article>;}
export default function ComponentDetailView({item,preview}:{item:ComponentEntry;preview:boolean}){
 const [size,setSize]=useState('desktop'),[generation,setGeneration]=useState(0),[file,setFile]=useState('index.html'),[copied,setCopied]=useState(false),[error,setError]=useState('');
 const files=item.files,html=files?.['index.html'];
 async function copy(){try{await navigator.clipboard.writeText(files?.[file]||'');setCopied(true);setError('');}catch{setError('Copy is unavailable. Select the source text or download the ZIP.');}}
 async function download(){try{if(!files||!html)throw Error('Source is unavailable.');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(html))),x=>x.toString(16).padStart(2,'0')).join('');if(digest!==item.sha256)throw Error('Source integrity could not be verified. Refresh before downloading.');const bytes=componentZip(files),url=URL.createObjectURL(new Blob([bytes.buffer as ArrayBuffer],{type:'application/zip'})),link=document.createElement('a');link.href=url;link.download=item.slug+'-'+item.version+'.zip';link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setError('');}catch(e){setError((e as Error).message);}}
 return <main id="main" className="kit-page"><Link href="/components" className="kit-back">← All components</Link><header className="kit-detail-head"><div><div className="kit-badges"><span className="kit-free">Free source · {item.license}</span><span>{item.executionMode}</span><span>v{item.version}</span></div><h1>{item.title}</h1><p>{item.summary}</p><p className="kit-credit">{item.builderSlug?<Link href={'/builders/'+item.builderSlug}>{item.creator} ↗</Link>:item.creator}{item.recipeSlug&&' · Based on an original getLancer curated recipe'}</p></div><div className="kit-detail-actions"><button className="button primary" onClick={download}><Download size={17}/>Download source</button><ComponentSaveButton slug={item.slug} preview={preview}/></div></header>
 {preview&&<p className="kit-notice">These curated components and downloads are real. Account and community records use the separate design preview.</p>}
 {item.status==='ARCHIVED'&&<p className="kit-notice">This component is archived. Its published MIT source remains free.</p>}
 <Tabs defaultValue="preview" className="kit-detail-tabs"><TabsList aria-label="Component details"><TabsTrigger value="preview">Preview</TabsTrigger><TabsTrigger value="source">Source</TabsTrigger><TabsTrigger value="setup">Setup & licence</TabsTrigger><TabsTrigger value="history">Version history</TabsTrigger></TabsList>
 <TabsContent value="preview"><section className="kit-preview-panel"><div className="kit-preview-toolbar"><span>Working browser preview</span><div className="kit-device-controls" role="group" aria-label="Preview viewport">{[['desktop','Desktop',Monitor],['tablet','Tablet',Tablet],['phone','Phone',Smartphone]].map(([key,label,Icon])=>{const DeviceIcon=Icon as typeof Monitor;return <button key={key as string} aria-label={label as string} aria-pressed={size===key} onClick={()=>setSize(key as string)}><DeviceIcon size={18}/><span>{label as string}</span></button>;})}<button aria-label="Reset preview" onClick={()=>setGeneration(n=>n+1)}><RotateCcw size={17}/></button></div></div><div className={'kit-preview-stage '+size}>{html?<iframe key={generation} title={item.title+' working preview'} sandbox="allow-scripts allow-forms" referrerPolicy="no-referrer" srcDoc={html}/>:<p role="status">A working preview is unavailable for this version.</p>}</div><div className="kit-preview-note"><Code2 size={18}/><div><strong>Try it: {item.scenario}</strong><p>Synthetic data only. Changes reset with the preview. No account or payment service is contacted.</p></div></div></section>{item.contribution&&<section className="kit-info-panel"><h2>Creator contribution</h2><p>{item.contribution}</p></section>}</TabsContent>
 <TabsContent value="source"><section className="kit-source-panel"><div className="kit-source-toolbar"><div role="group" aria-label="Source files">{Object.keys(files||{}).map(name=><button key={name} className={file===name?'selected':''} aria-pressed={file===name} onClick={()=>{setFile(name);setCopied(false);}}>{name}</button>)}</div><button className="button" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy file'}</button></div><pre tabIndex={0} aria-label={file+' source'}><code>{files?.[file]}</code></pre><p className="kit-source-hash">index.html SHA-256: <code>{item.sha256}</code></p></section></TabsContent>
 <TabsContent value="setup"><div className="kit-setup-grid"><section className="kit-info-panel"><h2>Open it. Make it yours.</h2><p>No dependencies, API keys or build tools are required. Download the ZIP, extract it and open <code>index.html</code> in your browser.</p><p>Optional local server:</p><pre><code>python3 -m http.server 8000</code></pre><h3>Version {item.version}</h3><p>Original curated release. Keyboard controls, visible focus and reduced-motion support are included. Test your modifications before publishing.</p></section><section className="kit-info-panel"><h2>MIT licence</h2><p>Use and modify the component for personal or commercial projects. Keep the copyright and licence notices in redistributed source.</p><details><summary>Read the full licence</summary><pre className="kit-license">{files?.LICENSE}</pre></details><p className="kit-credit">No external fonts, images or packages. Source and standard preview stay free.</p></section></div></TabsContent><TabsContent value="history"><ComponentVersionHistory slug={item.slug} preview={preview} version={item.version} sha256={item.sha256}/></TabsContent></Tabs>{error&&<p className="error" role="alert">{error}</p>}
 <section className="kit-related"><h2>Keep building.</h2><div className="kit-grid related">{componentSeeds.filter(c=>c.slug!==(item.recipeSlug||item.slug)).slice(0,3).map(c=><ComponentCard key={c.slug} item={c}/>)}</div></section></main>;
}
