'use client';
import {useState} from 'react';
import {api} from '@/lib/api';

type RecordRow=Record<string,any>;
export default function DeliveryOperations(){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[disputes,setDisputes]=useState<RecordRow[]>([]),[accounts,setAccounts]=useState<RecordRow[]>([]),[attention,setAttention]=useState<RecordRow[]>([]);
 async function load(){setBusy(true);setError('');try{const [d,a,p]=await Promise.all([api('/admin/delivery/disputes'),api('/admin/payments/accounts'),api('/admin/payments/attention')]);setDisputes(d.items);setAccounts(a.items);setAttention(p.items)}catch(e){setDisputes([]);setAccounts([]);setAttention([]);setError((e as Error).message)}finally{setBusy(false)}}
 async function save(path:string,body:unknown){setBusy(true);setError('');setNote('');try{await api(path,{method:'POST',body:JSON.stringify(body)});await load();setNote('Decision saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="panel" open={open} onToggle={e=>{const expanded=e.currentTarget.open;if(expanded!==open){setOpen(expanded);if(expanded)void load()}}}><summary>Delivery disputes and Razorpay operations</summary>
 <p>These controls require an administrator session with MFA. Capture, transfer and bank settlement are separate outcomes.</p>
 <button className="button" type="button" disabled={busy} onClick={()=>void load()}>Refresh payment operations</button>
 {error&&<p className="error" role="alert">{error}</p>}{note&&<p className="success" role="status">{note}</p>}
 <h3>Delivery disputes</h3>{!disputes.some(d=>d.status==='OPEN')&&<p>No open disputes.</p>}{disputes.filter(d=>d.status==='OPEN').map(d=><form className="form panel" key={d.id} onSubmit={e=>{e.preventDefault();void save('/admin/delivery/disputes/'+d.id+'/resolve',Object.fromEntries(new FormData(e.currentTarget)))}}><strong>{d.title||d.engagementId}</strong><p>{d.reason}</p><label>Resolution<select name="resolution"><option value="RESUME">Resume the engagement</option><option value="CANCEL">Cancel the engagement</option></select></label><label>Decision reason<textarea name="reason" minLength={10} maxLength={2000} required/></label><p>Record any refund or Route reversal separately in Razorpay, then reconcile the payment. This decision does not move money.</p><button className="button" disabled={busy}>Record dispute resolution</button></form>)}
 <h3>Seller linked accounts</h3><p>Complete seller onboarding in Razorpay Route first. Map its verified account identifier here; no bank details are stored in getLancer.</p>
 <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),kind=String(f.get('kind'));void save('/admin/payments/accounts',{[kind]:f.get('seller'),accountId:f.get('accountId'),activationConfirmed:f.get('activationConfirmed')==='on'})}}><label>Seller type<select name="kind"><option value="builderUserId">Builder</option><option value="teamId">Team</option></select></label><label>Seller ID<input name="seller" required pattern="[0-9a-fA-F-]{36}"/></label><label>Razorpay linked account ID<input name="accountId" required pattern="acc_[A-Za-z0-9]+" maxLength={80}/></label><label><input type="checkbox" name="activationConfirmed" required/> I verified completed seller KYC and active Route configuration in Razorpay.</label><button className="button" disabled={busy}>Verify and map linked account</button></form>
 {accounts.map(a=><p key={a.id||a.accountId}>{a.builderUserId||a.teamId} · {a.accountId}</p>)}
 <h3>Orders requiring attention</h3><p>An interrupted order creation must be reconciled before another checkout. Find the order in Razorpay using the payment attempt's receipt, and enter its order ID. The server checks receipt, amount, currency and seller before accepting it.</p>
 {!attention.length&&<p>No orders require attention.</p>}{attention.map(p=><form className="form panel" key={p.id} onSubmit={e=>{e.preventDefault();void save('/admin/payments/'+p.id+'/bind-order',Object.fromEntries(new FormData(e.currentTarget)))}}><strong>Attempt {p.id}</strong><p>{p.status} · {p.currency} {Number(p.amountMinor||0)/100}</p>{p.attentionReason&&<p>{p.attentionReason}</p>}{p.orderId?<><p>Provider order {p.orderId}</p><button type="button" className="button" disabled={busy} onClick={()=>void save('/admin/payments/'+p.id+'/reconcile',{})}>Reconcile provider state</button></>:<><label>Provider order ID<input name="orderId" required pattern="order_[A-Za-z0-9]+" maxLength={80}/></label><button className="button" disabled={busy}>Verify provider order</button></>}</form>)}
 </details>;
}
