'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
import {downloadTemplateSource,loadTemplateCheckout,templatePrice,templateStatus,type TemplateOrder} from '@/lib/templates';
import {type EducationOffer,type EducationRelease} from '@/lib/education';
import EducationPackage from './education-package';
export default function EducationSource({release,preview=false,previewPackageUrl}:{release:EducationRelease;preview?:boolean;previewPackageUrl?:string|null}){
 const [offer,setOffer]=useState<EducationOffer|null>(preview?{release,package:release.snapshot.sourceBinding,available:release.snapshot.mode==='FREE',checkoutAvailable:false,reason:'Illustrative source offer. No merchant checkout is available.'}:null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[consent,setConsent]=useState(false),[order,setOrder]=useState<TemplateOrder|null>(null);const key=useRef(''),alive=useRef(true),generation=useRef(0),summary=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{alive.current=true;const current=++generation.current;key.current='';setConsent(false);setOrder(null);setError('');if(preview)setOffer({release,package:release.snapshot.sourceBinding,available:release.snapshot.mode==='FREE',checkoutAvailable:false,reason:'Illustrative source offer. No merchant checkout is available.'});else{setOffer(null);api('/education-releases/'+release.id+'/source-offer').then(value=>{if(value.release?.id!==release.id||value.release?.productId!==release.productId||value.release?.sourceHash!==release.sourceHash)throw Error('The source offer did not match this reviewed release. Refresh its current state.');if(alive.current&&current===generation.current)setOffer(value);}).catch(problem=>{if(alive.current&&current===generation.current){setOffer(null);setError(problem.message);}});}return()=>{alive.current=false;generation.current++;};},[release.id,preview]);useEffect(()=>{if(error)summary.current?.focus();},[error]);
 async function free(){setBusy(true);setError('');try{await downloadTemplateSource('/education-releases/'+release.id+'/source','education-'+release.id+'.zip');setMessage('Reviewed free source downloaded. Preserve its license and attribution.');}catch(problem){setError((problem as Error).message);}finally{setBusy(false);}}
 async function reconcile(){if(!order)return;setBusy(true);setError('');try{const purchase=await api('/template-purchases/'+order.id+'/reconcile',{method:'POST',body:'{}'});setOrder({...order,status:purchase.status});setMessage('Current purchase status: '+templateStatus(purchase.status)+'. Purchase history shows current download eligibility.');}catch(problem){setError((problem as Error).message);}finally{setBusy(false);}}
 async function checkout(){if(preview||!consent||!offer?.checkoutAvailable||!offer.package?.templateId||!offer.package.versionId)return;setBusy(true);setError('');try{key.current||=crypto.randomUUID();const result:TemplateOrder=await api('/templates/'+offer.package.templateId+'/orders',{method:'POST',headers:{'Idempotency-Key':key.current},body:JSON.stringify({versionId:offer.package.versionId,licenseConsent:true,educationReleaseId:release.id})});setOrder(result);if(result.status!=='ORDER_CREATED'||!result.orderId||!result.keyId){setMessage('Purchase status: '+templateStatus(result.status)+'. Refresh the provider status before another checkout.');return;}const Gateway=await loadTemplateCheckout();if(!alive.current)return;const gateway=new Gateway({key:result.keyId,order_id:result.orderId,amount:result.amountMinor,currency:result.currency,name:result.mode==='test'?'getLancer · test checkout':'getLancer',description:release.snapshot.title,handler:async(payload:{razorpay_payment_id:string;razorpay_signature:string})=>{try{const purchase=await api('/template-purchases/'+result.id+'/verify',{method:'POST',body:JSON.stringify({razorpay_payment_id:payload.razorpay_payment_id,razorpay_signature:payload.razorpay_signature})});if(alive.current){setOrder({...result,status:purchase.status});setMessage('Server-verified purchase status: '+templateStatus(purchase.status)+'. Open purchase history for immutable terms and current entitlement.');}}catch(problem){if(alive.current)setError((problem as Error).message);}},modal:{ondismiss:()=>{if(alive.current)setMessage('Checkout closed. Reconcile this purchase before starting another payment.');}}});gateway.on('payment.failed',event=>{if(alive.current)setError(event.error?.description||'Payment did not complete. Reconcile its provider status.');});gateway.open();if(result.mode==='test')setMessage('Test checkout never grants real source downloads.');}catch(problem){setError((problem as Error).message);}finally{setBusy(false);}}
 const s=release.snapshot,offered=offer?.package,binding=offered?.sha256&&typeof offered.sizeBytes==='number'?offered:s.sourceBinding;
 return <><EducationPackage pack={s.package} binding={binding} showcase={s.mode==='SHOWCASE'}/><section className="kit-info-panel"><h2>{s.mode==='SHOWCASE'?'Showcase only':s.mode==='FREE'?'Learn with the source':'License this source version'}</h2><p>Reviewed content revision {release.revision}</p><p className="kit-source-hash">Content SHA-256: {release.sourceHash||'Not published'}</p><Link className="button" href={'?release='+release.id}>Link to this reviewed version ↗</Link><p>Source licensing does not confer authorship, university certification or academic marks.</p>{order?.mode==='test'&&<p className="kit-notice">Test checkout never grants real source downloads.</p>}{error&&<p role="alert" tabIndex={-1} ref={summary} className="error">{error}</p>}{message&&<p role="status" className="kit-notice">{message}</p>}{s.mode==='SHOWCASE'?<p>No source download or purchase is offered for this release.</p>:s.mode==='FREE'?preview?<><p>Original sample files are real. The listing and review state are illustrative.</p>{previewPackageUrl&&<a className="button primary" href={previewPackageUrl} download>Download original sample source</a>}</>:<button className="button primary" disabled={busy||!offer?.available} onClick={()=>void free()}>{busy?'Preparing source…':'Download reviewed free source'}</button>:<><p><strong>{templatePrice(s.priceMinor||0)}</strong> · {binding?.version||'Frozen source version'}</p><p>Payment licenses the inspected source package, with the included/excluded assets, setup and support stated above. Hosting and hardware are separate.</p>{(!offer?.checkoutAvailable||preview)&&<p role="status" className="kit-notice">{offer?.checkoutReason||offer?.reason||'Paid activation is pending merchant approval. Checkout is unavailable.'}</p>}<label className="kit-consent" style={{minHeight:44,alignItems:'center'}}><input type="checkbox" checked={consent} disabled={busy||preview||!offer?.checkoutAvailable} onChange={event=>setConsent(event.target.checked)}/>I have read and accept this exact source version’s license and package disclosures.</label><button className="button primary" disabled={busy||preview||!offer?.checkoutAvailable||!consent} onClick={()=>void checkout()}>Accept license & continue to payment</button>{order&&<button className="button" disabled={busy} onClick={()=>void reconcile()}>Refresh provider status</button>}<Link className="button" href="/workspace/templates">Purchase history & current source access ↗</Link></>}{!preview&&<Link className="button" href={'/report?product='+release.productId+'&educationReleaseId='+release.id}>Report this exact artifact ↗</Link>}</section></>;
}
