'use client';

import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,CheckCircle2,FileArchive,RefreshCw,ShieldCheck,Upload} from 'lucide-react';
import {Card,CardContent,CardHeader} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {api,ApiError} from '@/lib/api';
import {createHostingPreview,hostedDemoUrl,hostingAttention,hostingBytes,hostingCanPublish,hostingDate,hostingLabel,hostingLimits,hostingPage,validateHostingUpload,type HostedDemo,type HostingConfiguration,type HostingPage,type HostingSource} from '@/lib/hosting';
import {Field,TeamForm} from './workspace-form';
import {PreviewControls,WorkspaceFrame} from './workspace-frame';
import '@/app/hosting.css';

const empty=<T,>()=>hostingPage<T>([]);
const post=(path:string,body:unknown={})=>api(path,{method:'POST',body:JSON.stringify(body)});
async function binaryRequest(path:string,init:RequestInit={}){
  const response=await fetch('/api/v1'+path,{...init,credentials:'same-origin',headers:{'X-Requested-With':'getlancer',...init.headers}});
  if(!response.ok){const body=await response.json().catch(()=>({}));throw new ApiError(body.error?.message||'The package request failed.',body.error?.code||'REQUEST_FAILED',response.status,body.error?.requestId,body.error?.fieldErrors||{});}
  return response;
}
function Consent({name='rightsConsent',children}:{name?:string;children:React.ReactNode}){return <label className="hosting-consent"><input name={name} type="checkbox" required/>{children}</label>;}

export default function HostingWorkspace({demo=false}:{demo?:boolean}){
  const [preview]=useState(()=>demo?createHostingPreview():null),[actor,setActor]=useState<'BUILDER'|'OPERATOR'>('BUILDER');
  const [records,setRecords]=useState<HostingPage<HostedDemo>>(empty),[sources,setSources]=useState<HostingPage<HostingSource>>(empty),[detail,setDetail]=useState<HostedDemo|null>(null),[config,setConfig]=useState<HostingConfiguration|null>(null);
  const [selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[authenticated,setAuthenticated]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[dialog,setDialog]=useState(''),[privateEpoch,setPrivateEpoch]=useState(0),[sourceHint,setSourceHint]=useState(''),[fileError,setFileError]=useState('');
  const generation=useRef(0),operation=useRef(0),mounted=useRef(true),opener=useRef<HTMLElement|null>(null),uploadFile=useRef<File|null>(null),summary=useRef<HTMLParagraphElement>(null),focusHeading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{if(error)summary.current?.focus();},[error]);
  function close(){setDialog('');uploadFile.current=null;setFileError('');}
  function clear(){generation.current++;operation.current++;setLoading(false);setBusy(false);setAuthenticated(false);setRecords(empty());setSources(empty());setDetail(null);setConfig(null);setSelected('');setSourceHint('');setNote('');close();setPrivateEpoch(value=>value+1);opener.current=null;}
  async function load(id=selected,page=records.page,sourcePage=sources.page,failureContext=''){
    const run=++generation.current;setLoading(true);setError('');setDetail(null);setNote('');
    try{
      const [nextRecords,nextSources,nextConfig]:[HostingPage<HostedDemo>,HostingPage<HostingSource>,HostingConfiguration]=preview?[hostingPage(preview.list(),page),hostingPage(preview.sources(),sourcePage),{enabled:true,reason:'',...hostingLimits}]:await Promise.all([api('/me/hosting?page='+page+'&size=12'),api('/me/hosting/sources?page='+sourcePage+'&size=12'),api('/hosting/config')]);
      const chosen=id||nextRecords.items[0]?.id||'';
      const nextDetail:HostedDemo|null=chosen?(preview?preview.detail(chosen):await api('/me/hosting/'+encodeURIComponent(chosen))):null;
      if(!mounted.current||run!==generation.current)return false;
      setRecords(nextRecords);setSources(nextSources);setConfig(nextConfig);setSelected(chosen);setDetail(nextDetail);setAuthenticated(true);return true;
    }catch(problem){if(mounted.current&&run===generation.current){clear();setError((failureContext?failureContext+' ':'')+(problem as Error).message);}return false;}
    finally{if(mounted.current&&run===generation.current)setLoading(false);}
  }
  useEffect(()=>{mounted.current=true;const query=new URLSearchParams(window.location.search);setSourceHint(query.get('productId')||'');void load(query.get('demoId')||'');return()=>{mounted.current=false;generation.current++;operation.current++;uploadFile.current=null;};},[]);
  async function change(work:()=>unknown|Promise<unknown>,message:string,id=selected,page=records.page){
    const run=++generation.current,op=++operation.current;setBusy(true);setError('');setNote('');
    try{
      const result=await work();if(!mounted.current||run!==generation.current||op!==operation.current)return false;
      const next=id||((result&&typeof result==='object'&&'id' in result)?String(result.id):'');
      if(!await load(next,page,sources.page,'The action may have been saved, but its refreshed status is unavailable. Retry the connection to verify it.'))throw Error('The action may have been saved, but its refreshed status is unavailable. Retry the connection to verify the current record.');
      if(!mounted.current||op!==operation.current)return false;
      setNote(message);return true;
    }catch(problem){
      if(mounted.current&&op===operation.current){
        if(problem instanceof ApiError&&[401,403].includes(problem.status)){clear();setError(problem.message);}
        else {
          // A failed publisher response can follow a committed reservation or withdrawal.
          // GET the same record, without retrying POST or claiming success.
          if(!preview&&run===generation.current)await load(id,page,sources.page,(problem as Error).message+' Current status could not be confirmed after this response.');
          if(mounted.current&&op===operation.current)setError((problem as Error).message);
        }
      }
      throw problem;
    }
    finally{if(mounted.current&&op===operation.current)setBusy(false);}
  }
  function act(work:()=>unknown|Promise<unknown>,message:string){void change(work,message).catch(()=>{});}
  function show(value:string){opener.current=document.activeElement as HTMLElement;uploadFile.current=null;setFileError('');setError('');setDialog(value);}
  function select(id:string){operation.current++;setBusy(false);setSelected(id);const url=new URL(window.location.href);url.searchParams.set('demoId',id);window.history.replaceState(null,'',url);void load(id);}
  async function upload(data:Record<string,string>){
    const consent=data.rightsConsent==='on',file=preview?{name:'bundled-sample.zip',size:18432}:uploadFile.current;
    setFileError('');try{validateHostingUpload(file,data.title,data.version,consent);}catch(problem){setFileError((problem as Error&{fieldErrors?:Record<string,string>}).fieldErrors?.file||'');throw problem;}
    if(!data.productId)throw new ApiError('Choose an eligible current public proof.','INVALID_SOURCE',400,undefined,{productId:'Choose a currently approved public proof.'});
    if(await change(async()=>{if(preview)return preview.create(data.title,data.version,consent);const form=new FormData();form.append('file',uploadFile.current!);for(const name of ['productId','title','version'])form.append(name,data[name]);form.append('rightsConsent','true');return (await binaryRequest('/me/hosting',{method:'POST',body:form})).json();},preview?'Bundled sample draft copied locally. No archive was uploaded.':'Immutable package uploaded as a draft. Submit it for a separate operator review.','',0))close();
  }
  async function submit(data:Record<string,string>){if(!detail)return;if(await change(()=>preview?preview.submit(detail.id,data.rightsConsent==='on'):post('/me/hosting/'+detail.id+'/submit',{rightsConsent:data.rightsConsent==='on'}),preview?'Sample submitted for simulated operator review.':'Package submitted for operator review.'))close();}
  async function sampleReview(data:Record<string,string>){if(!detail||!preview)return;if(await change(()=>preview.review(detail.id,{action:data.action,reason:data.reason,packageReviewed:data.packageReviewed==='on',rightsReviewed:data.rightsReviewed==='on'}),'Simulated operator review recorded locally.'))close();}
  async function withdraw(){if(!detail)return;if(await change(()=>preview?preview.withdraw(detail.id):post('/me/hosting/'+detail.id+'/withdraw'),preview?'Sample withdrawn. No external deployment was deleted.':'Withdrawal recorded. Public access is denied; check the deployment state for deletion confirmation.'))close();}
  async function download(){if(!detail||preview)return;const id=detail.id,run=++generation.current,op=++operation.current;setBusy(true);setError('');setNote('');try{const response=await binaryRequest('/me/hosting/'+id+'/package'),blob=await response.blob();if(!mounted.current||run!==generation.current||op!==operation.current)return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='frontend-'+id+'.zip';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNote('Package ZIP downloaded.');}catch(problem){if(mounted.current&&run===generation.current){if(problem instanceof ApiError&&[401,403].includes(problem.status))clear();setError((problem as Error).message);}}finally{if(mounted.current&&op===operation.current)setBusy(false);}}
  const disabled=busy||loading,builder=!preview||actor==='BUILDER',link=detail&&!preview?hostedDemoUrl(detail):undefined;
  const steps=detail?detail.status==='APPROVED'?(detail.deploymentState==='READY'?100:67):detail.status==='PENDING'?34:0:0;
  return <WorkspaceFrame section="hosting" title="Hosted frontend demos" description="Upload a built static frontend, get it reviewed, then publish it on an isolated demo origin." preview={demo} actions={<button className="button primary" disabled={disabled||!authenticated||!builder||!config?.enabled||records.totalItems>=10} onClick={()=>show('upload')}><Upload size={17} aria-hidden="true"/>{preview?'Copy bundled sample':'Upload frontend ZIP'}</button>}>
    {preview&&<PreviewControls title="Hosted frontend sample" note="Bundled frontend metadata only. Review, publication and recovery are simulated in memory. No account, upload, API or publisher request is sent; no live demo is created."><label>Sample actor<select aria-label="Sample actor" value={actor} disabled={disabled} onChange={event=>{const next=event.target.value as typeof actor;operation.current++;preview.setActor(next);setActor(next);setBusy(false);close();void load();}}><option value="BUILDER">Builder</option><option value="OPERATOR">Operator (simulated)</option></select></label><button className="button" disabled={disabled} onClick={()=>{operation.current++;preview.reset();setActor('BUILDER');setBusy(false);close();void load('',0,0);}}>Reset sample</button>{detail&&builder&&hostingCanPublish(detail)&&<button className="button" disabled={disabled} onClick={()=>act(()=>preview.publish(detail.id,true),'Interrupted publication simulated. Reconcile the same reservation.')}>Simulate interrupted publication</button>}{detail&&builder&&['READY','UNKNOWN'].includes(detail.deploymentState)&&<button className="button" disabled={disabled} onClick={()=>act(()=>preview.withdraw(detail.id,true),'Delayed deletion simulated. Access is denied while recovery is pending.')}>Simulate delayed withdrawal</button>}</PreviewControls>}
    {error&&<p className="hosting-notice error" role="alert" tabIndex={-1} ref={summary}>{error}</p>}{note&&<p className="hosting-notice" role="status">{note}</p>}{loading&&<p className="hosting-notice" role="status">Loading frontend packages…</p>}
    {!loading&&!authenticated&&<Card><CardContent className="hosting-empty"><ShieldCheck aria-hidden="true"/><h2 ref={focusHeading} tabIndex={-1}>Connect to your hosting workspace</h2><p>Sign in with your individual builder account. Uploads require an active approved profile and a currently approved public proof with a verified repository.</p><div className="hosting-actions"><Link className="button primary" href="/login">Sign in</Link><button className="button" onClick={()=>void load('',0,0)}>Retry connection</button></div></CardContent></Card>}
    {authenticated&&<>
      {!config?.enabled&&<p className="hosting-notice">Hosting is unavailable. {config?.reason||'The static publisher is not configured.'} Existing withdrawal and recovery controls remain available.</p>}
      <div className="hosting-layout" aria-busy={loading}>
        <Card className="hosting-chooser"><CardHeader><h2>Frontend packages</h2><span className="hosting-muted">{records.totalItems} / {config?.maxRecords||10} retained</span></CardHeader><CardContent>{records.items.length?<nav aria-label="Frontend packages">{records.items.map(item=><button key={item.id} disabled={disabled} aria-current={item.id===selected?'true':undefined} onClick={()=>select(item.id)}><strong>{item.title}</strong><span>{item.productTitle}</span><small>{item.version} · {hostingLabel(item.status)}</small></button>)}</nav>:<p>No frontend packages yet. Upload a ZIP containing built HTML, CSS and JavaScript with a root index.html.</p>}<HostingPagination label="Package" page={records} busy={disabled} onPage={page=>void load('',page)}/></CardContent></Card>
        <div className="hosting-main">{detail?<>
          <Card className="hosting-current"><CardHeader><div><span className="hosting-kicker">{preview?'Bundled local exercise':'Immutable static package'}</span><h2 ref={focusHeading} tabIndex={-1}>{detail.title}</h2><p className="hosting-muted">{detail.productTitle} · version {detail.version}</p></div><Badge variant="outline">{hostingLabel(detail.status)}</Badge></CardHeader><CardContent>
            <div className="hosting-facts"><div><FileArchive size={21} aria-hidden="true"/><strong>{hostingBytes(detail.sizeBytes)}</strong><span>compressed ZIP</span></div><div><strong>{detail.fileCount} files</strong><span>{hostingBytes(detail.expandedBytes)} expanded</span></div><div><strong>{hostingLabel(detail.deploymentState)}</strong><span>{hostingLabel(detail.desiredState)} intent</span></div></div>
            <Progress value={steps} aria-label="Package review and publication progress" aria-valuetext={detail.status==='APPROVED'?(detail.deploymentState==='READY'?'Reviewed; publication ready':'Reviewed; publication pending'):detail.status==='PENDING'?'Waiting for review':'Draft or review blocked'}/><div className="hosting-steps"><span>1. Package</span><span>2. Review</span><span>3. Publish</span></div>
            <div className="hosting-state"><strong>{hostingAttention(detail)?'Recovery needs attention':detail.deploymentState==='READY'?(preview?'Simulated publication ready':link?'Publication ready':'Public access unavailable'):detail.deploymentState==='DELETED'?'Withdrawal completed':detail.status==='PENDING'?'Waiting for operator review':detail.status==='APPROVED'?'Reviewed and ready to publish':'Review required before publication'}</strong><p>{hostingAttention(detail)?'Refresh or reconcile this same deployment identity. An uncertain response must never create a second deployment.':detail.deploymentState==='DELETED'?'This identity stays withdrawn. Upload a new immutable version if you need another reviewed publication.':preview?'The bundled sample never serves a live frontend. All actions remain on this page.':'Packages are checked separately from publication. Public access is rechecked on every hosted request.'}</p>{detail.expiresAt&&<p>Fixed expiry: {hostingDate(detail.expiresAt)}</p>}{detail.deploymentId&&<p className="hosting-reference">Deployment: {detail.deploymentId}</p>}{detail.reviewReason&&<p>Review reason: {detail.reviewReason}</p>}</div>
            <div className="hosting-actions">
              {builder&&['DRAFT','CHANGES_REQUESTED'].includes(detail.status)&&detail.deploymentState==='NOT_CREATED'&&<button className="button primary" disabled={disabled||!config?.enabled} onClick={()=>show('submit')}>Review rights & submit</button>}
              {preview&&!builder&&['PENDING','APPROVED','SUSPENDED'].includes(detail.status)&&<button className="button primary" disabled={disabled} onClick={()=>show('review')}>Simulate operator review</button>}
              {builder&&hostingCanPublish(detail)&&<button className="button primary" disabled={disabled||!config?.enabled} onClick={()=>act(()=>preview?preview.publish(detail.id):post('/me/hosting/'+detail.id+'/deploy'),preview?'Publication simulated locally. No external demo exists.':'Publication status refreshed. Open the demo only when its URL is available.')}>{preview?'Simulate publication':'Publish reviewed frontend'}</button>}
              {link&&<a className="button primary" href={link} target="_blank" rel="noopener noreferrer">Open hosted demo<ArrowUpRight size={15} aria-hidden="true"/></a>}
              {builder&&hostingAttention(detail)&&<button className="button" disabled={disabled} onClick={()=>act(()=>preview?preview.reconcile(detail.id):post('/me/hosting/'+detail.id+'/reconcile'),preview?'Same sample deployment reconciled locally.':'Deployment reconciliation refreshed.')}><RefreshCw size={16} aria-hidden="true"/>{preview?'Simulate reconciliation':'Reconcile deployment'}</button>}
              {builder&&detail.deploymentState!=='DELETED'&&<button className="button" disabled={disabled} onClick={()=>show('withdraw')}>Withdraw frontend</button>}
              {!preview&&<button className="button" disabled={disabled} onClick={()=>void download()}>Download package ZIP</button>}
              <button className="button" disabled={disabled} onClick={()=>void load()}>Refresh status</button>
            </div>
          </CardContent></Card>
          <Card><CardHeader><h2>Package & rights</h2><p className="hosting-muted">Built static files only. No server source, builds or package installs run.</p></CardHeader><CardContent><dl className="hosting-details"><div><dt>Rights consent</dt><dd>{detail.rightsConsentAt?hostingDate(detail.rightsConsentAt):'Not yet recorded for this sample'}</dd></div><div><dt>Archive SHA-256</dt><dd className="hosting-hash">{detail.archiveSha256}</dd></div><div><dt>Manifest SHA-256</dt><dd className="hosting-hash">{detail.manifestSha256}</dd></div></dl><details className="hosting-manifest"><summary>File manifest ({detail.fileCount})</summary><ul>{detail.files.map(file=><li key={file.path}><strong>{file.path}</strong><span>{hostingBytes(file.sizeBytes)}</span><code>{file.sha256}</code></li>)}</ul></details><p className="hosting-muted">You retain responsibility for the package and permission to distribute its code, assets and data. Review does not guarantee safety or intellectual property rights.</p></CardContent></Card>
          <Card><CardHeader><h2>Activity</h2></CardHeader><CardContent>{detail.audit.length?<ol className="hosting-activity">{detail.audit.map(item=><li key={item.id}><strong>{hostingLabel(item.action)}</strong><p>{item.detail}</p><small>{hostingDate(item.createdAt)}</small></li>)}</ol>:<p className="hosting-muted">No review or deployment activity yet.</p>}</CardContent></Card>
        </>:<Card><CardContent className="hosting-empty"><FileArchive aria-hidden="true"/><h2>Prepare a static export</h2><p>Keep the ZIP under 5 MiB, expanded content under 10 MiB and files under 256. Include index.html at its root.</p></CardContent></Card>}</div>
      </div>
    </>}
    <Dialog open={!!dialog} onOpenChange={open=>{if(!open&&!busy)close();}}><DialogContent className="hosting-dialog" onEscapeKeyDown={event=>{if(busy)event.preventDefault();}} onPointerDownOutside={event=>{if(busy)event.preventDefault();}} onCloseAutoFocus={event=>{event.preventDefault();if(opener.current?.isConnected)opener.current.focus();else focusHeading.current?.focus();}}><DialogHeader><DialogTitle>{dialog==='upload'?(preview?'Copy bundled sample package':'Upload built frontend ZIP'):dialog==='submit'?'Review rights & submit':dialog==='review'?'Simulated operator review':'Withdraw frontend'}</DialogTitle><DialogDescription>{dialog==='upload'?'Every upload is an immutable version attached to your current eligible public proof.':dialog==='submit'?'Operator review comes first. Publication is a separate action after approval.':dialog==='review'?'Local sample checks only. A real operator must download the archive with MFA and inspect its contents and rights.':'Withdrawal denies public access before provider deletion finishes. Recovery keeps the same deployment identity.'}</DialogDescription></DialogHeader>
      {dialog==='upload'&&<TeamForm key={'upload-'+privateEpoch} busy={disabled} label={preview?'Copy sample draft':'Upload immutable package'} onSave={upload}><Field name="productId" label="Current public proof" value={sources.items.some(item=>item.id===sourceHint)?sourceHint:''} options={[{value:'',label:'Choose a current public proof'},...sources.items.map(item=>({value:item.id,label:item.title}))]}/>{!sources.items.length&&<p className="hosting-muted">No eligible proof on this page. Uploads need your currently approved public proof and a verified repository.</p>}<HostingPagination label="Proof source" page={sources} busy={disabled} onPage={page=>void load(selected,records.page,page)}/><Field name="title" label="Frontend title" value={preview?'Approval portal frontend':''} minLength={3} maxLength={100}/><Field name="version" label="Package version" value={preview?'1.0.1':''} minLength={1} maxLength={40} hint="1–40 letters, numbers, dots, underscores, plus or hyphen; start with a letter or number."/>{preview?<p className="hosting-notice"><CheckCircle2 size={17} aria-hidden="true"/>Bundled sample: index.html, CSS, JavaScript and license metadata. No file is uploaded.</p>:<label className="team-field"><span className="team-field-label">Built frontend ZIP</span><input aria-label="Built frontend ZIP" aria-invalid={fileError?true:undefined} aria-describedby={fileError?"hosting-file-hint hosting-file-error":"hosting-file-hint"} name="file" type="file" accept=".zip,application/zip" required onChange={event=>{uploadFile.current=event.target.files?.[0]||null;setFileError('');}}/><span id="hosting-file-hint" className="team-field-hint">5 MiB compressed / 10 MiB expanded / 256 files. Include root index.html. Secrets, private data, nested archives and server source are rejected.</span>{fileError&&<span id="hosting-file-error" className="team-error">{fileError}</span>}</label>}<Consent>I own this package or have permission to distribute and host its code, assets and data. I understand that review does not guarantee safety or rights.</Consent></TeamForm>}
      {dialog==='submit'&&detail&&<TeamForm key={'submit-'+detail.id+'-'+privateEpoch} busy={disabled} label={preview?'Submit sample for review':'Submit package for review'} onSave={submit}><p>{detail.title} · {detail.version} · {hostingBytes(detail.sizeBytes)} · {detail.fileCount} files</p><Consent>I confirm my rights to host this exact immutable package and accept responsibility for its code, assets and data.</Consent></TeamForm>}
      {dialog==='review'&&detail&&<TeamForm key={'review-'+detail.id+'-'+privateEpoch} busy={disabled} label="Record simulated review" onSave={sampleReview}><Field name="action" label="Sample review decision" options={detail.status==='APPROVED'?[{value:'SUSPEND',label:'Suspend sample approval'}]:[{value:'APPROVE',label:'Approve sample package'},{value:'CHANGES_REQUESTED',label:'Request changes'},{value:'REJECT',label:'Reject sample package'}]}/><Field name="reason" label="Sample review reason" type="textarea" minLength={10} maxLength={2000}/><Consent name="packageReviewed">I inspected the labelled bundled sample file manifest.</Consent><Consent name="rightsReviewed">I reviewed the sample rights consent.</Consent></TeamForm>}
      {dialog==='withdraw'&&detail&&<TeamForm key={'withdraw-'+detail.id+'-'+privateEpoch} busy={disabled} label={preview?'Withdraw sample':'Confirm withdrawal'} onSave={withdraw}><p>{detail.title} · {detail.version}. A withdrawn deployment cannot be resurrected by a delayed publication response.</p></TeamForm>}
    </DialogContent></Dialog>
  </WorkspaceFrame>;
}

export function HostingPagination<T>({page,busy,label,onPage}:{page:HostingPage<T>;busy:boolean;label:string;onPage:(page:number)=>void}){return page.page>0||page.hasMore?<nav className="hosting-pagination" aria-label={label+' pages'}><button className="button" type="button" disabled={busy||page.page===0} onClick={()=>onPage(page.page-1)}>Previous {label.toLowerCase()}s</button><span>Page {page.page+1} of {page.totalPages}</span><button className="button" type="button" disabled={busy||!page.hasMore} onClick={()=>onPage(page.page+1)}>Next {label.toLowerCase()}s</button></nav>:null;}
