'use client';

import {useEffect,useRef,useState} from 'react';
import {Card,CardContent,CardHeader} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {api,ApiError} from '@/lib/api';
import {hostingAttention,hostingBytes,hostingDate,hostingLabel,type HostedDemo,type HostingPage} from '@/lib/hosting';
import {Field,TeamForm} from './workspace-form';
import '@/app/hosting.css';

export default function HostingOperations(){
  const [page,setPage]=useState<HostingPage<HostedDemo>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[dialog,setDialog]=useState<{record:HostedDemo;action:string}|null>(null),[downloads,setDownloads]=useState<Record<string,string>>({}),[epoch,setEpoch]=useState(0);
  const generation=useRef(0),operation=useRef(0),mounted=useRef(true),opened=useRef(false),opener=useRef<HTMLElement|null>(null),panelTitle=useRef<HTMLElement>(null),summary=useRef<HTMLParagraphElement>(null);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current++;operation.current++;};},[]);
  useEffect(()=>{if(error)summary.current?.focus();},[error]);
  function clear(){generation.current++;operation.current++;setPage(null);setDownloads({});setDialog(null);setNote('');setEpoch(value=>value+1);setBusy(false);opener.current=null;}
  async function load(number=page?.page||0,failureContext=''){const run=++generation.current;setBusy(true);setError('');setNote('');try{const next:HostingPage<HostedDemo>=await api('/admin/hosting?page='+number+'&size=12');if(!mounted.current||run!==generation.current)return false;setPage(next);return true;}catch(problem){if(mounted.current&&run===generation.current){clear();setError((failureContext?failureContext+' ':'')+(problem as Error).message);}return false;}finally{if(mounted.current&&run===generation.current)setBusy(false);}}
  async function download(record:HostedDemo){const run=++generation.current,op=++operation.current;setBusy(true);setError('');setNote('');try{
    const response=await fetch('/api/v1/admin/hosting/'+record.id+'/package',{credentials:'same-origin',headers:{'X-Requested-With':'getlancer'}});
    if(!response.ok){const body=await response.json().catch(()=>({}));throw new ApiError(body.error?.message||'Archive download failed.',body.error?.code||'DOWNLOAD_FAILED',response.status,body.error?.requestId);}
    const blob=await response.blob();if(!mounted.current||run!==generation.current||op!==operation.current||!opened.current)return;
    const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='review-frontend-'+record.id+'.zip';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
    setDownloads(previous=>({...previous,[record.id]:record.archiveSha256}));setNote('ZIP downloaded for '+record.title+'. Inspect the actual archive and rights before recording review checks.');
  }catch(problem){if(mounted.current&&run===generation.current){if(problem instanceof ApiError&&[401,403].includes(problem.status))clear();setError((problem as Error).message);}}finally{if(mounted.current&&op===operation.current)setBusy(false);}}
  function show(record:HostedDemo,action:string){opener.current=document.activeElement as HTMLElement;setDialog({record,action});setError('');}
  async function save(data:Record<string,string>){if(!dialog)return;const {record,action}=dialog,run=++generation.current,op=++operation.current;setBusy(true);setError('');setNote('');try{
    const body=action==='review'?{action:data.action,reason:data.reason,rightsReviewed:data.rightsReviewed==='on',packageReviewed:data.packageReviewed==='on'}:{reason:data.reason};
    if(action==='review'&&downloads[record.id]!==record.archiveSha256)throw Error('Download and inspect this exact immutable archive before reviewing it.');
    await api('/admin/hosting/'+record.id+'/'+action,{method:'POST',body:JSON.stringify(body)});
    if(!mounted.current||run!==generation.current||op!==operation.current||!opened.current)return;
    if(!await load(page?.page||0,'The operator action may have been saved, but its refreshed status is unavailable. Retry to verify it.'))throw Error('The operator action may have been saved, but its refreshed status is unavailable. Retry to verify the record.');
    if(!mounted.current||op!==operation.current)return;setDialog(null);setNote('Operator '+action+' recorded and current hosting state refreshed.');
  }catch(problem){if(mounted.current&&op===operation.current){if(problem instanceof ApiError&&[401,403].includes(problem.status)){clear();setError(problem.message);}else{if(run===generation.current)await load(page?.page||0,(problem as Error).message+' Current status could not be confirmed after this response.');if(mounted.current&&op===operation.current)setError((problem as Error).message);}}throw problem;}finally{if(mounted.current&&op===operation.current)setBusy(false);}}
  return <details className="panel hosting-operations" onToggle={event=>{opened.current=event.currentTarget.open;if(opened.current&&!page&&!busy)void load(0);if(!opened.current)clear();}}><summary ref={panelTitle}>Hosted frontend review & recovery</summary><p>Administrator MFA is required for every request. Download the actual immutable ZIP, inspect its static files and review the builder’s rights consent before approving. Publishing remains the builder’s separate action.</p><button className="button" disabled={busy} onClick={()=>void load()}>Refresh hosting operations</button>{error&&<p className="hosting-notice error" role="alert" tabIndex={-1} ref={summary}>{error}</p>}{note&&<p className="hosting-notice" role="status">{note}</p>}{page&&!page.items.length&&<p>No hosted frontend records on this page.</p>}
    <div className="hosting-operator-list">{page?.items.map(record=><Card key={record.id}><CardHeader><div><h3>{record.title}</h3><p>{record.productTitle} · {record.version}</p></div><Badge variant="outline">{hostingLabel(record.status)} · {hostingLabel(record.deploymentState)}</Badge></CardHeader><CardContent><p>{hostingBytes(record.sizeBytes)} compressed · {record.fileCount} files · {hostingLabel(record.desiredState)} intent</p><dl className="hosting-details"><div><dt>Package ID</dt><dd>{record.id}</dd></div><div><dt>Archive SHA-256</dt><dd className="hosting-hash">{record.archiveSha256}</dd></div><div><dt>Deployment ID</dt><dd>{record.deploymentId||'Not reserved'}</dd></div><div><dt>Fixed expiry</dt><dd>{hostingDate(record.expiresAt)}</dd></div><div><dt>Rights consent</dt><dd>{record.rightsConsentAt?hostingDate(record.rightsConsentAt):'Not recorded'}</dd></div></dl>{record.reviewReason&&<p>Review reason: {record.reviewReason}</p>}{hostingAttention(record)&&<p className="hosting-notice">Recovery needs attention. Reconcile the existing deployment ID and frozen hashes. Withdrawal denies access before deletion is confirmed.</p>}<div className="hosting-actions"><button className="button" disabled={busy} onClick={()=>void download(record)}>Download actual ZIP</button>{['PENDING','APPROVED','SUSPENDED'].includes(record.status)&&<button className="button primary" disabled={busy||downloads[record.id]!==record.archiveSha256} onClick={()=>show(record,'review')}>Review package & rights</button>}{hostingAttention(record)&&<button className="button" disabled={busy} onClick={()=>show(record,'reconcile')}>Reconcile same deployment</button>}{record.deploymentState!=='DELETED'&&<button className="button" disabled={busy} onClick={()=>show(record,'withdraw')}>Withdraw hosted frontend</button>}</div>{['PENDING','APPROVED','SUSPENDED'].includes(record.status)&&downloads[record.id]!==record.archiveSha256&&<p className="hosting-muted">Download this exact archive to enable the review form. Both review checkboxes begin unchecked.</p>}</CardContent></Card>)}</div>
    {page&&(page.page>0||page.hasMore)&&<nav className="hosting-pagination" aria-label="Hosting operation pages"><button className="button" disabled={busy||page.page===0} onClick={()=>void load(page.page-1)}>Previous hosting records</button><span>Page {page.page+1} of {page.totalPages}</span><button className="button" disabled={busy||!page.hasMore} onClick={()=>void load(page.page+1)}>Next hosting records</button></nav>}
    <Dialog open={!!dialog} onOpenChange={open=>{if(!open&&!busy)setDialog(null);}}><DialogContent className="hosting-dialog" onEscapeKeyDown={event=>{if(busy)event.preventDefault();}} onPointerDownOutside={event=>{if(busy)event.preventDefault();}} onCloseAutoFocus={event=>{event.preventDefault();(opener.current?.isConnected?opener.current:panelTitle.current)?.focus();}}><DialogHeader><DialogTitle>{dialog?.action==='review'?'Review actual package & rights':dialog?.action==='reconcile'?'Reconcile existing deployment':'Withdraw hosted frontend'}</DialogTitle><DialogDescription>{dialog?.action==='review'?'Record checks only after inspecting the downloaded ZIP. Approval is separate from publication and does not guarantee safety or ownership.':'Use the fixed deployment ID. Record the evidence for this recovery or withdrawal; no new deployment is created.'}</DialogDescription></DialogHeader>{dialog&&<TeamForm key={dialog.record.id+'-'+dialog.action+'-'+epoch} busy={busy} label="Record operator decision" onSave={save}><p>{dialog.record.title} · {dialog.record.version}</p>{dialog.action==='review'&&<><Field name="action" label="Hosting review decision" options={dialog.record.status==='APPROVED'?[{value:'SUSPEND',label:'Suspend approval and public access'}]:[{value:'APPROVE',label:'Approve for separate builder publication'},{value:'CHANGES_REQUESTED',label:'Request package changes'},{value:'REJECT',label:'Reject package'}]}/><label className="hosting-consent"><input name="packageReviewed" type="checkbox" required/>I downloaded and inspected this exact immutable ZIP and its static files.</label><label className="hosting-consent"><input name="rightsReviewed" type="checkbox" required/>I reviewed the recorded rights consent and supporting package evidence.</label></>}<Field name="reason" label="Hosting evidence & decision reason" type="textarea" minLength={10} maxLength={2000}/></TeamForm>}</DialogContent></Dialog>
  </details>;
}
