'use client';
import {useState} from 'react';
import {api,ApiError} from '@/lib/api';
import {templatePrice,type TemplatePage} from '@/lib/templates';
import {Field,TeamForm} from './workspace-form';
type Attention={id:string;offerId:string;status:string;mode:string;creationStep:string;providerPlanId?:string;providerSubscriptionId?:string;amountMinor:number;accountId:string;attentionReason?:string;localHold:boolean;cancelState?:string;periods?:{id:string;providerInvoiceId:string;transferState:string;pendingRefund:boolean;refundedMinor:number;disputeStatus:string;transferStatus?:string;attentionReason?:string}[]};
export default function MaintenanceOperations(){
 const [page,setPage]=useState<TemplatePage<Attention>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState('');
 async function load(number=page?.page||0){setBusy(true);setError('');try{setPage(await api('/admin/maintenance/attention?page='+number+'&size=12'));return true;}catch(problem){setPage(null);setError((problem as Error).message);return false;}finally{setBusy(false);}}
 async function save(id:string,data:Record<string,string>){setBusy(true);setError('');setNote('');try{const result=await api('/admin/maintenance/'+id+'/'+data.action,{method:'POST',body:JSON.stringify({reason:data.reason,providerId:data.providerId,periodId:data.periodId})});if(!await load())throw new Error('The operator action was saved, but its refreshed status is unavailable. Reconnect to verify it.');setNote('Operator action recorded. Provider state: '+result.status);}catch(problem){if(problem instanceof ApiError&&[401,403].includes(problem.status))setPage(null);setError((problem as Error).message);throw problem;}finally{setBusy(false);}}
 return <details className="panel" onToggle={event=>{if(event.currentTarget.open&&!page&&!busy)void load(0);}}><summary>Maintenance billing & support operations</summary><p>Administrator MFA is required. Verify frozen amount, mode, notes and seller account before binding an uncertain effect. Recovery never creates paid access from a local decision.</p><button className="button" disabled={busy} onClick={()=>void load()}>Refresh maintenance operations</button>{error&&<p className="error" role="alert">{error}</p>}{note&&<p role="status">{note}</p>}{page&&page.items.length===0&&<p>No maintenance operations need attention.</p>}{page?.items.map(item=><div className="panel" key={item.id}><h3>{item.id}</h3><p>{item.mode} · {item.status} · {templatePrice(item.amountMinor)} / month</p><p>Frozen Route account: {item.accountId}</p><p>{item.attentionReason||(item.localHold?'Operator hold':'Financial or cancellation attention')} · creation stage {item.creationStep}</p>{item.providerPlanId&&<p>Plan: {item.providerPlanId}</p>}{item.providerSubscriptionId&&<p>Subscription: {item.providerSubscriptionId}</p>}<ul>{item.periods?.map(period=><li key={period.id}>Local period {period.id} · {period.providerInvoiceId} · {period.transferState} / {period.transferStatus||'Not confirmed'} · Dispute {period.disputeStatus} · Refunded {templatePrice(period.refundedMinor)}{period.pendingRefund?' · Refund pending':''}{period.attentionReason&&<p>{period.attentionReason}</p>}</li>)}</ul><TeamForm busy={busy} label="Verify & record maintenance action" onSave={data=>save(item.id,data)}><Field name="action" label="Operator action" options={[{value:'reconcile',label:'Reconcile financial state'},{value:'bind-plan',label:'Bind matching plan'},{value:'bind-subscription',label:'Bind matching subscription'},{value:'bind-transfer',label:'Bind matching period transfer'},{value:'cancel',label:'Confirm future billing cancellation'},{value:'hold',label:'Place local support hold'},{value:'release-hold',label:'Release only local hold'}]}/><Field name="providerId" label="Provider ID for binding" required={false} maxLength={40}/><Field name="periodId" label="Local invoice period ID for transfer binding" required={false} maxLength={36}/><Field name="reason" label="Evidence & decision reason" type="textarea" minLength={10} maxLength={1000}/></TeamForm><p>Find local period IDs in the billing workspace or the audited reconciliation response. A provider refund, dispute or unresolved transfer cannot be overridden by releasing a local hold.</p></div>)}{page&&(page.hasMore||page.page>0)&&<div className="care-actions"><button className="button" disabled={busy||page.page===0} onClick={()=>void load(page.page-1)}>Previous operations</button><span>Page {page.page+1}</span><button className="button" disabled={busy||!page.hasMore} onClick={()=>void load(page.page+1)}>Next operations</button></div>}</details>;
}
