'use client';

import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Clock3,LifeBuoy,Plus,RefreshCw,ShieldCheck} from 'lucide-react';
import {Card,CardContent,CardHeader} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {api,ApiError} from '@/lib/api';
import {careLabel,createMaintenancePreview,type CareConfiguration,type CareDetail,type CareOffer,type CareSide,type CareSource,type CareTerms,type CareCheckout} from '@/lib/maintenance';
import {loadTemplateCheckout,templateMinor,templatePrice,templateDate,type TemplatePage} from '@/lib/templates';
import {Field,TeamForm} from './workspace-form';
import {WorkspaceFrame,PreviewControls} from './workspace-frame';
import '@/app/maintenance.css';

const pageOf=<T,>(items:T[]):TemplatePage<T>=>({items,page:0,size:12,hasMore:false,totalItems:items.length,totalPages:items.length?1:0});
const emptyPage=<T,>()=>pageOf<T>([]);
const draft:CareTerms={title:'',scope:'',terms:'',amountMinor:0,requestsPerCycle:3,responseHours:24,totalCycles:12};
type PendingRequest={offerId:string;key:string;title:string;description:string};

export default function MaintenanceWorkspace({demo=false}:{demo?:boolean}) {
  const [preview]=useState(()=>demo?createMaintenancePreview():null),[side,setSide]=useState<CareSide>('SELLER');
  const [offers,setOffers]=useState<TemplatePage<CareOffer>>(emptyPage),[sources,setSources]=useState<TemplatePage<CareSource>>(emptyPage),[detail,setDetail]=useState<CareDetail|null>(null),[configuration,setConfiguration]=useState<CareConfiguration|null>(null);
  const [selected,setSelected]=useState(''),[tab,setTab]=useState('requests'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[authenticated,setAuthenticated]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[dialog,setDialog]=useState(''),[sourceHint,setSourceHint]=useState('');
  const generation=useRef(0),mounted=useRef(true),opener=useRef<HTMLElement|null>(null),summary=useRef<HTMLParagraphElement>(null),billingKey=useRef<Record<string,string>>({}),pendingRequests=useRef<PendingRequest[]>([]),account=useRef('');
  const checkoutGeneration=useRef(0),gatewayRef=useRef<{close?:()=>void}|null>(null);
  const focusHeading=useRef<HTMLHeadingElement|null>(null);
  function invalidateCheckout(){checkoutGeneration.current++;const previous=gatewayRef.current;gatewayRef.current=null;try{previous?.close?.();}catch{/* Callback generations stay invalid even if the SDK fails to close. */}}
  useEffect(()=>{if(error)summary.current?.focus();},[error]);
  function clear(keepKeys=false){generation.current++;invalidateCheckout();setLoading(false);setOffers(emptyPage());setSources(emptyPage());setDetail(null);setConfiguration(null);setAuthenticated(false);setSelected('');setDialog('');setNote('');setSourceHint('');if(!keepKeys){billingKey.current={};pendingRequests.current=[];account.current='';}opener.current=null;}
  async function load(id=selected,page=offers.page,sourcePage=sources.page,requestPage=0,failureMessage='') {
    invalidateCheckout();const run=++generation.current;setLoading(true);setError('');setDetail(null);
    try {
      let nextOffers:TemplatePage<CareOffer>,nextSources:TemplatePage<CareSource>,config:CareConfiguration;
      if(preview){nextOffers=pageOf(preview.list());nextSources=pageOf(preview.sources());config={enabled:true,keyId:'',mode:'preview',reason:''};}
      else {const me=await api('/me');if(run!==generation.current||!mounted.current)return;const identity=String(me.id||me.email||'');if(identity!==account.current){billingKey.current={};pendingRequests.current=[];}account.current=identity;[nextOffers,nextSources,config]=await Promise.all([api('/maintenance?page='+page+'&size=12'+(new URLSearchParams(window.location.search).get('engagementId')?'&engagementId='+encodeURIComponent(new URLSearchParams(window.location.search).get('engagementId')!):'')),api('/maintenance/sources?page='+sourcePage+'&size=12'+(new URLSearchParams(window.location.search).get('engagementId')?'&engagementId='+encodeURIComponent(new URLSearchParams(window.location.search).get('engagementId')!):'')),api('/maintenance/config')]);}
      let chosen=id||nextOffers.items[0]?.id||'';
      const record=chosen?(preview?preview.detail(chosen):await api('/maintenance/'+chosen+'?page='+requestPage+'&size=12')):null;
      if(run!==generation.current||!mounted.current)return;
      setOffers(nextOffers);setSources(nextSources);setConfiguration(config);setSelected(chosen);setDetail(record);setAuthenticated(true);return true;
    } catch(problem){if(run===generation.current&&mounted.current){clear(!(problem instanceof ApiError&&[401,403,404].includes(problem.status)));setError(failureMessage||(problem as Error).message);return false;}}
    finally{if(run===generation.current&&mounted.current)setLoading(false);}
  }
  useEffect(()=>{mounted.current=true;const query=new URLSearchParams(window.location.search);setSourceHint(query.get('engagementId')||'');const requested=query.get('tab');if(requested&&['requests','billing','terms'].includes(requested))setTab(requested);void load(query.get('maintenanceId')||'');return()=>{mounted.current=false;generation.current++;invalidateCheckout();};},[]);
  const post=(path:string,body:unknown={},key?:string)=>api(path,{method:'POST',headers:key?{'Idempotency-Key':key}:{},body:JSON.stringify(body)});
  async function recoverWrite(problem:unknown,id:string,page:number,run:number){
    if(!mounted.current||run!==generation.current)return;
    if(!preview&&problem instanceof ApiError&&[401,403,404].includes(problem.status)){clear();setError(problem.message);return;}
    const refreshed=await load(id,page,sources.page,detail?.requestPage?.page||0,(problem as Error).message);
    if(refreshed&&mounted.current)setError((problem as Error).message);
    return refreshed;
  }
  async function change(work:()=>unknown|Promise<unknown>,message:string,id=selected,page=offers.page) {
    const run=generation.current;setBusy(true);setError('');setNote('');
    try{const result=await work();const next=id||((result&&typeof result==='object'&&'id' in result)?String(result.id):'');if(mounted.current&&run===generation.current){const failureMessage='The action was saved, but the workspace could not be refreshed. Reconnect to verify its current state.',refreshed=await load(next,page,sources.page,0,failureMessage);if(refreshed===false)throw new Error(failureMessage);if(refreshed)setNote(message);}return result;}
    catch(problem){await recoverWrite(problem,id,page,run);throw problem;}
    finally{if(mounted.current)setBusy(false);}
  }
  function act(work:()=>unknown|Promise<unknown>,message:string){void change(work,message).catch(()=>{});}
  function show(value:string){opener.current=document.activeElement as HTMLElement;setError('');setDialog(value);}
  function select(id:string){setSelected(id);setNote('');const url=new URL(window.location.href);url.searchParams.set('maintenanceId',id);window.history.replaceState(null,'',url);void load(id);}
  async function create(data:Record<string,string>){let amountMinor:number;try{amountMinor=templateMinor(data.price);}catch(problem){throw new ApiError((problem as Error).message,'INVALID_PRICE',400,undefined,{price:(problem as Error).message});}const terms={title:data.title,scope:data.scope,terms:data.terms,amountMinor,requestsPerCycle:Number(data.requestsPerCycle),responseHours:Number(data.responseHours),totalCycles:Number(data.totalCycles)};await change(()=>preview?preview.create(data.engagementId,terms):post('/maintenance',{...terms,engagementId:data.engagementId}),'Maintenance draft created. Review the terms before sending.','',0);setDialog('');}
  async function offerAction(action:string,consent=false){if(!detail)return;await change(()=>preview?preview.offerAction(detail.id,action,consent):post('/maintenance/'+detail.id+'/'+action,{consent,digest:detail.digest}),'Agreement '+careLabel(action)+ ' recorded.');setDialog('');}
  async function authorize(consent:boolean){if(!detail||!consent)return;const id=detail.id;
    if(preview){await change(()=>preview.simulateBilling(id,consent),'A paid period was simulated. No mandate, money or transfer was created.');setDialog('');return;}
    invalidateCheckout();const checkoutRun=checkoutGeneration.current,run=generation.current;const currentCheckout=()=>mounted.current&&checkoutRun===checkoutGeneration.current;setBusy(true);setError('');setNote('');
    try {
      billingKey.current[id]||=crypto.randomUUID();const checkout:CareCheckout=await post('/maintenance/'+id+'/billing',{billingConsent:true},billingKey.current[id]);
      if(!currentCheckout())return;
      if(!checkout.providerSubscriptionId||['CREATING','UNKNOWN','REJECTED'].includes(checkout.status)){if(await load(id)){setDialog('');setNote('Billing needs operator reconciliation before checkout.');}return;}
      const Gateway=await loadTemplateCheckout();if(!currentCheckout())return;setDialog('');
      const gateway=new Gateway({key:checkout.keyId,subscription_id:checkout.providerSubscriptionId,name:'getLancer',description:detail.title,
        handler:(result:Record<string,string>)=>{if(currentCheckout()){invalidateCheckout();void change(()=>post('/maintenance/'+id+'/billing/confirm',result),'Checkout verified. Only a live paid invoice grants support access.',id).catch(()=>{});}},
        modal:{ondismiss:()=>{if(currentCheckout()){invalidateCheckout();setNote('Checkout closed. Refresh billing to check provider status.');}}}});
      gatewayRef.current=gateway;gateway.on('payment.failed',()=>{if(currentCheckout()){invalidateCheckout();setError('Billing authorization was not confirmed. Refresh billing before trying again.');}});gateway.open();
      if(checkout.mode==='test')setNote('Razorpay test authorization. Test payments never grant real support.');
    }catch(problem){if(await recoverWrite(problem,id,offers.page,run))setDialog('');throw problem;}
    finally{if(mounted.current)setBusy(false);}
  }
  async function openRequest(data:Record<string,string>){if(!detail)return;const offerId=detail.id,body={title:data.title,description:data.description};let attempt=pendingRequests.current.find(item=>item.offerId===offerId&&item.title===body.title&&item.description===body.description);if(!attempt){attempt={offerId,...body,key:crypto.randomUUID()};pendingRequests.current.push(attempt);}await change(()=>preview?preview.request(offerId,body):post('/maintenance/'+offerId+'/requests',body,attempt.key),'Support request opened. One slot in this paid period was used.',offerId);pendingRequests.current=pendingRequests.current.filter(item=>item!==attempt);setDialog('');}
  async function requestAction(action:string,data:Record<string,string>={}){if(!detail)return;const requestId=dialog.split(':')[1];await change(()=>preview?preview.requestAction(detail.id,requestId,action,data):post('/maintenance/'+detail.id+'/requests/'+requestId+'/'+action,data),'Support request updated.');setDialog('');}
  const disabled=busy||loading,buyer=detail?.side==='BUYER',access=detail?.entitlement,pendingRequest=pendingRequests.current.filter(item=>item.offerId===detail?.id).slice(-1)[0];
  return <WorkspaceFrame section="maintenance" title="Maintenance & support" description="Keep delivered work healthy with agreed monthly care and a clear support queue." preview={demo} actions={<button className="button primary" disabled={disabled||!authenticated} onClick={()=>show('create')}><Plus size={17} aria-hidden="true"/>Create support offer</button>}>
    {preview&&<PreviewControls title="Maintenance sample" note="Sample frontend records only. Billing and paid periods are simulated locally. No gateway, account or backend request is sent."><label>Sample actor<select aria-label="Sample actor" value={side} disabled={disabled} onChange={event=>{const value=event.target.value as CareSide;preview.setSide(value);setSide(value);setDialog('');void load();}}><option value="SELLER">Seller</option><option value="BUYER">Buyer</option></select></label><button className="button" disabled={disabled} onClick={()=>{preview.reset();preview.setSide('SELLER');setSide('SELLER');setDialog('');void load('',0,0);}}>Reset sample</button></PreviewControls>}
    {error&&<p className="care-notice error" role="alert" tabIndex={-1} ref={summary}>{error}</p>}{note&&<p className="care-notice" role="status">{note}</p>}
    {loading&&<p className="care-notice" role="status">Loading maintenance records…</p>}
    {!loading&&!authenticated&&<Card><CardContent className="care-empty"><ShieldCheck aria-hidden="true"/><h2 ref={focusHeading} tabIndex={-1}>Sign in to your maintenance workspace</h2><p>Use a verified account with current access to the delivered engagement.</p><div className="care-actions"><Link className="button primary" href="/login">Sign in</Link><button className="button" onClick={()=>void load()}>Retry connection</button></div></CardContent></Card>}
    {authenticated&&sourceHint&&<p className="care-notice">Showing maintenance for the selected engagement. <button className="button" disabled={disabled} onClick={()=>{const url=new URL(window.location.href);url.searchParams.delete('engagementId');url.searchParams.delete('maintenanceId');window.history.replaceState(null,'',url);setSourceHint('');void load('',0,0);}}>Show all agreements</button></p>}
    {authenticated&&<div className="care-layout" aria-busy={loading}>
      <Card className="care-chooser"><CardHeader><h2>Care agreements</h2><span className="care-muted">{offers.totalItems} records</span></CardHeader><CardContent>{offers.items.length?<nav aria-label="Care agreements">{offers.items.map(item=><button key={item.id} disabled={disabled} aria-current={item.id===selected?'true':undefined} onClick={()=>select(item.id)}><strong>{item.title}</strong><span>{item.engagementTitle}</span><small>{careLabel(item.status)} · {templatePrice(item.amountMinor)}/mo</small></button>)}</nav>:<p>No maintenance offers yet. A seller can offer care after completed, fully paid delivery.</p>}<Pagination page={offers} busy={disabled} label="Agreement" onPage={page=>void load('',page)}/></CardContent></Card>
      {detail?<div className="care-main">
        <Card className="care-current"><CardHeader><div><span className="care-kicker">{demo?'Simulated care plan':'Monthly care plan'}</span><h2 ref={focusHeading} tabIndex={-1}>{detail.title}</h2><Link href={(demo?'/preview':'/workspace')+'/delivery?engagementId='+detail.engagementId}>{detail.engagementTitle}<ArrowUpRight size={14} aria-hidden="true"/></Link></div><Badge variant="outline">{careLabel(detail.status)}</Badge></CardHeader><CardContent>
          <div className="care-plan-facts"><div><strong className="care-price">{templatePrice(detail.amountMinor)}<small>/ month</small></strong><p>{detail.totalCycles} cycles maximum</p></div><div><span><LifeBuoy size={17} aria-hidden="true"/>{detail.requestsPerCycle} requests / paid period</span><span><Clock3 size={17} aria-hidden="true"/>First response within {detail.responseHours} elapsed hours</span></div></div>
          <div className="care-access"><div><strong>{access?.available?(demo?'Simulated paid period':'Paid period available'):'Support unavailable'}</strong><Badge variant="outline">{demo?'Preview only':detail.billing?detail.billing.mode+' · '+careLabel(detail.billing.status):'No billing authorization'}</Badge></div><p>{access?.reason}</p>{access?.periodEnd&&<p>Paid period: {templateDate(access.periodStart||undefined)} – {templateDate(access.periodEnd)} (exclusive end)</p>}<div className="care-quota"><span>{access?.usedRequests||0} of {detail.requestsPerCycle} requests used</span><strong>{access?.remainingRequests||0} remaining</strong></div><Progress aria-label="Support request quota used" aria-valuetext={`${access?.usedRequests||0} of ${detail.requestsPerCycle} used; ${access?.remainingRequests||0} remaining`} value={100*(access?.usedRequests||0)/detail.requestsPerCycle}/><p className="care-muted">Resolved and cancelled requests still count toward this period.</p></div>
          {detail.billing?.attentionReason&&<p className="care-notice">{detail.billing.attentionReason} Reference: {detail.billing.id}</p>}
          {detail.billing?.cancelRequested&&<p className="care-notice">{detail.billing.cancelConfirmed?'Future billing stopped. An eligible paid period remains available until its end.':'Cancellation requested; the provider has not confirmed billing stopped. Refresh or contact the operator.'}</p>}
          <div className="care-actions">
            {detail.status==='DRAFT'&&!buyer&&<button className="button primary" disabled={disabled} onClick={()=>show('send')}>Review & send terms</button>}
            {detail.status==='OFFERED'&&buyer&&<><button className="button primary" disabled={disabled} onClick={()=>{setTab('terms');show('accept');}}>Review & accept terms</button><button className="button" disabled={disabled} onClick={()=>show('reject')}>Reject offer</button></>}
            {['DRAFT','OFFERED'].includes(detail.status)&&!buyer&&<button className="button" disabled={disabled} onClick={()=>show('withdraw')}>Withdraw offer</button>}
            {detail.status==='ACCEPTED'&&buyer&&!detail.billing&&<button className="button primary" disabled={disabled||!configuration?.enabled} onClick={()=>show('authorize')}>{demo?'Simulate billing & paid period':'Authorize recurring billing'}</button>}
            {detail.billing&&buyer&&!detail.billing.cancelRequested&&['CREATED','AUTHENTICATED','PENDING','HALTED'].includes(detail.billing.status)&&<button className="button" disabled={disabled||!configuration?.enabled} onClick={()=>show('authorize')}>Continue billing authorization</button>}
            {buyer&&access?.available&&<button className="button primary" disabled={disabled||access.remainingRequests<1} onClick={()=>show('request')}>New support request</button>}
            {detail.billing&&<button className="button" disabled={disabled} onClick={()=>act(()=>preview?undefined:post('/maintenance/'+detail.id+'/billing/refresh'),'Billing and financial status refreshed.')}><RefreshCw size={15} aria-hidden="true"/>Refresh billing</button>}
            {detail.billing&&buyer&&!detail.billing.cancelConfirmed&&<button className="button" disabled={disabled} onClick={()=>show('cancel-billing')}>Cancel future billing</button>}
          </div>{!demo&&detail.status==='ACCEPTED'&&!configuration?.enabled&&<p className="care-muted">{configuration?.reason}</p>}
        </CardContent></Card>
        <Tabs value={tab} onValueChange={setTab}><TabsList aria-label="Maintenance details"><TabsTrigger value="requests">Requests</TabsTrigger><TabsTrigger value="billing">Billing</TabsTrigger><TabsTrigger value="terms">Terms & consent</TabsTrigger></TabsList>
          <TabsContent value="requests"><Card><CardHeader><h2>Support queue</h2><p className="care-muted">Each request stays attached to the period that paid for it.</p></CardHeader><CardContent>{!detail.requests.length?<div className="care-empty"><LifeBuoy aria-hidden="true"/><h3>No support requests yet</h3><p>{access?.available?'Open a request within the agreed scope.':'A verified paid period is needed to open a request.'}</p></div>:<ul className="care-requests">{detail.requests.map(item=><li key={item.id}><div className="care-row-head"><h3>{item.title}</h3><Badge variant="outline">{careLabel(item.status)}</Badge></div><p>{item.description}</p><div className="care-request-meta"><span>Opened {templateDate(item.createdAt)}</span><span>First response due {new Date(item.responseDueAt).toLocaleString('en-IN')}</span></div>{item.deliveryNote&&<div className="care-delivery"><strong>Seller resolution</strong><p>{item.deliveryNote}</p>{item.deliveryUrl&&<a href={item.deliveryUrl} target="_blank" rel="noopener noreferrer">View delivery<ArrowUpRight size={14} aria-hidden="true"/></a>}</div>}<div className="care-actions">{!buyer&&['OPEN','REVISION_REQUESTED'].includes(item.status)&&<button className="button" disabled={disabled} onClick={()=>show('start:'+item.id)}>Start request</button>}{!buyer&&item.status==='IN_PROGRESS'&&<button className="button primary" disabled={disabled} onClick={()=>show('submit:'+item.id)}>Submit resolution</button>}{buyer&&item.status==='SUBMITTED'&&<><button className="button primary" disabled={disabled} onClick={()=>show('accept-request:'+item.id)}>Accept resolution</button><button className="button" disabled={disabled} onClick={()=>show('revision:'+item.id)}>Request revision</button></>}{buyer&&['OPEN','REVISION_REQUESTED'].includes(item.status)&&<button className="button" disabled={disabled} onClick={()=>show('cancel-request:'+item.id)}>Cancel request</button>}</div></li>)}</ul>}{detail.requestPage&&<Pagination page={detail.requestPage} busy={disabled} label="Request" onPage={page=>void load(selected,offers.page,sources.page,page)}/>}</CardContent></Card></TabsContent>
          <TabsContent value="billing"><Card><CardHeader><h2>Invoice periods</h2><p className="care-muted">Payment, seller routing and bank settlement are separate outcomes.</p></CardHeader><CardContent>{!detail.invoices.length?<p>No paid invoice has been verified.</p>:<ul className="care-invoices">{detail.invoices.map(item=><li key={item.id}><div><strong>{templateDate(item.periodStart)} – {templateDate(item.periodEnd)}</strong><small>{item.providerInvoiceId}</small><small>Local period: {item.id}</small></div><div><strong>{templatePrice(item.amountMinor)}</strong><Badge variant="outline">{demo?'Simulated':item.mode} · {careLabel(item.status)}</Badge><small>Routing: {careLabel(item.transferStatus||'NOT_CREATED')} · Dispute: {careLabel(item.disputeStatus||'NONE')}{item.refundedMinor>0?' · Refunded '+templatePrice(item.refundedMinor):''}{item.pendingRefund?' · Refund pending':''}</small>{item.attentionReason&&<small>{item.attentionReason}</small>}</div></li>)}</ul>}</CardContent></Card></TabsContent>
          <TabsContent value="terms"><Card><CardHeader><h2>Agreed scope & consent</h2></CardHeader><CardContent><h3>Included work</h3><p className="care-text">{detail.scope}</p><h3>Terms & exclusions</h3><p className="care-text">{detail.terms}</p><dl className="care-consents"><div><dt>Seller consent</dt><dd>{detail.sellerConsentedAt?`${new Date(detail.sellerConsentedAt).toLocaleString('en-IN')} · Actor: ${detail.sellerConsentActorId||'Recorded account'}`:'Not recorded'}</dd></div><div><dt>Buyer consent</dt><dd>{detail.buyerConsentedAt?`${new Date(detail.buyerConsentedAt).toLocaleString('en-IN')} · Actor: ${detail.buyerConsentActorId||'Recorded account'}`:'Not recorded'}</dd></div><div><dt>Frozen revision {detail.revision||1}</dt><dd>{detail.digest||'Draft terms'}</dd></div></dl><p className="care-muted">Term acceptance and recurring payment authorization are separate. Agreed terms are frozen; new terms need a new offer and consent.</p></CardContent></Card><Card><CardHeader><h2>Activity</h2><p className="care-muted">Latest 100 recorded actions. Your scoped retained records are available through an authorized account export.</p></CardHeader><CardContent><ol className="care-activity">{detail.activity.map(item=><li key={item.id}><strong>{careLabel(item.kind)}</strong><p>{item.detail}</p><small>{templateDate(item.createdAt)}</small></li>)}</ol>{!detail.activity.length&&<p>No recorded activity yet.</p>}</CardContent></Card></TabsContent>
        </Tabs>
      </div>:!loading&&<Card><CardContent className="care-empty"><LifeBuoy aria-hidden="true"/><h2>Care begins after delivery</h2><p>Complete an engagement and its live payments, then agree on a bounded monthly care plan.</p><Link className="button" href={(demo?'/preview':'/workspace')+'/delivery'}>Open delivery workspace</Link></CardContent></Card>}
    </div>}
    <Dialog open={!!dialog} onOpenChange={value=>{if(!busy)setDialog(value?dialog:'');}}><DialogContent className="care-dialog" onCloseAutoFocus={event=>{event.preventDefault();(opener.current?.isConnected?opener.current:focusHeading.current)?.focus();}}><DialogHeader><DialogTitle>{dialog==='create'?'Create support offer':dialog==='send'?'Review & send monthly terms':dialog==='accept'?'Accept maintenance terms':dialog==='authorize'?'Authorize monthly care':dialog==='request'?'New support request':dialog==='cancel-billing'?'Cancel future billing':dialog.startsWith('submit:')?'Submit your resolution':dialog.startsWith('revision:')?'Request a revision':'Confirm maintenance action'}</DialogTitle><DialogDescription>{dialog==='create'?'Fixed monthly INR price, a finite cycle cap and a clear scope.':dialog==='authorize'?(demo?'Local sample only. No recurring mandate or payment is created.':'Authorize the agreed monthly recurring charge. Support requires a separate verified live paid invoice.'):dialog==='cancel-billing'?'Stop future charges through the provider. Eligible prepaid access continues until the paid period ends.':'Review this action against the frozen agreement. It will be recorded in the activity history.'}</DialogDescription></DialogHeader>
      {dialog==='create'&&<TeamForm busy={busy} label="Create maintenance draft" onSave={create}><Field name="engagementId" label="Completed engagement" value={sourceHint} options={[{value:'',label:'Select completed work'},...sources.items.filter(item=>item.side==='SELLER').map(item=>({value:item.id,label:item.title}))]}/><Pagination page={sources} busy={disabled} label="Completed work" onPage={page=>void load(selected,offers.page,page)}/><Field name="title" label="Care plan title" value={draft.title} minLength={3} maxLength={100}/><Field name="scope" label="Included work" type="textarea" minLength={20} maxLength={4000}/><Field name="terms" label="Terms & exclusions" type="textarea" minLength={40} maxLength={8000}/><div className="care-form-grid"><Field name="price" label="Monthly price (INR)" minLength={1} maxLength={15}/><Field name="requestsPerCycle" label="Requests per paid period" type="number" value={3}/><Field name="responseHours" label="First response (elapsed hours)" type="number" value={24}/><Field name="totalCycles" label="Maximum billing cycles" type="number" value={12}/></div><p className="care-muted">1–50 requests, 1–720 elapsed response hours and 1–12 monthly cycles. The backend validates the completed engagement.</p></TeamForm>}
      {detail&&['send','accept','authorize'].includes(dialog)&&<><div className="care-review"><strong>{detail.title} · {templatePrice(detail.amountMinor)}/month</strong><p>{detail.requestsPerCycle} requests · {detail.responseHours} elapsed response hours · {detail.totalCycles} cycles maximum</p><p className="care-text">{detail.scope}</p><p className="care-text">{detail.terms}</p></div><Consent busy={busy} label={dialog==='send'?'Consent & send offer':dialog==='accept'?'Accept these terms':demo?'Simulate authorized paid period':'Continue to Razorpay'} text={dialog==='authorize'?`I authorize ${templatePrice(detail.amountMinor)} each month for up to ${detail.totalCycles} cycles under this agreement. I understand how to cancel future billing.`:'I have read and agree to this exact scope, monthly price, request quota, response time and terms.'} onSave={consent=>dialog==='authorize'?authorize(consent):offerAction(dialog,consent)}/></>}
      {dialog==='request'&&<TeamForm busy={busy} label="Open support request" onSave={openRequest}>{pendingRequest&&<p className="care-notice">A previous submission is awaiting confirmation. Retry these details to check the same request; changing them starts a new request.</p>}<Field name="title" label="Request title" value={pendingRequest?.title||''} minLength={3} maxLength={100}/><Field name="description" label="What needs attention?" value={pendingRequest?.description||''} type="textarea" minLength={20} maxLength={4000}/><p className="care-muted">Opening this request consumes one slot. Cancelling it does not restore the slot.</p></TeamForm>}
      {dialog.startsWith('submit:')&&<TeamForm busy={busy} label="Submit resolution" onSave={data=>requestAction('submit',data)}><Field name="deliveryNote" label="Resolution details" type="textarea" minLength={10} maxLength={4000}/><Field name="deliveryUrl" label="Delivery URL" required={false} maxLength={500} hint="HTTPS, without embedded credentials."/></TeamForm>}
      {dialog.startsWith('revision:')&&<TeamForm busy={busy} label="Record revision request" onSave={data=>requestAction('request-revision',data)}><Field name="reason" label="What needs revision?" type="textarea" minLength={10} maxLength={2000}/></TeamForm>}
      {detail&&['reject','withdraw','cancel-billing'].includes(dialog)&&<TeamForm busy={busy} label={dialog==='cancel-billing'?'Confirm billing cancellation':'Confirm '+dialog} onSave={async()=>{if(dialog==='cancel-billing'){await change(()=>preview?preview.cancel(detail.id):post('/maintenance/'+detail.id+'/billing/cancel'),'Cancellation status updated. Check provider confirmation above.');setDialog('');}else await offerAction(dialog);}}><p>{dialog==='cancel-billing'?'This requests provider cancellation; it does not automatically refund or prorate the paid period.':'This closes the unaccepted offer. Its history remains retained.'}</p></TeamForm>}
      {['start','accept-request','cancel-request'].some(action=>dialog.startsWith(action+':'))&&<TeamForm busy={busy} label="Confirm request action" onSave={()=>requestAction(dialog.startsWith('start:')?'start':dialog.startsWith('accept-request:')?'accept':'cancel')}><p>{dialog.startsWith('cancel-request:')?'The consumed slot stays in this paid period.':'The request update is recorded in the agreement activity.'}</p></TeamForm>}
    </DialogContent></Dialog>
  </WorkspaceFrame>;
}
function Consent({busy,label,text,onSave}:{busy:boolean;label:string;text:string;onSave:(consent:boolean)=>Promise<unknown>}){const [consent,setConsent]=useState(false);return <TeamForm busy={busy} label={label} onSave={()=>onSave(consent)}><label className="care-consent"><input type="checkbox" required checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>{text}</span></label></TeamForm>;}
function Pagination<T>({page,busy,label,onPage}:{page:TemplatePage<T>;busy:boolean;label:string;onPage:(page:number)=>void}){if(!page.hasMore&&page.page===0)return null;return <nav aria-label={label+' pages'} className="care-pagination"><button type="button" className="button" disabled={busy||page.page===0} onClick={()=>onPage(page.page-1)}>Previous</button><span>Page {page.page+1}</span><button type="button" className="button" disabled={busy||!page.hasMore} onClick={()=>onPage(page.page+1)}>Next</button></nav>;}
