'use client';
import ExternalLink from '@/app/components/external-link';

import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
import {useRef} from 'react';
import MoreRecords from './more-records';
type Row=Record<string,any>;
export default function ModerationWorkflow({admin=false}:{admin?:boolean}){
 const [items,setItems]=useState<Row[]>([]),[decisions,setDecisions]=useState<Row[]>([]),[jobs,setJobs]=useState<Row[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const errorRef=useRef<HTMLParagraphElement>(null);useEffect(()=>{if(error)errorRef.current?.focus()},[error]);
 const path=admin?'/admin/appeals':'/me/appeals';
 async function load(){try{setItems((await api(path)).items);if(admin)setJobs((await api('/admin/email-jobs')).items);else setDecisions((await api('/me/moderation-decisions')).items)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[admin]);
 async function submit(path:string,body:Row){setBusy(true);setError('');setMessage('');try{await api(path,{method:'POST',body:JSON.stringify(body)});await load();setMessage('Your changes were recorded.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel form"><h2>{admin?'Appeal review and delivery recovery':'Decisions and appeals'}</h2>{error&&<p role="alert" tabIndex={-1} ref={errorRef} className="error">{error}</p>}{message&&<p role="status" className="success">{message}</p>}
 {!admin&&<><p>Ask for a review of a decision affecting your work. Include evidence that explains what should change.</p>{decisions.length>0?<form className="form" onSubmit={e=>{e.preventDefault();void submit('/appeals',Object.fromEntries(new FormData(e.currentTarget)))}}><label htmlFor="appeal-decision">Original decision</label><select id="appeal-decision" name="decisionId" required>{decisions.map(d=><option value={d.id} key={d.id}>{d.target_type} · {d.action} · {d.reason}</option>)}</select><label htmlFor="appeal-statement">Why should this change?</label><textarea id="appeal-statement" name="statement" required minLength={20} maxLength={3000}/><label htmlFor="appeal-evidence">Evidence URL (optional)</label><input id="appeal-evidence" name="evidenceUrl" type="url" maxLength={1000}/><button className="button" disabled={busy}>Submit appeal</button></form>:<p>No moderation decisions to appeal.</p>}<MoreRecords path="/me/moderation-decisions" onItems={rows=>setDecisions(old=>[...old,...rows])}/></>}
 {items.map(a=><article key={a.id} className="panel form"><h3>{a.status.replaceAll('_',' ')}</h3>{admin&&<p>Original decision: {a.original_action} · {a.original_reason}</p>}<p>{a.statement}</p>{a.evidence_url&&<ExternalLink href={a.evidence_url} target="_blank" rel="noopener noreferrer">Open supporting evidence</ExternalLink>}{a.resolution&&<p>Review result: {a.resolution}</p>}{admin&&['OPEN','UNDER_REVIEW'].includes(a.status)&&<form className="form" onSubmit={e=>{e.preventDefault();void submit('/admin/appeals/'+a.id+'/decision',Object.fromEntries(new FormData(e.currentTarget)))}}><label htmlFor={'appeal-state-'+a.id}>Outcome</label><select name="status" id={'appeal-state-'+a.id}><option value="UNDER_REVIEW">Under review</option><option value="UPHELD">Uphold original decision</option><option value="OVERTURNED">Overturn and restore eligibility</option></select><p className="muted">Overturning applies the restoration through the original permission and capacity checks.</p><label htmlFor={'appeal-reason-'+a.id}>Review reason</label><textarea id={'appeal-reason-'+a.id} name="reason" minLength={3} maxLength={2000} required/><button disabled={busy} className="button">Record appeal decision</button></form>}</article>)}<MoreRecords path={path} onItems={rows=>setItems(old=>[...old,...rows])}/>
 {admin&&<><h3>Failed email delivery</h3><p>Retry only after fixing delivery settings. Expired confirmation links need renewal by the user.</p>{jobs.length===0&&<p>No failed jobs.</p>}{jobs.map(j=><form key={j.id} className="form" onSubmit={e=>{e.preventDefault();void submit('/admin/email-jobs/'+j.id+'/retry',Object.fromEntries(new FormData(e.currentTarget)))}}><p>{j.subject} · {j.attempts} attempts · {new Date(j.created_at).toLocaleString()}</p><label htmlFor={'mail-reason-'+j.id}>Recovery reason</label><input id={'mail-reason-'+j.id} name="reason" minLength={3} maxLength={2000} required/><button disabled={busy||j.expired} className="button">Retry delivery</button></form>)}<MoreRecords path="/admin/email-jobs" onItems={rows=>setJobs(old=>[...old,...rows])}/></>}
 </section>
}
