import Link from 'next/link';
import {ArrowUpRight,Braces,Layers,Search} from 'lucide-react';
import {componentCatalog} from '@/lib/component-server';
import {componentCategories} from '@/lib/components';
import {ComponentCard} from './component-library';
export const metadata={title:'Free components',description:'Try working frontend components, inspect their source and build something useful. Every component is free.'};
export default async function Components({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const filters=await searchParams,params=new URLSearchParams();for(const k of ['q','category','kind','page','builder'])if(filters[k])params.set(k,filters[k]!);const {data,preview}=await componentCatalog(params),backend=filters.kind==='BACKEND';
 return <main id="main" className="kit-page"><header className="kit-catalog-head"><div><span className="eyebrow">Small pieces. Real possibilities.</span><h1>Build your next<br/><span>good idea.</span></h1><p>Useful components you can try, understand and make your own.<br className="kit-desktop-break"/> Free source. Clear licences. Credit to the builder.</p></div><div className="kit-hero-side"><div className="kit-orbit-mark" aria-hidden="true"><Braces size={46}/><i/><b/></div><Link className="button" href="/workspace/components">Share your work <ArrowUpRight size={16}/></Link><small>3 free publishing slots per builder</small></div></header>
 <div className="kit-catalog-bar"><nav className="kit-lane-tabs" aria-label="Component type"><Link href="/components" aria-current={!backend?'page':undefined}>Frontend <Layers size={16}/></Link><Link href="/components?kind=BACKEND" aria-current={backend?'page':undefined}>Backend <Braces size={16}/></Link></nav><span>{backend?'Source-only foundation':data.totalItems+' components'} · Always free to use</span></div>
 <form className="kit-filters" action="/components" method="get"><input type="hidden" name="kind" value={backend?'BACKEND':'FRONTEND'}/><div className="kit-search"><Search size={19} aria-hidden="true"/><label className="sr-only" htmlFor="component-search">Search components</label><input id="component-search" name="q" placeholder="Find your next building block…" defaultValue={filters.q} maxLength={200}/></div><label className="sr-only" htmlFor="component-category">Component category</label><select id="component-category" name="category" defaultValue={filters.category||''}><option value="">All categories</option>{componentCategories.map(([key,title])=><option key={key} value={key}>{title}</option>)}</select><button className="button" type="submit">Search</button>{(filters.q||filters.category)&&<Link href={'/components'+(backend?'?kind=BACKEND':'')} className="link">Reset</Link>}</form>
 {backend?<section className="kit-empty"><Braces size={32}/><h2>Show the design behind the screen.</h2><p>Redis, security and payment labs are planned for V4.7–V4.8. V4.5 establishes source and language metadata; no live backend runtime is available yet.</p><Link href="/college-projects" className="button">Explore project contributions ↗</Link></section>:<>{preview&&<p className="kit-subtle-note">Original curated components with real working previews and free source. Community publishing requires a connected account.</p>}<div className="kit-grid">{data.items.map(item=><ComponentCard item={item} key={item.slug}/>)}</div>{!data.items.length&&<section className="kit-empty"><h2>No components found.</h2><p>Try another term or category.</p><Link href="/components" className="button">Clear filters</Link></section>}{data.hasMore&&<Link className="button" href={'/components?'+new URLSearchParams({...filters,page:String(data.page+1)} as Record<string,string>)}>Next page →</Link>}</>}
 <section className="kit-footer-callout"><div><h2>Your smallest work can make a big impression.</h2><p>Publish up to three active components free. Add reusable slots at the price set by the administrator.</p></div><Link href="/workspace/components" className="button primary">Open creator workspace <ArrowUpRight size={16}/></Link></section></main>;
}
