import {Box, LayoutDashboard, Package, ShoppingBag, Users, BarChart3, Settings, Search, CalendarDays, Bell} from 'lucide-react';
import type {Product} from '@/lib/catalog';
export default function Preview({product:p,naturalAspect=false}:{product:Product;naturalAspect?:boolean}) {
 if(p.imageUrl)return <img src={p.imageUrl} alt={`${p.title} project screenshot`} style={{width:'100%',height:naturalAspect?'auto':'100%',objectFit:naturalAspect?'contain':'cover',display:'block'}} loading="lazy"/>;
 if(naturalAspect&&p.illustrative&&p.previewFormat==='portrait')return <div className="portrait-demo" aria-label={`${p.title} illustrative mobile interface`}>
   <div className="phone-demo"><div className="phone-status"><span>9:41</span><span>••• ▰</span></div><div className="phone-top"><b>{p.title}</b><span>EC</span></div><p className="phone-eyebrow">YOUR LEARNING SPACE</p><h3>A little progress.<br/>Every day.</h3><p className="phone-intro">Welcome back, Elena.</p><div className="phone-course"><span>CONTINUE LEARNING</span><div className="phone-art">Aa<span>↗</span></div><h4>Designing for<br/>the real world.</h4><p>Lesson 04 · 12 min</p><div className="phone-progress"><i/></div></div><div className="phone-section"><b>Your next chapters</b><span>View all →</span></div>{['Layout & balance','Type that speaks','Putting it together'].map((t,i)=><div className="phone-lesson" key={t}><span>0{i+1}</span><div><b>{t}</b><small>{[8,14,12][i]} min · Design foundations</small></div><span>↗</span></div>)}<div className="phone-nav"><span>⌂ Home</span><span>▤ Courses</span><span>○ Profile</span></div></div>
 </div>;
 if(!p.illustrative)return <div className="proof-missing">{p.title}<span>Project screenshot unavailable</span></div>;
 if(['Inventory','Booking','CRM','Restaurants'].includes(p.category))return <div className={'product-demo demo-'+p.category.toLowerCase()} aria-label={`${p.title} illustrative interface`}>
  <aside className="product-demo-side"><b><Box size={14}/>{p.title}</b>{[LayoutDashboard,p.category==='Booking'?CalendarDays:Package,ShoppingBag,Users,BarChart3,Settings].map((Icon,i)=><span key={i}><Icon size={10}/>{(p.category==='Booking'?['Calendar','Bookings','Services','Customers','Reports','Settings']:p.category==='CRM'?['Overview','Contacts','Deals','Customers','Reports','Settings']:p.category==='Restaurants'?['Overview','Floor plan','Orders','Customers','Reports','Settings']:['Dashboard','Inventory','Orders','Suppliers','Reports','Settings'])[i]}</span>)}</aside>
  <div className="product-demo-body"><div className="product-demo-top"><span><Search size={9}/>Search {p.category==='Booking'?'bookings':'workspace'}…</span><Bell size={10}/><i>JD</i></div><div className="product-demo-title"><h3>{p.category==='Booking'?'Calendar':p.category==='CRM'?'Contacts':p.category==='Restaurants'?'Floor plan':'Inventory'}</h3><span>+ {p.category==='Booking'?'New booking':'Add new'}</span></div>
  {p.category==='Booking'?<><div className="product-demo-subhead"><b>September 2026</b><span>‹　Today　›</span></div><div className="product-demo-calendar">{['Mon','Tue','Wed','Thu','Fri'].map(d=><strong key={d}>{d}</strong>)}{Array.from({length:20},(_,i)=><div key={i}><small>{(i+6+Math.floor(i/5)*2)%30+1}</small>{[0,2,5,7,9,12,14,16,18].includes(i)&&<span className={'booking-color-'+i%3}><b>{i%2?'2:00 PM':'9:00 AM'}</b>{['Team meeting','Consultation','Design review','Planning'][i%4]}</span>}</div>)}</div></>:
   p.category==='Inventory'?<><div className="product-demo-metrics">{[['Total products','248'],['Low stock','12'],['Stock value','$24,320']].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div><div className="product-demo-table"><div className="product-demo-table-head"><span>Product</span><span>SKU</span><span>Stock</span></div>{['Wireless headphones','Canvas tote bag','Ceramic mug','Water bottle','Notebook'].map((n,i)=><div key={n}><span><i className={'stock-item stock-item-'+i}/>{n}</span><span>WH-{i+101}</span><span>{[142,28,64,97,35][i]}</span></div>)}</div></>:
   p.category==='CRM'?<div className="product-demo-table contacts-demo"><div className="product-demo-table-head"><span>Name</span><span>Company</span><span>Status</span></div>{['Sarah Chen','Michael Torres','Emily Watson','James Park','Alex Morgan'].map((n,i)=><div key={n}><span><i className="contact-dot">{n[0]}</i>{n}</span><span>{['GreenLeaf','Brightside','NextGen','Harbor','Skyline'][i]}</span><span className={'contact-status status-'+i%2}>{i%2?'Proposal':'Qualified'}</span></div>)}</div>:
   <><div className="product-demo-subhead"><span>● Available　● Occupied　● Reserved</span></div><div className="floor-demo">{Array.from({length:9},(_,i)=><div key={i} className={'floor-table floor-table-'+i%3}>T{i+1}<span>••</span></div>)}</div></>}
  </div></div>;
 return <div className={'miniapp mini-'+p.category.toLowerCase()} aria-label={`${p.title} illustrative interface`}>
  <div className="mini-side"><b>{p.title}</b>{['Overview','Activity','Projects','Customers','Reports','Settings'].map(t=><span key={t}>{t}</span>)}</div>
  <div className="mini-main"><small>Workspace / Overview</small><h3>{p.category==='Booking'?'Your week, at a glance.':p.category==='Education'?'Keep learning.':p.category==='Restaurants'?'Good service starts here.':p.category==='Productivity'?'Make room for great work.':p.category==='CRM'?'Every connection counts.':'Everything, in stock.'}</h3>
   {p.category==='Booking'?<><div className="mini-calendar-head">September 2026<span>Week view</span></div><div className="mini-calendar">{['MON','TUE','WED','THU','FRI'].map((d,i)=><div key={d}><small>{d}</small><b>{7+i}</b><span className={'calendar-event event-'+i}>{['Team sync','Consultation','Discovery call','Design review','Planning'][i]}</span><span className="calendar-empty"/></div>)}</div></>:
    p.category==='Restaurants'?<><div className="mini-pills"><b>Floor plan</b><span>Orders</span><span>Kitchen</span></div><div className="mini-tables">{['01','02','03','04','05','06'].map((n,i)=><div key={n} className={i%3===0?'table-open':''}><small>TABLE {n}</small><b>{i%3===0?'Available':'In service'}</b><span>{i%3===0?'Ready for guests':'Order in progress'}</span></div>)}</div></>:
    p.category==='Productivity'?<div className="mini-kanban">{['Planned','In progress','Ready'].map((t,i)=><div key={t}><b>{t}</b>{['Customer portal','API integration'].map((task,n)=><div key={task}><small>{['PRODUCT','ENGINEERING','REVIEW'][i]}</small><strong>{n===i?'Design system':task}</strong><span>{['LM','NP','DK'][i]} · This week</span></div>)}</div>)}</div>:
    p.category==='Education'?<><div className="mini-course"><span>CONTINUE LEARNING</span><strong>Building for the web.</strong><small>Lesson 04 · Designing a better experience</small></div><div className="mini-lessons">{['Foundations','Your first interface','Putting it together'].map((t,i)=><div key={t}><span>0{i+1}</span><b>{t}</b><small>{i===0?'Completed':'12 min'}</small></div>)}</div></>:
    <><div className="mini-metrics"><div><small>{p.category==='CRM'?'Open deals':'Products'}</small><b>{p.category==='CRM'?'42':'1,248'}</b></div><div><small>{p.category==='CRM'?'Follow-ups':'Orders'}</small><b>{p.category==='CRM'?'12':'86'}</b></div><div><small>{p.category==='CRM'?'New leads':'Low stock'}</small><b>{p.category==='CRM'?'18':'24'}</b></div></div><div className="minichart">{[35,49,41,64,53,76,65,88,79,96].map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div><div className="minilines">{(p.category==='CRM'?['Northstar Studio','Acme Systems','Brightside']:['Recent orders','Warehouse update','Stock transfers']).map(t=><div key={t}><span>{t}</span><span>View →</span></div>)}</div></>}
  </div>
 </div>;
}
