import type {Product} from '@/lib/catalog';
export default function Preview({product:p}:{product:Product}) {
 if(p.imageUrl)return <img src={p.imageUrl} alt={`${p.title} project screenshot`} style={{width:'100%',height:'100%',objectFit:'cover'}} loading="lazy"/>;
 if(!p.illustrative)return <div className="proof-missing">{p.title}<span>Project screenshot unavailable</span></div>;
 return <div className={'miniapp mini-'+p.category.toLowerCase()} aria-label={`${p.title} illustrative interface`}>
  <div className="mini-side"><b>{p.title}</b>{['Overview','Activity','Projects','Customers','Reports','Settings'].map(t=><span key={t}>{t}</span>)}</div>
  <div className="mini-main"><small>Workspace / Overview</small><h3>{p.category==='Booking'?'Your week, at a glance.':p.category==='Education'?'Keep learning.':p.category==='Restaurants'?'Good service starts here.':p.category==='Productivity'?'Make room for great work.':p.category==='CRM'?'Every connection counts.':'Everything, in stock.'}</h3>
   {p.category==='Booking'?<><div className="mini-calendar-head">September 2026<span>Week view</span></div><div className="mini-calendar">{['MON','TUE','WED','THU','FRI'].map((d,i)=><div key={d}><small>{d}</small><b>{7+i}</b><span className={'calendar-event event-'+i}>{['Team sync','Consultation','Discovery call','Design review','Planning'][i]}</span><span className="calendar-empty"/></div>)}</div></>:
    p.category==='Restaurants'?<><div className="mini-pills"><b>Floor plan</b><span>Orders</span><span>Kitchen</span></div><div className="mini-tables">{['01','02','03','04','05','06'].map((n,i)=><div key={n} className={i%3===0?'table-open':''}><small>TABLE {n}</small><b>{i%3===0?'Available':'In service'}</b><span>{i%3===0?'Ready for guests':'Order in progress'}</span></div>)}</div></>:
    p.category==='Productivity'?<div className="mini-kanban">{['Planned','In progress','Ready'].map((t,i)=><div key={t}><b>{t}</b>{['Customer portal','API integration'].map((task,n)=><div key={task}><small>{['PRODUCT','ENGINEERING','REVIEW'][i]}</small><strong>{n===i?'Design system':task}</strong><span>{['LM','NP','DK'][i]} · This week</span></div>)}</div>)}</div>:
    p.category==='Education'?<><div className="mini-course"><span>CONTINUE LEARNING</span><strong>Building for the web.</strong><small>Lesson 04 · Designing a better experience</small></div><div className="mini-lessons">{['Foundations','Your first interface','Putting it together'].map((t,i)=><div key={t}><span>0{i+1}</span><b>{t}</b><small>{i===0?'Completed':'12 min'}</small></div>)}</div></>:
    <><div className="mini-metrics"><div><small>{p.category==='CRM'?'Open deals':'Products'}</small><b>{p.category==='CRM'?'42':'1,248'}</b></div><div><small>{p.category==='CRM'?'Follow-ups':'Orders'}</small><b>{p.category==='CRM'?'12':'86'}</b></div><div><small>{p.category==='CRM'?'New leads':'Low stock'}</small><b>{p.category==='CRM'?'18':'24'}</b></div></div><div className="minichart">{[35,49,41,64,53,76,65,88,79,96].map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div><div className="minilines">{(p.category==='CRM'?['Northstar Studio','Acme Systems','Brightside']:['Recent orders','Warehouse update','Stock transfers']).map(t=><div key={t}><span>{t}</span><span>View →</span></div>)}</div></>}
  </div>
 </div>;
}
