'use client';
import {useState} from 'react';
import {api} from '@/lib/api';
type Proof={id:string;url:string;alt:string};
export default function ProofEditor({product,onChange}:{product:any;onChange:()=>void}){
 const [items,setItems]=useState<Proof[]>(product.media||[]),[busy,setBusy]=useState(false),[progress,setProgress]=useState<number|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 const editable=['DRAFT','CHANGES_REQUESTED'].includes(product.approvalStatus);
 async function reload(){const data=await api('/developer/products/'+product.id+'/proof');setItems(data.items);onChange();}
 if(!editable)return <p className="muted">Save material edits as a draft before changing proof images.</p>;
 return <section className="panel form"><h3>Proof images</h3><p className="muted">Up to six images. Describe what each screen demonstrates; the first image is the cover.</p>{items.map((m,i)=><div key={m.id} className="form"><img src={m.url} alt={m.alt} style={{maxHeight:180,objectFit:'contain'}}/><label htmlFor={'alt-'+m.id}>Image {i+1} description</label><input id={'alt-'+m.id} value={m.alt} maxLength={300} required onChange={e=>setItems(old=>old.map(x=>x.id===m.id?{...x,alt:e.target.value}:x))}/><div className="stack"><button type="button" className="button" disabled={busy||i===0} onClick={()=>setItems(old=>{const next=[...old];[next[i-1],next[i]]=[next[i],next[i-1]];return next})}>Move earlier</button><button type="button" className="button" disabled={busy||i===items.length-1} onClick={()=>setItems(old=>{const next=[...old];[next[i+1],next[i]]=[next[i],next[i+1]];return next})}>Move later</button><button type="button" className="button danger" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/developer/products/'+product.id+'/media/'+m.id,{method:'DELETE'});await reload();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Remove image</button></div></div>)}
 {items.length>0&&<button type="button" className="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api('/developer/products/'+product.id+'/media',{method:'PATCH',body:JSON.stringify({items:items.map(({id,alt})=>({id,alt}))})});setMessage('Image order and descriptions saved.');onChange();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Save image order and descriptions</button>}
 <label htmlFor={'proof-file-'+product.id}>Add proof image (PNG or JPEG, up to 5 MB)</label><input id={'proof-file-'+product.id} type="file" accept="image/png,image/jpeg" disabled={busy||items.length>=6} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');if(file.size>5242880){setError('Choose an image under 5 MB.');return;}setBusy(true);setProgress(0);
 try{const upload=await api('/developer/products/'+product.id+'/media/upload-request',{method:'POST',body:JSON.stringify({filename:file.name,contentType:file.type,sizeBytes:file.size})});
 await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',upload.url);for(const [name,value] of Object.entries(upload.headers))xhr.setRequestHeader(name,String(value));xhr.timeout=60000;xhr.upload.onprogress=ev=>ev.lengthComputable&&setProgress(Math.round(100*ev.loaded/ev.total));xhr.onerror=xhr.ontimeout=()=>reject(Error('Upload failed. Please try again.'));xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(Error('Image upload was rejected. Please try again.'));xhr.send(file)});
 await api('/developer/products/'+product.id+'/media/complete',{method:'POST',body:JSON.stringify({uploadId:upload.uploadId,altText:'Project screenshot'})});await reload();setMessage('Uploaded. Add a description and save.');
 }catch(err){setError((err as Error).message)}finally{setBusy(false);setProgress(null)}
 }}/>
 {progress!==null&&<label>Uploading {progress}%<progress max={100} value={progress}/></label>}{message&&<p role="status" className="success">{message}</p>}{error&&<p role="alert" className="error">{error}</p>}</section>;
}
