'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { componentSeeds, type ComponentEntry } from '@/lib/components';
import { componentSaveKey, parseComponentSaves, setComponentSave } from '@/lib/component-saves';
export default function SavedComponents({ preview }: { preview: boolean }) {
  const [items,setItems]=useState<(ComponentEntry&{available:boolean})[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null);
  useEffect(()=>{let active=true;async function load(){try{const data=preview?parseComponentSaves(sessionStorage.getItem(componentSaveKey('visitor'))).map(slug=>{const seed=componentSeeds.find(item=>item.slug===slug);return seed?{...seed,available:true}:{slug,available:false} as ComponentEntry&{available:boolean};}):(await api('/me/saved-components')).items;if(active)setItems(data);}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}}void load();return()=>{active=false;}},[preview]);
  async function remove(slug:string){if(busy)return;setBusy(slug);try{if(preview){const key=componentSaveKey('visitor');sessionStorage.setItem(key,JSON.stringify(setComponentSave(parseComponentSaves(sessionStorage.getItem(key)),slug,false)));}else await api('/components/'+encodeURIComponent(slug)+'/save',{method:'DELETE'});setItems(old=>old.filter(item=>item.slug!==slug));}catch(e){setError((e as Error).message);}finally{setBusy(null);}}
  return <main id="main" className="kit-page"><header className="kit-detail-head"><div><h1>Saved components</h1><p>Keep useful building blocks close.</p></div><Link href="/saved" className="button">Saved projects</Link></header>{preview&&<p className="kit-notice">Sample visitor saves in this browser. No real account data is changed.</p>}{error&&<p className="error" role="alert">{error}</p>}{loading?<p role="status">Loading saved components…</p>:!error&&!items.length?<section className="kit-empty"><h2>Your next building block is here.</h2><p>Save a component while exploring to return to it later.</p><Link className="button" href="/components">Explore components</Link></section>:<div className="kit-admin-list">{items.map(item=><article key={item.slug}><div><h2>{item.available?<Link href={'/components/'+item.slug}>{item.title}</Link>:'Component unavailable'}</h2><p>{item.available?item.summary:'This component was withdrawn or is no longer public.'}</p></div><button className="button" disabled={busy!==null} onClick={()=>void remove(item.slug)}>{busy===item.slug?'Removing…':'Remove'}</button></article>)}</div>}</main>;
}
