'use client';
import {useState} from 'react';
import {majorAmount,pricingCurrencies,toMinorAmount,type ShowcasePricing} from '@/lib/showcase-pricing';
export default function ShowcasePricingFields({value,onChange}:{value:ShowcasePricing;onChange:(next:ShowcasePricing)=>void}) {
 const [error,setError]=useState('');const mode=value.pricingMode||'NONE',currency=value.currency||'INR';
 const numeric=mode==='STARTING_FROM'||mode==='RANGE';
 function amount(field:'priceMinMinor'|'priceMaxMinor',text:string){try{const minor=toMinorAmount(text,currency);setError('');onChange({...value,[field]:minor});}catch(e){onChange({...value,[field]:null});setError((e as Error).message);}}
 return <fieldset className="showcase-pricing-fields"><legend>Indicative pricing <small>Optional</small></legend><p className="muted">Give clients a starting point. Final scope and payment terms belong in an agreed proposal.</p><label htmlFor="showcase-pricing-mode">Pricing display</label><select id="showcase-pricing-mode" value={mode} onChange={e=>{setError('');onChange({pricingMode:e.target.value as ShowcasePricing['pricingMode'],priceMinMinor:null,priceMaxMinor:null,currency:['RANGE','STARTING_FROM'].includes(e.target.value)?currency:null});}}><option value="NONE">Do not list a price</option><option value="STARTING_FROM">Starting from</option><option value="RANGE">Price range</option><option value="CUSTOM_QUOTE">Custom quote</option></select>{numeric&&<><label htmlFor="showcase-price-currency">Currency</label><select id="showcase-price-currency" value={currency} onChange={e=>{setError('');onChange({...value,currency:e.target.value,priceMinMinor:null,priceMaxMinor:null});}}>{[...new Set([...pricingCurrencies,currency])].map(code=><option key={code}>{code}</option>)}</select><div className="split"><label htmlFor="showcase-price-min">{mode==='RANGE'?'Minimum amount':'Starting amount'}<input key={currency+'min'} id="showcase-price-min" inputMode="decimal" required defaultValue={majorAmount(value.priceMinMinor,currency)} onChange={e=>amount('priceMinMinor',e.target.value)} aria-invalid={!!error} aria-describedby="showcase-price-hint"/></label>{mode==='RANGE'&&<label htmlFor="showcase-price-max">Maximum amount<input key={currency+'max'} id="showcase-price-max" inputMode="decimal" required defaultValue={majorAmount(value.priceMaxMinor,currency)} onChange={e=>amount('priceMaxMinor',e.target.value)} aria-invalid={!!error} aria-describedby="showcase-price-hint"/></label>}</div><p id="showcase-price-hint" className={error?'error':'muted'} role={error?'alert':undefined}>{error||'Enter amounts in the selected currency. The server validates the range before saving.'}</p></>}</fieldset>;
}
