'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
import {Field,TeamForm,human,type TeamRequest} from './team-workspace';
import './teams.css';

export default function TeamPublic({id,request=api,embedded=false,onSelect}:{id?:string,request?:TeamRequest,embedded?:boolean,onSelect?:(id:string)=>void}){
 const [data,setData]=useState<any>(null),[me,setMe]=useState<any>(null),[membership,setMembership]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[applied,setApplied]=useState<string[]>([]);const generation=useRef(0);
 useEffect(()=>{const run=++generation.current;setLoading(true);setData(null);setError('');setNotice('');setApplied([]);Promise.all([request(id?'/teams/'+encodeURIComponent(id):'/teams?q='+encodeURIComponent(search)),request('/me').catch(()=>null),request('/me/teams').catch(()=>null)]).then(([result,user,index])=>{if(run!==generation.current)return;setData(result);setMe(user);setMembership(!!index?.items?.some((t:any)=>t.id===id));setApplied(index?.applications?.filter((a:any)=>a.teamId===id).map((a:any)=>a.roleId)||[])}).catch(e=>{if(run===generation.current)setError(e.message)}).finally(()=>{if(run===generation.current)setLoading(false)});return()=>{generation.current++}},[id,search,request]);
 const team=data?.team;const approved=me?.profile?.approval_status==='APPROVED'||me?.profileStatus==='APPROVED';
 const select=(teamId:string,label:string)=>onSelect?<button className="button" onClick={()=>onSelect(teamId)}>{label}</button>:<Link href={'/teams/'+teamId} className="button">{label}</Link>;
 const contents=<>
 {!id?<><header className="team-hero"><div><span className="eyebrow">Independent talent. Shared ambition.</span><h1>Find your next team.</h1><p>Discover studios built around real work. Explore their products, meet their builders, or find a role where you can contribute.</p></div>{!embedded&&<Link href="/workspace/teams" className="button primary">Your team workspace</Link>}</header><form className="team-search" onSubmit={(e:FormEvent)=>{e.preventDefault();setSearch(query)}}><label className="team-field">Search teams<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Team name or specialty" type="search" maxLength={200}/></label><button className="button primary" disabled={loading}>Search teams</button></form></>:<div className="team-actions">{onSelect?<button className="button" onClick={()=>onSelect('')}>← All teams</button>:<Link href="/teams" className="button">← All teams</Link>}</div>}
 {loading&&<p role="status" className="team-empty">Loading {id?'team profile':'teams'}…</p>}{error&&<div className="team-error" role="alert"><p>{error}</p></div>}{notice&&<p className="team-success" role="status">{notice}</p>}
 {!loading&&!id&&data&&<><p className="muted" role="status">{data.items.length} team{data.items.length===1?'':'s'}{search?' matching “'+search+'”':''}</p>{!data.items.length?<div className="team-empty"><h2>No teams found yet.</h2><p>{search?'Try a different name or specialty.':'Teams will appear here as approved builders create them.'}</p></div>:<div className="team-grid">{data.items.map((t:any)=><article className="team-card" key={t.id}><div className="team-monogram" aria-hidden="true">{t.name.slice(0,2).toUpperCase()}</div><h2>{t.name}</h2><p>{t.summary}</p><div className="team-meta"><span>{t.memberCount} members</span><span>·</span><span>{t.roleCount} open roles</span></div><p className="team-badge">{t.availability}</p><p>{t.projectRange}</p><div className="team-actions">{select(t.id,'Meet the team ↗')}</div></article>)}</div>}</>}
 {!loading&&team&&<><header className="team-hero team-profile-hero"><div><div className="team-monogram" aria-hidden="true">{team.name.slice(0,2).toUpperCase()}</div><span className="eyebrow">Independent studio</span><h1>{team.name}</h1><p>{team.summary}</p><div className="team-meta"><span className="team-badge">{team.availability}</span><span>{team.projectRange}</span></div></div><div className="team-profile-count"><strong>{data.members.length}</strong><span>builders, working together</span></div></header><div className="team-two"><div>
 <section className="team-section"><h2>Work, with proof.</h2><p className="muted">Products shared with their original builders’ consent.</p>{!data.projects.length?<p className="team-empty">This team has not shared any products yet.</p>:<div className="team-project-grid">{data.projects.map((p:any)=><article className="team-card" key={p.id}>{p.imageUrl&&<img className="team-product-image" src={p.imageUrl} alt={p.title+' preview'} loading="lazy"/>}<h3>{p.title}</h3><p>{p.summary||p.description}</p><p className="muted">By {p.developer?.displayName||p.developerName||p.ownerName||p.builder||'the original builder'}</p>{!embedded&&<Link className="button" href={'/products/'+(p.slug||p.id)}>View product ↗</Link>}</article>)}</div>}</section>
 <section className="team-section"><h2>Meet the builders</h2>{data.members.map((m:any)=><div className="team-row" key={m.userId}><div><h3>{m.name}</h3><p>{human(m.role)}</p></div><span className="team-badge">Approved builder</span></div>)}</section>
 <section className="team-section"><h2>Member review history</h2><p className="muted">Existing verified reviews of individual members. These are not new team-verified reviews.</p>{data.reviews.length>0&&<p><strong>{(data.reviews.reduce((total:number,r:any)=>total+Number(r.rating||0),0)/data.reviews.length).toFixed(1)} / 5</strong> across {data.reviews.length} verified member reviews</p>}{!data.reviews.length?<p className="team-empty">No verified member reviews to display yet.</p>:data.reviews.map((r:any,i:number)=><blockquote className="team-note" key={r.id||i}><p>{r.text||r.reviewText||r.review_text}</p><footer>{r.rating&&<span>{r.rating}/5 · </span>}For {r.memberName||r.developerName||r.builderName||'an individual member'}{r.clientName?' · '+r.clientName:''}</footer></blockquote>)}</section>
 </div><aside>
 <section className="team-section team-card"><h2>Build with this team</h2><p>Introduce your project. Sending interest starts a conversation and creates no binding agreement.</p>{membership?<p className="team-notice">You belong to this team. Client interest is available to people outside the team.</p>:!me?<p><Link href="/login" className="button">Log in to send interest</Link></p>:!me.emailVerified?<p className="team-notice">Verify your account email before sending interest.</p>:<TeamForm label="Send project interest" onSave={async d=>{await request('/teams/'+id+'/leads',{method:'POST',body:JSON.stringify(d)});setNotice('Project interest sent. Follow its progress in your team workspace.')}}><Field name="title" label="Project title"/><Field name="description" label="What would you like to build?" type="textarea"/><Field name="budget" label="Budget range"/><Field name="timeline" label="Expected timeline"/></TeamForm>}</section>
 <section className="team-section"><h2>Open roles <span className="team-badge">{data.roles.length}</span></h2><p className="muted">Applications never add you to a team automatically. You choose whether to accept a later invitation.</p>{!data.roles.length?<p className="team-empty">No open roles right now.</p>:data.roles.map((r:any)=><article className="team-card team-role-card" key={r.id}><h3>{r.title}</h3><p>{r.description}</p><div className="team-meta"><span>{human(r.contractType)}</span><span>{r.compensationBand}</span></div><p>{Array.isArray(r.skills)?r.skills.join(' · '):r.skills}</p>{membership?<p className="muted">You are already a team member.</p>:applied.includes(r.id)?<p className="team-success" role="status">Application submitted. Check your workspace for updates.</p>:!me?<Link href="/login" className="button">Log in to apply</Link>:!approved||!me.emailVerified?<p className="team-notice">Apply with an approved builder profile and verified email.</p>:<details><summary>Apply for this role</summary><TeamForm label="Send application" onSave={async d=>{await request('/teams/'+id+'/roles/'+r.id+'/applications',{method:'POST',body:JSON.stringify(d)});setApplied(a=>[...a,r.id]);setNotice('Application sent. Membership requires your acceptance of a separate invitation.')}}><Field name="message" label="Introduce yourself and your relevant work" type="textarea"/></TeamForm></details>}</article>)}</section>
 </aside></div></>}
 </>;return embedded?<div className="team-public">{contents}</div>:<main id="main" className="wrap teams-page">{contents}</main>;
}
