'use client';
import {FormEvent,ReactNode,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
import {createTeamDemo} from '@/lib/team-demo';
import TeamPublic from './team-public';
import TeamModeration from './team-moderation';
import './teams.css';
export type TeamRequest=(path:string,init?:RequestInit)=>Promise<any>;
export const human=(s:string='')=>s.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
export function Field({name,label,value='',type='text',options,required=true}:{name:string,label:string,value?:any,type?:string,options?:{value:string,label:string}[],required?:boolean}){return <label className="team-field">{label}{options?<select name={name} defaultValue={value} required={required}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:type==='textarea'?<textarea name={name} defaultValue={value||''} required={required} maxLength={4000}/>:<input name={name} type={type} defaultValue={value||''} required={required} maxLength={type==='text'?500:undefined}/>}</label>}
export function TeamForm({children,onSave,label='Save changes',busy=false}:{children:ReactNode,onSave:(data:any)=>Promise<boolean|void>,label?:string,busy?:boolean}){const [error,setError]=useState(''),[pending,setPending]=useState(false);return <form className="team-form" onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;setError('');setPending(true);try{await onSave(Object.fromEntries(new FormData(form)))}catch(e){setError((e as Error).message)}finally{setPending(false)}}}><fieldset disabled={pending||busy}>{children}<div>{error&&<p role="alert" className="team-error">{error}</p>}<button className="button primary" disabled={pending||busy}>{pending?'Saving…':label}</button></div></fieldset></form>}
const opts=(values:string[])=>values.map(value=>({value,label:human(value)}));
const roles=['MEMBER','BUSINESS_MANAGER','RECRUITER','PROJECT_MANAGER'];
const blank={items:[],invitations:[],applications:[],requests:[]};
export default function TeamWorkspace({demo=false}:{demo?:boolean}){
 const [adapter]=useState(()=>demo?createTeamDemo():null);const request:TeamRequest=adapter?.request||api;
 const [actor,setActor]=useState(adapter?.actors[0]?.id||''),[me,setMe]=useState<any>(null),[index,setIndex]=useState<any>(blank),[selected,setSelected]=useState(''),[workspace,setWorkspace]=useState<any>(null),[products,setProducts]=useState<any[]>([]),[tab,setTab]=useState('Overview'),[view,setView]=useState('workspace'),[publicId,setPublicId]=useState('');
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[candidates,setCandidates]=useState<any[]>([]);const generation=useRef(0);
 async function load(id=selected){const run=++generation.current;setLoading(true);try{const user=await request('/me');const data=await request('/me/teams');const target=id&&data.items.some((t:any)=>t.id===id)?id:data.items[0]?.id||'';const ws=target?await request('/teams/'+target+'/workspace'):null;let owned:any[]=[];if(user.roles?.includes('DEVELOPER')||user.roles?.includes('BUILDER')||user.profile)try{owned=(await request('/developer/products?lifecycleStatus=ACTIVE')).items||[]}catch{}if(run!==generation.current)return;setMe(user);setIndex(data);setSelected(target);setWorkspace(ws);setProducts(owned);setError('')}catch(e){if(run===generation.current){setError((e as Error).message);setWorkspace(null)}}finally{if(run===generation.current)setLoading(false)}}
 useEffect(()=>{load('');return()=>{generation.current++}},[actor]);
 async function mutate(path:string,body:any={},method='POST'){setBusy(true);setError('');setMessage('');try{const result=await request(path,{method,body:JSON.stringify(body)});setMessage('Changes saved.');await load(path==='/teams'?result.id:selected);return true}catch(e){setError((e as Error).message);throw e}finally{setBusy(false)}}
 const act=(path:string,body:any={},method='POST')=>{void mutate(path,body,method).catch(()=>{})};
 const role=workspace?.myRole;const owner=role==='OWNER';const recruit=owner||role==='RECRUITER';const commercial=owner||role==='BUSINESS_MANAGER';const staffing=owner||role==='PROJECT_MANAGER';const base='/teams/'+selected;
 const active=workspace?.team.status==='ACTIVE';const canCreate=me?.emailVerified&&me?.profile?.approval_status==='APPROVED'&&products.some(p=>p.approvalStatus==='APPROVED');
 const tabs=['Overview','Members','Recruitment',...(commercial?['Leads']:[]),'Projects',...(staffing?['Staffing']:[]),'Activity'];
 return <main id="main" className="wrap teams-page">
 {demo&&<div className="team-notice demo"><strong>Interactive team preview · sample data</strong><p>Changes stay in this preview. No real accounts, invitations, email or client requests are created.</p><div className="team-actions"><label className="team-field">Preview actor<select value={actor} disabled={busy} onChange={e=>{adapter!.setActor(e.target.value);setActor(e.target.value);setTab('Overview');setWorkspace(null);setCandidates([]);setMe(null);setMessage('');setView('workspace')}}>{adapter!.actors.map(a=><option key={a.id} value={a.id}>{a.name} · {human(a.role)}</option>)}</select></label><button className="button" disabled={busy} onClick={()=>{adapter!.reset();adapter!.setActor(actor);setMessage('Sample data reset.');load('')}}>Reset sample data</button><button className="button" onClick={()=>{setView(view==='public'?'workspace':'public');setPublicId('')}}>{view==='public'?'Open team workspace':'Explore sample teams'}</button></div></div>}
 {demo&&view==='public'?<TeamPublic embedded request={request} id={publicId||undefined} onSelect={setPublicId}/>:<>
 <header className="team-hero"><div><span className="eyebrow">Team workspace</span><h1>Better work, together.</h1><p>A shared home for your studio, your people and the opportunities you build together.</p></div><Link href="/teams" className="button">Explore teams ↗</Link></header>
 {error&&<div className="team-error" role="alert">{error}</div>}{message&&<p className="team-success" role="status">{message}</p>}{loading&&<p role="status">Loading team workspace…</p>}
 {!loading&&!me?<div className="team-empty"><h2>Your team starts here.</h2><p>Log in to manage memberships and shared work.</p><Link href="/login" className="button primary">Log in</Link></div>:me&&<>
 <section className="team-section"><div className="team-actions">{index.items.length>0&&<label className="team-field">Your team<select value={selected} disabled={busy||loading} onChange={e=>{setSelected(e.target.value);setWorkspace(null);setCandidates([]);setTab('Overview');load(e.target.value)}}>{index.items.map((t:any)=><option key={t.id} value={t.id}>{t.name} · {human(t.myRole||'member')}</option>)}</select></label>}<span>{index.items.length} team{index.items.length===1?'':'s'}</span></div>
 <details><summary>Create a team</summary><p>Available to email-verified, approved builders with an approved product.</p>{canCreate?<TeamForm label="Create team" busy={busy} onSave={data=>mutate('/teams',data)}><ProfileFields/></TeamForm>:<p className="muted">Complete your builder approval, verify your email and publish an approved product to create a team. <Link href="/workspace">Open your personal workspace</Link></p>}</details></section>
 {index.invitations?.length>0&&<section className="team-section"><h2>Your invitations</h2><p>Membership begins only after you accept. Team membership is not employment.</p>{index.invitations.map((i:any)=><div className="team-row" key={i.id}><div><h3>{i.teamName}</h3><p>{human(i.role)} · {human(i.membershipType)} · {human(i.status)}</p>{i.expiresAt&&<p>Expires {new Date(i.expiresAt).toLocaleDateString()}</p>}</div>{i.status==='PENDING'&&<div className="team-actions"><button className="button primary" disabled={busy} onClick={()=>act('/team-invitations/'+i.id+'/respond',{action:'ACCEPT'})}>Accept invitation</button><button className="button" disabled={busy} onClick={()=>act('/team-invitations/'+i.id+'/respond',{action:'DECLINE'})}>Decline</button></div>}</div>)}</section>}
 {index.applications?.length>0&&<section className="team-section"><h2>Your applications</h2>{index.applications.map((a:any)=><div key={a.id} className="team-row"><strong>{a.roleTitle}</strong><span className="team-badge">{human(a.status)}</span></div>)}</section>}
 {me?.roles?.includes('ADMIN')&&<TeamModeration request={request}/>}
 {index.requests?.length>0&&<section className="team-section"><h2>Your team requests</h2>{index.requests.map((l:any)=><div key={l.id} className="team-row"><div><h3>{l.title}</h3><p>{l.teamName}</p></div><div><span className="team-badge">{human(l.status)}</span>{l.status==='PROPOSAL_SENT'&&<div className="team-actions"><button className="button" disabled={busy} onClick={()=>act('/teams/'+l.teamId+'/leads/'+l.id+'/respond',{action:'ACCEPT'})}>Acknowledge proposal</button><button className="button" disabled={busy} onClick={()=>act('/teams/'+l.teamId+'/leads/'+l.id+'/respond',{action:'DECLINE'})}>Decline proposal</button><small>This records your decision. Agree terms externally.</small></div>}</div></div>)}</section>}
 {!workspace&&!loading&&<div className="team-empty"><h2>A place for your next collaboration.</h2><p>You have no active team memberships. Accept an invitation, apply for an open role, or create an eligible team.</p>{demo?<button className="button" onClick={()=>setView('public')}>Explore sample teams</button>:<Link href="/teams" className="button">Find a team</Link>}</div>}
 {workspace&&<><div className="team-hero"><div><h2>{workspace.team.name}</h2><p>{workspace.team.summary}</p><span className="team-badge">{human(role)} access</span> <span className="team-badge">{human(workspace.team.status)}</span></div>{demo?<button className="button" onClick={()=>{setPublicId(selected);setView('public')}}>View public profile ↗</button>:<Link href={'/teams/'+selected} className="button">View public profile ↗</Link>}</div>
 {!active&&<p className="team-notice">This team is suspended. Recruitment and new client interest are unavailable.</p>}
 <nav className="team-tabs" aria-label="Team workspace sections">{tabs.map(t=><button key={t} aria-current={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 <section key={selected+tab+JSON.stringify(workspace)} className="team-section" aria-label={tab}>
 {tab==='Overview'&&<><h2>Team overview</h2><div className="team-stats"><div><strong>{workspace.members.length}</strong>Active members</div><div><strong>{workspace.roles.filter((r:any)=>r.status==='OPEN').length}</strong>Open roles</div><div><strong>{workspace.projects.length}</strong>Shared products</div></div><p>{workspace.team.availability} · {workspace.team.projectRange}</p><p className="muted">One account can build, hire and join multiple teams. Products stay owned by their original builders.</p>{owner&&<details><summary>Edit team profile</summary><TeamForm busy={busy} onSave={d=>mutate(base,d,'PUT')}><ProfileFields team={workspace.team}/></TeamForm></details>}</>}
 {tab==='Members'&&<><h2>People in your team</h2><p>Contract access ends at expiry. Membership does not establish employment.</p>{workspace.members.map((m:any)=><div className="team-row" key={m.userId}><div><h3>{m.name}</h3><p>{human(m.role)} · {human(m.membershipType)}{m.projectLabel?' · '+m.projectLabel:''}</p>{m.expiresAt&&<p>Access until {new Date(m.expiresAt).toLocaleDateString()}</p>}{owner&&m.role!=='OWNER'&&<details><summary>Manage {m.name}</summary><TeamForm busy={busy} onSave={d=>mutate(base+'/members/'+m.userId,d,'PATCH')}><Field name="role" label="Team role" value={m.role} options={opts(roles)}/></TeamForm><button disabled={busy} className="button" onClick={()=>{if(confirm('Remove '+m.name+' from this team?'))act(base+'/members/'+m.userId,{},'DELETE')}}>Remove member</button></details>}</div>{m.userId===me.id&&m.role!=='OWNER'&&<button disabled={busy} className="button" onClick={()=>{if(confirm('Leave this team and lose workspace access?'))act(base+'/members/'+m.userId,{},'DELETE')}}>Leave team</button>}</div>)}
 {recruit&&active&&<details><summary>Find and invite a builder</summary><TeamForm label="Search builders" busy={busy} onSave={async d=>{setCandidates((await request(base+'/candidates?q='+encodeURIComponent(d.q))).items)}}><Field name="q" label="Builder name or skill"/></TeamForm>{candidates.map(c=><details key={c.id}><summary>{c.name} · {c.headline}</summary><p>{Array.isArray(c.skills)?c.skills.join(', '):c.skills}</p><TeamForm label="Send invitation" busy={busy} onSave={d=>mutate(base+'/invitations',{...d,userId:c.id,expiresAt:d.expiresAt?new Date(d.expiresAt).toISOString():null})}><Field name="role" label="Membership role" value="MEMBER" options={opts(owner?roles:['MEMBER'])}/><MembershipFields/></TeamForm></details>)}</details>}
 {recruit&&<><h3>Sent invitations</h3><Empty items={workspace.invitations} text="No invitations yet."/>{workspace.invitations.map((i:any)=><div className="team-row" key={i.id}><div><strong>{i.name}</strong><p>{human(i.role)} · {human(i.membershipType)}</p></div><span className="team-badge">{human(i.status)}</span></div>)}</>}</>}
 {tab==='Recruitment'&&<><h2>Open roles & applications</h2><Empty items={workspace.roles} text="No roles published yet."/>{workspace.roles.map((r:any)=><div className="team-row" key={r.id}><div><h3>{r.title}</h3><p>{r.description}</p><p>{Array.isArray(r.skills)?r.skills.join(', '):r.skills} · {r.compensationBand}</p><span className="team-badge">{human(r.status)}</span></div>{recruit&&active&&<button className="button" disabled={busy} onClick={()=>act(base+'/roles/'+r.id,{status:r.status==='OPEN'?'CLOSED':'OPEN'},'PATCH')}>{r.status==='OPEN'?'Close role':'Reopen role'}</button>}</div>)}{recruit&&active&&<details><summary>Publish an open role</summary><TeamForm label="Publish role" busy={busy} onSave={d=>mutate(base+'/roles',d)}><Field name="title" label="Role title"/><Field name="description" label="What will this person do?" type="textarea"/><Field name="skills" label="Skills (comma separated)"/><Field name="contractType" label="Engagement type" options={opts(['CONTRACT','PERMANENT'])}/><Field name="compensationBand" label="Compensation range"/></TeamForm></details>}{recruit&&<><h3>Applications</h3><Empty items={workspace.applications} text="Applications will appear here."/>{workspace.applications.map((a:any)=><div className="team-row" key={a.id}><div><h3>{a.name} · {a.roleTitle}</h3><p>{a.message}</p><span className="team-badge">{human(a.status)}</span></div>{active&&['APPLIED','SUBMITTED','PENDING','SHORTLISTED'].includes(a.status)&&<div className="team-actions">{(a.status==='SHORTLISTED'?['INVITED','REJECTED']:['SHORTLISTED','REJECTED']).map(s=><button className="button" disabled={busy} key={s} onClick={()=>act(base+'/applications/'+a.id+'/decision',{status:s})}>{s==='INVITED'?'Invite to join':s==='SHORTLISTED'?'Shortlist':'Reject'}</button>)}</div>}</div>)}<p className="muted">Inviting an applicant asks for consent; it never joins them automatically.</p></>}</>}
 {tab==='Leads'&&commercial&&<><h2>Shared client leads</h2><p>Record conversations and follow-ups. A won lead is a reported outcome, not verified payment or completion.</p><Empty items={workspace.leads} text="No client leads yet. Share your public team profile to receive interest."/>{workspace.leads.map((l:any)=><details key={l.id}><summary>{l.title} · {human(l.status)}</summary><p>{l.clientName} · {l.budget} · {l.timeline}</p><p>{l.description}</p><TeamForm label="Update lead" busy={busy} onSave={d=>mutate(base+'/leads/'+l.id,{...d,note:d.note?.trim()||undefined,assigneeId:d.assigneeId||null,followUpAt:d.followUpAt?new Date(d.followUpAt).toISOString():null},'PATCH')}><Field name="status" label="Stage" value={l.status} options={opts([l.status,...(leadTransitions[l.status]||[])])}/><Field name="assigneeId" label="Assigned teammate" value={l.assigneeId||''} required={false} options={[{value:'',label:'Unassigned'},...workspace.members.map((m:any)=>({value:m.userId,label:m.name}))]}/><Field name="followUpAt" label="Follow-up (local time)" type="datetime-local" value={localDate(l.followUpAt)} required={false}/><Field name="note" label="Add a private note" type="textarea" required={false}/></TeamForm>{l.notes?.map((n:any,i:number)=><div className="team-note" key={i}><p>{n.text}</p><small>{n.actorName} · {new Date(n.createdAt).toLocaleString()}</small></div>)}</details>)}</>}
 {tab==='Projects'&&<><h2>Shared product showcase</h2><p>Contribute only approved public products you own. Sharing does not transfer ownership or use extra individual showcase slots.</p><Empty items={workspace.projects} text="No products shared yet."/>{workspace.projects.map((p:any)=><div className="team-row" key={p.id}><div><h3>{p.title}</h3><p>{p.summary}</p></div>{(owner||products.some(owned=>owned.id===p.id)||p.ownerId===me.id||p.developerId===me.id||p.developer?.id===me.id)&&<button className="button" disabled={busy} onClick={()=>act(base+'/projects/'+p.id,{},'DELETE')}>Remove from team</button>}</div>)}<details><summary>Contribute your product</summary><TeamForm label="Consent and share product" busy={busy} onSave={d=>mutate(base+'/projects',d)}><Field name="productId" label="Your approved public product" value="" options={[{value:'',label:'Select a product'},...products.filter(p=>p.approvalStatus==='APPROVED'&&p.visibility==='PUBLIC'&&!workspace.projects.some((s:any)=>s.id===p.id)).map(p=>({value:p.id,label:p.title}))]}/><p>By sharing, you consent to display this product on the team profile. You can withdraw it later.</p></TeamForm></details></>}
 {tab==='Staffing'&&<><h2>Temporary project staffing</h2><p>Plan who is working on what, with a clear end date.</p><Empty items={workspace.staffing} text="No staffing assignments yet."/>{workspace.staffing.map((s:any)=><div className="team-row" key={s.id}><div><h3>{s.name} · {s.projectLabel}</h3><p>{Array.isArray(s.skills)?s.skills.join(', '):s.skills} · Ends {new Date(s.endsAt).toLocaleDateString()}</p><span className="team-badge">{human(s.status)}</span></div>{staffing&&s.status==='ACTIVE'&&<button className="button" disabled={busy} onClick={()=>act(base+'/staffing/'+s.id,{status:'COMPLETED'},'PATCH')}>Mark completed</button>}</div>)}{staffing&&<details><summary>Assign a teammate</summary><TeamForm label="Create assignment" busy={busy} onSave={d=>mutate(base+'/staffing',{...d,skills:d.skills,endsAt:new Date(d.endsAt).toISOString()})}><Field name="userId" label="Active teammate" options={workspace.members.map((m:any)=>({value:m.userId,label:m.name}))}/><Field name="projectLabel" label="Project name"/><Field name="skills" label="Skills (comma separated)"/><Field name="endsAt" label="Assignment ends (local time)" type="datetime-local"/></TeamForm></details>}</>}
 {tab==='Activity'&&<><h2>Team activity</h2><Empty items={workspace.activity} text="Team changes will appear here."/>{workspace.activity.map((a:any)=><div className="team-row" key={a.id}><div><strong>{human(a.action)}</strong><p>{a.detail}</p><p>{a.actorName} · {new Date(a.createdAt).toLocaleString()}</p></div></div>)}</>}
 </section></>}
 </>}
 </>}
 </main>
}
function ProfileFields({team}: {team?:any}){return <><Field name="name" label="Team name" value={team?.name}/><Field name="summary" label="What does your team build?" type="textarea" value={team?.summary}/><Field name="availability" label="Availability" value={team?.availability||'Open to projects'}/><Field name="projectRange" label="Typical project budget range" value={team?.projectRange}/></>}
function MembershipFields(){const [kind,setKind]=useState('PERMANENT');return <><label className="team-field">Membership type<select name="membershipType" value={kind} onChange={e=>setKind(e.target.value)}><option value="PERMANENT">Permanent</option><option value="CONTRACT">Contract</option></select></label><Field name="expiresAt" label={kind==='CONTRACT'?'Contract expiry (required, local time)':'Invitation expiry (optional, local time)'} type="datetime-local" required={kind==='CONTRACT'}/><Field name="projectLabel" label="Project label (optional)" required={false}/></>}
function Empty({items,text}:{items:any[],text:string}){return !items?.length?<div className="team-empty">{text}</div>:null}
function localDate(value:string){if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
const leadTransitions:Record<string,string[]>={NEW:['INTERESTED','NEEDS_INFORMATION','DECLINED'],INTERESTED:['NEEDS_INFORMATION','PROPOSAL_SENT','DECLINED','LOST'],NEEDS_INFORMATION:['INTERESTED','DECLINED'],PROPOSAL_SENT:['WON','LOST','NEEDS_INFORMATION'],WON:[],LOST:[],DECLINED:[]};
