'use client';

import {useEffect,useId,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {ArrowUpRight,BookOpen,Download,FileArchive,Package,Plus,ShieldCheck,Upload} from 'lucide-react';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {api,ApiError} from '@/lib/api';
import {canSubmitVersion,downloadTemplateSource,eligibleTemplateDownload,templateDate,templateDisputeAvailable,templateMinor,templatePrice,templateStatus,type SourceTemplate,type TemplatePage,type TemplatePurchase,type TemplateVersion} from '@/lib/templates';
import {createTemplatePreview} from '@/lib/template-preview';
import {WorkspaceFrame,PreviewControls} from './workspace-frame';
import {Field,TeamForm} from './workspace-form';
import TemplateOperations from './template-operations';
import '@/app/templates.css';

type Product={id:string;title:string;approvalStatus:string;visibility:string;lifecycleStatus:string};
type Actor='SELLER'|'BUYER'|'OPERATOR';
const pageOf=<T,>(items:T[]):TemplatePage<T>=>({items,page:0,size:12,hasMore:false,totalItems:items.length,totalPages:items.length?1:0});
const emptyPage=<T,>()=>pageOf<T>([]);

export default function TemplateWorkspace({demo=false}:{demo?:boolean}){
 const [preview]=useState(()=>demo?createTemplatePreview():null),[actor,setActor]=useState<Actor>('SELLER'),[tab,setTab]=useState('releases'),[owned,setOwned]=useState<TemplatePage<SourceTemplate>>(emptyPage),[purchases,setPurchases]=useState<TemplatePage<TemplatePurchase>>(emptyPage),[products,setProducts]=useState<Product[]>([]),[productError,setProductError]=useState(''),[selected,setSelected]=useState(''),[authenticated,setAuthenticated]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[dialog,setDialog]=useState(''),[error,setError]=useState(''),[note,setNote]=useState('');
 const generation=useRef(0),summary=useRef<HTMLDivElement>(null),opener=useRef<HTMLElement|null>(null),detail=owned.items.find(item=>item.id===selected),purchase=purchases.items.find(item=>item.id===dialog.split(':')[1]);
 useEffect(()=>{if(error)summary.current?.focus();},[error]);
 function show(value:string){opener.current=document.activeElement as HTMLElement;setError('');setDialog(value);}
 function clear(){setOwned(emptyPage());setPurchases(emptyPage());setProducts([]);setAuthenticated(false);setSelected('');}
 async function load(id=selected,ownedNumber=owned.page,purchaseNumber=purchases.page){
  const run=++generation.current;setLoading(true);setError('');
  try{
   let nextOwned:TemplatePage<SourceTemplate>,nextPurchases:TemplatePage<TemplatePurchase>,nextProducts:Product[]=[];let unavailable='';
   if(preview){nextOwned=pageOf(preview.list());nextPurchases=pageOf(preview.purchases());nextProducts=[{id:'sample-proof',title:'Sample approved public project',approvalStatus:'APPROVED',visibility:'PUBLIC',lifecycleStatus:'ACTIVE'}];}
   else{
    const me=await api('/me');const [seller,buyer]=await Promise.all([api('/me/templates?page='+ownedNumber+'&size=12'),api('/me/template-purchases?page='+purchaseNumber+'&size=12')]);nextOwned=seller;nextPurchases=buyer;
    if(me.profile||me.roles?.includes('DEVELOPER')||me.roles?.includes('BUILDER')){try{let page=0,more=true;while(more){const response=await api('/developer/products?page='+page+'&size=50');nextProducts.push(...response.items);more=response.hasMore===true;page++;}}catch(problem){unavailable=(problem as Error).message;}}
   }
   if(run!==generation.current)return;setOwned(nextOwned);setPurchases(nextPurchases);setProducts(nextProducts.filter(item=>item.approvalStatus==='APPROVED'&&item.visibility==='PUBLIC'&&item.lifecycleStatus==='ACTIVE'));setProductError(unavailable);setSelected(nextOwned.items.some(item=>item.id===id)?id:nextOwned.items[0]?.id||'');setAuthenticated(true);
  }catch(problem){if(run===generation.current){clear();setError((problem as Error).message);}}finally{if(run===generation.current)setLoading(false);}
 }
 useEffect(()=>{const query=new URLSearchParams(window.location.search);if(query.get('tab')==='purchases')setTab('purchases');if(query.get('tab')==='purchases'&&demo)setActor('BUYER');void load(query.get('templateId')||'');return()=>{generation.current++;};},[]);
 async function change(work:()=>Promise<unknown>|unknown,message:string,next=selected,ownedNumber=owned.page){setBusy(true);setError('');setNote('');try{const result=await work();const resultId=typeof result==='object'&&result&&'id' in result?String(result.id):'';await load(next||resultId,ownedNumber);setNote(message);return result;}catch(problem){if(!preview&&problem instanceof ApiError&&[401,403].includes(problem.status))clear();setError((problem as Error).message);throw problem;}finally{setBusy(false);}}
 function act(work:()=>Promise<unknown>|unknown,message:string,next=selected){void change(work,message,next).catch(()=>{});}
 const post=(path:string,body:unknown={})=>api(path,{method:'POST',body:JSON.stringify(body)});
 async function create(data:Record<string,string>){let priceMinor:number;try{priceMinor=templateMinor(data.price);}catch(problem){throw new ApiError((problem as Error).message,'INVALID_PRICE',400,undefined,{price:(problem as Error).message});}const body={productId:data.productId,title:data.title,summary:data.summary,description:data.description,licenseTerms:data.licenseTerms,priceMinor};const result=await change(()=>preview?preview.create(body):post('/me/templates',body),'Template draft created. Upload a version to continue.','',0) as SourceTemplate;setDialog('');setSelected(result.id);}
 async function upload(data:FormData){if(!detail)return;const result=await change(()=>preview?preview.upload(detail.id,{version:String(data.get('version')),releaseNotes:String(data.get('releaseNotes')),rightsConsent:data.get('rightsConsent')==='true'}):uploadPackage('/me/templates/'+detail.id+'/versions',data),'Version uploaded privately. Review its metadata, then submit it for approval.');return result;}
 async function submit(version:TemplateVersion,consent:boolean){if(!detail)return;await change(()=>preview?preview.submit(detail.id,version.id,consent):post('/me/templates/'+detail.id+'/versions/'+version.id+'/submit',{rightsConsent:consent}),'Version submitted. It remains unavailable to buyers until an operator approves it.');setDialog('');}
 async function archive(){if(!detail)return;await change(()=>preview?preview.archive(detail.id):post('/me/templates/'+detail.id+'/archive'),'Template archived. Existing eligible purchases keep their pinned version.');setDialog('');}
 async function download(path:string,filename:string){if(preview){setNote('Sample packages are not real source archives. No download request was sent.');return;}act(()=>downloadTemplateSource(path,filename),'Source attachment requested.');}
 async function dispute(data:Record<string,string>){if(!purchase)return;await change(()=>preview?preview.dispute(purchase.id,data.reason):post('/template-purchases/'+purchase.id+'/disputes',{reason:data.reason}),'Concern recorded. Source access pauses while it is reviewed; this does not automatically issue a refund.');setDialog('');}
 function select(id:string){setSelected(id);const url=new URL(window.location.href);url.searchParams.set('templateId',id);url.searchParams.delete('tab');window.history.replaceState(null,'',url);}
 function selectTab(value:string){setTab(value);const url=new URL(window.location.href);url.searchParams.set('tab',value);window.history.replaceState(null,'',url);}

 return <WorkspaceFrame section="templates" preview={demo} className="commerce-workspace" title="Templates & purchases" description="Manage reviewed releases, read your purchase licenses and keep source delivery private." actions={<Link className="button" href="/templates">Browse source templates <ArrowUpRight size={16} aria-hidden="true"/></Link>}>
  {demo&&<PreviewControls title="Interactive source marketplace preview" note="Sample frontend records only. Uploads are simulated without reading files; no account, provider or source archive is contacted."><label className="commerce-field">Preview actor<select value={actor} aria-label="Preview actor" onChange={event=>{const value=event.target.value as Actor;setActor(value);setTab(value==='BUYER'?'purchases':'releases');setDialog('');setNote('');}}><option value="SELLER">Seller · independent builder</option><option value="BUYER">Buyer · source license</option><option value="OPERATOR">Operator · review & recovery</option></select></label><button className="button" disabled={busy} onClick={()=>{preview!.reset();setDialog('');setNote('Sample records reset.');void load('');}}>Reset sample data</button></PreviewControls>}
  {error&&<div ref={summary} tabIndex={-1} className="commerce-notice error" role="alert"><p>{error}</p><button className="button" disabled={busy} onClick={()=>void load()}>Reload template workspace</button></div>}{note&&<p className="commerce-notice" role="status">{note}</p>}
  {loading?<p className="commerce-loading" role="status">Loading template workspace…</p>:!authenticated?<div className="commerce-empty"><ShieldCheck size={30} aria-hidden="true"/><h2>Your source workspace is private.</h2><p>Sign in to manage releases and see the licenses you purchased.</p><Link className="button primary" href="/login">Log in</Link><button className="button" onClick={()=>void load()}>Retry</button></div>:demo&&actor==='OPERATOR'?<TemplateOperations demo previewStore={preview!} onChanged={()=>void load()}/>:<Tabs value={tab} onValueChange={selectTab} className="commerce-tabs studio-tabset"><TabsList className="studio-tabs" aria-label="Source workspace areas"><TabsTrigger value="releases">Your releases</TabsTrigger><TabsTrigger value="purchases">Purchases</TabsTrigger></TabsList>
   <TabsContent value="releases"><div className="commerce-section-heading"><div><p className="commerce-kicker">Seller studio</p><h2>Your template releases</h2><p>Every version has its own package review. Your existing buyers keep the release they purchased.</p></div><button className="button primary" disabled={busy||!products.length||!!productError} onClick={()=>show('create')}><Plus size={16} aria-hidden="true"/>Create template</button></div>{productError&&<p className="commerce-notice error" role="alert">Approved project choices could not load: {productError}</p>}{!products.length&&<p className="commerce-notice">Selling requires a verified, approved builder account and an approved public proof project. Review your <Link href={demo?'/preview/workspace':'/workspace'}>builder workspace</Link> and <Link href={demo?'/preview/trust':'/workspace/trust'}>repository ownership evidence</Link>.</p>}
    {!owned.items.length?<div className="commerce-empty"><Package size={30} aria-hidden="true"/><h3>Turn your approved work into a useful starting point.</h3><p>Create a listing, upload a safe ZIP with documentation and license notices, then request operator review.</p></div>:<div className="commerce-seller-grid"><nav aria-label="Your templates" className="commerce-template-list">{owned.items.map(item=><button className="commerce-template-item" aria-current={selected===item.id?'true':undefined} disabled={busy} key={item.id} onClick={()=>select(item.id)}><span className="commerce-badge">{templateStatus(item.status)}</span><strong>{item.title}</strong><span>{templatePrice(item.priceMinor)} · {item.version?'v'+item.version:'No release yet'}</span></button>)}<PageControls page={owned} busy={busy} name="releases" onPage={page=>void load('',page,purchases.page)}/></nav>{detail&&<div className="commerce-template-detail"><section className="commerce-section"><div className="commerce-section-heading"><div><p className="commerce-kicker">Private seller record</p><h2>{detail.title}</h2></div><span className="commerce-badge">{templateStatus(detail.status)}</span></div><p>{detail.summary}</p><p className="commerce-prose">{detail.description}</p><dl className="commerce-facts"><div><dt>Price</dt><dd>{templatePrice(detail.priceMinor)}</dd></div><div><dt>Stack</dt><dd>{detail.technology?.replaceAll('_',' ')}</dd></div></dl><details><summary>Listing license terms</summary><p className="commerce-prose">{detail.licenseTerms}</p></details><div className="commerce-actions">{detail.status==='ACTIVE'&&<Link href={'/templates/'+detail.slug} className="button">View public listing <ArrowUpRight size={16} aria-hidden="true"/></Link>}{!['ARCHIVED','SUSPENDED'].includes(detail.status)&&<button className="button" disabled={busy} onClick={()=>show('archive')}>Archive listing</button>}</div></section>
     <section className="commerce-section"><div className="commerce-section-heading"><div><p className="commerce-kicker">Immutable reviewed packages</p><h2>Release history</h2></div><FileArchive size={24} aria-hidden="true"/></div>{!detail.versions?.length&&<p className="commerce-muted">No package uploaded yet.</p>}{detail.versions?.slice().sort((a,b)=>new Date(b.createdAt||0).getTime()-new Date(a.createdAt||0).getTime()).map(version=><article className="commerce-version" key={version.id}><div className="commerce-row-heading"><h3>Version {version.version}</h3><span className="commerce-badge">{templateStatus(version.status)}</span></div><p className="commerce-prose">{version.releaseNotes}</p><p className="commerce-muted">{templateDate(version.createdAt)} · {version.entryCount??'—'} files · {version.sizeBytes===undefined?'Size pending':Math.ceil(version.sizeBytes/1024)+' KB'}</p>{version.sha256&&<p className="commerce-digest"><strong>Package SHA-256</strong><code>{version.sha256}</code></p>}{version.reviewReason&&<p className="commerce-notice"><strong>Review note</strong><br/>{version.reviewReason}</p>}<div className="commerce-actions"><button className="button" disabled={busy} onClick={()=>void download('/me/templates/'+detail.id+'/versions/'+version.id+'/package',detail.slug+'-'+version.version+'.zip')}><Download size={16} aria-hidden="true"/>{demo?'Explain sample package':'Download your package'}</button>{canSubmitVersion(version)&&!['ARCHIVED','SUSPENDED'].includes(detail.status)&&<button className="button primary" disabled={busy} onClick={()=>show('submit:'+version.id)}>Submit version for review</button>}</div></article>)}</section>
     {!['ARCHIVED','SUSPENDED'].includes(detail.status)&&<section className="commerce-section"><div className="commerce-section-heading"><div><p className="commerce-kicker">A new version, a fresh review</p><h2>Upload a release</h2></div><Upload size={22} aria-hidden="true"/></div><p className="commerce-muted">ZIP up to 5 MiB; expanded files up to 25 MiB, 500 entries. Include a README, license and third-party notices, and a supported build manifest. No credentials, binaries, nested archives or unsafe paths. Packages are never executed.</p><PackageForm demo={demo} busy={busy} onSave={upload}/></section>}
    </div>}</div>}
   </TabsContent>
   <TabsContent value="purchases"><div className="commerce-section-heading"><div><p className="commerce-kicker">Your license library</p><h2>Purchased source</h2><p>The version, license and package digest below are the immutable record of each purchase.</p></div><button className="button" disabled={busy} onClick={()=>void load()}>Refresh purchases</button></div>{demo&&actor==='BUYER'&&<section className="commerce-section commerce-preview-purchase"><p className="commerce-kicker">Try the consent flow</p><h3>Approval portal starter · ₹4,900</h3><p>Review a sample license, then simulate a test capture. No money moves and real source stays unavailable.</p><button className="button primary" disabled={busy||preview!.purchases().some(item=>item.templateId==='sample-template-portal')} onClick={()=>show('sample-buy')}>Review sample license</button></section>}
    {!purchases.items.length?<div className="commerce-empty"><BookOpen size={30} aria-hidden="true"/><h3>Your licenses will live here.</h3><p>Browse a reviewed template, accept the license and complete a server-verified purchase.</p><Link className="button" href="/templates">Explore source templates</Link></div>:<div className="commerce-purchases">{purchases.items.map(item=><article className="commerce-section" key={item.id} data-testid="template-purchase"><div className="commerce-row-heading"><div><p className="commerce-kicker">Version {item.version} · {item.mode==='live'?'Live purchase':'Test / sample purchase'}</p><h3>{item.title}</h3></div><span className="commerce-badge">{templateStatus(item.status)}</span></div><dl className="commerce-facts"><div><dt>Purchase amount</dt><dd>{templatePrice(item.amountMinor)}</dd></div><div><dt>Provider refund</dt><dd>{templatePrice(item.refundedMinor)}</dd></div><div><dt>Recorded</dt><dd>{templateDate(item.createdAt)}</dd></div></dl><details><summary>Purchased license terms</summary><p className="commerce-prose">{item.licenseTerms}</p></details><p className="commerce-digest"><strong>Purchased package SHA-256</strong><code>{item.sha256||'Not yet assigned'}</code></p>{item.dispute&&<p className="commerce-notice"><strong>Concern: {templateStatus(item.dispute.status)}</strong><br/>{item.dispute.reason}</p>}{!eligibleTemplateDownload(item)&&<p className="commerce-muted">{item.mode!=='live'?'Test and sample captures do not grant real source downloads.':'Download is currently unavailable. Refunds, open disputes, account eligibility and package suspension can pause access.'}</p>}<div className="commerce-actions"><button className="button primary" disabled={busy||!eligibleTemplateDownload(item)} onClick={()=>void download('/template-purchases/'+item.id+'/download','getlancer-'+item.version+'.zip')}><Download size={16} aria-hidden="true"/>Download purchased source</button>{!demo&&<button className="button" disabled={busy} onClick={()=>act(()=>post('/template-purchases/'+item.id+'/reconcile'),'Provider payment state refreshed.')}>Refresh provider status</button>}{templateDisputeAvailable(item)&&<button className="button" disabled={busy} onClick={()=>show('dispute:'+item.id)}>Raise a purchase concern</button>}</div></article>)}<PageControls page={purchases} busy={busy} name="purchases" onPage={page=>void load(selected,owned.page,page)}/></div>}
   </TabsContent>
  </Tabs>}
  <Dialog open={!!dialog} onOpenChange={value=>{if(!value&&!busy)setDialog('');}}><DialogContent className="commerce-dialog" onCloseAutoFocus={event=>{event.preventDefault();opener.current?.focus();}}><DialogHeader><DialogTitle>{dialog==='create'?'Create a source template':dialog.startsWith('submit:')?'Submit this version for review':dialog==='archive'?'Archive this listing':dialog==='sample-buy'?'Review the sample license':'Raise a purchase concern'}</DialogTitle><DialogDescription>{dialog==='create'?'Start with your approved public proof project. Package review happens separately for each release.':dialog.startsWith('submit:')?'Repository evidence, rights consent and package review are required before buyers can access this release.':dialog==='archive'?'Discovery and new purchases stop. Eligible existing purchases keep the version they bought.':dialog==='sample-buy'?'Frontend-only exercise. No gateway or source archive is contacted.':'Describe the issue. Opening a concern pauses source delivery and does not automatically issue a refund.'}</DialogDescription></DialogHeader>
   {dialog==='create'&&<TeamForm label="Create template draft" busy={busy} onSave={create}><Field name="productId" label="Approved public proof project" options={[{value:'',label:'Select your project'},...products.map(item=>({value:item.id,label:item.title}))]}/><Field name="title" label="Template title" minLength={3} maxLength={100}/><Field name="summary" label="Short summary" type="textarea" minLength={10} maxLength={240}/><Field name="description" label="What is included?" type="textarea" minLength={20} maxLength={12000}/><Field name="price" label="Price (INR)" minLength={1} maxLength={15}/><Field name="licenseTerms" label="License terms" type="textarea" minLength={40} maxLength={8000}/><p className="commerce-muted">Every license permits one commercial end product, modification for that project, and prohibits source redistribution as a competing template.</p></TeamForm>}
   {dialog.startsWith('submit:')&&detail&&<ConsentAction busy={busy} label="Confirm rights & submit version" consentLabel="I own this source or have permission to distribute every included file under the listing’s license. My ownership evidence and third-party notices are current." onSave={consent=>submit(detail.versions!.find(item=>item.id===dialog.split(':')[1])!,consent)}/>}
   {dialog==='archive'&&<TeamForm busy={busy} label="Archive source listing" onSave={archive}><p>The purchased license and package are immutable. To release new source, upload a new version before archiving this listing.</p></TeamForm>}
   {dialog.startsWith('dispute:')&&<TeamForm busy={busy} label="Record purchase concern" onSave={dispute}><Field name="reason" label="Describe the purchase concern" type="textarea" minLength={20} maxLength={2000}/></TeamForm>}
   {dialog==='sample-buy'&&preview&&<><p className="commerce-license-text">{preview.list().find(item=>item.id==='sample-template-portal')?.licenseTerms}</p><ConsentAction busy={busy} label="Accept sample license & simulate capture" consentLabel="I have read and accept this sample license for one commercial end product." onSave={async()=>{await change(()=>preview.buy('sample-template-portal'),'Test capture simulated locally. No money moved; real source downloads remain disabled.');setDialog('');}}/></>}
  </DialogContent></Dialog>
 </WorkspaceFrame>;
}

export async function uploadPackage(path:string,body:FormData){const response=await fetch('/api/v1'+path,{method:'POST',credentials:'same-origin',headers:{'X-Requested-With':'getlancer'},body});const data=await response.json().catch(()=>({}));if(!response.ok)throw new ApiError(data.error?.message||'The private package could not be uploaded.',data.error?.code||'UPLOAD_FAILED',response.status,data.error?.requestId,data.error?.fieldErrors||{});return data;}

function PackageForm({demo,busy,onSave}:{demo:boolean;busy:boolean;onSave:(data:FormData)=>Promise<unknown>}){
 const id=useId(),[pending,setPending]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState<Record<string,string>>({}),summary=useRef<HTMLParagraphElement>(null);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);data.set('rightsConsent',data.get('rightsConsent')==='on'?'true':'false');setPending(true);setError('');setFields({});try{const file=data.get('file');if(!demo&&(!(file instanceof File)||file.size===0))throw new ApiError('Select a source ZIP.','ZIP_REQUIRED',400,undefined,{file:'Select a non-empty source ZIP.'});if(!demo&&file instanceof File&&file.size>5*1024*1024)throw new ApiError('The compressed ZIP must be at most 5 MiB.','ZIP_TOO_LARGE',400,undefined,{file:'Choose a ZIP up to 5 MiB.'});await onSave(data);form.reset();}catch(problem){const issue=problem as Error&{fieldErrors?:Record<string,string>};setError(issue.message);setFields(issue.fieldErrors||{});requestAnimationFrame(()=>{const target=[...form.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input,textarea')].find(input=>issue.fieldErrors?.[input.name]);(target||summary.current)?.focus();});}finally{setPending(false);}}
 const invalid=(name:string)=>({'aria-invalid':fields[name]?true:undefined,'aria-describedby':fields[name]?id+'-'+name+'-error':undefined});
 return <form className="commerce-package-form" onSubmit={submit}><fieldset disabled={busy||pending}><label className="commerce-field" htmlFor={id+'-version'}>Version number<input id={id+'-version'} name="version" required maxLength={40} pattern="[A-Za-z0-9][A-Za-z0-9._+\-]*" placeholder="1.0.0" {...invalid('version')}/>{fields.version&&<span id={id+'-version-error'} className="team-error">{fields.version}</span>}</label><label className="commerce-field" htmlFor={id+'-notes'}>Release notes<textarea id={id+'-notes'} name="releaseNotes" required minLength={10} maxLength={4000} {...invalid('releaseNotes')}/>{fields.releaseNotes&&<span id={id+'-releaseNotes-error'} className="team-error">{fields.releaseNotes}</span>}</label>{demo?<p className="commerce-notice sample">The preview simulates package metadata. No file is selected, read or uploaded.</p>:<label className="commerce-field" htmlFor={id+'-file'}>Private source ZIP<input type="file" id={id+'-file'} name="file" accept=".zip,application/zip" required {...invalid('file')}/>{fields.file&&<span id={id+'-file-error'} className="team-error">{fields.file}</span>}</label>}<label className="commerce-consent"><input name="rightsConsent" type="checkbox" required {...invalid('rightsConsent')}/><span>I have the rights to distribute this source and its dependencies under my license. The package includes the required notices.</span></label>{fields.rightsConsent&&<span id={id+'-rightsConsent-error'} className="team-error">{fields.rightsConsent}</span>}{error&&<p tabIndex={-1} ref={summary} className="commerce-notice error" role="alert">{error}</p>}<button className="button primary">{pending?'Uploading privately…':demo?'Simulate private version upload':'Upload private version'}</button></fieldset></form>;
}

function ConsentAction({busy,label,consentLabel,onSave}:{busy:boolean;label:string;consentLabel:string;onSave:(consent:boolean)=>Promise<unknown>}){
 const [consent,setConsent]=useState(false),[error,setError]=useState(''),summary=useRef<HTMLParagraphElement>(null);
 return <form className="commerce-consent-form" onSubmit={async event=>{event.preventDefault();if(!consent)return;setError('');try{await onSave(consent);}catch(problem){setError((problem as Error).message);requestAnimationFrame(()=>summary.current?.focus());}}}><label className="commerce-consent"><input type="checkbox" required disabled={busy} checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>{consentLabel}</span></label>{error&&<p tabIndex={-1} ref={summary} className="commerce-notice error" role="alert">{error}</p>}<button className="button primary" disabled={busy||!consent}>{busy?'Saving…':label}</button></form>;
}
function PageControls<T>({page,busy,name,onPage}:{page:TemplatePage<T>;busy:boolean;name:string;onPage:(value:number)=>void}){if(page.totalPages<=1)return null;return <nav className="commerce-pagination" aria-label={name+' pages'}><button className="button" disabled={busy||page.page===0} onClick={()=>onPage(page.page-1)}>Previous</button><span>{page.page+1} / {page.totalPages}</span><button className="button" disabled={busy||!page.hasMore} onClick={()=>onPage(page.page+1)}>Next</button></nav>;}
