'use client';

import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowUpRight,Check,Code2,FileCheck2,PackageCheck,Search,ShieldCheck} from 'lucide-react';
import {Card,CardContent} from '@/components/ui/card';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {api} from '@/lib/api';
import {canOpenTemplateCheckout,loadTemplateCheckout,templateFilterParams,templatePrice,templateStatus,type SourceTemplate,type TemplateFilters,type TemplateOrder} from '@/lib/templates';
import '@/app/templates.css';

export function TemplateCatalog({items,preview,filters,page,totalPages,totalItems}:{items:SourceTemplate[];preview:boolean;filters:TemplateFilters;page:number;totalPages:number;totalItems:number}){
 const categories=[...new Set(items.map(item=>item.category).concat(filters.category?[filters.category]:[]))],technologies=[...new Set(items.map(item=>item.technology).concat(filters.technology?[filters.technology]:[]))];
 return <main id="main" className="commerce-public">
  <div className="commerce-catalog-head"><div><p className="eyebrow">Source marketplace</p><h1>A head start, with the source.</h1><p>Explore reviewed releases from approved builders. Read the license and inspect the project proof before buying.</p></div><Link className="button" href={preview?'/preview/templates':'/workspace/templates'}>Your templates & purchases <ArrowUpRight size={16} aria-hidden="true"/></Link></div>
  {preview&&<p className="commerce-notice sample" role="status"><Code2 size={18} aria-hidden="true"/><span>Frontend preview · Sample listings and license flows. No real sellers, payments or source downloads.</span></p>}
  <form method="get" action="/templates" className="commerce-filters" role="search" aria-label="Search source templates"><label className="commerce-search"><span>Search templates</span><div><Search size={18} aria-hidden="true"/><input type="search" name="q" defaultValue={filters.q} maxLength={100} placeholder="A project, a stack, a starting point…"/></div></label><label>Category<select name="category" defaultValue={filters.category}><option value="">All categories</option>{categories.map(value=><option key={value} value={value}>{templateStatus(value)}</option>)}</select></label><label>Technology<select name="technology" defaultValue={filters.technology}><option value="">All technologies</option>{technologies.map(value=><option key={value} value={value}>{templateStatus(value)}</option>)}</select></label><button className="button primary">Find templates</button>{(filters.q||filters.category||filters.technology)&&<Link href="/templates" className="button">Clear filters</Link>}</form>
  <div className="commerce-results"><p>{totalItems} {totalItems===1?'template':'templates'}{filters.q?' matching “'+filters.q+'”':''}</p><span><ShieldCheck size={15} aria-hidden="true"/>{preview?'Sample review statuses':'Approved packages only'}</span></div>
  {items.length?<div className="commerce-cards">{items.map(item=><Card className="commerce-card" key={item.id}><CardContent><div className="commerce-package-art" aria-hidden="true"><div className="commerce-package-window"><div><i/><i/><i/><span>{item.technology.replaceAll('_',' ')}</span></div><Code2 size={34}/><span>{item.title}</span><small>{item.version?'Release '+item.version:'Source package'}</small></div></div><div className="commerce-card-heading"><span className="commerce-kicker">{templateStatus(item.category)}</span><span className="commerce-badge">{preview?'Sample release':'Reviewed release'}</span></div><h2><Link href={'/templates/'+item.slug}>{item.title}</Link></h2><p>{item.summary}</p><div className="commerce-card-byline"><span>{item.sellerName}</span><strong>{templatePrice(item.priceMinor)}</strong></div><Link href={'/templates/'+item.slug} className="commerce-card-link">View release & license <ArrowUpRight size={17} aria-hidden="true"/></Link></CardContent></Card>)}</div>:<section className="commerce-empty"><Search size={28} aria-hidden="true"/><h2>{filters.q||filters.category||filters.technology?'No releases match these filters.':'The first releases are on their way.'}</h2><p>{filters.q||filters.category||filters.technology?'Try a broader search or clear the filters.':'Reviewed source packages will appear here once an eligible builder submits a release and an operator approves it.'}</p><Link className="button" href={filters.q||filters.category||filters.technology?'/templates':preview?'/preview/templates':'/workspace/templates'}>{filters.q||filters.category||filters.technology?'Clear filters':'Open template workspace'}</Link></section>}
  {totalPages>1&&<nav className="commerce-pagination" aria-label="Template pages">{page>0&&<Link className="button" href={'/templates?'+templateFilterParams(filters,page-1)}>Previous page</Link>}<span>Page {page+1} of {totalPages}</span>{page+1<totalPages&&<Link className="button" href={'/templates?'+templateFilterParams(filters,page+1)}>Next page</Link>}</nav>}
  <div className="commerce-trust-strip"><span><FileCheck2 size={20} aria-hidden="true"/>Versioned release & license</span><span><PackageCheck size={20} aria-hidden="true"/>Private source delivery</span><span><ShieldCheck size={20} aria-hidden="true"/>Ownership evidence & package review</span></div>
 </main>;
}

export function TemplateDetailView({template,preview}:{template:SourceTemplate;preview:boolean}){
 const [open,setOpen]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[order,setOrder]=useState<TemplateOrder|null>(null);
 const key=useRef(''),alive=useRef(true),summary=useRef<HTMLParagraphElement>(null),opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);useEffect(()=>{if(error)summary.current?.focus();},[error]);
 async function reconcile(){if(!order||preview)return;setBusy(true);setError('');try{const purchase=await api('/template-purchases/'+order.id+'/reconcile',{method:'POST',body:'{}'});setOrder(previous=>previous?{...previous,status:purchase.status}:previous);setNote('Provider status: '+templateStatus(purchase.status)+'. Your purchase history shows the current download eligibility.');}catch(problem){setError((problem as Error).message);}finally{setBusy(false);}}
 async function checkout(){
  if(!consent||preview||!canOpenTemplateCheckout(template)||!template.versionId)return;setBusy(true);setError('');setNote('');
  try{
   key.current||=crypto.randomUUID();const result:TemplateOrder=await api('/templates/'+template.id+'/orders',{method:'POST',headers:{'Idempotency-Key':key.current},body:JSON.stringify({versionId:template.versionId,licenseConsent:true})});setOrder(result);
   if(result.status!=='ORDER_CREATED'||!result.orderId||!result.keyId){setOpen(false);setBusy(false);setNote('Purchase status: '+templateStatus(result.status)+'. Refresh the provider state before starting another checkout.');return;}
   const Gateway=await loadTemplateCheckout();if(!alive.current)return;setOpen(false);if(result.mode==='test')setNote('Razorpay test checkout is active. Test capture never unlocks real source.');
   const gateway=new Gateway({key:result.keyId,order_id:result.orderId,amount:result.amountMinor,currency:result.currency,name:result.mode==='test'?'getLancer · test checkout':'getLancer',description:template.title+' · '+template.version,
    handler:async(payload:{razorpay_payment_id:string;razorpay_signature:string})=>{try{const purchase=await api('/template-purchases/'+result.id+'/verify',{method:'POST',body:JSON.stringify({razorpay_payment_id:payload.razorpay_payment_id,razorpay_signature:payload.razorpay_signature})});if(alive.current){setOrder({...result,status:purchase.status});setNote('Server-verified purchase status: '+templateStatus(purchase.status)+'. Open your purchase history for the frozen license and download eligibility.');}}catch(problem){if(alive.current)setError((problem as Error).message+' Reconcile this purchase before retrying.');}finally{if(alive.current)setBusy(false);}},
    modal:{ondismiss:()=>{if(alive.current){setBusy(false);setNote('Checkout closed. Reconcile the purchase if you completed payment.');}}},theme:{color:'#2563eb'}});
   gateway.on('payment.failed',payload=>{if(alive.current){setBusy(false);setNote(payload.error?.description||'Payment was not completed. Reconcile before retrying.');}});gateway.open();
  }catch(problem){if(alive.current){setError((problem as Error).message);setBusy(false);}}
 }
 return <main id="main" className="commerce-public commerce-detail"><Link className="commerce-back" href="/templates"><ArrowLeft size={17} aria-hidden="true"/>All source templates</Link>{preview&&<p className="commerce-notice sample">Frontend preview · This is a sample listing. No source package or payment provider is available.</p>}
  <div className="commerce-detail-grid"><div><p className="eyebrow">{templateStatus(template.category)} / {template.technology.replaceAll('_',' ')}</p><h1>{template.title}</h1><p className="commerce-lede">{template.summary}</p><div className="commerce-detail-proof"><Code2 size={44} aria-hidden="true"/><div><strong>Versioned source package</strong><span>{template.technology.replaceAll('_',' ')} · {template.version||'Release unavailable'}</span></div><PackageCheck size={24} aria-hidden="true"/></div><section className="commerce-section"><h2>What you’re starting with</h2><p className="commerce-prose">{template.description}</p>{template.productSlug&&<Link className="button" href={'/products/'+template.productSlug}>See the builder’s project proof <ArrowUpRight size={16} aria-hidden="true"/></Link>}</section><section className="commerce-section"><h2>Release notes</h2><p className="commerce-prose">{template.releaseNotes||'No release notes available.'}</p>{(template.versions?.length||0)>1&&<details><summary>Earlier reviewed versions</summary>{template.versions?.filter(version=>version.id!==template.versionId).map(version=><article key={version.id}><h3>{version.version}</h3><p className="commerce-prose">{version.releaseNotes}</p></article>)}</details>}</section><section className="commerce-section" id="template-license"><h2>Your license</h2><p className="commerce-prose">{template.licenseTerms}</p><p className="commerce-muted">The purchased version, package digest, price and license are frozen in your purchase record. Ownership verification records repository evidence; it is not a copyright warranty.</p></section></div>
  <aside className="commerce-checkout-card">{template.educationProduct&&<p className="commerce-notice">{template.educationProjectSlug?<Link className="button" href={'/college-projects/'+template.educationProjectSlug}>Review the college package & license ↗</Link>:'This college source requires an approved education release before purchase.'}</p>}<span className="commerce-badge"><ShieldCheck size={14} aria-hidden="true"/>{preview?'Sample approved release':'Approved release'}</span><h2>{templatePrice(template.priceMinor)}</h2><p>INR · One commercial end product</p><dl className="commerce-facts"><div><dt>Seller</dt><dd>{template.sellerName}</dd></div><div><dt>Version</dt><dd>{template.version||'Unavailable'}</dd></div><div><dt>Delivery</dt><dd>Private ZIP after eligible live capture</dd></div></dl><ul className="commerce-benefits"><li><Check size={16} aria-hidden="true"/>Modify for your licensed project</li><li><Check size={16} aria-hidden="true"/>Version and terms pinned at purchase</li><li><Check size={16} aria-hidden="true"/>Review history and raise a concern</li></ul>{preview?<Link className="button primary" href="/preview/templates?tab=purchases">Try the sample purchase flow</Link>:<button className="button primary" disabled={busy||!canOpenTemplateCheckout(template)} onClick={()=>{opener.current=document.activeElement as HTMLElement;setConsent(false);setError('');setOpen(true);}}>{busy?'Confirming purchase…':'Review license & buy'}</button>}<p className="commerce-muted">Razorpay supports available payment methods for the merchant account. Test payments never unlock real source.</p>{error&&<p ref={summary} tabIndex={-1} className="commerce-notice error" role="alert">{error}</p>}{note&&<p className="commerce-notice" role="status">{note}</p>}{order&&<div className="commerce-recovery"><span>Purchase {templateStatus(order.status)}</span><button className="button" disabled={busy} onClick={()=>void reconcile()}>Refresh provider status</button></div>}<Link className="commerce-text-link" href="/workspace/templates?tab=purchases">Your purchase history <ArrowUpRight size={15} aria-hidden="true"/></Link></aside></div>
  <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value);}}><DialogContent className="commerce-dialog" onCloseAutoFocus={event=>{event.preventDefault();opener.current?.focus();}}><DialogHeader><DialogTitle>Review your license</DialogTitle><DialogDescription>{template.title} · Version {template.version} · {templatePrice(template.priceMinor)}</DialogDescription></DialogHeader><div className="commerce-license-text">{template.licenseTerms}</div><label className="commerce-consent"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/><span>I have read and accept this version’s license. It permits one commercial end product and prohibits redistribution as a competing template.</span></label><p className="commerce-muted">The server fixes the version, price and license before opening Razorpay. A completed checkout must still be verified.</p>{error&&<p className="commerce-notice error" role="alert">{error}</p>}<button className="button primary" disabled={busy||!consent} onClick={()=>void checkout()}>{busy?'Preparing checkout…':'Accept license & continue to payment'}</button><Link className="commerce-text-link" href="/login">Sign in if your session has expired</Link></DialogContent></Dialog>
 </main>;
}
