'use client';

import {useEffect,useRef,useState} from 'react';
import {Download,FileCheck2,ShieldCheck} from 'lucide-react';
import {api} from '@/lib/api';
import {downloadTemplateSource,templatePrice,templateStatus,type SourceTemplate,type TemplatePage,type TemplatePurchase,type TemplateVersion} from '@/lib/templates';
import type {createTemplatePreview} from '@/lib/template-preview';
import {Field,TeamForm} from './workspace-form';
import '@/app/templates.css';

export default function TemplateOperations({demo=false,previewStore,onChanged}:{demo?:boolean;previewStore?:ReturnType<typeof createTemplatePreview>;onChanged?:()=>void}){
 const [expanded,setExpanded]=useState(demo),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[templates,setTemplates]=useState<SourceTemplate[]>([]),[attention,setAttention]=useState<TemplatePurchase[]>([]),summary=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{if(error)summary.current?.focus();},[error]);
 async function load(){setBusy(true);setError('');try{if(demo&&previewStore){setTemplates(previewStore.list());setAttention(previewStore.purchases().filter(item=>item.dispute||['UNKNOWN','CREATING','DISPUTED'].includes(item.status)));}else{const all=async<T,>(path:string)=>{let page=0,more=true;const items:T[]=[];while(more){const response:TemplatePage<T>=await api(path+'?page='+page+'&size=50');items.push(...response.items);more=response.hasMore===true;page++;}return items;};const [records,purchases]=await Promise.all([all<SourceTemplate>('/admin/templates'),all<TemplatePurchase>('/admin/template-purchases/attention')]);setTemplates(records);setAttention(purchases);}setLoaded(true);}catch(problem){setTemplates([]);setAttention([]);setLoaded(false);setError((problem as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(demo)void load();},[]);
 async function save(path:string,body:unknown){setBusy(true);setError('');setNote('');try{await api(path,{method:'POST',body:JSON.stringify(body)});await load();setNote('Operator decision recorded. Provider state and entitlement are still verified independently.');onChanged?.();}catch(problem){setError((problem as Error).message);throw problem;}finally{setBusy(false);}}
 async function review(template:SourceTemplate,version:TemplateVersion,body:Record<string,string>){
  if(demo&&previewStore){setBusy(true);try{previewStore.review(template.id,version.id,body.action,body.reason);await load();setNote('Sample review updated locally. No live package or entitlement changed.');onChanged?.();}finally{setBusy(false);}return;}
  await save('/admin/templates/'+template.id+'/versions/'+version.id+'/review',{action:body.action,reason:body.reason,rightsReviewed:body.rightsReviewed==='on',packageReviewed:body.packageReviewed==='on'});
 }
 async function packageDownload(template:SourceTemplate,version:TemplateVersion){setError('');if(demo){setNote('The sample has no source archive. No package request was sent.');return;}setBusy(true);try{await downloadTemplateSource('/admin/templates/'+template.id+'/versions/'+version.id+'/package',template.slug+'-'+version.version+'.zip');setNote('Private review attachment requested. Inspect its source, manifest, README and license notices before deciding.');}catch(problem){setError((problem as Error).message);}finally{setBusy(false);}}
 return <details className="commerce-operations" open={expanded} onToggle={event=>{const value=event.currentTarget.open;if(value!==expanded){setExpanded(value);if(value&&!loaded)void load();}}}><summary><ShieldCheck size={20} aria-hidden="true"/><span>{demo?'Sample operator review & recovery':'Source marketplace review & recovery'}</span></summary><div className="commerce-operations-body"><p className="commerce-muted">These operations require an administrator session with MFA. Review source manually without executing it. Approval records evidence and package checks, not a copyright warranty.</p>{demo&&<p className="commerce-notice sample">Isolated frontend sample. Package downloads and provider reconciliation stay disabled.</p>}<button className="button" disabled={busy} onClick={()=>void load()}>{busy?'Loading operations…':'Refresh source operations'}</button>{error&&<p tabIndex={-1} ref={summary} className="commerce-notice error" role="alert">{error}</p>}{note&&<p className="commerce-notice" role="status">{note}</p>}
  {loaded&&<><section className="commerce-section"><div className="commerce-section-heading"><div><p className="commerce-kicker">Seller rights & immutable source</p><h2>Package review</h2></div><FileCheck2 size={23} aria-hidden="true"/></div>{!templates.length&&<p>No template records are awaiting review.</p>}{templates.map(template=><article className="commerce-operator-record" key={template.id}><h3>{template.title}</h3><p>{template.sellerName} · {templatePrice(template.priceMinor)} · {templateStatus(template.status)}</p><details><summary>Listing scope and license</summary><p className="commerce-prose">{template.description}</p><p className="commerce-prose">{template.licenseTerms}</p></details>{template.versions?.map(version=><section className="commerce-version" key={version.id}><div className="commerce-row-heading"><h4>Version {version.version}</h4><span className="commerce-badge">{templateStatus(version.status)}</span></div><p className="commerce-prose">{version.releaseNotes}</p><p>{version.entryCount??'—'} files · {version.sizeBytes===undefined?'Size pending':Math.ceil(version.sizeBytes/1024)+' KB'}</p>{version.manifestFiles?.length&&<p className="commerce-muted">Build manifests: {version.manifestFiles.join(', ')}</p>}{version.sha256&&<p className="commerce-digest"><strong>Immutable package SHA-256</strong><code>{version.sha256}</code></p>}{version.reviewReason&&<p className="commerce-notice">Previous review: {version.reviewReason}</p>}<button className="button" disabled={busy} onClick={()=>void packageDownload(template,version)}><Download size={16} aria-hidden="true"/>{demo?'Explain sample review package':'Download private review package'}</button>{['PENDING','APPROVED','SUSPENDED'].includes(version.status)&&<TeamForm busy={busy} label={version.status==='APPROVED'?'Record package suspension':'Record package review'} onSave={body=>review(template,version,body)}><Field name="action" label={'Decision for version '+version.version} options={version.status==='APPROVED'?[{value:'SUSPEND',label:'Suspend package and source access'}]:[{value:'',label:'Select a decision'},{value:'APPROVE',label:'Approve reviewed release'},{value:'CHANGES_REQUESTED',label:'Request changes'},{value:'REJECT',label:'Reject release'},{value:'SUSPEND',label:'Suspend package and source access'}]}/><Field name="reason" label={'Review reason for version '+version.version} type="textarea" minLength={10} maxLength={2000}/><label className="commerce-consent"><input name="rightsReviewed" type="checkbox" required/><span>I reviewed current repository ownership evidence, the seller’s rights consent and third-party license notices.</span></label><label className="commerce-consent"><input name="packageReviewed" type="checkbox" required/><span>I inspected this immutable package, README, license and supported build manifest without executing submitted code.</span></label></TeamForm>}</section>)}</article>)}</section>
   <section className="commerce-section"><div className="commerce-section-heading"><div><p className="commerce-kicker">Provider-authoritative state</p><h2>Purchase recovery & concerns</h2></div><ShieldCheck size={23} aria-hidden="true"/></div><p className="commerce-muted">Find interrupted orders in Razorpay by their receipt. Binding checks receipt, amount, currency and payee. Local resolutions do not refund money or clear confirmed provider refund/dispute holds.</p>{!attention.length&&<p>No purchases currently require attention.</p>}{attention.map(purchase=><article className="commerce-operator-record" key={purchase.id}><h3>{purchase.title||'Purchase '+purchase.id}</h3><p>Version {purchase.version} · {templatePrice(purchase.amountMinor)} · {purchase.mode} · {templateStatus(purchase.status)}</p><p className="commerce-digest"><strong>Purchase receipt / ID</strong><code>{purchase.id}</code></p>{purchase.attentionReason&&<p className="commerce-notice">{purchase.attentionReason}</p>}{purchase.dispute&&<p className="commerce-notice"><strong>Concern: {templateStatus(purchase.dispute.status)}</strong><br/>{purchase.dispute.reason}</p>}{demo?<p className="commerce-muted">Sample provider recovery is not performed. Connect a real Java backend and an MFA administrator to reconcile genuine purchase state.</p>:<>{!purchase.orderId?<TeamForm busy={busy} label="Verify & bind provider order" onSave={body=>save('/admin/template-purchases/'+purchase.id+'/bind-order',{orderId:body.orderId})}><Field name="orderId" label="Razorpay order ID" minLength={10} maxLength={40}/></TeamForm>:<><p className="commerce-digest"><strong>Provider order</strong><code>{purchase.orderId}</code></p><button className="button" disabled={busy} onClick={()=>void save('/admin/template-purchases/'+purchase.id+'/reconcile',{}).catch(()=>{})}>Reconcile provider state</button></>}<TeamForm busy={busy} label="Record purchase resolution" onSave={body=>save('/admin/template-purchases/'+purchase.id+'/resolve',{resolution:body.resolution,reason:body.reason})}><Field name="resolution" label="Purchase resolution" options={[{value:'',label:'Select a resolution'},{value:'RESUME',label:'Resume after local concern review'},{value:'REVOKE',label:'Revoke source entitlement'}]}/><Field name="reason" label="Purchase decision reason" type="textarea" minLength={20} maxLength={2000}/><p className="commerce-muted">A resume decision cannot override provider-confirmed refunds or disputes. Downloads also require current account, seller and package eligibility.</p></TeamForm></>}</article>)}</section>
  </>}
 </div></details>;
}
