'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ShieldCheck,Activity,CalendarDays,Layers} from 'lucide-react';
import {api} from '@/lib/api';
import {label} from '@/lib/catalog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';

type Project={id:string;title:string;repository_url:string|null;demo_health:string;demo_checked_at:string|null;verification_status:string|null;challenge?:string;expires_at?:string;reason?:string};
type Data={profile:{availability_status:string;booked_until:string|null;availability_confirmed_at:string|null};activeSlotLimit:number;projects:Project[];awards:{inquiry_id:string;reason:string;created_at:string}[]};
type Queue={verified?:{product_id:string;title:string;repository_url:string}[];verifications:{product_id:string;title:string;repository_url:string;challenge:string}[];eligibleOutcomes:{id:string;display_name:string;title:string}[]};
const sample:Data={profile:{availability_status:'AVAILABLE_NOW',booked_until:null,availability_confirmed_at:null},activeSlotLimit:3,projects:[{id:'stockroom',title:'Stockroom',repository_url:'https://github.com/example/stockroom',demo_health:'UNKNOWN',demo_checked_at:null,verification_status:null},{id:'booklane',title:'Booklane',repository_url:null,demo_health:'UNKNOWN',demo_checked_at:null,verification_status:null}],awards:[]};
const date=(value:string|null|undefined)=>value?new Date(value).toLocaleDateString():'Not yet confirmed';
export default function TrustWorkspace({demo=false}:{demo?:boolean}){
 const [data,setData]=useState<Data|null>(demo?sample:null),[queue,setQueue]=useState<Queue>({verifications:[],eligibleOutcomes:[]}),[admin,setAdmin]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [status,setStatus]=useState('AVAILABLE_NOW'),[until,setUntil]=useState('');
 async function load(){const me=await api('/me');const isAdmin=me.roles.includes('ADMIN');setAdmin(isAdmin);if(isAdmin){setData({profile:{availability_status:'NOT_ACCEPTING',booked_until:null,availability_confirmed_at:null},activeSlotLimit:0,projects:[],awards:[]});setQueue(await api('/admin/trust'));}else{const d=await api('/developer/trust');setData(d);setStatus(d.profile.availability_status);setUntil(d.profile.booked_until||'');}}
 useEffect(()=>{if(!demo)load().catch(e=>setError(e.message));},[demo]);
 async function run(action:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await action();if(!demo)await load();setMessage(demo?'Simulation updated. No live account or external service changed.':'Your changes have been saved.');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function decision(id:string,action:string,reason:string){await run(async()=>{if(demo){setData(old=>old&&({...old,projects:old.projects.map(p=>p.id===id?{...p,verification_status:action==='approve'?'VERIFIED':'REJECTED',reason}:p)}));setQueue(old=>({...old,verifications:old.verifications.filter(v=>v.product_id!==id)}));}else await api('/admin/verifications/'+id+'/'+action,{method:'POST',body:JSON.stringify({reason})});});}
 return <main className="wrap trust-workspace" id="main"><Link className="link" href={demo?'/preview/workspace':'/workspace'}>← Back to workspace</Link><div className="intro"><div><p className="eyebrow">V1.5 · Trust & reliability</p><h1>Let your work earn confidence.</h1><p>Keep your availability current, show evidence, and help clients choose confidently.</p></div><ShieldCheck size={36} aria-hidden="true"/></div>
 {demo&&<div className="samplebar">Interactive V1.5 simulation · Sample records reset when you leave this page. <button className="link" onClick={()=>setAdmin(!admin)}>{admin?'View as builder':'Preview administrator tools'}</button></div>}
 {error&&<p className="error" role="alert">{error} {!data&&<Link className="link" href="/login">Log in</Link>}</p>}{message&&<p className="success" role="status" aria-atomic="true">{message}</p>}
 {!data&&!error&&<p role="status">Loading trust details…</p>}
 {data&&<><div className="trust-metrics">{[[CalendarDays,'Availability',label(data.profile.availability_status)],[ShieldCheck,'Repository evidence',data.projects.filter(p=>p.verification_status==='VERIFIED').length+' reviewed'],[Activity,'Demo monitoring',data.projects.filter(p=>p.demo_checked_at).length+' checked'],[Layers,'Showcase capacity',data.activeSlotLimit+' slots']].map(([Icon,title,value])=>{const I=Icon as typeof Layers;return <div className="panel" key={String(title)}><I size={20} aria-hidden="true"/><p>{String(title)}</p><strong>{String(value)}</strong></div>})}</div>
 <Tabs key={admin?'admin':'builder'} defaultValue={admin?'review':'availability'}><TabsList className="workspace-tabs" variant="line">{(!admin||demo)&&<><TabsTrigger value="availability">Availability</TabsTrigger><TabsTrigger value="evidence">Project evidence</TabsTrigger><TabsTrigger value="capacity">Earned capacity</TabsTrigger></>}{admin&&<TabsTrigger value="review">Administrator review</TabsTrigger>}</TabsList>
 <TabsContent value="availability"><section className="trust-split"><div><h2>Ready for your next project?</h2><p>Availability describes client work. It does not change your showcase capacity.</p><p className="muted">Last confirmed: {date(data.profile.availability_confirmed_at)}</p><h3>Response reliability</h3><p className="muted">Your public profile shows response statistics only after the minimum qualified inquiry sample is reached. Unconfirmed and restricted inquiries are excluded.</p></div><form className="form panel" onSubmit={e=>{e.preventDefault();run(async()=>{if(demo)setData({...data,profile:{availability_status:status,booked_until:status==='BOOKED_UNTIL'?until:null,availability_confirmed_at:new Date().toISOString()}});else await api('/developer/availability',{method:'PUT',body:JSON.stringify({status,bookedUntil:until})});});}}><label htmlFor="availability-status">Current availability</label><select id="availability-status" value={status} onChange={e=>setStatus(e.target.value)}>{['AVAILABLE_NOW','ONE_SLOT_LEFT','LIMITED','BOOKED_UNTIL','NOT_ACCEPTING'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select>{status==='BOOKED_UNTIL'&&<><label htmlFor="booked-until">Booked until</label><input id="booked-until" type="date" required min={new Date().toISOString().slice(0,10)} value={until} onChange={e=>setUntil(e.target.value)}/></>}<button disabled={busy} className="button primary">{busy?'Saving…':'Confirm availability'}</button></form></section></TabsContent>
 <TabsContent value="evidence"><h2>Evidence, with clear boundaries.</h2><p className="muted">Repository review checks your demonstrated control of one repository. Demo health records reachability, not ownership, security or uptime guarantees.</p>{!data.projects.length&&<p className="empty">Create a showcase to add repository evidence.</p>}{data.projects.map(p=><article className="trust-project panel" key={p.id}><div><h3>{p.title}</h3><p>Repository: {label(p.verification_status||'NOT_REQUESTED')}</p><p className="muted">Demo: {label(p.demo_health)} · {p.demo_checked_at?'Last check '+date(p.demo_checked_at):'No check recorded'}</p>{p.reason&&<p>{p.reason}</p>}{p.challenge&&p.verification_status==='PENDING'&&<div className="trust-challenge"><p>Add this exact challenge to your repository README before the administrator reviews it.</p><code>{p.challenge}</code><p className="muted">Expires: {date(p.expires_at)}</p></div>}</div><div className="stack"><button className="button" disabled={busy||!p.repository_url||p.verification_status==='VERIFIED'} onClick={()=>run(async()=>{if(demo){const challenge='getlancer-proof-demo-'+p.id;setData({...data,projects:data.projects.map(x=>x.id===p.id?{...x,challenge,verification_status:'PENDING',expires_at:new Date(Date.now()+604800000).toISOString()}:x)});setQueue(q=>({...q,verifications:[...q.verifications.filter(x=>x.product_id!==p.id),{product_id:p.id,title:p.title,repository_url:p.repository_url!,challenge}]}));}else await api('/developer/products/'+p.id+'/verification',{method:'POST'});})}>Request repository review</button>{!p.repository_url&&<small>Add a GitHub repository in your showcase editor first.</small>}{demo&&<button className="button" disabled={busy} onClick={()=>run(async()=>setData({...data,projects:data.projects.map(x=>x.id===p.id?{...x,demo_health:x.demo_health==='REACHABLE'?'UNREACHABLE':'REACHABLE',demo_checked_at:new Date().toISOString()}:x)}))}>Simulate demo health change</button>}</div></article>)}</TabsContent>
 <TabsContent value="capacity"><h2>Capacity earned through real outcomes.</h2><p>Your current allowance is <strong>{data.activeSlotLimit} active showcases</strong>. Drafts and archives do not use slots.</p><p className="muted">Administrators may award capacity after reviewing a client-confirmed completion. Awards are recorded, cannot be duplicated for the same engagement, and do not buy verification or search position.</p>{data.awards.length?data.awards.map(a=><div className="row" key={a.inquiry_id}><strong>+1 showcase slot</strong><p>{a.reason}</p><span>{date(a.created_at)}</span></div>):<div className="empty">No earned-capacity awards yet.</div>}</TabsContent>
 {admin&&<TabsContent value="review"><h2>Review evidence</h2><p className="muted">Inspect the exact repository README and challenge. Record what you checked before approving. Do not approve your own work.</p>{!queue.verifications.length&&<p>No repository requests waiting.</p>}{queue.verifications.map(v=><form className="form panel" key={v.product_id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);decision(v.product_id,String(f.get('action')),String(f.get('reason')));}}><h3>{v.title}</h3><a className="link" href={v.repository_url} target="_blank" rel="noopener noreferrer">Inspect repository ↗</a><code className="trust-challenge">{v.challenge}</code><label>Review evidence<textarea name="reason" required minLength={10} maxLength={2000}/></label><label>Decision<select name="action"><option value="approve">Approve repository evidence</option><option value="reject">Reject evidence</option></select></label><button className="button primary" disabled={busy}>Save decision</button></form>)}<h2>Reviewed repository evidence</h2>{(demo?data.projects.filter(p=>p.verification_status==='VERIFIED').map(p=>({product_id:p.id,title:p.title,repository_url:p.repository_url!})):queue.verified||[]).map(v=><form className="form panel" key={'verified-'+v.product_id} onSubmit={e=>{e.preventDefault();decision(v.product_id,'revoke',String(new FormData(e.currentTarget).get('reason')));}}><h3>{v.title}</h3><a className="link" href={v.repository_url} target="_blank" rel="noopener noreferrer">Inspect repository ↗</a><label>Reason for revoking evidence<textarea name="reason" required minLength={10} maxLength={2000}/></label><p className="muted">This removes the repository-review label. The showcase remains subject to its existing approval status.</p><button className="button danger" disabled={busy}>Revoke repository evidence</button></form>)}<h2>Earned capacity review</h2>{demo&&<button className="button" onClick={()=>setQueue(q=>({...q,eligibleOutcomes:[{id:'demo-completion',display_name:'Leah Morgan',title:'Stockroom'}]}))}>Load sample client-confirmed completion</button>}{!queue.eligibleOutcomes.length&&<p>No eligible completions awaiting an award.</p>}{queue.eligibleOutcomes.map(o=><form className="form panel" key={o.id} onSubmit={e=>{e.preventDefault();const reason=String(new FormData(e.currentTarget).get('reason'));run(async()=>{if(demo){if(!data.awards.some(a=>a.inquiry_id===o.id))setData({...data,activeSlotLimit:data.activeSlotLimit+1,awards:[...data.awards,{inquiry_id:o.id,reason,created_at:new Date().toISOString()}]});setQueue(q=>({...q,eligibleOutcomes:q.eligibleOutcomes.filter(x=>x.id!==o.id)}));}else await api('/admin/earned-capacity/'+o.id,{method:'POST',body:JSON.stringify({reason})});});}}><h3>{o.display_name} · {o.title}</h3><label>Award reason<textarea name="reason" required minLength={10} maxLength={2000}/></label><button className="button" disabled={busy}>Award one showcase slot</button></form>)}</TabsContent>}
 </Tabs></>}
 </main>;
}
