import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {canonicalDataAiJson,dataAiHash,dataAiCatalogue,parseDataAiIndex,parseDataAiRecording,readDataAiFile,DATA_AI_RECORDING_LIMIT,DATA_AI_RESULT_LIMIT} from '../lib/data-ai.ts';
const indexText=await readFile(new URL('../public/data-ai/material-index.json',import.meta.url),'utf8');
const index=parseDataAiIndex(indexText), recordings=Object.fromEntries(await Promise.all(index.items.map(async item=>[item.id,JSON.parse(await readFile(new URL(`../public${item.recordingUrl}`,import.meta.url),'utf8'))])));
const copy=id=>structuredClone(recordings[id]);
const material=id=>index.items.find(item=>item.id===id);
async function reject(id,mutate){const value=copy(id);await mutate(value);await assert.rejects(parseDataAiRecording(value,index,material(id)));}
async function rehash(run){run.resultSha256=await dataAiHash(run.result);}

test('all four actual source recordings retain their LOCAL identities and distinct default/changed results',async()=>{for(const item of index.items){const actual=await parseDataAiRecording(recordings[item.id],index,item);assert.equal(actual.mode,'REPLAY');assert.equal(actual.runs.length,2);assert.equal(actual.runs[0].mode,'LOCAL');assert.deepEqual(actual.runs[0].input,item.defaultInputs);assert.deepEqual(actual.runs[1].input,item.changedInputs);assert.notEqual(actual.runs[0].inputSha256,actual.runs[1].inputSha256);assert.notEqual(actual.runs[0].resultSha256,actual.runs[1].resultSha256);assert.ok(actual.runs.every(run=>Buffer.byteLength(JSON.stringify(run))<=DATA_AI_RESULT_LIMIT));}});
test('canonical result hashes match Node SHA-256 over recursively sorted bounded numbers',async()=>{const value={z:[.000003,1.0,{b:12,a:.123456}],a:'synthetic'};assert.equal(canonicalDataAiJson(value),'\u007b"a":"synthetic","z":[0.000003,1,{"a":0.123456,"b":12}]\u007d');assert.equal(await dataAiHash(value),createHash('sha256').update(canonicalDataAiJson(value)).digest('hex'));assert.throws(()=>canonicalDataAiJson({a:Infinity}));});
test('index rejects private fields, stale artifacts, repeated scenarios and nonlocal recording URLs',()=>{for(const mutate of [value=>value.privateEmail='private@example.org',value=>value.sourceSha256='a'.repeat(64),value=>value.archiveSha256='a'.repeat(64),value=>value.items[0].dataSha256='a'.repeat(64),value=>value.items[1]=value.items[0],value=>value.items[0].recordingUrl='https://example.org/evidence.json',value=>value.items[2].modelFormat='pickle',value=>value.items[0].inputs[0].choices.push('foreign'),value=>value.items[0].inputs[1].max+=.0000001]){const value=JSON.parse(indexText);mutate(value);assert.throws(()=>parseDataAiIndex(value));}});
test('raw duplicate keys are rejected at root and nested levels even when escapes hide them',async()=>{assert.throws(()=>parseDataAiIndex(indexText.replace('"schemaVersion":','"schemaVersion":"foreign","schemaVersion":')));const value=JSON.stringify(copy('revenue-summary')).replace('"region":"all"','"region":"all","re\\u0067ion":"all"');await assert.rejects(parseDataAiRecording(value,index,material('revenue-summary')),/duplicate/);});
test('wrong scenario, replay/hosted envelopes and foreign run UUIDs are rejected',async()=>{for(const mutate of [v=>v.scenarioId='sentiment-inference',v=>v.mode='LOCAL',v=>v.runs[0].mode='HOSTED',v=>v.runs[0].runId='not-a-uuid',v=>v.runs[1].runId='00000000-0000-4000-8000-000000000099'])await reject('revenue-summary',mutate);});
test('source, dataset, model and evaluation identities cannot drift across recording and result',async()=>{for(const field of ['sourceSha256','dataSha256','modelSha256','evaluationSha256']){await reject('sentiment-inference',v=>v[field]='a'.repeat(64));await reject('sentiment-inference',v=>v.runs[0][field]='a'.repeat(64));}await reject('revenue-summary',v=>v.runs[0].modelSha256='a'.repeat(64));});
test('changed cases cannot substitute foreign private text even after both hashes are recomputed',async()=>{await reject('sentiment-inference',async v=>{v.runs[0].input.text='private interview text';v.runs[0].inputSha256=await dataAiHash(v.runs[0].input);});await reject('equipment-inference',async v=>{v.runs[1].input.temperature='900';v.runs[1].inputSha256=await dataAiHash(v.runs[1].input);});await reject('revenue-summary',async v=>{v.runs[0].input.upliftPercent='00';v.runs[0].inputSha256=await dataAiHash(v.runs[0].input);});});
test('input and result hashes are independently checked and repeating an inference result is rejected',async()=>{await reject('revenue-summary',v=>v.runs[0].inputSha256='a'.repeat(64));await reject('sentiment-inference',v=>v.runs[0].resultSha256='a'.repeat(64));await reject('equipment-inference',v=>{v.runs[1].result=structuredClone(v.runs[0].result);v.runs[1].resultSha256=v.runs[0].resultSha256;});});
test('future, malformed, backward and duration-inconsistent timestamps are rejected',async()=>{for(const mutate of [v=>v.recordedAt='2999-01-01T00:00:00.000Z',v=>v.runs[0].startedAt='2026-01-01',v=>v.runs[1].startedAt='2000-01-01T00:00:00.000Z',v=>v.runs[1].elapsedMs=10001,v=>v.runs[1].startedAt=v.recordedAt,v=>v.runs[0].elapsedMs=-1]){await reject('revenue-summary',value=>{mutate(value);if(value.runs[1].startedAt===value.recordedAt)value.runs[1].elapsedMs=500;});}});
test('exact table/metric labels, types and units cannot be relabelled by imported evidence',async()=>{for(const mutate of [run=>run.result.tables[0].columns[1].unit='USD',run=>run.result.tables[0].title='Certified accuracy',run=>run.result.tables[0].rows[0].revenue='110',run=>run.result.metrics[0].label='Hosted revenue',run=>run.result.metrics[0].unit='USD',run=>run.result.tables[0].rows[0].email='private@example.org'])await reject('revenue-summary',async value=>{mutate(value.runs[0]);await rehash(value.runs[0]);});});
test('analytics totals, row counts and integer INR average must reconcile after rehashing',async()=>{for(const mutate of [run=>run.result.metrics[0].value+=1,run=>run.result.metrics[1].value+=1,run=>run.result.metrics[2].value+=2,run=>run.result.tables[0].rows.pop(),run=>run.result.tables[0].rows[0].orders=3,run=>run.result.prediction={label:'normal',probability:1}])await reject('revenue-summary',async value=>{mutate(value.runs[0]);await rehash(value.runs[0]);});});
test('sensor accepted/rejected counts and percentage must reconcile with bounded original channels',async()=>{for(const mutate of [run=>run.result.tables[0].rows[0].total=3,run=>run.result.tables[0].rows[0].accepted=5,run=>run.result.metrics[2].value+=1,run=>run.result.tables[0].rows[0].channel='private',run=>run.result.evaluation={samples:8}])await reject('sensor-quality',async value=>{mutate(value.runs[0]);await rehash(value.runs[0]);});});
test('inference class probabilities, predicted winner and confidence reconcile',async()=>{for(const mutate of [run=>run.result.tables[0].rows[0].probability=.5,run=>run.result.tables[0].rows[0].class='private',run=>run.result.prediction.label='negative',run=>run.result.prediction.probability=.5,run=>run.result.metrics[0].value=.5])await reject('sentiment-inference',async value=>{mutate(value.runs[0]);await rehash(value.runs[0]);});});
test('held-out accuracy reconciles with samples/correct and fixed evaluation context',async()=>{for(const mutate of [run=>run.result.evaluation.correct=7,run=>run.result.evaluation.samples=9,run=>run.result.evaluation.accuracy=.9,run=>run.result.evaluation.split='training',run=>run.result.evaluation.protocol='remote-model',run=>run.result.evaluation.limitations='Claimed real-world accuracy',run=>run.result.metrics[1].value=.9])await reject('equipment-inference',async value=>{mutate(value.runs[0]);await rehash(value.runs[0]);});});
test('depth, total bytes, envelope bytes, row bounds and numeric precision stay bounded',async()=>{await assert.rejects(parseDataAiRecording(' '.repeat(DATA_AI_RECORDING_LIMIT+1),index,material('revenue-summary')),/byte limit/);await reject('sentiment-inference',v=>v.runs[0].result.evaluation.limitations='x'.repeat(DATA_AI_RESULT_LIMIT));await reject('revenue-summary',async v=>{v.runs[0].result.tables[0].rows=Array(33).fill(v.runs[0].result.tables[0].rows[0]);await rehash(v.runs[0]);});await reject('sentiment-inference',async v=>{v.runs[0].result.prediction.probability=.1234567;await rehash(v.runs[0]);});await assert.rejects(dataAiHash(Array(18).fill(0).reduce(value=>[value],0)),/nesting limit/);});
test('bounded JSON transport rejects HTTP errors, HTML, oversize streams and invalid UTF-8',async()=>{assert.equal(await readDataAiFile(new Response(indexText,{headers:{'content-type':'application/json; charset=utf-8'}}),65536),indexText);await assert.rejects(readDataAiFile(new Response('no',{status:503,headers:{'content-type':'application/json'}}),100),/HTTP 503/);await assert.rejects(readDataAiFile(new Response('<html/>',{headers:{'content-type':'text/html'}}),100),/did not return JSON/);await assert.rejects(readDataAiFile(new Response('x'.repeat(101),{headers:{'content-type':'application/json'}}),100),/byte limit/);await assert.rejects(readDataAiFile(new Response(new Uint8Array([0xc3,0x28]),{headers:{'content-type':'application/json'}}),100));});
test('analytics permits no model or evaluation and catalogue remains unchanged by rejected input',async()=>{assert.equal(material('revenue-summary').modelSha256,null);const before=JSON.stringify(dataAiCatalogue);await reject('sensor-quality',v=>v.runs[0].privateAcademic={institution:'Private'});assert.equal(JSON.stringify(dataAiCatalogue),before);});
