import test from 'node:test';import assert from 'node:assert/strict';import {emptyEducationDraft,educationEvidence,educationDraftBody,educationDraftFrom,educationSubmissionIssues,dataAiEvidenceIssues,dataAiEvidenceBody} from '../lib/education.ts';
function evidence(ai=true){return {codeLicense:'MIT',dataLicense:'MIT',dataProvenance:'Original synthetic data fixture.',dataSha256:'a'.repeat(64),outputSchema:'Exact typed fields with declared units.',limitations:'Tiny illustrative synthetic fixture only.',redistributionAllowed:true,syntheticData:true,noRemoteCode:true,...(ai?{modelLicense:'MIT',modelProvenance:'Original frozen model.',modelSha256:'b'.repeat(64),modelFormat:'JSON',evaluationSplit:'Held-out synthetic fixture.',evaluationProtocol:'Frozen model without training.'}:{})};}
function complete(){const draft=emptyEducationDraft();draft.categoryEvidence=Object.fromEntries(educationEvidence.FULL_STACK.map(([key])=>[key,'Concrete original category evidence.']));for(const key of ['includedAssets','excludedAssets','setupSteps','prerequisites','limitations'])draft.package[key]=['Explicit original package disclosure.'];draft.package.supportTerms='Self-guided learning with no maintenance contract.';draft.package.licenseTerms='MIT License. Preserve permission and copyright notices.';draft.rightsConsent=true;return draft;}
test('each category requires concrete category-specific evidence before submitting',()=>{for(const category of Object.keys(educationEvidence)){const draft=complete();draft.category=category;if(['DATA_ANALYTICS','AI_ML'].includes(category))draft.dataAiEvidence=evidence(category==='AI_ML');draft.categoryEvidence=Object.fromEntries(educationEvidence[category].map(([key])=>[key,'Original evidence with documented limitations.']));assert.deepEqual(educationSubmissionIssues(draft),[]);delete draft.categoryEvidence[educationEvidence[category][0][0]];assert.ok(educationSubmissionIssues(draft).length);}});
test('FREE and PAID distribution require separate exact source bindings',()=>{const draft=complete();draft.mode='FREE';assert.match(educationSubmissionIssues(draft).join(' '),/Upload/);assert.deepEqual(educationSubmissionIssues(draft,{packageId:'original-private-package'}),[]);draft.mode='PAID';assert.match(educationSubmissionIssues(draft).join(' '),/approved source version/);draft.versionId='owned-approved-version';assert.deepEqual(educationSubmissionIssues(draft),[]);});
test('draft serialization permits incomplete values without leaking frozen proofs or other category fields',()=>{const draft=emptyEducationDraft();draft.categoryEvidence={schemaApi:'Unfinished',metrics:'Other category'};draft.versionId='old-paid-version';const copy=educationDraftBody(draft);assert.equal(copy.categoryEvidence.schemaApi,'Unfinished');assert.equal(copy.categoryEvidence.metrics,undefined);assert.equal(copy.versionId,undefined);assert.equal(copy.rightsConsent,false);assert.equal(draft.categoryEvidence.metrics,'Other category');});
test('fresh corrected drafts omit source hash, academic annotations and component proof fields',()=>{const draft=complete(),release={revision:7,snapshot:{...draft,componentLinks:[{componentId:'00000000-0000-4000-8000-000000000001',revision:2,attribution:'Original MIT attribution.',license:'MIT',sha256:'proof',creator:'Private name',slug:'current'}],sourceBinding:{versionId:'exact-version'}},academic:{institution:'Private',revision:3},sourceHash:'frozen'};const copy=educationDraftFrom(release);assert.equal(copy.revision,7);assert.equal(copy.versionId,'exact-version');assert.deepEqual(copy.componentLinks,[{componentId:'00000000-0000-4000-8000-000000000001',revision:2,license:'MIT',attribution:'Original MIT attribution.'}]);assert.equal(copy.academic,undefined);assert.equal(copy.sourceHash,undefined);assert.equal(copy.rightsConsent,false);});
test('insecure external demonstrations and incomplete reusable component attribution block submission',()=>{const draft=complete();draft.demoMode='EXTERNAL';draft.demoUrl='http://127.0.0.1';assert.match(educationSubmissionIssues(draft).join(' '),/HTTPS/);draft.demoUrl='https://example.org/demo';draft.componentLinks=[{componentId:'bad',revision:0,attribution:''}];assert.match(educationSubmissionIssues(draft).join(' '),/exact UUID/);});

test('new analytics and AI submissions require exact separate rights/provenance with synthetic safe flags',()=>{for(const category of ['DATA_ANALYTICS','AI_ML']){assert.ok(Object.keys(dataAiEvidenceIssues(category)).length);const safe=evidence(category==='AI_ML');assert.deepEqual(dataAiEvidenceIssues(category,safe),{});for(const key of ['codeLicense','dataLicense','dataProvenance','dataSha256','outputSchema','limitations','redistributionAllowed','syntheticData','noRemoteCode']){const value={...safe};delete value[key];assert.ok(dataAiEvidenceIssues(category,value)[key]);}if(category==='AI_ML')for(const key of ['modelLicense','modelProvenance','modelSha256','modelFormat','evaluationSplit','evaluationProtocol']){const value={...safe};delete value[key];assert.ok(dataAiEvidenceIssues(category,value)[key]);}}});
test('analytics evaluation is optional while unsafe optional model metadata remains invalid',()=>{const safe=evidence(false);assert.deepEqual(dataAiEvidenceIssues('DATA_ANALYTICS',safe),{});for(const [key,value] of [['modelFormat','pickle'],['modelSha256','BAD'],['dataSha256','A'.repeat(64)],['dataProvenance','x'.repeat(4001)],['syntheticData','true'],['noRemoteCode',false]])assert.ok(dataAiEvidenceIssues('DATA_ANALYTICS',{...safe,[key]:value})[key]);});
test('partial drafts preserve exact optional evidence fields and never copy private or frozen additions',()=>{const draft=emptyEducationDraft();draft.category='AI_ML';draft.dataAiEvidence={codeLicense:'MI',dataSha256:'',redistributionAllowed:false,modelFormat:'',privateAcademic:{college:'Private'},sourceHash:'server-owned',creatorEmail:'private@example.org'};const body=educationDraftBody(draft);assert.deepEqual(body.dataAiEvidence,{codeLicense:'MI',dataSha256:'',modelFormat:'',redistributionAllowed:false});assert.ok(educationSubmissionIssues(draft).length);assert.deepEqual(dataAiEvidenceBody(draft.dataAiEvidence),body.dataAiEvidence);assert.equal(draft.dataAiEvidence.privateAcademic.college,'Private');});
test('historical absent evidence stays absent and correction retains mutable provenance without server proofs',()=>{const draft=complete(),release={revision:8,snapshot:{...draft,category:'AI_ML'}};assert.equal(educationDraftFrom(release).dataAiEvidence,undefined);release.snapshot.dataAiEvidence={...evidence(),sourceHash:'frozen-proof',institution:'Private'};const corrected=educationDraftFrom(release);assert.deepEqual(corrected.dataAiEvidence,evidence());assert.equal(corrected.rightsConsent,false);assert.equal(corrected.dataAiEvidence.sourceHash,undefined);});
test('non-data categories reject supplied structured evidence while an unselected draft can retain it',()=>{for(const category of ['FULL_STACK','IOT'])assert.ok(dataAiEvidenceIssues(category,evidence()).dataAiEvidence);assert.deepEqual(dataAiEvidenceIssues('',{codeLicense:'Partial'}),{});assert.deepEqual(dataAiEvidenceIssues('FULL_STACK'),{});});
