import test from 'node:test';
import assert from 'node:assert/strict';
import {createMaintenancePreview} from '../lib/maintenance.ts';
const now=new Date('2026-10-03T05:00:00Z');
const body={title:'Correct approval routing',description:'The second approval step should notify the assigned reviewer.'};
function accepted(){const p=createMaintenancePreview(now),id=p.list()[0].id;p.offerAction(id,'send',true);p.setSide('BUYER');p.offerAction(id,'accept',true);return {p,id};}
function paid(){const {p,id}=accepted();p.simulateBilling(id,true);return {p,id};}
test('local care exercise never contacts the network, copies state and separates both consents from billing',()=>{const fetch=globalThis.fetch;globalThis.fetch=()=>{throw Error('Unexpected network request');};try{const p=createMaintenancePreview(now),id=p.list()[0].id;assert.throws(()=>p.offerAction(id,'send',false));p.offerAction(id,'send',true);assert.throws(()=>p.offerAction(id,'accept',true));p.setSide('BUYER');assert.throws(()=>p.offerAction(id,'accept',false));p.offerAction(id,'accept',true);assert.equal(p.detail(id).entitlement.available,false);assert.throws(()=>p.simulateBilling(id,false));p.simulateBilling(id,true);const detached=p.detail(id);detached.terms='Changed';assert.notEqual(p.detail(id).terms,'Changed');assert.equal(p.detail(id).billing.mode,'test');assert.throws(()=>p.simulateBilling(id,true));assert.equal(createMaintenancePreview(now).detail(id).billing,null);p.reset();assert.equal(p.detail(id).status,'DRAFT');}finally{globalThis.fetch=fetch;}});
test('support quota counts every request and cancellation preserves the simulated paid period',()=>{const {p,id}=paid();const first=p.request(id,body);p.requestAction(id,first.id,'cancel');assert.equal(p.detail(id).entitlement.remainingRequests,2);p.request(id,body);p.request(id,body);assert.throws(()=>p.request(id,body));p.cancel(id);assert.equal(p.detail(id).billing.cancelConfirmed,true);assert.equal(p.detail(id).entitlement.available,true);assert.equal(p.detail(id).entitlement.remainingRequests,0);p.setSide('SELLER');assert.throws(()=>p.cancel(id));assert.throws(()=>p.request(id,body));});
test('request transitions enforce current side, sequence, reason and HTTPS delivery',()=>{const {p,id}=paid(),r=p.request(id,body);assert.throws(()=>p.requestAction(id,r.id,'start'));p.setSide('SELLER');assert.throws(()=>p.requestAction(id,r.id,'submit',{deliveryNote:'A useful resolution'}));p.requestAction(id,r.id,'start');assert.throws(()=>p.requestAction(id,r.id,'submit',{deliveryNote:'A useful resolution',deliveryUrl:'javascript:alert(1)'}));p.requestAction(id,r.id,'submit',{deliveryNote:'Fixed and checked the approval routing.',deliveryUrl:'https://example.test/changes'});p.setSide('BUYER');assert.throws(()=>p.requestAction(id,r.id,'request-revision',{reason:'x'}));p.requestAction(id,r.id,'request-revision',{reason:'Please include the second reviewer notification.'});p.setSide('SELLER');p.requestAction(id,r.id,'start');p.requestAction(id,r.id,'submit',{deliveryNote:'Included the second reviewer and verified notification.'});p.setSide('BUYER');p.requestAction(id,r.id,'accept');assert.equal(p.detail(id).requests[0].status,'RESOLVED');assert.throws(()=>p.requestAction(id,r.id,'cancel'));assert.equal(p.detail(id).entitlement.usedRequests,1);assert.ok(p.detail(id).activity.length>=8);});
test('draft rejects nonfinite and excessive terms, and accepted terms cannot be withdrawn',()=>{const p=createMaintenancePreview(now),initial=p.list()[0],terms={title:initial.title,scope:initial.scope,terms:initial.terms,amountMinor:initial.amountMinor,requestsPerCycle:3,responseHours:24,totalCycles:12};p.offerAction(initial.id,'withdraw');for(const invalid of [{amountMinor:NaN},{amountMinor:100.1},{requestsPerCycle:51},{responseHours:0},{totalCycles:13},{title:'x'}])assert.throws(()=>p.create(initial.engagementId,{...terms,...invalid}));const created=p.create(initial.engagementId,terms);p.offerAction(created.id,'send',true);p.setSide('BUYER');p.offerAction(created.id,'accept',true);p.setSide('SELLER');assert.throws(()=>p.offerAction(created.id,'withdraw'));});
