package com.getlancer;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.getlancer.commerce.CommerceStorage;
import com.getlancer.commerce.SourceArchive;
import com.getlancer.payments.RazorpayClient;
import com.getlancer.shared.ApiError;
import com.getlancer.shared.Support;
import com.getlancer.testing.TestDatabaseGuard;
import jakarta.servlet.http.Cookie;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

@org.springframework.test.context.ContextConfiguration(initializers=TestDatabaseGuard.class)
@SpringBootTest(properties={"app.environment=local","app.jobs-enabled=false","app.admin-email=admin@example.test","app.admin-password=","app.admin-totp=","spring.config.import=",
  "spring.datasource.url=${TEST_DB_URL:jdbc:postgresql://localhost:5432/getlancer_test}","spring.datasource.username=${TEST_DB_USERNAME:postgres}","spring.datasource.password=${TEST_DB_PASSWORD:}",
  "spring.datasource.hikari.schema=getlancer_test","spring.flyway.default-schema=getlancer_test","spring.flyway.schemas=getlancer_test","app.origin=http://localhost:3000","app.secure-cookie=false","app.storage.access-key=","app.storage.secret-key=","app.education.paid-enabled=false","app.policies-approved=true"})
@AutoConfigureMockMvc
class EducationIntegrationTest {
  @Autowired JdbcTemplate db;
  @Autowired MockMvc mvc;
  @Autowired ObjectMapper json;
  @Autowired PlatformTransactionManager transactions;
  @MockBean CommerceStorage storage;
  @MockBean RazorpayClient provider;
  UUID owner,other,admin,product;
  List<Map<String,Object>> examples;
  Map<String,byte[]> objects=new HashMap<>();
  UUID user(String name){UUID id=UUID.randomUUID();db.update("INSERT INTO users(id,email,password_hash,email_verified_at) VALUES(?,?,'unused',now())",id,name+"@example.test");db.update("INSERT INTO user_roles(user_id,role) VALUES(?,'CLIENT'),(?,'DEVELOPER')",id,id);db.update("INSERT INTO developer_profiles(user_id,slug,display_name,approval_status) VALUES(?,?,?,'APPROVED')",id,name,name);db.update("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,now()+interval '1 hour')",Support.hash(name),id);db.update("INSERT INTO showcase_entitlements(user_id) VALUES(?)",id);return id;}
  UUID product(UUID owner){UUID id=UUID.randomUUID();db.update("INSERT INTO products(id,owner_user_id,slug,title,summary,description,project_type,category,technology,contribution_text,rights_confirmed,approval_status,lifecycle_status,visibility) VALUES(?,?,?,'Original college project','Original reproducible project outcome','Original source with independently inspectable category evidence and realistic local setup.','LEARNING','CRM','JavaScript','Built the original source and reproduced the stated category evidence.',true,'APPROVED','ACTIVE','PUBLIC')",id,owner,id.toString());return id;}
  @BeforeEach void setup()throws Exception{
    db.execute("TRUNCATE users CASCADE");db.execute("TRUNCATE rate_buckets");objects.clear();reset(storage,provider);owner=user("owner");other=user("other");admin=user("admin");db.update("INSERT INTO user_roles(user_id,role) VALUES(?,'ADMIN')",admin);db.update("UPDATE sessions SET mfa_verified=true WHERE user_id=?",admin);product=product(owner);
    try(var input=getClass().getResourceAsStream("/catalog/education.json")){examples=json.readValue(input,new TypeReference<List<Map<String,Object>>>(){});}
    when(provider.configuration()).thenReturn(Map.of("enabled",false,"mode","disabled"));
    when(storage.put(any(UUID.class),any(byte[].class),anyString())).thenAnswer(invocation->{String key="commerce/"+invocation.getArgument(0)+"/"+UUID.randomUUID()+".zip";objects.put(key,((byte[])invocation.getArgument(1)).clone());return key;});
    when(storage.read(anyString(),anyString(),anyInt())).thenAnswer(invocation->{byte[] bytes=objects.get(invocation.getArgument(0));if(bytes==null)throw new ApiError(503,"STORAGE_UNAVAILABLE","Archive unavailable.");var inspection=SourceArchive.inspect(bytes);if(!inspection.sha256().equals(invocation.getArgument(1))||bytes.length!=(Integer)invocation.getArgument(2))throw new ApiError(409,"ARCHIVE_INTEGRITY_ERROR","Archive integrity failed.");return bytes.clone();});
    doAnswer(invocation->{objects.remove(invocation.getArgument(0));return null;}).when(storage).discardUnlinked(anyString());
  }
  @AfterEach void cleanup(){db.execute("TRUNCATE users CASCADE");}
  MockHttpServletRequestBuilder as(MockHttpServletRequestBuilder request,String actor){return actor==null?request:request.cookie(new Cookie("gl_session",actor));}
  MockHttpServletRequestBuilder body(MockHttpServletRequestBuilder request,String actor,Object value)throws Exception{return as(request,actor).header("Origin","http://localhost:3000").header("X-Requested-With","getlancer").contentType("application/json").content(json.writeValueAsBytes(value));}
  JsonNode ok(MockHttpServletRequestBuilder request)throws Exception{return json.readTree(mvc.perform(request).andExpect(status().isOk()).andReturn().getResponse().getContentAsString());}
  Map<String,Object> draftBody(String mode,int index){var example=json.convertValue(examples.get(index).get("release"),new TypeReference<LinkedHashMap<String,Object>>(){});var source=json.convertValue(example.get("snapshot"),new TypeReference<LinkedHashMap<String,Object>>(){});var result=new LinkedHashMap<String,Object>();for(String key:List.of("category","difficulty","demoMode","demoUrl","package","categoryEvidence","componentLinks"))if(source.containsKey(key))result.put(key,source.get(key));result.put("mode",mode);return result;}
  JsonNode create(String mode,int index)throws Exception{return ok(body(post("/api/v1/me/college-projects/"+product+"/releases"),"owner",draftBody(mode,index)));}
  JsonNode submit(JsonNode release)throws Exception{return ok(body(post("/api/v1/me/education-releases/"+release.path("id").asText()+"/submit"),"owner",Map.of("revision",release.path("revision").asLong(),"rightsConsent",true)));}
  byte[] archive(int index)throws Exception{return Files.readAllBytes(Path.of("..","public",examples.get(index).get("previewPackageUrl").toString().substring(1)));}
  MockHttpServletRequestBuilder upload(JsonNode release,byte[] bytes,boolean rights){return as(multipart("/api/v1/me/education-releases/"+release.path("id").asText()+"/source").file(new MockMultipartFile("file","source.zip","application/zip",bytes)).param("revision",release.path("revision").asText()).param("rightsConsent",Boolean.toString(rights)),"owner").header("Origin","http://localhost:3000").header("X-Requested-With","getlancer");}
  Map<String,Object> review(JsonNode release,String decision){return Map.of("revision",release.path("revision").asLong(),"sourceHash",release.path("sourceHash").asText(),"decision",decision,"reason","Reviewed category evidence, package disclosures and exact source redistribution rights.","rightsReviewed",true,"packageReviewed",true);}
  JsonNode approve(JsonNode pending)throws Exception{return ok(body(post("/api/v1/admin/education-releases/"+pending.path("id").asText()+"/review"),"admin",review(pending,"APPROVE")));}
  JsonNode freePending()throws Exception{return submit(ok(upload(create("FREE",0),archive(0),true)));}
  JsonNode freeApproved()throws Exception{var pending=freePending();mvc.perform(body(post("/api/v1/admin/education-releases/"+pending.path("id").asText()+"/package"),"admin",Map.of())).andExpect(status().isOk());return approve(pending);}

  @Test void unfinishedDraftSavesAndOwnershipStaleRevisionAndConcreteInputAreEnforced()throws Exception{
    var release=ok(body(post("/api/v1/me/college-projects/"+product+"/releases"),"owner",Map.of("mode","SHOWCASE")));String id=release.path("id").asText();var command=Map.of("revision",1,"mode","SHOWCASE","category","FULL_STACK");var saved=ok(body(patch("/api/v1/me/education-releases/"+id),"owner",command));assertEquals(2,saved.path("revision").asInt());
    mvc.perform(body(patch("/api/v1/me/education-releases/"+id),"owner",command)).andExpect(status().isConflict());mvc.perform(as(get("/api/v1/me/education-releases/"+id),"other")).andExpect(status().isNotFound());mvc.perform(body(patch("/api/v1/me/education-releases/"+id),"other",command)).andExpect(status().isNotFound());
    mvc.perform(body(patch("/api/v1/me/education-releases/"+id),"owner",Map.of("revision",2.5,"mode","SHOWCASE"))).andExpect(status().isBadRequest());mvc.perform(body(patch("/api/v1/me/education-releases/"+id),"owner",Map.of("revision",2,"mode","SHOWCASE","categoryEvidence",Map.of("secretKey","never accepted")))).andExpect(status().isBadRequest());mvc.perform(body(patch("/api/v1/me/education-releases/"+id),"owner",Map.of("revision",2,"mode","SHOWCASE","categoryEvidence",Map.of("modules","x".repeat(4001))))).andExpect(status().isBadRequest());
    mvc.perform(body(post("/api/v1/me/education-releases/"+id+"/submit"),"owner",Map.of("revision",2,"rightsConsent",true))).andExpect(status().isBadRequest());assertEquals("DRAFT",db.queryForObject("SELECT status FROM education_releases WHERE id=?",String.class,UUID.fromString(id)));
  }
  @Test void allFourOriginalCategorySchemasPublishAndExactModeDifficultyFiltersWork()throws Exception{
    for(int index=0;index<4;index++){String name="category"+index;UUID actor=user(name),p=product(actor);var draft=ok(body(post("/api/v1/me/college-projects/"+p+"/releases"),name,draftBody("SHOWCASE",index)));var pending=ok(body(post("/api/v1/me/education-releases/"+draft.path("id").asText()+"/submit"),name,Map.of("revision",1,"rightsConsent",true)));approve(pending);var catalog=ok(get("/api/v1/college-projects").param("category",draftBody("SHOWCASE",index).get("category").toString()).param("mode","SHOWCASE").param("difficulty",draftBody("SHOWCASE",index).get("difficulty").toString()));assertEquals(1,catalog.path("totalItems").asInt());assertEquals("APPROVED",ok(get("/api/v1/college-projects/"+p)).path("education").path("release").path("status").asText());}
    assertEquals(4,ok(get("/api/v1/college-projects")).path("totalItems").asInt());assertEquals(0,ok(get("/api/v1/college-projects").param("mode","PAID")).path("totalItems").asInt());
  }
  @Test void categoryEvidencePackageDisclosuresAndDistributionConsentAreRequiredAtSubmission()throws Exception{
    for(int index=0;index<4;index++){var command=draftBody("SHOWCASE",index);command.put("categoryEvidence",Map.of());var release=ok(body(post("/api/v1/me/college-projects/"+product+"/releases"),"owner",command));mvc.perform(body(post("/api/v1/me/education-releases/"+release.path("id").asText()+"/submit"),"owner",Map.of("revision",1,"rightsConsent",true))).andExpect(status().isBadRequest());}
    var release=create("SHOWCASE",0);mvc.perform(body(post("/api/v1/me/education-releases/"+release.path("id").asText()+"/submit"),"owner",Map.of("revision",1,"rightsConsent",false))).andExpect(status().isBadRequest()).andExpect(jsonPath("$.error.code").value("RIGHTS_CONSENT_REQUIRED"));var command=draftBody("SHOWCASE",0);command.put("package",Map.of("licenseTerms","A correct license alone is insufficient."));var incomplete=ok(body(post("/api/v1/me/college-projects/"+product+"/releases"),"owner",command));mvc.perform(body(post("/api/v1/me/education-releases/"+incomplete.path("id").asText()+"/submit"),"owner",Map.of("revision",1,"rightsConsent",true))).andExpect(status().isBadRequest());
  }
  @Test void privateNetworkCredentialsAndFakeHostedClaimsAreRejected()throws Exception{
    for(String url:List.of("https://127.0.0.1/demo","http://localhost/demo","https://user:password@example.com/demo")){var command=draftBody("SHOWCASE",0);command.put("demoMode","EXTERNAL");command.put("demoUrl",url);var release=ok(body(post("/api/v1/me/college-projects/"+product+"/releases"),"owner",command));mvc.perform(body(post("/api/v1/me/education-releases/"+release.path("id").asText()+"/submit"),"owner",Map.of("revision",1,"rightsConsent",true))).andExpect(status().isBadRequest()).andExpect(jsonPath("$.error.code").value("UNSAFE_EXTERNAL_URL"));}
    var command=draftBody("SHOWCASE",0);command.put("demoMode","HOSTED");var release=ok(body(post("/api/v1/me/college-projects/"+product+"/releases"),"owner",command));mvc.perform(body(post("/api/v1/me/education-releases/"+release.path("id").asText()+"/submit"),"owner",Map.of("revision",1,"rightsConsent",true))).andExpect(status().isConflict()).andExpect(jsonPath("$.error.code").value("EDUCATION_DEMO_UNAVAILABLE"));
  }
  @Test void privateFreeUploadHasExactFilesAndNeverCreatesPurchaseAccounting()throws Exception{
    var draft=create("FREE",0);mvc.perform(upload(draft,archive(0),false)).andExpect(status().isBadRequest());mvc.perform(upload(draft,new byte[32],true)).andExpect(status().isBadRequest());var uploaded=ok(upload(draft,archive(0),true));assertEquals(2,uploaded.path("revision").asInt());assertEquals(SourceArchive.inspect(archive(0)).sha256(),uploaded.path("sourceBinding").path("sha256").asText());assertEquals(SourceArchive.inspect(archive(0)).files().size(),ok(as(get("/api/v1/me/education-releases/"+uploaded.path("id").asText()),"owner")).path("sourceBinding").path("files").size());mvc.perform(upload(draft,archive(0),true)).andExpect(status().isConflict());assertEquals(0,db.queryForObject("SELECT count(*) FROM template_purchases",Integer.class));assertEquals(SourceArchive.inspect(archive(0)).files(),json.readValue(db.queryForObject("SELECT files::text FROM education_free_packages",String.class),List.class));assertFalse(uploaded.toString().contains("storage_key"));assertFalse(uploaded.toString().contains("commerce/"));
  }
  @Test void confirmedUploadRollbackDiscardsOnlyItsUnlinkedPrivateObject()throws Exception{
    var draft=create("FREE",0);String id=draft.path("id").asText(),key="commerce/"+UUID.randomUUID()+"/"+UUID.randomUUID()+".zip";when(storage.put(any(UUID.class),any(byte[].class),anyString())).thenAnswer(invocation->{objects.put(key,archive(0));db.update("UPDATE education_releases SET revision=revision+1 WHERE id=?",UUID.fromString(id));return key;});mvc.perform(upload(draft,archive(0),true)).andExpect(status().isConflict());verify(storage).discardUnlinked(key);assertFalse(objects.containsKey(key));assertEquals(0,db.queryForObject("SELECT count(*) FROM education_free_packages",Integer.class));
  }
  @Test void exactHashInspectionRequiresUnsafeProtectedPostAndRecentMfaBeforeApproval()throws Exception{
    var pending=freePending();String id=pending.path("id").asText(),path="/api/v1/admin/education-releases/"+id+"/package";mvc.perform(get("/api/v1/education-releases/"+id+"/source")).andExpect(status().isNotFound());mvc.perform(body(post("/api/v1/admin/education-releases/"+id+"/review"),"admin",review(pending,"APPROVE"))).andExpect(status().isConflict()).andExpect(jsonPath("$.error.code").value("EDUCATION_PACKAGE_REVIEW_REQUIRED"));
    mvc.perform(as(get(path),"admin")).andExpect(status().isForbidden());mvc.perform(as(post(path),"admin")).andExpect(status().isForbidden());mvc.perform(as(post(path),"admin").header("Origin","https://attacker.example.test").header("X-Requested-With","getlancer")).andExpect(status().isForbidden());mvc.perform(body(post(path),"other",Map.of())).andExpect(status().isForbidden());db.update("UPDATE sessions SET issued_at=now()-interval '1 hour' WHERE user_id=?",admin);mvc.perform(body(post(path),"admin",Map.of())).andExpect(status().isForbidden());db.update("UPDATE sessions SET issued_at=now() WHERE user_id=?",admin);assertEquals(0,db.queryForObject("SELECT count(*) FROM education_audit WHERE release_id=? AND action='PACKAGE_REVIEW_DOWNLOAD'",Integer.class,UUID.fromString(id)));
    byte[] inspected=mvc.perform(body(post(path),"admin",Map.of())).andExpect(status().isOk()).andExpect(header().stringValues("Cache-Control","no-store","private, no-store")).andReturn().getResponse().getContentAsByteArray();assertArrayEquals(archive(0),inspected);var wrong=new LinkedHashMap<>(review(pending,"APPROVE"));wrong.put("sourceHash","a".repeat(64));mvc.perform(body(post("/api/v1/admin/education-releases/"+id+"/review"),"admin",wrong)).andExpect(status().isConflict());approve(pending);var offer=ok(get("/api/v1/education-releases/"+id+"/source-offer"));assertTrue(offer.path("available").asBoolean());assertEquals(SourceArchive.inspect(archive(0)).sha256(),offer.path("package").path("sha256").asText());assertArrayEquals(archive(0),mvc.perform(get("/api/v1/education-releases/"+id+"/source")).andExpect(status().isOk()).andExpect(content().contentType("application/zip")).andExpect(header().string("X-Content-Type-Options","nosniff")).andReturn().getResponse().getContentAsByteArray());
  }
  @Test void reviewedCoreIsImmutableAndHistoricalFreeRemainsFreeAfterNewShowcase()throws Exception{
    var release=freeApproved();String id=release.path("id").asText();var command=draftBody("SHOWCASE",0);command.put("revision",release.path("revision").asLong());mvc.perform(body(patch("/api/v1/me/education-releases/"+id),"owner",command)).andExpect(status().isConflict());assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("UPDATE education_releases SET snapshot='{}'::jsonb WHERE id=?",UUID.fromString(id)));assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("DELETE FROM education_free_packages"));assertThrows(org.springframework.dao.DataAccessException.class,()->db.update("DELETE FROM education_audit"));var next=approve(submit(create("SHOWCASE",0)));assertEquals("SHOWCASE",ok(get("/api/v1/college-projects/"+product)).path("education").path("mode").asText());assertTrue(ok(get("/api/v1/education-releases/"+id+"/source-offer")).path("available").asBoolean());mvc.perform(get("/api/v1/education-releases/"+id+"/source")).andExpect(status().isOk());assertFalse(ok(get("/api/v1/education-releases/"+next.path("id").asText()+"/source-offer")).path("available").asBoolean());
  }
  @Test void serializedApprovalOrderOverridesEarlierWaitingTransactionStart()throws Exception{
    var first=submit(create("SHOWCASE",0));
    var later=submit(create("SHOWCASE",1));
    var ready=new java.util.concurrent.CountDownLatch(1);
    var proceed=new java.util.concurrent.CountDownLatch(1);
    var waiterPid=new java.util.concurrent.atomic.AtomicInteger();
    var waiterStarted=new java.util.concurrent.atomic.AtomicReference<java.sql.Timestamp>();
    var executor=java.util.concurrent.Executors.newSingleThreadExecutor();
    var transaction=new TransactionTemplate(transactions);
    try{
      var waiting=executor.submit(()->transaction.execute(status->{
        waiterPid.set(db.queryForObject("SELECT pg_backend_pid()",Integer.class));
        waiterStarted.set(db.queryForObject("SELECT transaction_timestamp()",java.sql.Timestamp.class));
        ready.countDown();
        try{
          assertTrue(proceed.await(10,java.util.concurrent.TimeUnit.SECONDS));
          return approve(later);
        }catch(Exception error){throw new IllegalStateException(error);}
      }));
      assertTrue(ready.await(10,java.util.concurrent.TimeUnit.SECONDS));
      transaction.execute(status->{
        assertTrue(db.queryForObject("SELECT transaction_timestamp() > ?",Boolean.class,waiterStarted.get()),"The waiting approval must start its transaction before the holder.");
        db.queryForList("SELECT pg_advisory_xact_lock(hashtextextended(?,0))","education:"+product);
        proceed.countDown();
        long deadline=System.nanoTime()+java.util.concurrent.TimeUnit.SECONDS.toNanos(10);
        boolean blocked=false;
        while(System.nanoTime()<deadline){
          blocked=db.queryForObject("SELECT count(*) FROM pg_locks WHERE pid=? AND locktype='advisory' AND NOT granted",Integer.class,waiterPid.get())>0;
          if(blocked)break;
          java.util.concurrent.locks.LockSupport.parkNanos(java.util.concurrent.TimeUnit.MILLISECONDS.toNanos(10));
        }
        assertTrue(blocked,"Observe the real PostgreSQL advisory-lock waiter before approving the first release.");
        try{return approve(first);}catch(Exception error){throw new IllegalStateException(error);}
      });
      assertEquals("APPROVED",waiting.get(15,java.util.concurrent.TimeUnit.SECONDS).path("status").asText());
      assertTrue(db.queryForObject("SELECT a.reviewed_at > b.reviewed_at FROM education_releases a JOIN education_releases b ON b.id=? WHERE a.id=?",Boolean.class,UUID.fromString(first.path("id").asText()),UUID.fromString(later.path("id").asText())));
      assertEquals(later.path("id").asText(),ok(get("/api/v1/college-projects/"+product)).path("education").path("release").path("id").asText());
    }finally{proceed.countDown();executor.shutdownNow();assertTrue(executor.awaitTermination(15,java.util.concurrent.TimeUnit.SECONDS));}
  }
  @Test void academicSharingCanBeWithdrawnWithoutChangingReleaseRevisionOrHash()throws Exception{
    var release=approve(submit(create("SHOWCASE",0)));String id=release.path("id").asText(),hash=release.path("sourceHash").asText();var command=Map.of("revision",1,"institution","Private College","academicYear","Final year","branch","Private branch","shareAcademicDetails",false);var annotated=ok(body(patch("/api/v1/me/education-releases/"+id+"/academic"),"owner",command));assertEquals("Private College",annotated.path("academic").path("institution").asText());assertFalse(ok(get("/api/v1/college-projects/"+product)).toString().contains("Private College"));assertFalse(db.queryForObject("SELECT snapshot::text FROM education_releases WHERE id=?",String.class,UUID.fromString(id)).contains("Private College"));
    var shared=ok(body(patch("/api/v1/me/education-releases/"+id+"/academic"),"owner",Map.of("revision",2,"institution","Private College","academicYear","Final year","branch","Private branch","shareAcademicDetails",true)));assertEquals("Private College",ok(get("/api/v1/college-projects/"+product)).path("education").path("academic").path("institution").asText());mvc.perform(body(patch("/api/v1/me/education-releases/"+id+"/academic"),"owner",command)).andExpect(status().isConflict());var withdrawn=ok(body(patch("/api/v1/me/education-releases/"+id+"/academic"),"owner",Map.of("revision",shared.path("academic").path("revision").asLong(),"shareAcademicDetails",false)));assertEquals("Private College",withdrawn.path("academic").path("institution").asText());assertEquals(hash,withdrawn.path("sourceHash").asText());assertEquals(release.path("revision"),withdrawn.path("revision"));assertFalse(ok(get("/api/v1/college-projects/"+product)).toString().contains("Private College"));
  }
  @Test void currentProfileRoleProductAndReleaseSuspensionRevokeFreeAccess()throws Exception{
    var release=freeApproved();String id=release.path("id").asText();db.update("UPDATE developer_profiles SET approval_status='CHANGES_REQUESTED' WHERE user_id=?",owner);mvc.perform(get("/api/v1/education-releases/"+id+"/source")).andExpect(status().isConflict());db.update("UPDATE developer_profiles SET approval_status='APPROVED' WHERE user_id=?",owner);db.update("DELETE FROM user_roles WHERE user_id=? AND role='DEVELOPER'",owner);mvc.perform(get("/api/v1/education-releases/"+id+"/source")).andExpect(status().isConflict());db.update("INSERT INTO user_roles(user_id,role) VALUES(?,'DEVELOPER')",owner);ok(body(post("/api/v1/admin/education-releases/"+id+"/review"),"admin",review(release,"SUSPEND")));mvc.perform(get("/api/v1/education-releases/"+id+"/source")).andExpect(status().isNotFound());assertEquals("SUSPENDED",db.queryForObject("SELECT approval_status FROM products WHERE id=?",String.class,product));assertEquals("SUSPENDED",db.queryForObject("SELECT status FROM college_project_metadata WHERE product_id=?",String.class,product));
  }
  @Test void componentLinksPinExistingImmutableLicenseAndCurrentWithdrawalRemovesSourceAccess()throws Exception{
    UUID component=UUID.randomUUID();String source=json.writeValueAsString(Map.of("license","MIT","sha256","b".repeat(64),"kind","FRONTEND","version","1.0.0")),context=json.writeValueAsString(Map.of("title","Reusable source","summary","Original reusable MIT source","contribution","Built the reusable source"));db.update("INSERT INTO component_entries(id,owner_id,recipe_slug,slug,title,summary,contribution,status,published_at,published_source,published_context) VALUES(?,?,'original',?,'Reusable source','Original reusable MIT source','Built the reusable source','ACTIVE',now(),?::jsonb,?::jsonb)",component,other,"component-"+component,source,context);db.update("INSERT INTO component_releases(component_id,revision,source,context,source_sha256) VALUES(?,1,?::jsonb,?::jsonb,?)",component,source,context,"b".repeat(64));var command=draftBody("SHOWCASE",0);command.put("componentLinks",List.of(Map.of("componentId",component,"revision",1,"license","MIT","attribution","Original MIT reusable component by the Other builder; notice retained.")));var draft=ok(body(post("/api/v1/me/college-projects/"+product+"/releases"),"owner",command));approve(submit(draft));assertEquals("MIT",ok(get("/api/v1/college-projects/"+product)).path("education").path("componentLinks").get(0).path("license").asText());for(String editing:List.of("DRAFT","PENDING")){db.update("UPDATE component_entries SET status=? WHERE id=?",editing,component);assertEquals(1,ok(get("/api/v1/college-projects/"+product)).path("education").path("componentLinks").size());}db.update("UPDATE component_entries SET status='ARCHIVED',withdrawn_at=now() WHERE id=?",component);assertEquals(0,ok(get("/api/v1/college-projects/"+product)).path("education").path("componentLinks").size());var second=ok(body(post("/api/v1/me/college-projects/"+product+"/releases"),"owner",command));mvc.perform(body(post("/api/v1/me/education-releases/"+second.path("id").asText()+"/submit"),"owner",Map.of("revision",1,"rightsConsent",true))).andExpect(status().isConflict()).andExpect(jsonPath("$.error.code").value("EDUCATION_COMPONENT_UNAVAILABLE"));
  }
  @Test void existingTeamOwnerConsentProjectsOnlyCurrentEligibleMembership()throws Exception{
    approve(submit(create("SHOWCASE",0)));UUID team=UUID.randomUUID();
    db.update("INSERT INTO teams(id,slug,name,summary,availability,project_range,owner_id) VALUES(?,?,'Consenting team','Team of original contributors','Available','Small original projects',?)",team,"team-"+team,other);
    db.update("INSERT INTO team_members(team_id,user_id,role,membership_type) VALUES(?,?,'OWNER','PERMANENT'),(?,?,'MEMBER','PERMANENT')",team,other,team,owner);
    db.update("INSERT INTO team_projects(team_id,product_id,consented_by) VALUES(?,?,?)",team,product,owner);
    assertEquals("Consenting team",ok(get("/api/v1/college-projects/"+product)).path("education").path("teams").get(0).path("name").asText());
    db.update("UPDATE users SET account_status='SUSPENDED' WHERE id=?",other);assertEquals(0,ok(get("/api/v1/college-projects/"+product)).path("education").path("teams").size());
    db.update("UPDATE users SET account_status='ACTIVE' WHERE id=?",other);db.update("UPDATE developer_profiles SET approval_status='SUSPENDED' WHERE user_id=?",other);assertEquals(0,ok(get("/api/v1/college-projects/"+product)).path("education").path("teams").size());
    db.update("UPDATE developer_profiles SET approval_status='APPROVED' WHERE user_id=?",other);db.update("DELETE FROM team_projects WHERE team_id=?",team);
    assertEquals(0,ok(get("/api/v1/college-projects/"+product)).path("education").path("teams").size());assertFalse(ok(get("/api/v1/college-projects/"+product)).toString().contains("other@example.test"));
  }
  @Test void concurrentDraftUpdatesAcceptOnlyOneCurrentRevision()throws Exception{
    var draft=create("SHOWCASE",0);String id=draft.path("id").asText();var pool=java.util.concurrent.Executors.newFixedThreadPool(2);var start=new java.util.concurrent.CountDownLatch(1);try{var one=pool.submit(()->{start.await();return mvc.perform(body(patch("/api/v1/me/education-releases/"+id),"owner",Map.of("revision",1,"mode","SHOWCASE","category","AI_ML"))).andReturn().getResponse().getStatus();});var two=pool.submit(()->{start.await();return mvc.perform(body(patch("/api/v1/me/education-releases/"+id),"owner",Map.of("revision",1,"mode","SHOWCASE","category","IOT"))).andReturn().getResponse().getStatus();});start.countDown();assertEquals(Set.of(200,409),Set.of(one.get(15,java.util.concurrent.TimeUnit.SECONDS),two.get(15,java.util.concurrent.TimeUnit.SECONDS)));assertEquals(2,db.queryForObject("SELECT revision FROM education_releases WHERE id=?",Integer.class,UUID.fromString(id)));}finally{pool.shutdownNow();}
  }
  @Test void separateCollegePublishingCapacityDoesNotExpandFromDrafts()throws Exception{
    for(int index=0;index<3;index++){UUID p=index==0?product:product(owner);submit(ok(body(post("/api/v1/me/college-projects/"+p+"/releases"),"owner",draftBody("SHOWCASE",0))));}UUID p=product(owner);var draft=ok(body(post("/api/v1/me/college-projects/"+p+"/releases"),"owner",draftBody("SHOWCASE",0)));mvc.perform(body(post("/api/v1/me/education-releases/"+draft.path("id").asText()+"/submit"),"owner",Map.of("revision",1,"rightsConsent",true))).andExpect(status().isConflict()).andExpect(jsonPath("$.error.code").value("SLOT_LIMIT_REACHED"));assertEquals(3,db.queryForObject("SELECT count(*) FROM college_project_metadata e JOIN products p ON p.id=e.product_id WHERE p.owner_user_id=?",Integer.class,owner));
  }
  @Test void reportPinsCanonicalArtifactObjectWithoutPublicPrivateFactsAndModerationRevokesSource()throws Exception{
    var release=freeApproved();String id=release.path("id").asText();var reference=json.readTree(mvc.perform(body(post("/api/v1/reports"),null,Map.of("targetType","PRODUCT","targetId",product,"educationReleaseId",id,"reason","MISLEADING_CLAIM","detail","The advertised setup evidence needs independent artifact review."))).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());assertEquals(1,reference.size());String report=reference.path("reference").asText();mvc.perform(as(get("/api/v1/admin/reports/"+report),"other")).andExpect(status().isForbidden());var detail=ok(as(get("/api/v1/admin/reports/"+report),"admin")).path("report");assertEquals(id,detail.path("education_release_id").asText());assertEquals(release.path("sourceHash").asText(),detail.path("source_hash").asText());assertTrue(detail.path("education_snapshot").isObject());assertEquals(release.path("snapshot"),detail.path("education_snapshot"));assertFalse(detail.path("education_snapshot").toString().contains("institution"));ok(body(post("/api/v1/admin/reports/"+report+"/resolve"),"admin",Map.of("targetAction","SUSPEND","reason","Suspend the exact reported package pending independent evidence review.")));mvc.perform(get("/api/v1/education-releases/"+id+"/source")).andExpect(status().isConflict());
  }
  @Test void actualOwnerExportEmailConfirmedDeletionAndRetentionEraseAnnotationsButPreserveAgreement()throws Exception{
    var release=freeApproved();String id=release.path("id").asText();UUID releaseId=UUID.fromString(id);ok(body(patch("/api/v1/me/education-releases/"+id+"/academic"),"owner",Map.of("revision",1,"institution","Private retained college","academicYear","Final year","branch","Private retained branch","shareAcademicDetails",false)));db.update("UPDATE college_project_metadata SET institution='Private legacy college',academic_year='Final year',branch='Private legacy branch',share_academic_details=false WHERE product_id=?",product);String frozen=db.queryForObject("SELECT snapshot::text FROM education_releases WHERE id=?",String.class,releaseId);int audit=db.queryForObject("SELECT count(*) FROM education_audit WHERE release_id=?",Integer.class,releaseId);
    var ownExport=ok(as(get("/api/v1/me/export"),"owner"));var exported=ownExport.path("educationReleases").get(0);assertEquals(id,exported.path("id").asText());assertEquals("Private retained college",exported.path("institution").asText());assertEquals(release.path("sourceHash").asText(),exported.path("source_hash").asText());assertTrue(exported.hasNonNull("free_package_id"));assertFalse(ownExport.toString().contains("storage_key"));var foreign=ok(as(get("/api/v1/me/export"),"other"));assertEquals(0,foreign.path("educationReleases").size());assertFalse(foreign.toString().contains(id));assertFalse(foreign.toString().contains("Private retained college"));
    mvc.perform(body(delete("/api/v1/me"),"owner",Map.of())).andExpect(status().isAccepted()).andExpect(jsonPath("$.status").value("EMAIL_CONFIRMATION_REQUIRED"));String email=db.queryForObject("SELECT body FROM email_outbox WHERE recipient='owner@example.test' AND subject='Confirm closing your getLancer account' ORDER BY created_at DESC LIMIT 1",String.class);String token=email.substring(email.indexOf("/confirm#token=")+"/confirm#token=".length()).split("\\n",2)[0].trim();ok(body(post("/api/v1/auth/confirm"),null,Map.of("token",token,"decision","DELETE")));mvc.perform(as(get("/api/v1/me/export"),"owner")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/education-releases/"+id+"/source")).andExpect(status().isConflict());var retained=ok(body(post("/api/v1/admin/deletion-requests/"+owner+"/review"),"admin",Map.of("action","ANONYMIZE_PROFILE","reason","Apply the approved retention policy and erase private academic annotations.")));assertEquals("PROFILE_ANONYMIZED",retained.path("status").asText());assertEquals(0,db.queryForObject("SELECT count(*) FROM education_private_details WHERE release_id=?",Integer.class,releaseId));var legacy=db.queryForMap("SELECT institution,academic_year,branch,share_academic_details FROM college_project_metadata WHERE product_id=?",product);assertEquals("",legacy.get("institution"));assertEquals("",legacy.get("academic_year"));assertEquals("",legacy.get("branch"));assertEquals(false,legacy.get("share_academic_details"));assertEquals(frozen,db.queryForObject("SELECT snapshot::text FROM education_releases WHERE id=?",String.class,releaseId));assertEquals(release.path("sourceHash").asText(),db.queryForObject("SELECT source_hash FROM education_releases WHERE id=?",String.class,releaseId));assertEquals(audit,db.queryForObject("SELECT count(*) FROM education_audit WHERE release_id=?",Integer.class,releaseId));assertEquals(1,db.queryForObject("SELECT count(*) FROM education_free_packages",Integer.class));
  }
  @Test void paidReleaseBindsActualReviewedSourceApisAndStaysUnavailableWithoutActivation()throws Exception{
    db.update("UPDATE products SET repository_url='https://github.com/example/college-source' WHERE id=?",product);db.update("INSERT INTO repository_verifications(product_id,repository_url,challenge,status,reviewed_at,reviewer_id) VALUES(?,'https://github.com/example/college-source','private-repository-challenge','VERIFIED',now(),?)",product,admin);
    var template=json.readTree(mvc.perform(body(post("/api/v1/me/templates"),"owner",Map.of("productId",product,"title","Original paid source","summary","Original inspected source package","description","Original source with exact package, setup and redistribution notices.","priceMinor",12000,"licenseTerms","Commercial use for one end product; retain original MIT and third-party source notices."))).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());String templateId=template.path("id").asText();
    var source=json.readTree(mvc.perform(as(multipart("/api/v1/me/templates/"+templateId+"/versions").file(new MockMultipartFile("file","source.zip","application/zip",archive(0))).param("version","paid-source-1").param("releaseNotes","Original inspectable source, setup and third-party notices.").param("rightsConsent","true"),"owner").header("Origin","http://localhost:3000").header("X-Requested-With","getlancer")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString());String sourceId=source.path("id").asText();ok(body(post("/api/v1/me/templates/"+templateId+"/versions/"+sourceId+"/submit"),"owner",Map.of("rightsConsent",true)));ok(body(post("/api/v1/admin/templates/"+templateId+"/versions/"+sourceId+"/review"),"admin",Map.of("action","APPROVE","reason","Reviewed exact original source, supported manifest and redistribution notices.","rightsReviewed",true,"packageReviewed",true)));
    String license=db.queryForObject("SELECT license_terms FROM source_versions WHERE id=?",String.class,UUID.fromString(sourceId));var command=draftBody("PAID",0);var pack=json.convertValue(command.get("package"),new TypeReference<LinkedHashMap<String,Object>>(){});pack.put("licenseTerms",license);command.put("package",pack);command.put("versionId",sourceId);var draft=ok(body(post("/api/v1/me/college-projects/"+product+"/releases"),"owner",command));assertEquals(sourceId,draft.path("sourceBinding").path("versionId").asText());assertEquals(sourceId,ok(as(get("/api/v1/me/education-releases/"+draft.path("id").asText()),"owner")).path("sourceBinding").path("versionId").asText());var approved=approve(submit(draft));String id=approved.path("id").asText();assertEquals(12000,approved.path("snapshot").path("priceMinor").asInt());assertEquals(sourceId,approved.path("snapshot").path("sourceBinding").path("versionId").asText());assertEquals(license,approved.path("snapshot").path("sourceBinding").path("licenseTerms").asText());assertEquals(SourceArchive.inspect(archive(0)).sha256(),approved.path("snapshot").path("sourceBinding").path("sha256").asText());
    ok(body(patch("/api/v1/me/education-releases/"+id+"/academic"),"owner",Map.of("revision",1,"institution","Private paid college","shareAcademicDetails",false)));var ownExport=ok(as(get("/api/v1/me/export"),"owner")).path("educationReleases").get(0);assertEquals(sourceId,ownExport.path("source_version_id").asText());assertEquals(templateId,ownExport.path("snapshot").path("sourceBinding").path("templateId").asText());assertEquals(approved.path("sourceHash").asText(),ownExport.path("source_hash").asText());assertEquals("Private paid college",ownExport.path("institution").asText());var foreign=ok(as(get("/api/v1/me/export"),"other"));assertEquals(0,foreign.path("educationReleases").size());assertFalse(foreign.toString().contains(sourceId));assertFalse(foreign.toString().contains("Private paid college"));
    var offer=ok(get("/api/v1/education-releases/"+id+"/source-offer"));assertFalse(offer.path("available").asBoolean());assertFalse(offer.path("checkoutAvailable").asBoolean());assertFalse(offer.path("paidEnabled").asBoolean());mvc.perform(get("/api/v1/education-releases/"+id+"/source")).andExpect(status().isNotFound());mvc.perform(body(post("/api/v1/templates/"+templateId+"/orders"),"other",Map.of("versionId",sourceId,"educationReleaseId",id,"licenseConsent",true)).header("Idempotency-Key",UUID.randomUUID().toString())).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.error.code").value("EDUCATION_PAID_UNAVAILABLE"));assertEquals(0,db.queryForObject("SELECT count(*) FROM template_purchases",Integer.class));verify(provider,never()).createOrder(any(UUID.class),anyLong(),anyString());
    var next=submit(ok(body(post("/api/v1/me/college-projects/"+product+"/releases"),"owner",command)));db.update("UPDATE source_templates SET price_minor=13000 WHERE id=?",UUID.fromString(templateId));mvc.perform(body(post("/api/v1/admin/education-releases/"+next.path("id").asText()+"/review"),"admin",review(next,"APPROVE"))).andExpect(status().isConflict()).andExpect(jsonPath("$.error.code").value("EDUCATION_SOURCE_CHANGED"));
  }
}
