package com.getlancer;
import java.util.*;import org.junit.jupiter.api.Test;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.mock.web.*;import com.fasterxml.jackson.databind.ObjectMapper;import jakarta.servlet.http.Cookie;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class GitHubAuthTest {
 final JdbcTemplate db=mock(JdbcTemplate.class);final Security security=mock(Security.class);final ObjectMapper json=new ObjectMapper();final AuthController auth=new AuthController(db,security,mock(Mail.class),true,"admin@example.com");
 GitHubAuthController controller(String id,String secret){return new GitHubAuthController(db,auth,mock(GitHubAccounts.class),json,id,secret,"https://getlancer.example");}
 @Test void missingConfigurationFailsClosed(){assertFalse(controller("","").enabled());assertThrows(ApiError.class,()->controller("","").start(Map.of("intent","login"),new MockHttpServletResponse()));verifyNoInteractions(db);}
 @Test void primaryEmailMustBeVerified()throws Exception{var profile=json.readTree("{\"id\":123,\"login\":\"builder\"}");var emails=json.readTree("[{\"email\":\"member@example.com\",\"primary\":true,\"verified\":false}]");assertEquals("email_unverified",assertThrows(ApiError.class,()->GitHubAuthController.identity(profile,emails)).code);}
 @Test void secondaryVerifiedEmailIsNotAccepted()throws Exception{assertThrows(ApiError.class,()->GitHubAuthController.identity(json.readTree("{\"id\":123}"),json.readTree("[{\"email\":\"member@example.com\",\"primary\":false,\"verified\":true}]")));}
 @Test void identityUsesStableNumericIdAndPrimaryVerifiedEmail()throws Exception{var id=GitHubAuthController.identity(json.readTree("{\"id\":123,\"login\":\"builder\",\"name\":null}"),json.readTree("[{\"email\":\"Member@example.com\",\"primary\":true,\"verified\":true}]"));assertEquals("123",id.subject());assertEquals("member@example.com",id.email());assertEquals("builder",id.name());}
 @Test void invalidIdentityIsRejected()throws Exception{assertThrows(ApiError.class,()->GitHubAuthController.identity(json.readTree("{\"id\":\"attacker\"}"),json.readTree("[]")));}
 @Test void startBindsBrowserAndPkceWithoutExposingSecret()throws Exception{var res=new MockHttpServletResponse();String url=(String)controller("client","private-secret").start(Map.of("intent","login","rememberMe",true),res).get("authorizationUrl");assertTrue(url.startsWith("https://github.com/login/oauth/authorize?"));assertTrue(url.contains("code_challenge_method=S256"));assertTrue(url.contains("state="));assertFalse(url.contains("private-secret"));assertTrue(res.getHeader("Set-Cookie").contains("HttpOnly"));assertTrue(res.getHeader("Set-Cookie").contains("Secure"));}
 @Test void signupRequiresConsent(){assertThrows(ApiError.class,()->controller("client","secret").start(Map.of("intent","signup"),new MockHttpServletResponse()));verifyNoInteractions(db);}
 @Test void missingBrowserBindingDoesNotExchangeCode(){var result=controller("client","secret").callback("state","code","",new MockHttpServletRequest(),new MockHttpServletResponse());assertEquals("/login?auth_error=expired&provider=github",result.getHeaders().getLocation().toString());verifyNoInteractions(db);}
 @Test void cancelledFlowConsumesStateBeforeReturning(){var req=new MockHttpServletRequest();req.setCookies(new Cookie("gl_github_oauth","b".repeat(43)));when(db.queryForList(anyString(),eq(Support.hash("a".repeat(43))),eq(Support.hash("b".repeat(43))))).thenReturn(List.of(Map.of("intent","signup","code_verifier","v")));var result=controller("client","secret").callback("a".repeat(43),"","access_denied",req,new MockHttpServletResponse());assertEquals("/signup?auth_error=cancelled&provider=github",result.getHeaders().getLocation().toString());verify(db).queryForList(contains("provider='github'"),eq(Support.hash("a".repeat(43))),eq(Support.hash("b".repeat(43))));}
 @Test void administratorCannotUseGithub(){var accounts=new GitHubAccounts(db,security,"admin@example.com");assertEquals("admin_password",assertThrows(ApiError.class,()->accounts.resolve(new GitHubAccounts.Identity("123","admin@example.com","Admin"),"signup")).code);verifyNoInteractions(db);}
 @Test void existingPasswordAccountIsNeverAutomaticallyLinked(){var accounts=new GitHubAccounts(db,security,"admin@example.com");when(db.queryForObject("SELECT count(*) FROM users WHERE email=?",Integer.class,"member@example.com")).thenReturn(1);assertEquals("email_account",assertThrows(ApiError.class,()->accounts.resolve(new GitHubAccounts.Identity("123","member@example.com","Member"),"signup")).code);verify(db,never()).update(startsWith("INSERT INTO oauth_identities"),any(Object[].class));}
 @Test void ordinarySessionsAreNotPersistentUnlessRequested(){var shortSession=new MockHttpServletResponse();auth.issueSession(UUID.randomUUID(),false,false,shortSession);assertFalse(shortSession.getHeader("Set-Cookie").contains("Max-Age"));var remembered=new MockHttpServletResponse();auth.issueSession(UUID.randomUUID(),false,true,remembered);assertTrue(remembered.getHeader("Set-Cookie").contains("Max-Age=86400"));var admin=new MockHttpServletResponse();auth.issueSession(UUID.randomUUID(),true,true,admin);assertTrue(admin.getHeader("Set-Cookie").contains("Max-Age=3600"));}
}
