package com.getlancer.integration;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.fasterxml.jackson.databind.*;
import com.getlancer.payments.MaintenanceFixture;
import com.getlancer.shared.Support;
import com.getlancer.testing.TestDatabaseGuard;
import jakarta.servlet.http.Cookie;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
@org.springframework.test.context.ContextConfiguration(initializers=TestDatabaseGuard.class)
@SpringBootTest(properties={"app.environment=local","app.jobs-enabled=false","app.admin-email=admin@example.test","app.admin-password=","app.admin-totp=","spring.config.import=",
 "spring.datasource.url=${TEST_DB_URL:jdbc:postgresql://localhost:5432/getlancer_test}","spring.datasource.username=${TEST_DB_USERNAME:postgres}","spring.datasource.password=${TEST_DB_PASSWORD:}",
 "spring.datasource.hikari.schema=getlancer_test","spring.flyway.default-schema=getlancer_test","spring.flyway.schemas=getlancer_test","app.origin=http://localhost:3000","app.secure-cookie=false","app.storage.access-key=","app.storage.secret-key=","app.maintenance.enabled=true","app.maintenance.subscriptions-approved=true","app.maintenance.webhook-secret=fixture-webhook-not-for-production"})
@AutoConfigureMockMvc
@Import(MaintenanceFixture.Configuration.class)
class MaintenanceIntegrationTest {
 @Autowired JdbcTemplate db;@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired MaintenanceFixture fixture;
 UUID buyer,seller,admin,engagement,milestone,originalPayment;
 UUID user(String name,boolean approved){UUID id=UUID.randomUUID();db.update("INSERT INTO users(id,email,password_hash,email_verified_at) VALUES(?,?,'unused',now())",id,name+"@example.test");db.update("INSERT INTO user_roles(user_id,role) VALUES(?,'CLIENT'),(?,'DEVELOPER')",id,id);db.update("INSERT INTO developer_profiles(user_id,slug,display_name,approval_status) VALUES(?,?,?,?)",id,name,name,approved?"APPROVED":"DRAFT");db.update("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,now()+interval '1 hour')",Support.hash(name),id);return id;}
 @BeforeEach void setup(){db.execute("TRUNCATE users CASCADE");db.execute("TRUNCATE rate_buckets");db.execute("TRUNCATE maintenance_webhook_events");fixture.reset();fixture.period(false);buyer=user("care-buyer",false);seller=user("care-seller",true);user("care-outsider",false);admin=user("care-admin",false);db.update("UPDATE users SET email='admin@example.test' WHERE id=?",admin);db.update("INSERT INTO user_roles(user_id,role) VALUES(?,'ADMIN')",admin);db.update("UPDATE sessions SET mfa_verified=true WHERE user_id=?",admin);
  UUID product=UUID.randomUUID(),inquiry=UUID.randomUUID();db.update("INSERT INTO products(id,owner_user_id,slug,title,summary,description,project_type,category,technology,contribution_text) VALUES(?,?,?,'Portal','Approval portal','Delivered approval portal','SAAS','CRM','Java','Built it')",product,seller,product.toString());db.update("INSERT INTO inquiries(id,reference_product_id,developer_user_id,client_email,client_name,request_type,description,budget_band,timeline_band,idempotency_key,request_hash,current_status,email_confirmed_at) VALUES(?,?,?,'care-buyer@example.test','Buyer','CUSTOMIZE','Customer portal care','NEED_ESTIMATE','FLEXIBLE',?,'fixture','COMPLETED',now())",inquiry,product,seller,UUID.randomUUID());
  engagement=UUID.randomUUID();db.update("INSERT INTO delivery_engagements(id,source_inquiry_id,buyer_user_id,builder_user_id,title,created_by,status) VALUES(?,?,?,?,'Delivered portal',?,'COMPLETED')",engagement,inquiry,buyer,seller,seller);milestone=UUID.randomUUID();db.update("INSERT INTO delivery_milestones(id,engagement_id,ordinal,title,description,amount_minor,due_date,status,accepted_by,accepted_at) VALUES(?,?,1,'Portal','Delivered portal',10000,current_date,'ACCEPTED',?,now())",milestone,engagement,buyer);originalPayment=UUID.randomUUID();
  // Disposable synthetic prior live-paid record isolates V4 eligibility; no real merchant charge is asserted.
  db.update("INSERT INTO payment_attempts(id,milestone_id,payer_user_id,idempotency_key,amount_minor,account_id,mode,status,order_id,payment_id,transfer_status) VALUES(?,?,?,?,10000,?,'live','CAPTURED','order_original123456','pay_original123456','PROCESSED')",originalPayment,milestone,buyer,UUID.randomUUID(),MaintenanceFixture.ACCOUNT);db.update("INSERT INTO payment_accounts(id,builder_user_id,account_id,mode,provider_status,activation_confirmed,verified_by) VALUES(?,?,?,'live','created',true,?)",UUID.randomUUID(),seller,MaintenanceFixture.ACCOUNT,admin);
 }
 MockHttpServletRequestBuilder as(MockHttpServletRequestBuilder r,String actor){return r.cookie(new Cookie("gl_session",actor));}
 MockHttpServletRequestBuilder body(MockHttpServletRequestBuilder r,String actor,Object b)throws Exception{return as(r,actor).header("Origin","http://localhost:3000").header("X-Requested-With","getlancer").contentType("application/json").content(json.writeValueAsString(b));}
 JsonNode ok(MockHttpServletRequestBuilder r)throws Exception{return json.readTree(mvc.perform(r).andExpect(status().isOk()).andReturn().getResponse().getContentAsString());}
 Map<String,Object> terms(){return Map.of("engagementId",engagement,"title","Portal care","scope","Bug fixes and small approval workflow improvements.","terms","Includes bounded support. New features need a new agreement. Future billing may be cancelled.","amountMinor",10000,"requestsPerCycle",1,"responseHours",24,"totalCycles",12);}
 UUID draft()throws Exception{return UUID.fromString(ok(body(post("/api/v1/maintenance"),"care-seller",terms())).path("id").asText());}
 String base(UUID offer){return "/api/v1/maintenance/"+offer;}
 UUID accepted()throws Exception{UUID offer=draft();ok(body(post(base(offer)+"/send"),"care-seller",Map.of("consent",true)));String digest=ok(as(get(base(offer)),"care-buyer")).path("digest").asText();ok(body(post(base(offer)+"/accept"),"care-buyer",Map.of("consent",true,"digest",digest)));return offer;}
 JsonNode start(UUID offer)throws Exception{return ok(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",UUID.randomUUID()));}
 UUID paid()throws Exception{UUID offer=accepted();start(offer);fixture.paid=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));return offer;}
 String sign(String secret,String body)throws Exception{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return HexFormat.of().formatHex(mac.doFinal(body.getBytes(StandardCharsets.UTF_8)));}
 @Test void currentPartiesConsentDigestAndFrozenTermsAreRequired()throws Exception{mvc.perform(body(post("/api/v1/maintenance"),"care-outsider",terms())).andExpect(status().isNotFound());UUID offer=draft();mvc.perform(body(post(base(offer)+"/send"),"care-seller",Map.of())).andExpect(status().isBadRequest());ok(body(post(base(offer)+"/send"),"care-seller",Map.of("consent",true)));mvc.perform(body(post(base(offer)+"/accept"),"care-buyer",Map.of("consent",true,"digest","stale"))).andExpect(status().isConflict());db.update("UPDATE developer_profiles SET approval_status='SUSPENDED' WHERE user_id=?",seller);String digest=db.queryForObject("SELECT digest FROM maintenance_offers WHERE id=?",String.class,offer);mvc.perform(body(post(base(offer)+"/accept"),"care-buyer",Map.of("consent",true,"digest",digest))).andExpect(status().isConflict());assertThrows(DataAccessException.class,()->db.update("UPDATE maintenance_offers SET amount_minor=11000 WHERE id=?",offer));}
 @Test void reservationsCommitBeforeEachHttpPostAndRetriesDoNotDuplicate()throws Exception{UUID offer=accepted();mvc.perform(body(post(base(offer)+"/billing"),"care-buyer",Map.of()).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isBadRequest());JsonNode checkout=start(offer);start(offer);assertEquals(1,fixture.plans.get());assertEquals(1,fixture.subscriptions.get());assertTrue(fixture.committedPlan);assertTrue(fixture.committedSubscription);assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());fixture.paid=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertTrue(fixture.committedTransfer);assertEquals(1,fixture.transfers.get());assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(1,fixture.transfers.get());}
 @Test void checkoutUsesSubscriptionSignatureAndNeverGrantsFromActivationAlone()throws Exception{UUID offer=accepted();start(offer);String signature=sign(MaintenanceFixture.SECRET,MaintenanceFixture.PAYMENT+"|"+MaintenanceFixture.SUB);var b=Map.of("razorpay_subscription_id",MaintenanceFixture.SUB,"razorpay_payment_id",MaintenanceFixture.PAYMENT,"razorpay_signature",signature);ok(body(post(base(offer)+"/billing/confirm"),"care-buyer",b));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());var wrong=new HashMap<String,Object>(b);wrong.put("razorpay_signature",sign(MaintenanceFixture.SECRET,MaintenanceFixture.SUB+"|"+MaintenanceFixture.PAYMENT));mvc.perform(body(post(base(offer)+"/billing/confirm"),"care-buyer",wrong)).andExpect(status().isBadRequest());}
 @Test void unknownPlanBlocksRetriesAndMfaRecoveryVerifiesNotes()throws Exception{UUID offer=accepted();fixture.unknownPlan=true;mvc.perform(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isBadGateway());start(offer);assertEquals(1,fixture.plans.get());assertEquals(0,fixture.subscriptions.get());UUID id=db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class);mvc.perform(body(post("/api/v1/admin/maintenance/"+id+"/bind-plan"),"care-buyer",Map.of("providerId",MaintenanceFixture.PLAN,"reason","Verified matching provider plan notes."))).andExpect(status().isForbidden());ok(body(post("/api/v1/admin/maintenance/"+id+"/bind-plan"),"care-admin",Map.of("providerId",MaintenanceFixture.PLAN,"reason","Verified matching provider plan notes.")));assertEquals(1,fixture.subscriptions.get());}
 @Test void uncertainRoutingCannotBeRepeatedAndRequiresExactOperatorBinding()throws Exception{UUID offer=accepted();start(offer);fixture.paid=true;fixture.unknownTransfer=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(1,fixture.transfers.get());assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());UUID subscription=db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class),period=db.queryForObject("SELECT id FROM maintenance_periods",UUID.class);ok(body(post("/api/v1/admin/maintenance/"+subscription+"/bind-transfer"),"care-admin",Map.of("providerId",MaintenanceFixture.TRANSFER,"periodId",period,"reason","Verified one exact invoice transfer in the provider.")));assertEquals(1,fixture.transfers.get());assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());}
 @Test void invoiceMismatchRefundStatusPendingRefundAndMonotonicRefundsHoldService()throws Exception{UUID offer=accepted();start(offer);fixture.paid=true;fixture.wrongInvoice=true;mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());assertEquals(0,fixture.transfers.get());fixture.wrongInvoice=false;fixture.invalidRefundStatus=true;mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());fixture.invalidRefundStatus=false;fixture.pendingRefund=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(0,fixture.transfers.get());fixture.pendingRefund=false;fixture.refunded=1000;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));fixture.refunded=0;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(1000,db.queryForObject("SELECT refunded_minor FROM maintenance_periods",Long.class));assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_refunds",Integer.class));assertEquals(1000,db.queryForObject("SELECT sum(amount_minor) FROM maintenance_ledger WHERE kind='REFUND'",Long.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());}
 @Test void signedDisputeIsFetchedByExactIdEvenBeforeAccountListShowsItAndDeduped()throws Exception{UUID offer=paid();String payload=json.writeValueAsString(Map.of("event","payment.dispute.created","payload",Map.of("dispute",Map.of("entity",Map.of("id",MaintenanceFixture.DISPUTE,"payment_id",MaintenanceFixture.PAYMENT)))));var hook=post("/api/v1/maintenance/razorpay/webhook").contentType("application/json").content(payload).header("X-Razorpay-Event-Id","care-event-1").header("X-Razorpay-Signature",sign(MaintenanceFixture.WEBHOOK,payload));ok(hook);ok(hook);assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_webhook_events",Integer.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());fixture.raiseDispute=true;fixture.listDispute=false;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_provider_disputes WHERE status='open'",Integer.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());fixture.disputeStatus="won";ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());String other=payload+" ";mvc.perform(post("/api/v1/maintenance/razorpay/webhook").content(other).header("X-Razorpay-Event-Id","care-event-1").header("X-Razorpay-Signature",sign(MaintenanceFixture.WEBHOOK,other))).andExpect(status().isConflict());assertThrows(DataAccessException.class,()->db.update("DELETE FROM maintenance_webhook_events"));}
 @Test void quotaStatesAndLateOriginalFinancialHoldAreEnforced()throws Exception{UUID offer=paid();var support=Map.of("title","Approval notification","description","Correct the notification for the second approval reviewer.");UUID key=UUID.randomUUID();String id=ok(body(post(base(offer)+"/requests"),"care-buyer",support).header("Idempotency-Key",key)).path("id").asText();assertEquals(id,ok(body(post(base(offer)+"/requests"),"care-buyer",support).header("Idempotency-Key",key)).path("id").asText());mvc.perform(body(post(base(offer)+"/requests"),"care-buyer",support).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isConflict());mvc.perform(body(post(base(offer)+"/requests/"+id+"/start"),"care-buyer",Map.of())).andExpect(status().isForbidden());ok(body(post(base(offer)+"/requests/"+id+"/start"),"care-seller",Map.of()));ok(body(post(base(offer)+"/requests/"+id+"/submit"),"care-seller",Map.of("deliveryNote","Corrected and verified both reviewer notifications.")));ok(body(post(base(offer)+"/requests/"+id+"/request-revision"),"care-buyer",Map.of("reason","Please include the third reviewer's notification too.")));ok(body(post(base(offer)+"/requests/"+id+"/cancel"),"care-buyer",Map.of()));assertEquals(0,ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("remainingRequests").asInt());assertThrows(DataAccessException.class,()->db.update("DELETE FROM maintenance_requests"));db.update("UPDATE payment_attempts SET refunded_minor=1000 WHERE id=?",originalPayment);assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());mvc.perform(body(post(base(offer)+"/requests"),"care-buyer",support).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isConflict());}
 @Test void cancellationRemainsPossibleWhenSellerIsSuspendedAndDoesNotErasePaidPeriod()throws Exception{UUID offer=paid();fixture.cancelUncertain=true;db.update("UPDATE developer_profiles SET approval_status='SUSPENDED' WHERE user_id=?",seller);ok(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of()));assertEquals(1,fixture.cancels.get());assertTrue(ok(as(get(base(offer)),"care-buyer")).path("billing").path("cancelConfirmed").asBoolean());assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_periods",Integer.class));db.update("UPDATE developer_profiles SET approval_status='APPROVED' WHERE user_id=?",seller);assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());ok(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of()));assertEquals(1,fixture.cancels.get());}
 @Test void cancellationDuringUnboundSubscriptionPersistsAndCancelsLateBinding()throws Exception{UUID offer=accepted();fixture.blockSubscription=true;var pool=Executors.newSingleThreadExecutor();try{var create=pool.submit(()->start(offer));assertTrue(fixture.entered.await(3,TimeUnit.SECONDS));mvc.perform(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of())).andExpect(status().isConflict());assertTrue(db.queryForObject("SELECT cancel_requested FROM maintenance_subscriptions",Boolean.class));fixture.release.countDown();create.get(8,TimeUnit.SECONDS);assertEquals(1,fixture.subscriptions.get());assertEquals(1,fixture.cancels.get());assertTrue(db.queryForObject("SELECT cancel_confirmed FROM maintenance_subscriptions",Boolean.class));}finally{fixture.release.countDown();pool.shutdownNow();}}
 @Test void exportsAreScopedAndOrdinarySessionsCannotOperateRecovery()throws Exception{UUID offer=paid();var export=ok(as(get("/api/v1/me/export"),"care-buyer"));assertEquals(1,export.path("maintenanceBilling").size());assertEquals(1,export.path("maintenancePeriods").size());assertEquals(0,ok(as(get("/api/v1/me/export"),"care-outsider")).path("maintenanceBilling").size());mvc.perform(as(get("/api/v1/admin/maintenance/attention"),"care-buyer")).andExpect(status().isForbidden());db.update("UPDATE sessions SET mfa_verified=false WHERE user_id=?",admin);mvc.perform(as(get("/api/v1/admin/maintenance/attention"),"care-admin")).andExpect(status().isForbidden());}
 @Test void accountDeletionWaitsForConfirmedBillingButDefinitiveRejectionDoesNotTrapAccount()throws Exception{UUID offer=accepted();start(offer);String token="care-delete-token-123456789012345";db.update("INSERT INTO account_tokens(id,token_hash,kind,user_id,email,expires_at) VALUES(?,?,'ACCOUNT_DELETION',?,'care-buyer@example.test',now()+interval '1 hour')",UUID.randomUUID(),Support.hash(token),buyer);mvc.perform(body(post("/api/v1/auth/confirm"),"care-buyer",Map.of("token",token,"decision","DELETE"))).andExpect(status().isConflict());ok(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of()));ok(body(post("/api/v1/auth/confirm"),"care-buyer",Map.of("token",token,"decision","DELETE")));assertEquals("DELETED",db.queryForObject("SELECT account_status FROM users WHERE id=?",String.class,buyer));assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_subscriptions",Integer.class));}
 @Test void definitivelyRejectedPlanAllowsNewTermsAndAccountClosure()throws Exception{UUID offer=accepted();fixture.rejectPlan=true;mvc.perform(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isBadGateway());UUID fresh=draft();assertNotEquals(offer,fresh);String token="care-rejected-delete-token-123456789";db.update("INSERT INTO account_tokens(id,token_hash,kind,user_id,email,expires_at) VALUES(?,?,'ACCOUNT_DELETION',?,'care-buyer@example.test',now()+interval '1 hour')",UUID.randomUUID(),Support.hash(token),buyer);ok(body(post("/api/v1/auth/confirm"),"care-buyer",Map.of("token",token,"decision","DELETE")));assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_subscriptions WHERE status='REJECTED'",Integer.class));}
 @Test void testModePaidPeriodNeverGrantsRealSupport()throws Exception{UUID offer=accepted(),subscription=UUID.randomUUID(),period=UUID.randomUUID();String digest=db.queryForObject("SELECT digest FROM maintenance_offers WHERE id=?",String.class,offer);db.update("INSERT INTO maintenance_subscriptions(id,engagement_id,offer_id,payer_id,request_key,amount_minor,currency,requests_per_cycle,response_hours,total_cycles,digest,account_id,mode,status,creation_step,plan_state,subscription_state,provider_plan_id,provider_subscription_id,reconciled_at) VALUES(?,?,?,?,?,10000,'INR',1,24,12,?,?,'test','ACTIVE','COMPLETE','CONFIRMED','CONFIRMED',?,?,now())",subscription,engagement,offer,buyer,UUID.randomUUID(),digest,MaintenanceFixture.ACCOUNT,MaintenanceFixture.PLAN,MaintenanceFixture.SUB);db.update("INSERT INTO maintenance_periods(id,subscription_id,provider_invoice_id,payment_id,order_id,amount_minor,currency,period_start,period_end,transfer_key,transfer_state,transfer_id,transfer_status,reconciled_at) VALUES(?,?,?,?,?,10000,'INR',now()-interval '1 day',now()+interval '20 days',?,'CONFIRMED',?,'CREATED',now())",period,subscription,MaintenanceFixture.INVOICE,MaintenanceFixture.PAYMENT,"order_fixture123456",UUID.randomUUID(),MaintenanceFixture.TRANSFER);assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());mvc.perform(body(post(base(offer)+"/requests"),"care-buyer",Map.of("title","Real support request","description","A test payment must not authorize any real support work.")).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isConflict());assertEquals(0,db.queryForObject("SELECT count(*) FROM maintenance_requests",Integer.class));}

 @Test void simultaneousRequestsCannotExceedOnePeriodQuota()throws Exception{UUID offer=paid();var pool=Executors.newFixedThreadPool(2);try{var work=new ArrayList<Callable<Integer>>();for(int n=0;n<2;n++){UUID key=UUID.randomUUID();work.add(()->mvc.perform(body(post(base(offer)+"/requests"),"care-buyer",Map.of("title","Concurrent support","description","Only one of these requests may consume the last paid-period slot.")).header("Idempotency-Key",key)).andReturn().getResponse().getStatus());}for(var result:pool.invokeAll(work)){int status=result.get();assertTrue(status==200||status==409,"Unexpected concurrent result "+status);}assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_requests",Integer.class));}finally{pool.shutdownNow();}}

 @Test void existingRequestActionsRefreshHoldsAndOperatorSeesFinancialAttention()throws Exception{
  UUID offer=paid();String request=ok(body(post(base(offer)+"/requests"),"care-buyer",Map.of("title","Notification fix","description","Correct the approval notification for the second reviewer.")).header("Idempotency-Key",UUID.randomUUID())).path("id").asText();
  fixture.invalidRefundStatus=true;mvc.perform(body(post(base(offer)+"/requests/"+request+"/start"),"care-seller",Map.of())).andExpect(status().isConflict());assertEquals("OPEN",db.queryForObject("SELECT status FROM maintenance_requests",String.class));
  fixture.invalidRefundStatus=false;fixture.pendingRefund=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));var attention=ok(as(get("/api/v1/admin/maintenance/attention"),"care-admin"));assertEquals(1,attention.path("items").size());assertTrue(attention.path("items").get(0).path("periods").get(0).path("pendingRefund").asBoolean());mvc.perform(body(post(base(offer)+"/requests/"+request+"/start"),"care-seller",Map.of())).andExpect(status().isConflict());
  fixture.pendingRefund=false;fixture.failedRefund=true;ok(body(post(base(offer)+"/requests/"+request+"/start"),"care-seller",Map.of()));assertEquals("IN_PROGRESS",db.queryForObject("SELECT status FROM maintenance_requests",String.class));
 }

 @Test void tooManySignedDisputeReferencesRemainPendingAndCannotMarkFresh()throws Exception{
  UUID offer=paid();for(int n=0;n<501;n++)db.update("INSERT INTO maintenance_webhook_events(event_id,payload_hash,event_kind,payment_id,dispute_id) VALUES(?,repeat('a',64),'payment.dispute.created',?,?)","care-cap-"+n,MaintenanceFixture.PAYMENT,"disp_bounded"+n);
  mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());assertNull(db.queryForObject("SELECT reconciled_at FROM maintenance_subscriptions",java.sql.Timestamp.class));assertEquals(501,db.queryForObject("SELECT count(*) FROM maintenance_webhook_events WHERE processed_at IS NULL",Integer.class));assertEquals(1,fixture.transfers.get());assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());
 }

 @Test void expiredPeriodDeniesNewRequestsButRetainedExistingWorkCanContinue()throws Exception{
  fixture.period(true);UUID offer=accepted();start(offer);fixture.paid=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));UUID subscription=db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class),period=db.queryForObject("SELECT id FROM maintenance_periods",UUID.class),request=UUID.randomUUID();
  // Disposable historical request fixture models work opened during this now-expired period.
  db.update("INSERT INTO maintenance_requests(id,subscription_id,period_id,actor_id,request_key,title,description,response_due_at,created_at) VALUES(?,?,?,?,?,'Prior care request','Retained work opened while the historical period was paid.',now()-interval '1 day',now()-interval '2 days')",request,subscription,period,buyer,UUID.randomUUID());
  assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());mvc.perform(body(post(base(offer)+"/requests"),"care-buyer",Map.of("title","New care request","description","New requests require a currently active paid invoice period.")).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isConflict());
  ok(body(post(base(offer)+"/requests/"+request+"/start"),"care-seller",Map.of()));assertEquals("IN_PROGRESS",db.queryForObject("SELECT status FROM maintenance_requests",String.class));mvc.perform(body(post(base(offer)+"/requests/"+UUID.randomUUID()+"/start"),"care-seller",Map.of())).andExpect(status().isNotFound());
 }

 @Test void failedCancellationPreflightRetainsAuditedVisibleIntentWithoutInventingAnAttempt()throws Exception{
  UUID offer=paid();fixture.failSubscriptionGet=true;mvc.perform(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of())).andExpect(status().isBadGateway());assertTrue(db.queryForObject("SELECT cancel_requested FROM maintenance_subscriptions",Boolean.class));assertNull(db.queryForObject("SELECT cancel_state FROM maintenance_subscriptions",String.class));assertEquals(0,fixture.cancels.get());assertEquals(1,ok(as(get("/api/v1/admin/maintenance/attention"),"care-admin")).path("items").size());assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_audit WHERE kind='CANCELLATION_INTENT_REQUESTED'",Integer.class));
  fixture.failSubscriptionGet=false;ok(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of()));assertEquals(1,fixture.cancels.get());assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());
 }

}
