package com.getlancer.integration;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.fasterxml.jackson.databind.*;
import com.getlancer.payments.MaintenanceFixture;
import com.getlancer.payments.PaymentRepository;
import com.getlancer.payments.RazorpayClient;
import com.getlancer.maintenance.*;
import com.getlancer.security.Security;
import com.getlancer.shared.Support;
import com.getlancer.shared.ApiError;
import com.getlancer.testing.TestDatabaseGuard;
import jakarta.servlet.http.Cookie;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.transaction.PlatformTransactionManager;
@org.springframework.test.context.ContextConfiguration(initializers=TestDatabaseGuard.class)
@SpringBootTest(properties={"app.environment=local","app.jobs-enabled=false","app.admin-email=admin@example.test","app.admin-password=","app.admin-totp=","spring.config.import=",
 "spring.datasource.url=${TEST_DB_URL:jdbc:postgresql://localhost:5432/getlancer_test}","spring.datasource.username=${TEST_DB_USERNAME:postgres}","spring.datasource.password=${TEST_DB_PASSWORD:}",
 "spring.datasource.hikari.schema=getlancer_test","spring.flyway.default-schema=getlancer_test","spring.flyway.schemas=getlancer_test","app.origin=http://localhost:3000","app.secure-cookie=false","app.storage.access-key=","app.storage.secret-key=","app.maintenance.enabled=true","app.maintenance.subscriptions-approved=true","app.maintenance.webhook-secret=fixture-webhook-not-for-production"})
@AutoConfigureMockMvc
@Import(MaintenanceFixture.Configuration.class)
class MaintenanceIntegrationTest {
 @Autowired JdbcTemplate db;@Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired MaintenanceFixture fixture;
 @Autowired MaintenanceRepository repository;@Autowired MaintenanceAccess access;@Autowired PaymentRepository payments;@Autowired RazorpayClient provider;@Autowired Security security;@Autowired PlatformTransactionManager transactions;
 UUID buyer,seller,admin,engagement,milestone,originalPayment;
 UUID user(String name,boolean approved){UUID id=UUID.randomUUID();db.update("INSERT INTO users(id,email,password_hash,email_verified_at) VALUES(?,?,'unused',now())",id,name+"@example.test");db.update("INSERT INTO user_roles(user_id,role) VALUES(?,'CLIENT'),(?,'DEVELOPER')",id,id);db.update("INSERT INTO developer_profiles(user_id,slug,display_name,approval_status) VALUES(?,?,?,?)",id,name,name,approved?"APPROVED":"DRAFT");db.update("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,now()+interval '1 hour')",Support.hash(name),id);return id;}
 @BeforeEach void setup(){db.execute("TRUNCATE users CASCADE");db.execute("TRUNCATE rate_buckets");db.execute("TRUNCATE maintenance_webhook_events");fixture.reset();fixture.period(false);buyer=user("care-buyer",false);seller=user("care-seller",true);user("care-outsider",false);admin=user("care-admin",false);db.update("UPDATE users SET email='admin@example.test' WHERE id=?",admin);db.update("INSERT INTO user_roles(user_id,role) VALUES(?,'ADMIN')",admin);db.update("UPDATE sessions SET mfa_verified=true WHERE user_id=?",admin);
  UUID product=UUID.randomUUID(),inquiry=UUID.randomUUID();db.update("INSERT INTO products(id,owner_user_id,slug,title,summary,description,project_type,category,technology,contribution_text) VALUES(?,?,?,'Portal','Approval portal','Delivered approval portal','SAAS','CRM','Java','Built it')",product,seller,product.toString());db.update("INSERT INTO inquiries(id,reference_product_id,developer_user_id,client_email,client_name,request_type,description,budget_band,timeline_band,idempotency_key,request_hash,current_status,email_confirmed_at) VALUES(?,?,?,'care-buyer@example.test','Buyer','CUSTOMIZE','Customer portal care','NEED_ESTIMATE','FLEXIBLE',?,'fixture','COMPLETED',now())",inquiry,product,seller,UUID.randomUUID());
  engagement=UUID.randomUUID();db.update("INSERT INTO delivery_engagements(id,source_inquiry_id,buyer_user_id,builder_user_id,title,created_by,status) VALUES(?,?,?,?,'Delivered portal',?,'COMPLETED')",engagement,inquiry,buyer,seller,seller);milestone=UUID.randomUUID();db.update("INSERT INTO delivery_milestones(id,engagement_id,ordinal,title,description,amount_minor,due_date,status,accepted_by,accepted_at) VALUES(?,?,1,'Portal','Delivered portal',10000,current_date,'ACCEPTED',?,now())",milestone,engagement,buyer);originalPayment=UUID.randomUUID();
  // Disposable synthetic prior live-paid record isolates V4 eligibility; no real merchant charge is asserted.
  db.update("INSERT INTO payment_attempts(id,milestone_id,payer_user_id,idempotency_key,amount_minor,account_id,mode,status,order_id,payment_id,transfer_status) VALUES(?,?,?,?,10000,?,'live','CAPTURED','order_original123456','pay_original123456','PROCESSED')",originalPayment,milestone,buyer,UUID.randomUUID(),MaintenanceFixture.ACCOUNT);db.update("INSERT INTO payment_accounts(id,builder_user_id,account_id,mode,provider_status,activation_confirmed,verified_by) VALUES(?,?,?,'live','created',true,?)",UUID.randomUUID(),seller,MaintenanceFixture.ACCOUNT,admin);
 }
 MockHttpServletRequestBuilder as(MockHttpServletRequestBuilder r,String actor){return r.cookie(new Cookie("gl_session",actor));}
 MockHttpServletRequestBuilder body(MockHttpServletRequestBuilder r,String actor,Object b)throws Exception{return as(r,actor).header("Origin","http://localhost:3000").header("X-Requested-With","getlancer").contentType("application/json").content(json.writeValueAsString(b));}
 JsonNode ok(MockHttpServletRequestBuilder r)throws Exception{return json.readTree(mvc.perform(r).andExpect(status().isOk()).andReturn().getResponse().getContentAsString());}
 Map<String,Object> terms(){return Map.of("engagementId",engagement,"title","Portal care","scope","Bug fixes and small approval workflow improvements.","terms","Includes bounded support. New features need a new agreement. Future billing may be cancelled.","amountMinor",10000,"requestsPerCycle",1,"responseHours",24,"totalCycles",12);}
 UUID draft()throws Exception{return UUID.fromString(ok(body(post("/api/v1/maintenance"),"care-seller",terms())).path("id").asText());}
 String base(UUID offer){return "/api/v1/maintenance/"+offer;}
 UUID accepted()throws Exception{UUID offer=draft();ok(body(post(base(offer)+"/send"),"care-seller",Map.of("consent",true)));String digest=ok(as(get(base(offer)),"care-buyer")).path("digest").asText();ok(body(post(base(offer)+"/accept"),"care-buyer",Map.of("consent",true,"digest",digest)));return offer;}
 JsonNode start(UUID offer)throws Exception{return ok(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",UUID.randomUUID()));}
 UUID paid()throws Exception{UUID offer=accepted();start(offer);fixture.paid=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));return offer;}
 String sign(String secret,String body)throws Exception{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return HexFormat.of().formatHex(mac.doFinal(body.getBytes(StandardCharsets.UTF_8)));}
 void automaticPass(){new MaintenanceBillingService(repository,access,payments,provider,security,json,transactions,true,true,MaintenanceFixture.WEBHOOK,true).pending();}
 void refundEvent(String event)throws Exception{String payload=json.writeValueAsString(Map.of("event","refund.created","payload",Map.of("refund",Map.of("entity",Map.of("id",MaintenanceFixture.REFUND,"payment_id",MaintenanceFixture.PAYMENT)))));ok(post("/api/v1/maintenance/razorpay/webhook").contentType("application/json").content(payload).header("X-Razorpay-Event-Id",event).header("X-Razorpay-Signature",sign(MaintenanceFixture.WEBHOOK,payload)));}
 String operator(UUID id,String action){return "/api/v1/admin/maintenance/"+id+"/"+action;}
 UUID boundPlanWithoutSubscription()throws Exception{
  UUID offer=accepted();fixture.blockPlan=true;var pool=Executors.newSingleThreadExecutor();try{var start=pool.submit(()->mvc.perform(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",UUID.randomUUID())).andReturn().getResponse().getStatus());assertTrue(fixture.entered.await(3,TimeUnit.SECONDS));db.update("UPDATE developer_profiles SET approval_status='SUSPENDED' WHERE user_id=?",seller);fixture.release.countDown();assertEquals(409,start.get(8,TimeUnit.SECONDS));}finally{fixture.release.countDown();pool.shutdownNow();fixture.blockPlan=false;}
  assertEquals(1,fixture.plans.get());assertEquals(0,fixture.subscriptions.get());assertEquals("CONFIRMED",db.queryForObject("SELECT plan_state FROM maintenance_subscriptions",String.class));assertEquals("NOT_CREATED",db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions",String.class));db.update("UPDATE developer_profiles SET approval_status='APPROVED' WHERE user_id=?",seller);return db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class);
 }
 void noSubscriptionRetry(UUID offer,UUID id,String state)throws Exception{
  assertEquals("CONFIRMED",db.queryForObject("SELECT plan_state FROM maintenance_subscriptions WHERE id=?",String.class,id));assertEquals(MaintenanceFixture.PLAN,db.queryForObject("SELECT provider_plan_id FROM maintenance_subscriptions WHERE id=?",String.class,id));assertEquals("SUBSCRIPTION",db.queryForObject("SELECT creation_step FROM maintenance_subscriptions WHERE id=?",String.class,id));assertEquals(state,db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions WHERE id=?",String.class,id));assertNull(db.queryForObject("SELECT provider_subscription_id FROM maintenance_subscriptions WHERE id=?",String.class,id));UUID key=db.queryForObject("SELECT request_key FROM maintenance_subscriptions WHERE id=?",UUID.class,id);ok(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",key));start(offer);mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",Map.of("reason","Previously attempted subscription creation must never be retried."))).andExpect(status().isConflict());assertEquals(state,db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions WHERE id=?",String.class,id));assertTrue(fixture.committedSubscription);assertEquals(1,fixture.plans.get());assertEquals(1,fixture.subscriptions.get());
 }
 void recoverCreatedSubscription(UUID id)throws Exception{
  ok(body(post(operator(id,"bind-subscription")),"care-admin",Map.of("providerId",MaintenanceFixture.SUB,"reason","Verified exact provider subscription identity and frozen agreement facts.")));assertEquals("CONFIRMED",db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions WHERE id=?",String.class,id));assertEquals("CONFIRMED",db.queryForObject("SELECT plan_state FROM maintenance_subscriptions WHERE id=?",String.class,id));assertEquals(MaintenanceFixture.SUB,db.queryForObject("SELECT provider_subscription_id FROM maintenance_subscriptions WHERE id=?",String.class,id));assertEquals(1,fixture.plans.get());assertEquals(1,fixture.subscriptions.get());
 }
 @Test void currentPartiesConsentDigestAndFrozenTermsAreRequired()throws Exception{mvc.perform(body(post("/api/v1/maintenance"),"care-outsider",terms())).andExpect(status().isNotFound());UUID offer=draft();mvc.perform(body(post(base(offer)+"/send"),"care-seller",Map.of())).andExpect(status().isBadRequest());ok(body(post(base(offer)+"/send"),"care-seller",Map.of("consent",true)));mvc.perform(body(post(base(offer)+"/accept"),"care-buyer",Map.of("consent",true,"digest","stale"))).andExpect(status().isConflict());db.update("UPDATE developer_profiles SET approval_status='SUSPENDED' WHERE user_id=?",seller);String digest=db.queryForObject("SELECT digest FROM maintenance_offers WHERE id=?",String.class,offer);mvc.perform(body(post(base(offer)+"/accept"),"care-buyer",Map.of("consent",true,"digest",digest))).andExpect(status().isConflict());assertThrows(DataAccessException.class,()->db.update("UPDATE maintenance_offers SET amount_minor=11000 WHERE id=?",offer));}
 @Test void reservationsCommitBeforeEachHttpPostAndRetriesDoNotDuplicate()throws Exception{UUID offer=accepted();mvc.perform(body(post(base(offer)+"/billing"),"care-buyer",Map.of()).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isBadRequest());JsonNode checkout=start(offer);start(offer);assertEquals(1,fixture.plans.get());assertEquals(1,fixture.subscriptions.get());assertTrue(fixture.committedPlan);assertTrue(fixture.committedSubscription);assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());fixture.paid=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertTrue(fixture.committedTransfer);assertEquals(1,fixture.transfers.get());assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(1,fixture.transfers.get());}
 @Test void checkoutUsesSubscriptionSignatureAndNeverGrantsFromActivationAlone()throws Exception{UUID offer=accepted();start(offer);String signature=sign(MaintenanceFixture.SECRET,MaintenanceFixture.PAYMENT+"|"+MaintenanceFixture.SUB);var b=Map.of("razorpay_subscription_id",MaintenanceFixture.SUB,"razorpay_payment_id",MaintenanceFixture.PAYMENT,"razorpay_signature",signature);ok(body(post(base(offer)+"/billing/confirm"),"care-buyer",b));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());var wrong=new HashMap<String,Object>(b);wrong.put("razorpay_signature",sign(MaintenanceFixture.SECRET,MaintenanceFixture.SUB+"|"+MaintenanceFixture.PAYMENT));mvc.perform(body(post(base(offer)+"/billing/confirm"),"care-buyer",wrong)).andExpect(status().isBadRequest());}
 @Test void unknownPlanBlocksRetriesAndMfaRecoveryVerifiesNotes()throws Exception{UUID offer=accepted();fixture.unknownPlan=true;mvc.perform(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isBadGateway());start(offer);assertEquals(1,fixture.plans.get());assertEquals(0,fixture.subscriptions.get());UUID id=db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class);mvc.perform(body(post("/api/v1/admin/maintenance/"+id+"/bind-plan"),"care-buyer",Map.of("providerId",MaintenanceFixture.PLAN,"reason","Verified matching provider plan notes."))).andExpect(status().isForbidden());ok(body(post("/api/v1/admin/maintenance/"+id+"/bind-plan"),"care-admin",Map.of("providerId",MaintenanceFixture.PLAN,"reason","Verified matching provider plan notes.")));assertEquals(1,fixture.subscriptions.get());}
 @Test void uncertainRoutingCannotBeRepeatedAndRequiresExactOperatorBinding()throws Exception{UUID offer=accepted();start(offer);fixture.paid=true;fixture.unknownTransfer=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(1,fixture.transfers.get());assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());UUID subscription=db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class),period=db.queryForObject("SELECT id FROM maintenance_periods",UUID.class);ok(body(post("/api/v1/admin/maintenance/"+subscription+"/bind-transfer"),"care-admin",Map.of("providerId",MaintenanceFixture.TRANSFER,"periodId",period,"reason","Verified one exact invoice transfer in the provider.")));assertEquals(1,fixture.transfers.get());assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());}
 @Test void invoiceMismatchRefundStatusPendingRefundAndMonotonicRefundsHoldService()throws Exception{UUID offer=accepted();start(offer);fixture.paid=true;fixture.wrongInvoice=true;mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());assertEquals(0,fixture.transfers.get());fixture.wrongInvoice=false;fixture.invalidRefundStatus=true;mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());fixture.invalidRefundStatus=false;fixture.pendingRefund=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(0,fixture.transfers.get());fixture.pendingRefund=false;fixture.refunded=1000;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));fixture.refunded=0;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(1000,db.queryForObject("SELECT refunded_minor FROM maintenance_periods",Long.class));assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_refunds",Integer.class));assertEquals(1000,db.queryForObject("SELECT sum(amount_minor) FROM maintenance_ledger WHERE kind='REFUND'",Long.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());}
 @Test void signedDisputeIsFetchedByExactIdEvenBeforeAccountListShowsItAndDeduped()throws Exception{UUID offer=paid();String payload=json.writeValueAsString(Map.of("event","payment.dispute.created","payload",Map.of("dispute",Map.of("entity",Map.of("id",MaintenanceFixture.DISPUTE,"payment_id",MaintenanceFixture.PAYMENT)))));var hook=post("/api/v1/maintenance/razorpay/webhook").contentType("application/json").content(payload).header("X-Razorpay-Event-Id","care-event-1").header("X-Razorpay-Signature",sign(MaintenanceFixture.WEBHOOK,payload));ok(hook);ok(hook);assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_webhook_events",Integer.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());fixture.raiseDispute=true;fixture.listDispute=false;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_provider_disputes WHERE status='open'",Integer.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());fixture.disputeStatus="won";ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());String other=payload+" ";mvc.perform(post("/api/v1/maintenance/razorpay/webhook").content(other).header("X-Razorpay-Event-Id","care-event-1").header("X-Razorpay-Signature",sign(MaintenanceFixture.WEBHOOK,other))).andExpect(status().isConflict());assertThrows(DataAccessException.class,()->db.update("DELETE FROM maintenance_webhook_events"));}
 @Test void quotaStatesAndLateOriginalFinancialHoldAreEnforced()throws Exception{UUID offer=paid();var support=Map.of("title","Approval notification","description","Correct the notification for the second approval reviewer.");UUID key=UUID.randomUUID();String id=ok(body(post(base(offer)+"/requests"),"care-buyer",support).header("Idempotency-Key",key)).path("id").asText();assertEquals(id,ok(body(post(base(offer)+"/requests"),"care-buyer",support).header("Idempotency-Key",key)).path("id").asText());mvc.perform(body(post(base(offer)+"/requests"),"care-buyer",support).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isConflict());mvc.perform(body(post(base(offer)+"/requests/"+id+"/start"),"care-buyer",Map.of())).andExpect(status().isForbidden());ok(body(post(base(offer)+"/requests/"+id+"/start"),"care-seller",Map.of()));ok(body(post(base(offer)+"/requests/"+id+"/submit"),"care-seller",Map.of("deliveryNote","Corrected and verified both reviewer notifications.")));ok(body(post(base(offer)+"/requests/"+id+"/request-revision"),"care-buyer",Map.of("reason","Please include the third reviewer's notification too.")));ok(body(post(base(offer)+"/requests/"+id+"/cancel"),"care-buyer",Map.of()));assertEquals(0,ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("remainingRequests").asInt());assertThrows(DataAccessException.class,()->db.update("DELETE FROM maintenance_requests"));db.update("UPDATE payment_attempts SET refunded_minor=1000 WHERE id=?",originalPayment);assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());mvc.perform(body(post(base(offer)+"/requests"),"care-buyer",support).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isConflict());}
 @Test void cancellationRemainsPossibleWhenSellerIsSuspendedAndDoesNotErasePaidPeriod()throws Exception{UUID offer=paid();fixture.cancelUncertain=true;db.update("UPDATE developer_profiles SET approval_status='SUSPENDED' WHERE user_id=?",seller);ok(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of()));assertEquals(1,fixture.cancels.get());assertTrue(ok(as(get(base(offer)),"care-buyer")).path("billing").path("cancelConfirmed").asBoolean());assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_periods",Integer.class));db.update("UPDATE developer_profiles SET approval_status='APPROVED' WHERE user_id=?",seller);assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());ok(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of()));assertEquals(1,fixture.cancels.get());}
 @Test void cancellationDuringUnboundSubscriptionPersistsAndCancelsLateBinding()throws Exception{UUID offer=accepted();fixture.blockSubscription=true;var pool=Executors.newSingleThreadExecutor();try{var create=pool.submit(()->start(offer));assertTrue(fixture.entered.await(3,TimeUnit.SECONDS));mvc.perform(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of())).andExpect(status().isConflict());assertTrue(db.queryForObject("SELECT cancel_requested FROM maintenance_subscriptions",Boolean.class));fixture.release.countDown();create.get(8,TimeUnit.SECONDS);assertEquals(1,fixture.subscriptions.get());assertEquals(1,fixture.cancels.get());assertTrue(db.queryForObject("SELECT cancel_confirmed FROM maintenance_subscriptions",Boolean.class));}finally{fixture.release.countDown();pool.shutdownNow();}}
 @Test void exportsAreScopedAndOrdinarySessionsCannotOperateRecovery()throws Exception{UUID offer=paid();var export=ok(as(get("/api/v1/me/export"),"care-buyer"));assertEquals(1,export.path("maintenanceBilling").size());assertEquals(1,export.path("maintenancePeriods").size());assertEquals(0,ok(as(get("/api/v1/me/export"),"care-outsider")).path("maintenanceBilling").size());mvc.perform(as(get("/api/v1/admin/maintenance/attention"),"care-buyer")).andExpect(status().isForbidden());db.update("UPDATE sessions SET mfa_verified=false WHERE user_id=?",admin);mvc.perform(as(get("/api/v1/admin/maintenance/attention"),"care-admin")).andExpect(status().isForbidden());}
 @Test void accountDeletionWaitsForConfirmedBillingButDefinitiveRejectionDoesNotTrapAccount()throws Exception{UUID offer=accepted();start(offer);String token="care-delete-token-123456789012345";db.update("INSERT INTO account_tokens(id,token_hash,kind,user_id,email,expires_at) VALUES(?,?,'ACCOUNT_DELETION',?,'care-buyer@example.test',now()+interval '1 hour')",UUID.randomUUID(),Support.hash(token),buyer);mvc.perform(body(post("/api/v1/auth/confirm"),"care-buyer",Map.of("token",token,"decision","DELETE"))).andExpect(status().isConflict());ok(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of()));ok(body(post("/api/v1/auth/confirm"),"care-buyer",Map.of("token",token,"decision","DELETE")));assertEquals("DELETED",db.queryForObject("SELECT account_status FROM users WHERE id=?",String.class,buyer));assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_subscriptions",Integer.class));}
 @Test void definitivelyRejectedPlanAllowsNewTermsAndAccountClosure()throws Exception{UUID offer=accepted();fixture.rejectPlan=true;mvc.perform(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isBadGateway());UUID fresh=draft();assertNotEquals(offer,fresh);String token="care-rejected-delete-token-123456789";db.update("INSERT INTO account_tokens(id,token_hash,kind,user_id,email,expires_at) VALUES(?,?,'ACCOUNT_DELETION',?,'care-buyer@example.test',now()+interval '1 hour')",UUID.randomUUID(),Support.hash(token),buyer);ok(body(post("/api/v1/auth/confirm"),"care-buyer",Map.of("token",token,"decision","DELETE")));assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_subscriptions WHERE status='REJECTED'",Integer.class));}
 @Test void testModePaidPeriodNeverGrantsRealSupport()throws Exception{UUID offer=accepted(),subscription=UUID.randomUUID(),period=UUID.randomUUID();String digest=db.queryForObject("SELECT digest FROM maintenance_offers WHERE id=?",String.class,offer);db.update("INSERT INTO maintenance_subscriptions(id,engagement_id,offer_id,payer_id,request_key,amount_minor,currency,requests_per_cycle,response_hours,total_cycles,digest,account_id,mode,status,creation_step,plan_state,subscription_state,provider_plan_id,provider_subscription_id,reconciled_at) VALUES(?,?,?,?,?,10000,'INR',1,24,12,?,?,'test','ACTIVE','COMPLETE','CONFIRMED','CONFIRMED',?,?,now())",subscription,engagement,offer,buyer,UUID.randomUUID(),digest,MaintenanceFixture.ACCOUNT,MaintenanceFixture.PLAN,MaintenanceFixture.SUB);db.update("INSERT INTO maintenance_periods(id,subscription_id,provider_invoice_id,payment_id,order_id,amount_minor,currency,period_start,period_end,transfer_key,transfer_state,transfer_id,transfer_status,reconciled_at) VALUES(?,?,?,?,?,10000,'INR',now()-interval '1 day',now()+interval '20 days',?,'CONFIRMED',?,'CREATED',now())",period,subscription,MaintenanceFixture.INVOICE,MaintenanceFixture.PAYMENT,"order_fixture123456",UUID.randomUUID(),MaintenanceFixture.TRANSFER);assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());mvc.perform(body(post(base(offer)+"/requests"),"care-buyer",Map.of("title","Real support request","description","A test payment must not authorize any real support work.")).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isConflict());assertEquals(0,db.queryForObject("SELECT count(*) FROM maintenance_requests",Integer.class));}

 @Test void simultaneousRequestsCannotExceedOnePeriodQuota()throws Exception{UUID offer=paid();var pool=Executors.newFixedThreadPool(2);try{var work=new ArrayList<Callable<Integer>>();for(int n=0;n<2;n++){UUID key=UUID.randomUUID();work.add(()->mvc.perform(body(post(base(offer)+"/requests"),"care-buyer",Map.of("title","Concurrent support","description","Only one of these requests may consume the last paid-period slot.")).header("Idempotency-Key",key)).andReturn().getResponse().getStatus());}for(var result:pool.invokeAll(work)){int status=result.get();assertTrue(status==200||status==409,"Unexpected concurrent result "+status);}assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_requests",Integer.class));}finally{pool.shutdownNow();}}

 @Test void existingRequestActionsRefreshHoldsAndOperatorSeesFinancialAttention()throws Exception{
  UUID offer=paid();String request=ok(body(post(base(offer)+"/requests"),"care-buyer",Map.of("title","Notification fix","description","Correct the approval notification for the second reviewer.")).header("Idempotency-Key",UUID.randomUUID())).path("id").asText();
  fixture.invalidRefundStatus=true;mvc.perform(body(post(base(offer)+"/requests/"+request+"/start"),"care-seller",Map.of())).andExpect(status().isConflict());assertEquals("OPEN",db.queryForObject("SELECT status FROM maintenance_requests",String.class));
  fixture.invalidRefundStatus=false;fixture.pendingRefund=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));var attention=ok(as(get("/api/v1/admin/maintenance/attention"),"care-admin"));assertEquals(1,attention.path("items").size());assertTrue(attention.path("items").get(0).path("periods").get(0).path("pendingRefund").asBoolean());mvc.perform(body(post(base(offer)+"/requests/"+request+"/start"),"care-seller",Map.of())).andExpect(status().isConflict());
  fixture.pendingRefund=false;fixture.failedRefund=true;ok(body(post(base(offer)+"/requests/"+request+"/start"),"care-seller",Map.of()));assertEquals("IN_PROGRESS",db.queryForObject("SELECT status FROM maintenance_requests",String.class));
 }

 @Test void tooManySignedDisputeReferencesRemainPendingAndCannotMarkFresh()throws Exception{
  UUID offer=paid();for(int n=0;n<501;n++)db.update("INSERT INTO maintenance_webhook_events(event_id,payload_hash,event_kind,payment_id,dispute_id) VALUES(?,repeat('a',64),'payment.dispute.created',?,?)","care-cap-"+n,MaintenanceFixture.PAYMENT,"disp_bounded"+n);
  mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());assertNull(db.queryForObject("SELECT reconciled_at FROM maintenance_subscriptions",java.sql.Timestamp.class));assertEquals(501,db.queryForObject("SELECT count(*) FROM maintenance_webhook_events WHERE processed_at IS NULL",Integer.class));assertEquals(1,fixture.transfers.get());assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());
 }

 @Test void expiredPeriodDeniesNewRequestsButRetainedExistingWorkCanContinue()throws Exception{
  fixture.period(true);UUID offer=accepted();start(offer);fixture.paid=true;ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));UUID subscription=db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class),period=db.queryForObject("SELECT id FROM maintenance_periods",UUID.class),request=UUID.randomUUID();
  // Disposable historical request fixture models work opened during this now-expired period.
  db.update("INSERT INTO maintenance_requests(id,subscription_id,period_id,actor_id,request_key,title,description,response_due_at,created_at) VALUES(?,?,?,?,?,'Prior care request','Retained work opened while the historical period was paid.',now()-interval '1 day',now()-interval '2 days')",request,subscription,period,buyer,UUID.randomUUID());
  assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());mvc.perform(body(post(base(offer)+"/requests"),"care-buyer",Map.of("title","New care request","description","New requests require a currently active paid invoice period.")).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isConflict());
  ok(body(post(base(offer)+"/requests/"+request+"/start"),"care-seller",Map.of()));assertEquals("IN_PROGRESS",db.queryForObject("SELECT status FROM maintenance_requests",String.class));mvc.perform(body(post(base(offer)+"/requests/"+UUID.randomUUID()+"/start"),"care-seller",Map.of())).andExpect(status().isNotFound());
 }

 @Test void failedCancellationPreflightRetainsAuditedVisibleIntentWithoutInventingAnAttempt()throws Exception{
  UUID offer=paid();fixture.failSubscriptionGet=true;mvc.perform(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of())).andExpect(status().isBadGateway());assertTrue(db.queryForObject("SELECT cancel_requested FROM maintenance_subscriptions",Boolean.class));assertNull(db.queryForObject("SELECT cancel_state FROM maintenance_subscriptions",String.class));assertEquals(0,fixture.cancels.get());assertEquals(1,ok(as(get("/api/v1/admin/maintenance/attention"),"care-admin")).path("items").size());assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_audit WHERE kind='CANCELLATION_INTENT_REQUESTED'",Integer.class));
  fixture.failSubscriptionGet=false;ok(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of()));assertEquals(1,fixture.cancels.get());assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());
 }

 @Test void automaticReconciliationIsFairDespiteFiveUnknownActiveCancellations()throws Exception{
  UUID offer=accepted();start(offer);fixture.cancelUncertain=true;fixture.cancelStaysActive=true;mvc.perform(body(post(base(offer)+"/billing/cancel"),"care-buyer",Map.of())).andExpect(status().isBadGateway());assertEquals("UNKNOWN",db.queryForObject("SELECT cancel_state FROM maintenance_subscriptions",String.class));UUID first=db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class);db.update("UPDATE maintenance_subscriptions SET updated_at=now()-interval '6 days' WHERE id=?",first);UUID sixth=null;
  // Six independently retained synthetic enrollments exercise the bounded scheduler, which the Spring test context disables.
  for(int n=1;n<6;n++){UUID nextOffer=UUID.randomUUID(),id=UUID.randomUUID();String plan="plan_queue00000"+n,sub="sub_queue00000"+n;db.update("INSERT INTO maintenance_offers(id,engagement_id,revision,status,title,scope,terms,amount_minor,currency,requests_per_cycle,response_hours,total_cycles,seller_id,seller_consented_at,buyer_id,buyer_consented_at,digest) SELECT ?,engagement_id,?,'ACCEPTED',title,scope,terms,amount_minor,currency,requests_per_cycle,response_hours,total_cycles,seller_id,seller_consented_at,buyer_id,buyer_consented_at,digest FROM maintenance_offers WHERE id=?",nextOffer,n+1,offer);db.update("INSERT INTO maintenance_subscriptions(id,engagement_id,offer_id,payer_id,request_key,amount_minor,currency,requests_per_cycle,response_hours,total_cycles,digest,account_id,mode,status,creation_step,plan_state,subscription_state,provider_plan_id,provider_subscription_id,cancel_requested,cancel_state,updated_at) SELECT ?,engagement_id,?,payer_id,?,amount_minor,currency,requests_per_cycle,response_hours,total_cycles,digest,account_id,mode,'CREATED','COMPLETE','CONFIRMED','CONFIRMED',?,?,true,'UNKNOWN',now()-make_interval(days=>?) FROM maintenance_subscriptions WHERE id=?",id,nextOffer,UUID.randomUUID(),plan,sub,6-n,first);fixture.queue(id,plan,sub,db.queryForObject("SELECT digest FROM maintenance_subscriptions WHERE id=?",String.class,id));if(n==5)sixth=id;}
  automaticPass();assertEquals(5,db.queryForObject("SELECT count(*) FROM maintenance_subscriptions WHERE reconcile_generation=1",Integer.class));assertEquals(0L,db.queryForObject("SELECT reconcile_generation FROM maintenance_subscriptions WHERE id=?",Long.class,sixth));assertEquals(5,db.queryForObject("SELECT count(*) FROM maintenance_subscriptions WHERE last_reconcile_attempt_at IS NOT NULL",Integer.class));assertEquals(1,fixture.cancels.get());
  automaticPass();assertEquals(1L,db.queryForObject("SELECT reconcile_generation FROM maintenance_subscriptions WHERE id=?",Long.class,sixth));assertEquals(6,db.queryForObject("SELECT count(*) FROM maintenance_subscriptions WHERE last_reconcile_attempt_at IS NOT NULL",Integer.class));assertEquals(1,fixture.cancels.get());assertEquals(1,fixture.subscriptions.get());
 }

 @Test void automaticFinancialAttemptStillRunsAfterCancellationPreflightFailure()throws Exception{
  UUID offer=accepted();start(offer);db.update("UPDATE maintenance_subscriptions SET cancel_requested=true");fixture.failSubscriptionGet=true;automaticPass();assertEquals(1L,db.queryForObject("SELECT reconcile_generation FROM maintenance_subscriptions",Long.class));assertNotNull(db.queryForObject("SELECT last_reconcile_attempt_at FROM maintenance_subscriptions",java.sql.Timestamp.class));assertNull(db.queryForObject("SELECT reconciled_at FROM maintenance_subscriptions",java.sql.Timestamp.class));assertNull(db.queryForObject("SELECT cancel_state FROM maintenance_subscriptions",String.class));assertEquals(0,fixture.cancels.get());
 }

 @Test void signedRefundReferenceIsVerifiedExactlyWhileCollectionsLagAndRetainsMonotonicMoney()throws Exception{
  UUID offer=paid();fixture.hideRefundList=true;refundEvent("care-refund-lag");assertEquals(MaintenanceFixture.REFUND,db.queryForObject("SELECT refund_id FROM maintenance_webhook_events",String.class));assertThrows(DataAccessException.class,()->db.update("UPDATE maintenance_webhook_events SET refund_id='rfnd_attacker123456'"));fixture.failRefundGet=true;mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isBadGateway());assertNull(db.queryForObject("SELECT processed_at FROM maintenance_webhook_events",java.sql.Timestamp.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());
  fixture.failRefundGet=false;fixture.refundStatus="pending";ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertTrue(db.queryForObject("SELECT pending_refund FROM maintenance_periods",Boolean.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());fixture.refundStatus="processed";ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(1000L,db.queryForObject("SELECT refunded_minor FROM maintenance_periods",Long.class));assertNotNull(db.queryForObject("SELECT processed_at FROM maintenance_webhook_events",java.sql.Timestamp.class));fixture.refundStatus="failed";ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals("processed",db.queryForObject("SELECT status FROM maintenance_refunds",String.class));assertEquals(1000L,db.queryForObject("SELECT refunded_minor FROM maintenance_periods",Long.class));assertEquals(1000L,db.queryForObject("SELECT sum(amount_minor) FROM maintenance_ledger WHERE kind='REFUND'",Long.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());
 }

 @Test void invalidExactRefundFactsCannotClearSignedHoldAndFailedRefundMayReleaseIt()throws Exception{
  UUID offer=paid();fixture.hideRefundList=true;refundEvent("care-refund-facts");for(int n=0;n<6;n++){fixture.refundPayment=MaintenanceFixture.PAYMENT;fixture.refundCurrency="INR";fixture.refundStatus="pending";fixture.refundIdentity=MaintenanceFixture.REFUND;fixture.refundAmount=1000;switch(n){case 0->fixture.refundPayment="pay_foreign123456";case 1->fixture.refundCurrency="USD";case 2->fixture.refundAmount=10001;case 3->fixture.refundAmount=0;case 4->fixture.refundStatus="unknown";case 5->fixture.refundIdentity="rfnd_foreign123456";}mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());assertNull(db.queryForObject("SELECT processed_at FROM maintenance_webhook_events",java.sql.Timestamp.class));assertNull(db.queryForObject("SELECT reconciled_at FROM maintenance_subscriptions",java.sql.Timestamp.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());}
  fixture.refundIdentity=MaintenanceFixture.REFUND;fixture.refundStatus="failed";ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertFalse(db.queryForObject("SELECT pending_refund FROM maintenance_periods",Boolean.class));assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());
 }

 @Test void tooManySignedRefundReferencesRemainPendingAndCannotMarkFresh()throws Exception{
  UUID offer=paid();for(int n=0;n<501;n++)db.update("INSERT INTO maintenance_webhook_events(event_id,payload_hash,event_kind,payment_id,refund_id) VALUES(?,repeat('a',64),'refund.created',?,?)","care-refund-cap-"+n,MaintenanceFixture.PAYMENT,"rfnd_bounded"+n);mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());assertNull(db.queryForObject("SELECT reconciled_at FROM maintenance_subscriptions",java.sql.Timestamp.class));assertEquals(501,db.queryForObject("SELECT count(*) FROM maintenance_webhook_events WHERE processed_at IS NULL",Integer.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());
 }

 @Test void retainedRefundAmountCannotBeChangedAndMissingCollectionCannotHidePendingRefund()throws Exception{
  UUID offer=paid();fixture.hideRefundList=true;refundEvent("care-refund-retained");ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals("pending",db.queryForObject("SELECT status FROM maintenance_refunds",String.class));refundEvent("care-refund-changed");fixture.refundAmount=999;mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());assertNull(db.queryForObject("SELECT processed_at FROM maintenance_webhook_events WHERE event_id='care-refund-changed'",java.sql.Timestamp.class));assertEquals(1000L,db.queryForObject("SELECT amount_minor FROM maintenance_refunds",Long.class));assertTrue(db.queryForObject("SELECT pending_refund FROM maintenance_periods",Boolean.class));fixture.refundAmount=1000;fixture.refundStatus="failed";ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertFalse(db.queryForObject("SELECT pending_refund FROM maintenance_periods",Boolean.class));assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());
 }

 @Test void legacyRefundInboxCannotClearHoldUntilOriginalSignedReplayEnrichesItsReference()throws Exception{
  UUID offer=paid();fixture.hideRefundList=true;String payload=json.writeValueAsString(Map.of("event","refund.created","payload",Map.of("refund",Map.of("entity",Map.of("id",MaintenanceFixture.REFUND,"payment_id",MaintenanceFixture.PAYMENT)))));db.update("INSERT INTO maintenance_webhook_events(event_id,payload_hash,event_kind,payment_id) VALUES('care-refund-legacy',?,'refund.created',?)",Support.hash(payload),MaintenanceFixture.PAYMENT);db.update("INSERT INTO maintenance_webhook_events(event_id,payload_hash,event_kind,payment_id,processed_at) VALUES('care-refund-legacy-processed',?,'refund.created',?,now())",Support.hash(payload),MaintenanceFixture.PAYMENT);var retainedProcessed=db.queryForObject("SELECT processed_at FROM maintenance_webhook_events WHERE event_id='care-refund-legacy-processed'",java.sql.Timestamp.class);
  mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());assertNull(db.queryForObject("SELECT processed_at FROM maintenance_webhook_events WHERE event_id='care-refund-legacy'",java.sql.Timestamp.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());for(String event:List.of("care-refund-legacy","care-refund-legacy-processed"))ok(post("/api/v1/maintenance/razorpay/webhook").contentType("application/json").content(payload).header("X-Razorpay-Event-Id",event).header("X-Razorpay-Signature",sign(MaintenanceFixture.WEBHOOK,payload)));assertEquals(2,db.queryForObject("SELECT count(*) FROM maintenance_webhook_events WHERE refund_id=?",Integer.class,MaintenanceFixture.REFUND));assertEquals(retainedProcessed,db.queryForObject("SELECT processed_at FROM maintenance_webhook_events WHERE event_id='care-refund-legacy-processed'",java.sql.Timestamp.class));
  String changed=payload.replace(MaintenanceFixture.REFUND,"rfnd_foreign123456");mvc.perform(post("/api/v1/maintenance/razorpay/webhook").contentType("application/json").content(changed).header("X-Razorpay-Event-Id","care-refund-legacy").header("X-Razorpay-Signature",sign(MaintenanceFixture.WEBHOOK,changed))).andExpect(status().isConflict());assertThrows(DataAccessException.class,()->db.update("UPDATE maintenance_webhook_events SET refund_id='rfnd_foreign123456' WHERE event_id='care-refund-legacy'"));fixture.failRefundGet=true;mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isBadGateway());assertNull(db.queryForObject("SELECT processed_at FROM maintenance_webhook_events WHERE event_id='care-refund-legacy'",java.sql.Timestamp.class));fixture.failRefundGet=false;fixture.refundStatus="failed";ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertNotNull(db.queryForObject("SELECT processed_at FROM maintenance_webhook_events WHERE event_id='care-refund-legacy'",java.sql.Timestamp.class));assertEquals(retainedProcessed,db.queryForObject("SELECT processed_at FROM maintenance_webhook_events WHERE event_id='care-refund-legacy-processed'",java.sql.Timestamp.class));assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());
 }

 @Test void legacyPaymentOnlyRefundBeforeFirstInvoicePreventsAnyRoutingReservation()throws Exception{
  UUID offer=accepted();start(offer);db.update("INSERT INTO maintenance_webhook_events(event_id,payload_hash,event_kind,payment_id) VALUES('care-refund-before-invoice',repeat('a',64),'refund.created',?)",MaintenanceFixture.PAYMENT);fixture.paid=true;fixture.hideRefundList=true;mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andExpect(status().isConflict());assertEquals(0,fixture.transfers.get());assertEquals(0,db.queryForObject("SELECT count(*) FROM maintenance_periods",Integer.class));assertNull(db.queryForObject("SELECT processed_at FROM maintenance_webhook_events",java.sql.Timestamp.class));assertNull(db.queryForObject("SELECT reconciled_at FROM maintenance_subscriptions",java.sql.Timestamp.class));
 }

 @Test void refundReceivedDuringFinancialReadCannotRouteUntilNextVerifiedRefresh()throws Exception{
  UUID offer=accepted();start(offer);fixture.paid=true;fixture.hideRefundList=true;fixture.blockNextPaymentGet.set(true);var pool=Executors.newSingleThreadExecutor();try{var refresh=pool.submit(()->mvc.perform(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of())).andReturn().getResponse().getStatus());assertTrue(fixture.paymentGetEntered.await(3,TimeUnit.SECONDS));refundEvent("care-refund-during-read");fixture.paymentGetRelease.countDown();assertEquals(200,refresh.get(8,TimeUnit.SECONDS));assertEquals(0,fixture.transfers.get());assertEquals("NOT_CREATED",db.queryForObject("SELECT transfer_state FROM maintenance_periods",String.class));assertNull(db.queryForObject("SELECT processed_at FROM maintenance_webhook_events",java.sql.Timestamp.class));assertNull(db.queryForObject("SELECT reconciled_at FROM maintenance_subscriptions",java.sql.Timestamp.class));assertFalse(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());fixture.refundStatus="failed";ok(body(post(base(offer)+"/billing/refresh"),"care-buyer",Map.of()));assertEquals(1,fixture.transfers.get());assertNotNull(db.queryForObject("SELECT processed_at FROM maintenance_webhook_events",java.sql.Timestamp.class));assertTrue(ok(as(get(base(offer)),"care-buyer")).path("entitlement").path("available").asBoolean());}finally{fixture.paymentGetRelease.countDown();pool.shutdownNow();}
 }

 @Test void operatorCanResumeOnlyProvenUnattemptedSubscriptionAndOnlyOnce()throws Exception{
  UUID id=boundPlanWithoutSubscription();var b=Map.of("reason","Eligibility restored and provider plan facts verified.");mvc.perform(body(post(operator(id,"resume-subscription")),"care-buyer",b)).andExpect(status().isForbidden());db.update("UPDATE sessions SET mfa_verified=false WHERE user_id=?",admin);mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",b)).andExpect(status().isForbidden());db.update("UPDATE sessions SET mfa_verified=true WHERE user_id=?",admin);ok(body(post(operator(id,"resume-subscription")),"care-admin",b));assertTrue(fixture.committedSubscription);assertEquals(1,fixture.plans.get());assertEquals(1,fixture.subscriptions.get());mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",b)).andExpect(status().isConflict());assertEquals(1,fixture.subscriptions.get());
 }

 @Test void simultaneousOperatorResumesCannotDuplicateTheFirstSubscriptionPost()throws Exception{
  UUID id=boundPlanWithoutSubscription();fixture.entered=new CountDownLatch(1);fixture.release=new CountDownLatch(1);fixture.blockSubscription=true;var pool=Executors.newSingleThreadExecutor();try{var resume=pool.submit(()->ok(body(post(operator(id,"resume-subscription")),"care-admin",Map.of("reason","Revalidate current agreement and safely resume the first request."))));assertTrue(fixture.entered.await(3,TimeUnit.SECONDS));mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",Map.of("reason","Concurrent retry must never repeat subscription creation."))).andExpect(status().isConflict());assertEquals("CREATING",db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions",String.class));fixture.release.countDown();resume.get(8,TimeUnit.SECONDS);assertEquals(1,fixture.subscriptions.get());assertEquals("CONFIRMED",db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions",String.class));}finally{fixture.release.countDown();pool.shutdownNow();}
 }

 @Test void resumeThatReadUnattemptedBeforeAnotherReservationCannotMarkItsInFlightRequestUnknown()throws Exception{
  UUID id=boundPlanWithoutSubscription();fixture.entered=new CountDownLatch(1);fixture.release=new CountDownLatch(1);fixture.blockSubscription=true;fixture.blockNextPlanGet.set(true);var pool=Executors.newFixedThreadPool(2);try{var earlier=pool.submit(()->mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",Map.of("reason","Read the unattempted reservation then verify provider facts."))).andReturn().getResponse().getStatus());assertTrue(fixture.planGetEntered.await(3,TimeUnit.SECONDS));var winner=pool.submit(()->ok(body(post(operator(id,"resume-subscription")),"care-admin",Map.of("reason","Concurrent recovery safely reserves the first provider request."))));assertTrue(fixture.entered.await(3,TimeUnit.SECONDS));fixture.planGetRelease.countDown();assertEquals(409,earlier.get(5,TimeUnit.SECONDS));assertEquals("CREATING",db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions",String.class));assertEquals(1,fixture.subscriptions.get());fixture.release.countDown();winner.get(8,TimeUnit.SECONDS);assertEquals("CONFIRMED",db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions",String.class));assertEquals(1,fixture.subscriptions.get());}finally{fixture.planGetRelease.countDown();fixture.release.countDown();pool.shutdownNow();}
 }

 @Test void resumeRechecksCurrentConsentEligibilityProviderFactsAndAmbiguousStates()throws Exception{
  UUID id=boundPlanWithoutSubscription();var b=Map.of("reason","Recovery must revalidate all current authority and provider facts.");db.update("UPDATE developer_profiles SET approval_status='SUSPENDED' WHERE user_id=?",seller);mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",b)).andExpect(status().isConflict());db.update("UPDATE developer_profiles SET approval_status='APPROVED' WHERE user_id=?",seller);db.update("DELETE FROM user_roles WHERE user_id=? AND role='CLIENT'",buyer);mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",b)).andExpect(status().isConflict());db.update("INSERT INTO user_roles(user_id,role) VALUES(?,'CLIENT')",buyer);fixture.alterPlanAmount(9999);mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",b)).andExpect(status().isConflict());fixture.alterPlanAmount(10000);for(String state:List.of("CREATING","UNKNOWN","REJECTED")){db.update("UPDATE maintenance_subscriptions SET subscription_state=? WHERE id=?",state,id);mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",b)).andExpect(status().isConflict());}db.update("UPDATE maintenance_subscriptions SET subscription_state='NOT_CREATED',cancel_requested=true WHERE id=?",id);mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",b)).andExpect(status().isConflict());assertEquals(0,fixture.subscriptions.get());assertEquals(1,fixture.plans.get());
 }

 @Test void operatorResumeCannotUseDifferentProviderMode()throws Exception{
  UUID id=boundPlanWithoutSubscription();var request=new MockHttpServletRequest();request.setCookies(new Cookie("gl_session","care-admin"));var otherMode=new MaintenanceBillingService(repository,access,payments,fixture.testModeProvider(),security,json,transactions,true,true,MaintenanceFixture.WEBHOOK,false);ApiError error=assertThrows(ApiError.class,()->otherMode.operator(id,"resume-subscription",Map.of("reason","Wrong provider mode must not create a new subscription."),request));assertEquals("PAYMENT_MODE_MISMATCH",error.code);assertEquals(0,fixture.subscriptions.get());assertEquals("NOT_CREATED",db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions",String.class));
 }

 @Test void operatorResumeRevalidatesMfaAfterProviderReadBeforeReserving()throws Exception{
  UUID id=boundPlanWithoutSubscription();fixture.blockNextPlanGet.set(true);var pool=Executors.newSingleThreadExecutor();try{var resume=pool.submit(()->mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",Map.of("reason","Operator authority must remain current before reservation."))).andReturn().getResponse().getStatus());assertTrue(fixture.planGetEntered.await(3,TimeUnit.SECONDS));db.update("UPDATE sessions SET mfa_verified=false WHERE user_id=?",admin);fixture.planGetRelease.countDown();assertEquals(403,resume.get(8,TimeUnit.SECONDS));assertEquals(0,fixture.subscriptions.get());assertEquals("NOT_CREATED",db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions",String.class));}finally{fixture.planGetRelease.countDown();pool.shutdownNow();}
 }

 @Test void operatorResumeRequiresCurrentVerifiedFrozenPayee()throws Exception{
  UUID id=boundPlanWithoutSubscription();fixture.failPlanGet=true;mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",Map.of("reason","Unavailable plan verification must leave the request unattempted."))).andExpect(status().isBadGateway());assertEquals("NOT_CREATED",db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions",String.class));fixture.failPlanGet=false;db.update("UPDATE payment_accounts SET provider_status='suspended' WHERE builder_user_id=?",seller);mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",Map.of("reason","Current linked account activation must be verified again."))).andExpect(status().isConflict());assertEquals(0,fixture.subscriptions.get());assertEquals("NOT_CREATED",db.queryForObject("SELECT subscription_state FROM maintenance_subscriptions",String.class));db.update("UPDATE payment_accounts SET provider_status='created' WHERE builder_user_id=?",seller);ok(body(post(operator(id,"resume-subscription")),"care-admin",Map.of("reason","Provider linked account activation has been restored.")));assertEquals(1,fixture.subscriptions.get());
 }

 @Test void committedSubscriptionWithUnavailableReplyBecomesUnknownAndExactBindingRecoversWithoutRetry()throws Exception{
  UUID offer=accepted();fixture.unknownSubscription=true;mvc.perform(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isBadGateway());UUID id=db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class);noSubscriptionRetry(offer,id,"UNKNOWN");recoverCreatedSubscription(id);
 }

 @Test void definitivelyRejectedSubscriptionRetainsConfirmedPlanAndCannotRepeatItsPost()throws Exception{
  UUID offer=accepted();fixture.rejectSubscription=true;mvc.perform(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isBadGateway());UUID id=db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class);noSubscriptionRetry(offer,id,"REJECTED");assertEquals("REJECTED",db.queryForObject("SELECT status FROM maintenance_subscriptions WHERE id=?",String.class,id));
 }

 @Test void malformedSuccessfulSubscriptionReplyBecomesUnknownAndExactGetFactsRecoverIt()throws Exception{
  UUID offer=accepted();fixture.malformedSubscription=true;mvc.perform(body(post(base(offer)+"/billing"),"care-buyer",Map.of("billingConsent",true)).header("Idempotency-Key",UUID.randomUUID())).andExpect(status().isConflict());UUID id=db.queryForObject("SELECT id FROM maintenance_subscriptions",UUID.class);noSubscriptionRetry(offer,id,"UNKNOWN");recoverCreatedSubscription(id);
 }

 @Test void operatorResumeAuditCommitsBeforePostAndSurvivesUnavailableReply()throws Exception{
  UUID id=boundPlanWithoutSubscription(),offer=db.queryForObject("SELECT offer_id FROM maintenance_subscriptions WHERE id=?",UUID.class,id);String reason="Restored current seller eligibility and verified the frozen plan before first subscription request.";fixture.unknownSubscription=true;mvc.perform(body(post(operator(id,"resume-subscription")),"care-admin",Map.of("reason",reason))).andExpect(status().isBadGateway());assertTrue(fixture.committedResumeAudit);assertEquals(admin,db.queryForObject("SELECT actor_id FROM maintenance_audit WHERE kind='OPERATOR_RESUME_SUBSCRIPTION'",UUID.class));assertEquals(reason,db.queryForObject("SELECT detail FROM maintenance_audit WHERE kind='OPERATOR_RESUME_SUBSCRIPTION'",String.class));noSubscriptionRetry(offer,id,"UNKNOWN");assertEquals(1,db.queryForObject("SELECT count(*) FROM maintenance_audit WHERE kind='OPERATOR_RESUME_SUBSCRIPTION'",Integer.class));recoverCreatedSubscription(id);
 }

}
