import type {Business,Brief,Candidate,BusinessRequest,BusinessWorkspaceData,SavedCandidate,TalentList} from './business.ts';

/** Frontend-only sample state. Never imported by the Java service or used as an API fallback. */
export function createBusinessDemo(){
 const actors=[{id:'owner',name:'Leah · Business owner'},{id:'manager',name:'Ravi · Hiring manager'},{id:'outsider',name:'Alex · Invited manager'},{id:'admin',name:'Platform administrator'}];
 let actor='owner',sequence=0;
 let businesses:Business[],briefs:Brief[],lists:(TalentList&{businessId:string})[],saved:(SavedCandidate&{listId:string})[],shortlists:(SavedCandidate&{requestId:string})[],members:{businessId:string;userId:string;name:string;role:'OWNER'|'HIRING_MANAGER'}[],invites:{id:string;businessId:string;businessName:string;userId:string;email:string;status:string}[],activity:(BusinessWorkspaceData['activity'][number]&{businessId:string})[],concierge:{id:string;requestId:string;status:string}[];
 const candidates:Candidate[]=[{kind:'BUILDER',targetId:'builder-leah',name:'Leah Morgan',summary:'Independent builder of practical operations software.',url:'/builders/leah-morgan',availability:'AVAILABLE_NOW',reasons:['Category evidence: Inventory','Technology evidence: React','Available now (self-reported)'],evidenceCount:2},{kind:'TEAM',targetId:'team-studio',name:'Northstar Studio',summary:'A small studio building customer portals and operations tools.',url:'/teams/team-studio',availability:'AVAILABLE_NOW',reasons:['Category evidence: CRM','Technology evidence: React','Available now (self-reported)'],evidenceCount:1}];
 const clone=<T,>(v:T):T=>structuredClone(v);
 function fail(message:string,status=400):never{throw Object.assign(new Error(message),{status});}
 function ensure(v:unknown,message:string,status=400):asserts v{if(!v)fail(message,status);}
 const id=()=>`business-sample-${++sequence}`;
 function audit(businessId:string,action:string,detail:string){activity.unshift({id:id(),businessId,action,detail,createdAt:new Date().toISOString()});}
 function access(businessId:string,owner=false){const m=members.find(m=>m.businessId===businessId&&m.userId===actor);ensure(m,'Business workspace not found.',404);ensure(!owner||m.role==='OWNER','Only the business owner can do this.',403);return m;}
 function brief(businessId:string,requestId:string,open=false){const r=briefs.find(r=>r.id===requestId&&r.businessId===businessId);ensure(r,'Request not found.',404);ensure(!open||r.status==='OPEN','Open the project request first.',409);return r;}
 function candidate(b:any){const c=candidates.find(c=>c.kind===b.kind&&c.targetId===b.targetId);ensure(c,'Eligible public proof is required.',404);return clone(c);}
 function fields(b:any){for(const [field,min,max] of [['title',3,120],['description',20,5000],['budget',1,200],['timeline',1,200]] as const)ensure(typeof b[field]==='string'&&b[field].trim().length>=min&&b[field].length<=max,`Check the ${field} field.`);ensure(b.category||b.technology,'Choose a category or technology.');ensure(['DRAFT','OPEN','CLOSED'].includes(b.status),'Choose a request status.');return {title:b.title,description:b.description,category:b.category||'',technology:b.technology||'',budget:b.budget,timeline:b.timeline,availableOnly:!!b.availableOnly,repositoryVerifiedOnly:!!b.repositoryVerifiedOnly,status:b.status} as Omit<Brief,'id'|'businessId'>;}
 function matches(r:Brief){if(r.repositoryVerifiedOnly)return [];return candidates.filter(c=>(!r.availableOnly||c.availability==='AVAILABLE_NOW')&&c.reasons.some(reason=>reason===`Category evidence: ${r.category}`||reason===`Technology evidence: ${r.technology}`)).map(c=>({...clone(c),reasons:c.reasons.filter(reason=>!reason.startsWith('Category evidence:')||reason===`Category evidence: ${r.category}`).filter(reason=>!reason.startsWith('Technology evidence:')||reason===`Technology evidence: ${r.technology}`)}));}
 function reset(){sequence=0;actor='owner';businesses=[{id:'business-sample',name:'Meridian Labs',summary:'Building better operations for a growing business.',ownerId:'owner'}];members=[{businessId:'business-sample',userId:'owner',name:'Leah Morgan',role:'OWNER'},{businessId:'business-sample',userId:'manager',name:'Ravi Shah',role:'HIRING_MANAGER'}];briefs=[{id:'brief-portal',businessId:'business-sample',title:'Customer approval portal',description:'Create a secure customer portal for reviewing orders, approving changes and tracking delivery. Our operations team needs an accessible experience with clear permissions.',category:'CRM',technology:'React',budget:'$10k–$25k',timeline:'Within 3 months',availableOnly:true,repositoryVerifiedOnly:false,status:'OPEN',createdBy:'owner'},{id:'brief-inventory',businessId:'business-sample',title:'Inventory planning workspace',description:'Replace spreadsheets with one reliable workspace for stock levels, purchase planning and exception handling across our two warehouses.',category:'Inventory',technology:'React',budget:'$5k–$10k',timeline:'Flexible',availableOnly:false,repositoryVerifiedOnly:false,status:'DRAFT',createdBy:'manager'}];lists=[{id:'list-portal',businessId:'business-sample',name:'Operations shortlist'}];saved=[{id:'saved-leah',listId:'list-portal',kind:'BUILDER',targetId:'builder-leah',candidate:clone(candidates[0])}];shortlists=[];invites=[{id:'invite-alex',businessId:'business-sample',businessName:'Meridian Labs',userId:'outsider',email:'alex@example.test',status:'PENDING'}];concierge=[];activity=[{id:'activity-start',businessId:'business-sample',action:'BUSINESS_CREATED',detail:'Business workspace created',createdAt:new Date().toISOString()}];}
 reset();
 const request:BusinessRequest=async(path,init={})=>{
  const method=init.method||'GET',b=init.body?JSON.parse(String(init.body)):{};const parts=path.replace(/^\/api\/v1/,'').split('?')[0].split('/').filter(Boolean);
  if(path==='/me')return {id:actor,email:`${actor}@example.test`,emailVerified:true,roles:actor==='admin'?['ADMIN']:['CLIENT']};
  if(parts[0]==='business-invitations'){const i=invites.find(i=>i.id===parts[1]&&i.userId===actor);ensure(i,'Invitation not found.',404);ensure(i.status==='PENDING','Invitation is no longer pending.',409);ensure(['ACCEPT','DECLINE'].includes(b.action),'Choose accept or decline.');if(b.action==='ACCEPT')members.push({businessId:i.businessId,userId:actor,name:'Alex Chen',role:'HIRING_MANAGER'});i.status=b.action==='ACCEPT'?'ACCEPTED':'DECLINED';audit(i.businessId,'INVITATION_'+i.status,'Hiring invitation response recorded');return {ok:true};}
  if(parts[0]==='admin'){
   ensure(actor==='admin','Administrator authentication is required.',403);
   if(parts.length===2)return {items:concierge.filter(c=>briefs.find(r=>r.id===c.requestId)?.status==='OPEN').map(c=>({...clone(briefs.find(r=>r.id===c.requestId)!),...c,businessName:businesses.find(b=>b.id===briefs.find(r=>r.id===c.requestId)?.businessId)?.name}))};
   const c=concierge.find(c=>c.id===parts[2]);ensure(c,'Sourcing request not found.',404);const r=briefs.find(r=>r.id===c.requestId)!;ensure(r.status==='OPEN','Request is closed.',409);
   if(parts[3]==='matches')return {items:matches(r)};
   if(parts[3]==='shortlist'){ensure(c.status==='IN_PROGRESS','Start sourcing first.',409);ensure(b.reason?.trim().length>=3,'Add a client-visible reason.');const target=candidate(b);if(!shortlists.some(s=>s.requestId===r.id&&s.kind===b.kind&&s.targetId===b.targetId))shortlists.unshift({id:id(),requestId:r.id,kind:b.kind,targetId:b.targetId,candidate:target,reason:b.reason,source:'CONCIERGE'});audit(r.businessId,'CONCIERGE_RECOMMENDATION','Manual recommendation added with a client-visible reason');return {ok:true};}
   ensure((c.status==='REQUESTED'&&b.status==='IN_PROGRESS')||(c.status==='IN_PROGRESS'&&b.status==='FULFILLED'),'Invalid concierge transition.',409);if(b.status==='FULFILLED')ensure(shortlists.some(s=>s.requestId===r.id&&s.source==='CONCIERGE'),'Add a concierge recommendation first.',409);c.status=b.status;r.conciergeStatus=b.status;audit(r.businessId,'CONCIERGE_'+b.status,'Manual sourcing updated');return {ok:true};
  }
  ensure(parts[0]==='businesses','Unknown preview route.',404);
  if(parts.length===1){if(method==='GET')return clone({items:businesses.filter(b=>members.some(m=>m.businessId===b.id&&m.userId===actor)),invitations:invites.filter(i=>i.userId===actor)});ensure(b.name?.trim().length>=2&&b.summary?.trim().length>=10,'Add a business name and summary.');const business={id:id(),name:b.name,summary:b.summary,ownerId:actor};businesses.push(business);members.push({businessId:business.id,userId:actor,name:actors.find(a=>a.id===actor)!.name.split(' · ')[0],role:'OWNER'});audit(business.id,'BUSINESS_CREATED','Business workspace created');return clone(business);}
  const businessId=parts[1],m=access(businessId);const business=businesses.find(b=>b.id===businessId)!;
  if(parts.length===2){if(method==='PUT'){access(businessId,true);ensure(b.name?.length>=2&&b.summary?.length>=10,'Add a business name and summary.');Object.assign(business,{name:b.name,summary:b.summary});audit(businessId,'BUSINESS_UPDATED','Business profile updated');return clone(business);}return clone({business,myRole:m.role,members:members.filter(m=>m.businessId===businessId),invitations:m.role==='OWNER'?invites.filter(i=>i.businessId===businessId):[],activity:activity.filter(a=>a.businessId===businessId)});}
  if(parts[2]==='invitations'){access(businessId,true);const target=actors.find(a=>`${a.id}@example.test`===b.email&&a.id!=='admin');ensure(target,'Use a verified sample actor email: outsider@example.test.');ensure(!members.some(m=>m.businessId===businessId&&m.userId===target.id),'Already a member.',409);ensure(!invites.some(i=>i.businessId===businessId&&i.userId===target.id&&i.status==='PENDING'),'Invitation already pending.',409);const i={id:id(),businessId,businessName:business.name,userId:target.id,email:b.email,status:'PENDING'};invites.push(i);audit(businessId,'MANAGER_INVITED','Hiring manager invited; acceptance required');return clone(i);}
  if(parts[2]==='members'){const target=members.find(m=>m.businessId===businessId&&m.userId===parts[3]);ensure(target,'Member not found.',404);if(target.userId!==actor)access(businessId,true);ensure(target.role!=='OWNER','The owner cannot be removed.',409);members=members.filter(m=>m!==target);audit(businessId,'MANAGER_REMOVED','Hiring access revoked');return {ok:true};}
  if(parts[2]==='requests'){
   if(parts.length===3){if(method==='GET')return clone({items:briefs.filter(r=>r.businessId===businessId)});const f=fields(b);ensure(f.status!=='CLOSED','Create a draft or open request.');const r={...f,id:id(),businessId,createdBy:actor};briefs.unshift(r);audit(businessId,'REQUEST_CREATED','Private project request created');return clone(r);}
   const r=brief(businessId,parts[3]);
   if(parts.length===4){ensure(r.status!=='CLOSED','Closed requests are read-only.',409);const f=fields(b);ensure(!(r.status==='OPEN'&&f.status==='DRAFT'),'An open request cannot return to draft.',409);Object.assign(r,f);if(f.status==='CLOSED'){concierge.filter(c=>c.requestId===r.id&&c.status!=='FULFILLED').forEach(c=>c.status='CANCELLED');if(r.conciergeStatus&&r.conciergeStatus!=='FULFILLED')r.conciergeStatus='CANCELLED';}audit(businessId,'REQUEST_UPDATED','Private request updated');return clone(r);}
   if(parts[4]==='matches'){brief(businessId,r.id,true);return {items:matches(r)};}
   if(parts[4]==='shortlist'){if(method==='GET')return clone({items:shortlists.filter(s=>s.requestId===r.id)});brief(businessId,r.id,true);if(method==='DELETE'){ensure(shortlists.some(s=>s.id===parts[5]&&s.requestId===r.id),'Entry not found.',404);shortlists=shortlists.filter(s=>!(s.id===parts[5]&&s.requestId===r.id));}else{ensure(b.reason?.trim().length>=3,'Add a shortlist reason.');const target=candidate(b);if(!shortlists.some(s=>s.requestId===r.id&&s.kind===b.kind&&s.targetId===b.targetId))shortlists.unshift({id:id(),requestId:r.id,kind:b.kind,targetId:b.targetId,candidate:target,reason:b.reason,source:'BUSINESS'});}audit(businessId,'SHORTLIST_UPDATED','Request shortlist updated');return {ok:true};}
   if(parts[4]==='concierge'){brief(businessId,r.id,true);if(!concierge.some(c=>c.requestId===r.id)){concierge.push({id:id(),requestId:r.id,status:'REQUESTED'});r.conciergeStatus='REQUESTED';audit(businessId,'CONCIERGE_REQUESTED','Brief shared with the platform administrator for manual sourcing');}return {ok:true};}
  }
  if(parts[2]==='talent-lists'){
   if(parts.length===3){if(method==='GET')return clone({items:lists.filter(l=>l.businessId===businessId)});ensure(b.name?.trim().length>=2,'Name your talent list.');const list={id:id(),businessId,name:b.name};lists.unshift(list);audit(businessId,'TALENT_LIST_CREATED','Shared talent list created');return clone(list);}
   const list=lists.find(l=>l.id===parts[3]&&l.businessId===businessId);ensure(list,'Talent list not found.',404);if(method==='GET')return clone({items:saved.filter(s=>s.listId===list.id)});if(method==='DELETE'){ensure(saved.some(s=>s.listId===list.id&&s.id===parts[5]),'Entry not found.',404);saved=saved.filter(s=>!(s.listId===list.id&&s.id===parts[5]));}else{const target=candidate(b);if(!saved.some(s=>s.listId===list.id&&s.kind===b.kind&&s.targetId===b.targetId))saved.unshift({id:id(),listId:list.id,kind:b.kind,targetId:b.targetId,candidate:target});}audit(businessId,'TALENT_LIST_UPDATED','Shared talent list updated');return {ok:true};
  }
  fail('Unknown preview route.',404);
 };
 return {request,reset,actors,setActor:(id:string)=>{ensure(actors.some(a=>a.id===id),'Unknown actor.');actor=id;}};
}
