import { backendOrigin } from './server';
import { componentSeeds, seedCatalog, type ComponentEntry, type ComponentPage } from './components';
import { examples, type Product } from './catalog';
export type Education = { category: string; language: string; problem: string; outcome: string; prerequisites: string; contribution: string; executionMode: string; mode: string; status: string; institution?: string; academicYear?: string; branch?: string; shareAcademicDetails: boolean; reviewReason?: string };
export type CollegeProject = Product & { education: Education };
export const sampleCollegeProjects: CollegeProject[] = examples.slice(0, 4).map((p, i) => ({ ...p, education: { category: ['FULL_STACK', 'DATA_ANALYTICS', 'AI_ML', 'IOT'][i], language: ['TypeScript / SQL', 'Python / SQL', 'Python', 'C++ / MicroPython'][i], problem: ['Coordinate a team’s project updates in one place.', 'Understand changes in a synthetic business dataset.', 'Compare predictions using a small labelled sample.', 'Explain a simulated sensor-to-dashboard workflow.'][i], outcome: 'Illustrative college metadata showing how a creator can explain their work. No verified project execution is implied.', prerequisites: 'Language fundamentals and the project’s documented local setup.', contribution: 'Sample creator contribution. Replace this with your own work and evidence when publishing.', executionMode: 'Source only', mode: 'Showcase only', status: 'APPROVED', shareAcademicDetails: false } }));
async function read<T>(path: string): Promise<T | undefined> { const origin = await backendOrigin(); if (!origin) return undefined; const res = await fetch(origin + '/api/v1' + path, { cache: 'no-store', signal: AbortSignal.timeout(15000) }); if (res.status === 404) return undefined; if (!res.ok) throw Error('This catalogue is temporarily unavailable. Please try again.'); return res.json(); }
export async function componentCatalog(params: URLSearchParams) { const connected = !!(await backendOrigin()); const data = connected ? await read<ComponentPage>('/components?' + params) : (params.get('builder') ? { items: [], totalItems: 0, hasMore: false, page: 0 } : seedCatalog(params.get('q') || '', params.get('category') || '', params.get('kind') || 'FRONTEND', Number(params.get('page') || 0))); if (!data) throw Error('Component catalogue unavailable.'); return { data, preview: !connected }; }
export async function componentDetail(slug: string) { const connected = !!(await backendOrigin()); return { item: connected ? await read<ComponentEntry>('/components/' + encodeURIComponent(slug)) : componentSeeds.find(c => c.slug === slug), preview: !connected }; }
export async function collegeCatalog(params: URLSearchParams) {
  const connected = !!(await backendOrigin());
  const filtered = params.get('builder') ? [] : sampleCollegeProjects.filter(p => (!params.get('category') || p.education.category === params.get('category')) && (!params.get('language') || p.education.language.toLowerCase().includes(params.get('language')!.toLowerCase())) && (!params.get('q') || (p.title + ' ' + p.education.problem).toLowerCase().includes(params.get('q')!.toLowerCase())));
  const page = Number(params.get('page') || 0);
  const data = connected ? await read<{ items: CollegeProject[]; totalItems: number; hasMore: boolean }>('/college-projects?' + params) : { items: filtered.slice(page * 12, (page + 1) * 12), totalItems: filtered.length, hasMore: (page + 1) * 12 < filtered.length };
  if (!data) throw Error('College project catalogue unavailable.'); return { data, preview: !connected };
}
export async function collegeDetail(slug: string) { const connected = !!(await backendOrigin()); return { item: connected ? await read<CollegeProject>('/college-projects/' + encodeURIComponent(slug)) : sampleCollegeProjects.find(p => p.slug === slug), preview: !connected }; }
