export type ProposalMilestone = {title:string;description:string;amountMinor:number;dueDate:string};
export type Proposal = {id:string;revision:number;status:string;scope:string;terms:string;amountMinor:number;currency:string;milestones:ProposalMilestone[];sentAt?:string|null;acceptedAt?:string|null};
export type Milestone = ProposalMilestone & {id:string;status:string;deliveryNote?:string|null;deliveryUrl?:string|null;acceptedAt?:string|null};
export type Agreement = {proposalId:string;scope:string;terms:string;amountMinor:number;currency:string;digest:string;sellerConsentedAt:string;buyerConsentedAt:string};
export type DeliveryActivity = {id:string;kind?:string;action?:string;detail:string;createdAt:string};
export type DeliveryDispute = {id:string;reason:string;status:string;resolution?:string|null;createdAt:string};
export type Engagement = {id:string;title:string;status:string;side:'BUYER'|'SELLER';sourceInquiryId?:string|null;businessRequestId?:string|null;buyerUserId?:string|null;businessId?:string|null;builderUserId?:string|null;teamId?:string|null;createdAt:string};
export type EngagementDetail = Engagement & {proposals:Proposal[];milestones:Milestone[];activity:DeliveryActivity[];disputes:DeliveryDispute[];agreement:Agreement|null};
export type PaymentSummary = {id:string;milestoneId:string;status:string;amountMinor:number;currency:string;orderId?:string|null;paymentId?:string|null;refundedMinor:number;transferStatus?:string|null;mode?:'test'|'live'};
export type PaymentConfig = {enabled:boolean;keyId?:string|null;mode:'disabled'|'test'|'live';reason?:string|null};
export type CheckoutOrder = {id:string;orderId?:string|null;amountMinor:number;currency:string;keyId?:string|null;mode:string;status:string};
export type EngagementSource = {inquiryId:string}|{businessRequestId:string;candidateKind:'BUILDER'|'TEAM';candidateId:string};
export const deliveryStatus=(value:string)=>value.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
export const inr=(amountMinor:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(amountMinor/100);

/** Convert a decimal rupee string without floating-point multiplication or rounding. */
export function rupeesToMinor(value:string):number {
 const trimmed=value.trim();
 if(!/^\d+(?:\.\d{1,2})?$/.test(trimmed))throw new Error('Enter a positive INR amount with at most two decimal places.');
 const [whole,fraction='']=trimmed.split('.');const amount=Number(whole)*100+Number(fraction.padEnd(2,'0'));
 if(!Number.isSafeInteger(amount)||amount<100||amount>1_000_000_000)throw new Error('Each milestone must be between ₹1.00 and ₹1,00,00,000.');
 return amount;
}

/** Local UI exercise only. This object never sends requests or contacts a gateway. */
export function createDeliveryPreview(){
 const initial=():EngagementDetail[]=>[{id:'preview-engagement',title:'Customer approval portal',status:'OPEN',side:'SELLER',sourceInquiryId:'preview-inquiry',builderUserId:'preview-builder',buyerUserId:'preview-client',createdAt:'2026-09-30T09:00:00Z',agreement:null,milestones:[],disputes:[],activity:[{id:'preview-start',kind:'ENGAGEMENT_CREATED',detail:'Sample inquiry became an engagement.',createdAt:'2026-09-30T09:00:00Z'}],proposals:[{id:'preview-proposal',revision:1,status:'DRAFT',scope:'Design and build an accessible approval portal for the operations team, with a clear review queue and audit history.',terms:'Milestones are paid after the client accepts the deliverable. Scope changes require a new written agreement. No escrow is held.',amountMinor:6000000,currency:'INR',milestones:[{title:'Design and review queue',description:'Responsive interface and accessible approval workflow.',amountMinor:2500000,dueDate:'2026-10-14'},{title:'Delivery and handover',description:'Audit history, testing and deployment documentation.',amountMinor:3500000,dueDate:'2026-10-28'}]}]}];
 let engagements=initial(),payments:PaymentSummary[]=[],side:'BUYER'|'SELLER'='SELLER';
 const clone=<T,>(value:T):T=>structuredClone(value);
 const find=(id:string)=>{const value=engagements.find(e=>e.id===id);if(!value)throw new Error('This sample engagement is no longer available.');return value;};
 const event=(engagement:EngagementDetail,kind:string,detail:string)=>engagement.activity.unshift({id:crypto.randomUUID(),kind,detail,createdAt:new Date().toISOString()});
 const requireSide=(expected:'BUYER'|'SELLER')=>{if(side!==expected)throw new Error('Switch the sample actor to '+expected.toLowerCase()+' to perform this action.');};
 return {
  setSide(value:'BUYER'|'SELLER'){side=value;},reset(){engagements=initial();payments=[];},
  list():Engagement[]{return clone(engagements.map(({proposals,milestones,agreement,activity,disputes,...engagement})=>({...engagement,side})));},
  detail(id:string):EngagementDetail{return clone({...find(id),side});},payments(id:string):PaymentSummary[]{const ids=find(id).milestones.map(m=>m.id);return clone(payments.filter(p=>ids.includes(p.milestoneId)));},
  create(_source:EngagementSource){const id=crypto.randomUUID();engagements.unshift({...initial()[0],id,title:'New sample engagement',proposals:[],activity:[],sourceInquiryId:'preview-inquiry'});event(find(id),'ENGAGEMENT_CREATED','A new sample engagement was created.');return{id};},
  proposal(id:string,body:{scope:string;terms:string;milestones:ProposalMilestone[]}){requireSide('SELLER');const e=find(id);if(e.agreement||e.status==='DISPUTED')throw new Error('This engagement cannot receive a new proposal.');if(e.proposals.some(p=>p.status==='SENT'))throw new Error('Withdraw the sent offer before preparing another revision.');const previous=e.proposals.at(-1);if(previous?.status==='DRAFT')previous.status='WITHDRAWN';e.proposals.push({...clone(body),id:crypto.randomUUID(),revision:(previous?.revision||0)+1,status:'DRAFT',amountMinor:body.milestones.reduce((sum,m)=>sum+m.amountMinor,0),currency:'INR'});event(e,'PROPOSAL_DRAFTED','A sample proposal revision was saved.');},
  proposalAction(id:string,proposalId:string,action:string,consent=false){const e=find(id),p=e.proposals.find(p=>p.id===proposalId);if(!p)throw new Error('Proposal not found.');if(e.status==='DISPUTED')throw new Error('Resolve the dispute before changing the agreement.');if(action==='send'){requireSide('SELLER');if(!consent||p.status!=='DRAFT')throw new Error('Explicit consent is required to send this draft.');p.status='SENT';p.sentAt=new Date().toISOString();}else if(action==='accept'){requireSide('BUYER');if(!consent||p.status!=='SENT')throw new Error('Explicit consent is required to accept this sent proposal.');p.status='ACCEPTED';p.acceptedAt=new Date().toISOString();e.status='ACTIVE';e.agreement={proposalId:p.id,scope:p.scope,terms:p.terms,amountMinor:p.amountMinor,currency:'INR',digest:'Sample agreement digest — no legal signature',sellerConsentedAt:p.sentAt!,buyerConsentedAt:p.acceptedAt};e.milestones=p.milestones.map(m=>({...clone(m),id:crypto.randomUUID(),status:'PLANNED'}));}else if(action==='withdraw'){requireSide('SELLER');if(!['DRAFT','SENT'].includes(p.status))throw new Error('This proposal cannot be withdrawn.');p.status='WITHDRAWN';}else if(action==='reject'){requireSide('BUYER');if(p.status!=='SENT')throw new Error('Only a sent proposal can be rejected.');p.status='REJECTED';}event(e,'PROPOSAL_'+action.toUpperCase(),'Sample proposal '+action+' recorded.');},
  milestoneAction(id:string,milestoneId:string,action:string,body:Record<string,string>={}){const e=find(id),m=e.milestones.find(m=>m.id===milestoneId);if(!m)throw new Error('Milestone not found.');if(e.status==='DISPUTED')throw new Error('Resolve the dispute before changing a milestone.');if(action==='start'){requireSide('SELLER');if(!['PLANNED','REVISION_REQUESTED'].includes(m.status))throw new Error('Only a planned or revision-requested milestone can start.');m.status='IN_PROGRESS';}else if(action==='submit'){requireSide('SELLER');if(m.status!=='IN_PROGRESS')throw new Error('Start work before submitting this milestone.');m.status='SUBMITTED';m.deliveryNote=body.deliveryNote;m.deliveryUrl=body.deliveryUrl;}else if(action==='request-revision'){requireSide('BUYER');if(m.status!=='SUBMITTED')throw new Error('Only a submitted milestone can be revised.');m.status='REVISION_REQUESTED';}else if(action==='accept'){requireSide('BUYER');if(m.status!=='SUBMITTED')throw new Error('Only a submitted milestone can be accepted.');m.status='ACCEPTED';m.acceptedAt=new Date().toISOString();}event(e,'MILESTONE_'+action.toUpperCase(),m.title+': '+(body.reason||body.deliveryNote||action)+'.');},
  simulatePayment(id:string,milestoneId:string){requireSide('BUYER');const e=find(id),m=e.milestones.find(m=>m.id===milestoneId);if(!m||m.status!=='ACCEPTED'||e.status==='DISPUTED')throw new Error('Only an accepted milestone in an active engagement can be paid.');if(payments.some(p=>p.milestoneId===m.id&&p.status==='CAPTURED'))return;payments.push({id:crypto.randomUUID(),milestoneId:m.id,status:'CAPTURED',amountMinor:m.amountMinor,currency:'INR',refundedMinor:0,transferStatus:'PREVIEW_ONLY'});event(e,'PREVIEW_PAYMENT_CONFIRMED','A payment status was simulated locally. No money moved.');},
  dispute(id:string,reason:string){const e=find(id);if(['DISPUTED','COMPLETED','CANCELLED'].includes(e.status))throw new Error('This sample engagement cannot open another dispute.');e.status='DISPUTED';e.disputes.unshift({id:crypto.randomUUID(),reason,status:'OPEN',createdAt:new Date().toISOString()});event(e,'DISPUTE_OPENED',reason+' No refund has been issued.');},
  completion(id:string){const e=find(id);if(!e.milestones.length||!e.milestones.every(m=>m.status==='ACCEPTED'&&payments.some(p=>p.milestoneId===m.id&&p.status==='CAPTURED'&&p.refundedMinor===0)))throw new Error('Every milestone must be accepted and paid before completion.');if(side==='SELLER'&&e.status==='ACTIVE')e.status='COMPLETION_PENDING';else if(side==='BUYER'&&e.status==='COMPLETION_PENDING')e.status='COMPLETED';else throw new Error('The other party must acknowledge this completion step.');event(e,'COMPLETION_'+e.status,side==='SELLER'?'Sample seller requested completion.':'Sample buyer confirmed completion.');},
 };
}
