export type EducationDataAiEvidence={codeLicense?:string|null;dataLicense?:string|null;dataProvenance?:string|null;dataSha256?:string|null;modelLicense?:string|null;modelProvenance?:string|null;modelSha256?:string|null;modelFormat?:string|null;evaluationSplit?:string|null;evaluationProtocol?:string|null;outputSchema?:string|null;limitations?:string|null;redistributionAllowed?:boolean|null;syntheticData?:boolean|null;noRemoteCode?:boolean|null};
export const educationDataAiFields=[['codeLicense','Code license'],['dataLicense','Data license'],['dataProvenance','Data provenance'],['dataSha256','Data SHA-256'],['modelLicense','Model license'],['modelProvenance','Model provenance'],['modelSha256','Model SHA-256'],['modelFormat','Model format'],['evaluationSplit','Evaluation split'],['evaluationProtocol','Evaluation protocol'],['outputSchema','Output schema'],['limitations','Data and model limitations']] as const;
export const educationDataAiChecks=[['redistributionAllowed','I have verified separate code, dataset and model redistribution rights.'],['syntheticData','All included datasets and evaluation fixtures are synthetic.'],['noRemoteCode','The package uses no executable model loader or remote code.']] as const;
export const isDataAiCategory=(category:string)=>['DATA_ANALYTICS','AI_ML'].includes(category);
export function dataAiEvidenceIssues(category:string,evidence?:EducationDataAiEvidence):Record<string,string>{
 if(!isDataAiCategory(category))return evidence&&['FULL_STACK','IOT'].includes(category)?{dataAiEvidence:'Structured data/AI evidence is available only for analytics and AI releases.'}:{};
 const issues:Record<string,string>={};
 for(const [key,label]of educationDataAiFields){const value=evidence?.[key],required=category==='AI_ML'||!key.startsWith('model')&&!key.startsWith('evaluation');
 if(required&&(typeof value!=='string'||value.trim().length<3)){issues[key]='Add '+label.toLowerCase()+'.';continue;}
 if(value===undefined||value===null||value==='')continue;
 if(typeof value!=='string'||value.length>4000)issues[key]=label+' must be bounded text of at most 4000 characters.';
 else if(key.endsWith('Sha256')&&!/^[0-9a-f]{64}$/.test(value))issues[key]=label+' requires exactly 64 lowercase hexadecimal characters.';
 else if(key==='modelFormat'&&value!=='JSON')issues[key]='Use a frozen JSON model; executable and remote loaders are not accepted.';}
 for(const [key]of educationDataAiChecks)if(evidence?.[key]!==true)issues[key]=key==='redistributionAllowed'?'Confirm separate code, dataset and model redistribution rights.':key==='syntheticData'?'Confirm synthetic dataset and evaluation fixtures.':'Confirm that no executable model loader or remote code is used.';
 return issues;
}
/** Mutable allowlist only; source proofs, unexpected fields and academic metadata are never copied. */
export function dataAiEvidenceBody(value?:EducationDataAiEvidence):EducationDataAiEvidence|undefined{if(!value)return;return Object.fromEntries([...educationDataAiFields,...educationDataAiChecks].filter(([key])=>Object.hasOwn(value,key)).map(([key])=>[key,value[key]]));}
export type EducationMode='SHOWCASE'|'FREE'|'PAID';
export type EducationPackage={includedAssets:string[];excludedAssets:string[];setupSteps:string[];prerequisites:string[];limitations:string[];supportTerms:string;licenseTerms:string};
export type EducationBinding={packageId?:string;templateId?:string;versionId?:string;version?:string;sha256:string;sizeBytes:number;entryCount:number;files:string[];manifestFiles?:string[];licenseTerms:string};
export type EducationComponent={componentId:string;revision:number;license?:string;sha256?:string;attribution:string;slug?:string;creator?:string;creatorSlug?:string};
export type EducationAcademic={revision:number;institution?:string;academicYear?:string;branch?:string;shareAcademicDetails:boolean};
export type EducationSnapshot={productId:string;slug:string;title:string;summary:string;category:string;language?:string;mode:EducationMode;difficulty:string;demoMode:string;demoUrl?:string;demoAvailability?:string;package:EducationPackage;categoryEvidence:Record<string,string>;dataAiEvidence?:EducationDataAiEvidence;contribution:string;componentLinks:EducationComponent[];sourceBinding?:EducationBinding;priceMinor?:number;currency?:string;problem?:string;outcome?:string;teams?:{id:string;name:string}[]};
export type EducationRelease={id:string;productId:string;revision:number;status:string;sourceHash?:string;snapshot:EducationSnapshot;academic:EducationAcademic;freePackageId?:string;versionId?:string;sourceBinding?:EducationBinding;teams?:{id:string;slug?:string;name:string}[];demoAvailability?:string;demoUrl?:string;componentLinks?:EducationComponent[];reviewReason?:string};
export type EducationOffer={release:EducationRelease;package?:EducationBinding;available:boolean;reason?:string;checkoutReason?:string;checkoutAvailable?:boolean;paidEnabled?:boolean;paymentMode?:string};
export type EducationDraft={revision?:number;category:string;mode:EducationMode;difficulty:string;demoMode:string;demoUrl:string;package:EducationPackage;categoryEvidence:Record<string,string>;dataAiEvidence?:EducationDataAiEvidence;componentLinks:EducationComponent[];versionId?:string;rightsConsent:boolean};
export const educationModes=[['SHOWCASE','Showcase only'],['FREE','Free learning package'],['PAID','Paid source license']] as const;
export const educationDifficulties=['BEGINNER','INTERMEDIATE','ADVANCED'];
export const educationLabel=(value:string)=>value.toLowerCase().replaceAll('_',' ').replace(/^./,letter=>letter.toUpperCase());
export const educationModeLabel=(value:string)=>educationModes.find(([key])=>key===value)?.[1]||educationLabel(value);
export const educationEvidence:Record<string,[string,string][]>=Object.fromEntries(Object.entries({FULL_STACK:{modules:'Application modules',schemaApi:'Schema & API outline',demoAccounts:'Demo accounts & access',setupMigrations:'Setup & migrations',versions:'Runtime & dependency versions',tests:'Tests & observed results',deployment:'Deployment steps & limitations'},DATA_ANALYTICS:{dataSourceLicense:'Data source & license',sampleSchema:'Sample schema & fields',transformations:'Transformations & cleaning',notebook:'Notebook or analysis entry point',charts:'Charts or output tables',interpretation:'Interpretation & limitations',reproducibility:'Reproducibility steps'},AI_ML:{task:'Model task',datasetModelLicense:'Dataset & model licenses',splits:'Training / evaluation splits',evaluation:'Evaluation method',metrics:'Observed metrics & context',inference:'Inference entry point',limitations:'Model limitations'},IOT:{boardFirmware:'Board & firmware or simulation',billOfMaterials:'Bill of materials',wiring:'Wiring & safety',powerConnectivity:'Power & connectivity',topics:'Topics / payload schema',evidence:'Observed results & simulation evidence'}}).map(([category,fields])=>[category,Object.entries(fields)]));
export const educationPackageLists=[['includedAssets','Included source & assets'],['excludedAssets','Excluded source, data, models & hardware'],['setupSteps','Setup effort & reproduction steps'],['prerequisites','External dependencies & prerequisites'],['limitations','Limitations & responsibilities']] as const;
export function emptyEducationDraft():EducationDraft{return {category:'FULL_STACK',mode:'SHOWCASE',difficulty:'BEGINNER',demoMode:'SOURCE_ONLY',demoUrl:'',package:{includedAssets:[],excludedAssets:[],setupSteps:[],prerequisites:[],limitations:[],supportTerms:'',licenseTerms:''},categoryEvidence:{},componentLinks:[],rightsConsent:false};}
/** Only mutable creator inputs leave the browser; reviewed proofs remain server-owned. */
export function educationDraftFrom(release:EducationRelease):EducationDraft{const s=release.snapshot;return {revision:release.revision,category:s.category,mode:s.mode,difficulty:s.difficulty,demoMode:s.demoMode,demoUrl:s.demoUrl||'',package:structuredClone(s.package),categoryEvidence:{...s.categoryEvidence},dataAiEvidence:dataAiEvidenceBody(s.dataAiEvidence),componentLinks:s.componentLinks.map(link=>({componentId:link.componentId,revision:link.revision,license:link.license,attribution:link.attribution})),versionId:release.versionId||s.sourceBinding?.versionId,rightsConsent:false};}
export function educationDraftBody(draft:EducationDraft):EducationDraft{return {...draft,versionId:draft.mode==='PAID'?draft.versionId:undefined,demoUrl:draft.demoMode==='SOURCE_ONLY'?'':draft.demoUrl,dataAiEvidence:dataAiEvidenceBody(draft.dataAiEvidence),categoryEvidence:Object.fromEntries((educationEvidence[draft.category]||[]).map(([key])=>[key,draft.categoryEvidence[key]||''])),componentLinks:draft.componentLinks.map(link=>({componentId:link.componentId,revision:link.revision,license:link.license,attribution:link.attribution})),package:structuredClone(draft.package)};}
export function educationSubmissionIssues(d:EducationDraft,source?:EducationBinding){const issues:string[]=Object.values(dataAiEvidenceIssues(d.category,d.dataAiEvidence));for(const [key,label]of educationEvidence[d.category]||[])if((d.categoryEvidence[key]?.trim().length||0)<10)issues.push('Add '+label.toLowerCase()+'.');for(const [key,label]of educationPackageLists)if(!d.package[key].length||d.package[key].some(value=>value.trim().length<3))issues.push('Disclose '+label.toLowerCase()+'.');if(d.package.supportTerms.trim().length<10)issues.push('Describe the support scope and duration.');if(d.package.licenseTerms.trim().length<20)issues.push('State the license and attribution terms.');if(d.demoMode==='EXTERNAL'&&!/^https:\/\//i.test(d.demoUrl))issues.push('External demonstrations require a public HTTPS URL.');if(d.mode==='FREE'&&!source?.packageId)issues.push('Upload and inspect the original free source ZIP.');if(d.mode==='PAID'&&!d.versionId)issues.push('Select an owned approved source version.');if(d.componentLinks.some(link=>!/^[0-9a-f-]{36}$/i.test(link.componentId)||!Number.isInteger(link.revision)||link.revision<1||!link.license?.trim()||!link.attribution.trim()))issues.push('Each reusable component requires its exact UUID, revision and attribution.');if(!d.rightsConsent)issues.push('Confirm source rights and your existing contribution.');return issues;}
