import type {SourceTemplate,TemplatePurchase,TemplateVersion,TemplateFilters,TemplatePage} from './templates';

const license='One commercial end product. You may modify the source for that end product. You may not redistribute the source or resell it as a competing template. Sample terms for this frontend preview only.';
const templates:SourceTemplate[]=[
 {id:'sample-template-portal',slug:'sample-approval-portal',title:'Approval portal starter',summary:'A clear review queue, role-based decisions and a complete handover foundation.',description:'A sample source listing illustrating a responsive customer approval portal. Explore the review queue, decision forms and license flow in the frontend preview. This is not a real seller listing or downloadable package.',category:'BUSINESS',technology:'REACT',priceMinor:490000,currency:'INR',productId:'sample-proof',productSlug:'flowboard',sellerId:'sample-seller',sellerName:'Sample independent builder',versionId:'sample-version-1',version:'1.0.0',releaseNotes:'Initial release with responsive review screens, accessible forms and setup documentation.',licenseTerms:license,status:'ACTIVE',createdAt:'2026-10-01T04:00:00Z',versions:[{id:'sample-version-1',version:'1.0.0',releaseNotes:'Initial release with responsive review screens, accessible forms and setup documentation.',status:'APPROVED',sha256:'a'.repeat(64),sizeBytes:124000,entryCount:24,createdAt:'2026-10-01T04:00:00Z'}]},
 {id:'sample-template-studio',slug:'sample-studio-dashboard',title:'Studio operations kit',summary:'Plan projects, follow client leads and keep a small studio’s work organized.',description:'A sample listing for a studio operations dashboard. All preview records are held in frontend memory. The sample release represents the same approval and license interactions as a connected marketplace.',category:'PRODUCTIVITY',technology:'NEXT_JS',priceMinor:790000,currency:'INR',productId:'sample-studio-proof',sellerId:'sample-seller',sellerName:'Sample independent builder',versionId:'sample-version-studio',version:'2.1.0',releaseNotes:'Updated project cards, lead stages and mobile layouts.',licenseTerms:license,status:'ACTIVE',createdAt:'2026-10-01T04:00:00Z',versions:[{id:'sample-version-studio',version:'2.1.0',releaseNotes:'Updated project cards, lead stages and mobile layouts.',status:'APPROVED',sha256:'b'.repeat(64),sizeBytes:184000,entryCount:32,createdAt:'2026-10-01T04:00:00Z'}]},
];
const copy=<T,>(value:T):T=>structuredClone(value);
export function previewTemplateCatalog(filters:TemplateFilters={q:'',category:'',technology:''},page=0):TemplatePage<SourceTemplate>{
 const items=templates.filter(item=>(!filters.q||(item.title+' '+item.summary).toLowerCase().includes(filters.q.toLowerCase()))&&(!filters.category||item.category===filters.category)&&(!filters.technology||item.technology===filters.technology));
 return {items:page===0?copy(items):[],page,size:12,hasMore:false,totalItems:items.length,totalPages:items.length?1:0};
}
export function previewTemplateDetail(slug:string){return copy(templates.find(item=>item.slug===slug));}

/** Isolated frontend exercise: no fetch, provider script, ZIP read or source archive is used. */
export function createTemplatePreview(){
 let owned=copy(templates),purchases:TemplatePurchase[]=[];
 const find=(id:string)=>{const item=owned.find(item=>item.id===id);if(!item)throw Error('Sample template not found.');return item;};
 return {
  list:()=>copy(owned),purchases:()=>copy(purchases),
  create:(body:{title:string;summary:string;description:string;priceMinor:number;licenseTerms:string;productId:string})=>{const id=crypto.randomUUID(),item:SourceTemplate={...copy(templates[0]),...body,id,slug:'sample-'+id,status:'DRAFT',versionId:undefined,version:undefined,versions:[]};owned.push(item);return copy(item);},
  upload:(id:string,body:{version:string;releaseNotes:string;rightsConsent:boolean})=>{if(!body.rightsConsent)throw Error('Confirm that you have the rights to submit this package.');const item=find(id);if(item.versions?.some(version=>version.version===body.version))throw Error('Use a new version number.');const version:TemplateVersion={id:crypto.randomUUID(),version:body.version,releaseNotes:body.releaseNotes,status:'DRAFT',sha256:'c'.repeat(64),sizeBytes:120000,entryCount:20,createdAt:new Date().toISOString()};item.versions=[...(item.versions||[]),version];return copy(version);},
  submit:(id:string,versionId:string,consent:boolean)=>{if(!consent)throw Error('Rights consent is required.');const item=find(id),version=item.versions?.find(version=>version.id===versionId);if(!version||!['DRAFT','CHANGES_REQUESTED'].includes(version.status))throw Error('This sample version cannot be submitted.');version.status='PENDING';return copy(item);},
  archive:(id:string)=>{const item=find(id);item.status='ARCHIVED';return copy(item);},
  review:(id:string,versionId:string,action:string,reason:string)=>{const item=find(id),version=item.versions?.find(version=>version.id===versionId);if(!version)throw Error('Sample version not found.');if((action==='SUSPEND'&&!['PENDING','APPROVED','SUSPENDED'].includes(version.status))||(action!=='SUSPEND'&&!['PENDING','SUSPENDED'].includes(version.status)))throw Error('This sample release is not eligible for that decision.');if(reason.trim().length<10)throw Error('Explain the review decision.');version.status=action==='APPROVE'?'APPROVED':action==='SUSPEND'?'SUSPENDED':action==='REJECT'?'REJECTED':'CHANGES_REQUESTED';version.reviewReason=reason;if(action==='APPROVE'){if(item.status!=='ARCHIVED')item.status='ACTIVE';item.versionId=version.id;item.version=version.version;}if(action==='SUSPEND')item.status='SUSPENDED';return copy(item);},
  buy:(id:string)=>{const item=find(id);if(item.status!=='ACTIVE'||!item.versionId)throw Error('This sample template is unavailable.');if(purchases.some(purchase=>purchase.versionId===item.versionId))throw Error('This sample release is already in your purchase history.');const purchase:TemplatePurchase={id:crypto.randomUUID(),templateId:id,versionId:item.versionId,title:item.title,version:item.version||'',licenseTerms:item.licenseTerms,sha256:item.versions?.find(version=>version.id===item.versionId)?.sha256||'',amountMinor:item.priceMinor,currency:'INR',mode:'test',status:'CAPTURED',refundedMinor:0,downloadAvailable:false,createdAt:new Date().toISOString()};purchases.push(purchase);return copy(purchase);},
  dispute:(id:string,reason:string)=>{const purchase=purchases.find(item=>item.id===id);if(!purchase||purchase.dispute)throw Error('This sample purchase cannot accept another dispute.');purchase.dispute={status:'OPEN',reason};purchase.status='DISPUTED';return copy(purchase);},
  reset:()=>{owned=copy(templates);purchases=[];},
 };
}
