import Link from 'next/link';
import {ArrowUpRight,Braces,ChartNoAxesCombined,Cpu,GraduationCap,Search} from 'lucide-react';
import {collegeCatalog} from '@/lib/component-server';
import {educationModes,educationDifficulties,educationLabel,educationModeLabel} from '@/lib/education';
import {collegeCategories,componentLabel} from '@/lib/components';
export const metadata={title:'College projects',description:'Explore student contributions across full stack, data analytics, AI and IoT. See the problem, outcome and technology behind each project.'};
export default async function College({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const filters=await searchParams,params=new URLSearchParams();for(const k of ['q','category','language','mode','difficulty','builder','page'])if(filters[k])params.set(k,filters[k]!);const {data,preview}=await collegeCatalog(params);
 const icons={FULL_STACK:Braces,DATA_ANALYTICS:ChartNoAxesCombined,AI_ML:Cpu,IOT:Cpu};
 return <main id="main" className="kit-page"><header className="kit-catalog-head kit-college-head"><div><span className="eyebrow">Learning, made visible.</span><h1>A project is more<br/>than its screenshot.</h1><p>Discover the problem, the approach and the person behind it.<br className="kit-desktop-break"/> Full stack, analytics, AI and IoT, in the languages you use.</p></div><div className="kit-hero-side"><GraduationCap size={58} strokeWidth={1.3}/><Link href="/workspace/college-projects" className="button">Showcase your project <ArrowUpRight size={16}/></Link><small>Built on your existing builder profile</small></div></header>
 {preview&&<p className="kit-notice">Illustrative college releases and creators. Original learning packages are inspectable; no platform review, hosted runtime, merchant or purchase is implied.</p>}
 <form className="kit-filters" method="get" action="/college-projects"><div className="kit-search"><Search size={19}/><label className="sr-only" htmlFor="college-q">Search college projects</label><input id="college-q" name="q" defaultValue={filters.q} maxLength={200} placeholder="Find a project or problem…"/></div><label className="sr-only" htmlFor="college-category">Project category</label><select style={{flex:'1 1 220px'}} id="college-category" name="category" defaultValue={filters.category||''}><option value="">All project categories</option>{collegeCategories.map(([key,title])=><option key={key} value={key}>{title}</option>)}</select><label className="sr-only" htmlFor="college-language">Coding language</label><input id="college-language" name="language" defaultValue={filters.language} placeholder="Language, e.g. Python" maxLength={100} style={{flex:'1 1 220px',minWidth:0,minHeight:44,maxWidth:'100%',padding:'10px 12px',border:'1px solid var(--control-border)',borderRadius:10,background:'var(--control-surface)',fontSize:16}}/><label className="sr-only" htmlFor="college-mode">Access mode</label><select id="college-mode" name="mode" style={{flex:'1 1 220px'}} defaultValue={filters.mode||''}><option value="">All access modes</option>{educationModes.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><label className="sr-only" htmlFor="college-difficulty">Difficulty</label><select id="college-difficulty" name="difficulty" style={{flex:'1 1 220px'}} defaultValue={filters.difficulty||''}><option value="">All difficulties</option>{educationDifficulties.map(key=><option value={key} key={key}>{educationLabel(key)}</option>)}</select><button className="button">Search</button>{(filters.q||filters.category||filters.language||filters.mode||filters.difficulty)&&<Link className="link" href="/college-projects">Reset</Link>}</form>
 <div className="kit-grid">{data.items.map(p=>{const Icon=icons[p.education.category as keyof typeof icons]||Braces;return <article className="kit-card" key={p.id}><Link aria-label={'Explore '+p.title} href={'/college-projects/'+p.slug} className="kit-college-art-link"><div className={'kit-college-art '+p.education.category.toLowerCase()} aria-hidden="true"><Icon size={74} strokeWidth={1}/><strong>{componentLabel(p.education.category)}</strong></div></Link><div className="kit-card-copy"><div className="kit-card-meta"><span>{p.education.language}</span><span>{educationModeLabel(p.education.release?.snapshot.mode||p.education.mode)}</span></div><h2><Link href={'/college-projects/'+p.slug}>{p.title}</Link></h2><p>{p.education.problem}</p><div className="kit-card-foot"><span>{p.builder}</span><span>{educationLabel(p.education.release?.snapshot.difficulty||p.education.difficulty||'BEGINNER')}</span></div></div></article>;})}</div>
 {!data.items.length&&<section className="kit-empty"><h2>No college projects found.</h2><p>Try another language or category, or be the first to share your work.</p><Link href="/workspace/college-projects" className="button">Showcase a project</Link></section>}
 {data.hasMore&&<Link className="button" href={'/college-projects?'+new URLSearchParams({...filters,page:String(Number(filters.page||0)+1)} as Record<string,string>)}>Next page →</Link>}
 <section className="kit-footer-callout"><div><h2>Show what you contributed.</h2><p>Publish category evidence and an exact source package with your existing showcase. Free learning does not need a purchase. Paid source requires reviewed terms and merchant activation.</p></div><Link href="/workspace/college-projects" className="button primary">Publish a learning release ↗</Link></section></main>;
}
