import Link from 'next/link';
import {ArrowUpRight,Braces,ChartNoAxesCombined,Cpu,GraduationCap,Search} from 'lucide-react';
import {collegeCatalog} from '@/lib/component-server';
import {collegeCategories,componentLabel} from '@/lib/components';
export const metadata={title:'College projects',description:'Explore student contributions across full stack, data analytics, AI and IoT. See the problem, outcome and technology behind each project.'};
export default async function College({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const filters=await searchParams,params=new URLSearchParams();for(const k of ['q','category','language','builder','page'])if(filters[k])params.set(k,filters[k]!);const {data,preview}=await collegeCatalog(params);
 const icons={FULL_STACK:Braces,DATA_ANALYTICS:ChartNoAxesCombined,AI_ML:Cpu,IOT:Cpu};
 return <main id="main" className="kit-page"><header className="kit-catalog-head kit-college-head"><div><span className="eyebrow">Learning, made visible.</span><h1>A project is more<br/>than its screenshot.</h1><p>Discover the problem, the approach and the person behind it.<br className="kit-desktop-break"/> Full stack, analytics, AI and IoT, in the languages you use.</p></div><div className="kit-hero-side"><GraduationCap size={58} strokeWidth={1.3}/><Link href="/workspace/college-projects" className="button">Showcase your project <ArrowUpRight size={16}/></Link><small>Built on your existing builder profile</small></div></header>
 {preview&&<p className="kit-notice">Illustrative college project records. These explain the V4.5 metadata experience and do not claim verified runtimes or source packages.</p>}
 <form className="kit-filters" method="get" action="/college-projects"><div className="kit-search"><Search size={19}/><label className="sr-only" htmlFor="college-q">Search college projects</label><input id="college-q" name="q" defaultValue={filters.q} maxLength={200} placeholder="Find a project or problem…"/></div><label className="sr-only" htmlFor="college-category">Project category</label><select id="college-category" name="category" defaultValue={filters.category||''}><option value="">All project categories</option>{collegeCategories.map(([key,title])=><option key={key} value={key}>{title}</option>)}</select><label className="sr-only" htmlFor="college-language">Coding language</label><input id="college-language" name="language" defaultValue={filters.language} placeholder="Language, e.g. Python" maxLength={100} style={{minHeight:44,maxWidth:220,padding:'10px 12px',border:'1px solid var(--control-border)',borderRadius:10,background:'var(--control-surface)',fontSize:16}}/><button className="button">Search</button>{(filters.q||filters.category||filters.language)&&<Link className="link" href="/college-projects">Reset</Link>}</form>
 <div className="kit-grid">{data.items.map(p=>{const Icon=icons[p.education.category as keyof typeof icons]||Braces;return <article className="kit-card" key={p.id}><Link aria-label={'Explore '+p.title} href={'/college-projects/'+p.slug} className="kit-college-art-link"><div className={'kit-college-art '+p.education.category.toLowerCase()} aria-hidden="true"><Icon size={74} strokeWidth={1}/><strong>{componentLabel(p.education.category)}</strong></div></Link><div className="kit-card-copy"><div className="kit-card-meta"><span>{p.education.language}</span><span>Showcase only</span></div><h2><Link href={'/college-projects/'+p.slug}>{p.title}</Link></h2><p>{p.education.problem}</p><div className="kit-card-foot"><span>{p.builder}</span><span>Source only</span></div></div></article>;})}</div>
 {!data.items.length&&<section className="kit-empty"><h2>No college projects found.</h2><p>Try another language or category, or be the first to share your work.</p><Link href="/workspace/college-projects" className="button">Showcase a project</Link></section>}
 {data.hasMore&&<Link className="button" href={'/college-projects?'+new URLSearchParams({...filters,page:String(Number(filters.page||0)+1)} as Record<string,string>)}>Next page →</Link>}
 <section className="kit-footer-callout"><div><h2>Show what you contributed.</h2><p>Your college project uses an existing showcase, with a clear contribution and optional academic details. Source-sale and hosted lab capabilities arrive in later phases.</p></div><Link href="/workspace/college-projects" className="button primary">Add project context ↗</Link></section></main>;
}
