'use client';

import {useEffect, useRef, useState} from 'react';
import Link from 'next/link';
import {ArrowDownToLine, ArrowLeft, ArrowRight, BarChart3, BookOpen, Cpu, RefreshCw, ShieldCheck} from 'lucide-react';
import {Card, CardContent, CardHeader} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {DATA_AI_INDEX_LIMIT, DATA_AI_RECORDING_LIMIT, dataAiCatalogue, parseDataAiIndex, parseDataAiRecording, readDataAiFile, type DataAiId, type DataAiIndex, type DataAiRecording, type DataAiResult, type DataAiTable} from '@/lib/data-ai';
import './data-ai.css';

const failure = (problem: unknown) => problem instanceof Error ? problem.message : 'The evidence could not be read. Retry to check again.';
const formatted = (value: number | string) => typeof value === 'number' ? value.toLocaleString('en-IN', {maximumFractionDigits: 6}) : value;
type View = 'source' | 'recording' | 'hosted';

function ReturnedTable({table}: {table: DataAiTable}) {
  const label = table.columns.find(column => column.type === 'string')!, value = table.columns.find(column => column.type === 'number')!;
  const maximum = Math.max(...table.rows.map(row => Number(row[value.key])), 1);
  return <section className="data-ai-result-table" aria-labelledby={'data-ai-table-' + table.id}>
    <h4 id={'data-ai-table-' + table.id}>{table.title}</h4>
    <figure className="data-ai-chart"><figcaption>{value.label} by {label.label.toLowerCase()} · {value.unit}</figcaption><div className="data-ai-bars" aria-hidden="true">{table.rows.map(row => <div className="data-ai-bar-row" key={String(row[label.key])}><span>{row[label.key]}</span><div className="data-ai-bar-track"><div style={{width: `${Number(row[value.key]) / maximum * 100}%`}}/></div><strong>{formatted(row[value.key])}</strong></div>)}</div></figure>
    <div className="data-ai-table-wrap" role="region" aria-label={table.title + ' recorded values'} tabIndex={0}><table><caption>Actual returned {table.title.toLowerCase()}</caption><thead><tr>{table.columns.map(column => <th scope="col" key={column.key}>{column.label}{column.unit !== 'none' ? ` (${column.unit})` : ''}</th>)}</tr></thead><tbody>{table.rows.map(row => <tr key={String(row[label.key])}>{table.columns.map((column, index) => index === 0 ? <th scope="row" key={column.key}>{formatted(row[column.key])}</th> : <td key={column.key}>{formatted(row[column.key])}</td>)}</tr>)}</tbody></table></div>
    <details><summary>Table fields, types and units</summary><dl className="data-ai-schema">{table.columns.map(column => <div key={column.key}><dt>{column.key}</dt><dd>{column.type} · {column.unit}</dd></div>)}</dl></details>
  </section>;
}

function ReturnedOutput({output}: {output: DataAiResult}) {
  return <section className="data-ai-output" aria-labelledby="data-ai-output-heading"><h3 id="data-ai-output-heading">Rendered output · Recorded local result</h3><p className="data-ai-muted">These tables and charts render the selected original response. Selecting another case inspects its recording; computation happens when you run the source locally.</p>
    <dl className="data-ai-metrics">{output.metrics.map(metric => <div key={metric.key}><dt>{metric.label}</dt><dd>{formatted(metric.value)}<span>{metric.unit}</span></dd></div>)}</dl>
    {output.prediction && <div className="data-ai-prediction"><Cpu size={22} aria-hidden="true"/><div><h4>Recorded prediction: {output.prediction.label}</h4><p>{formatted(output.prediction.probability)} model probability · frozen illustrative model</p></div></div>}
    {output.tables.map(table => <ReturnedTable key={table.id} table={table}/>)}
    {output.evaluation && <section className="data-ai-evaluation" aria-labelledby="data-ai-evaluation-heading"><h4 id="data-ai-evaluation-heading">Held-out synthetic evaluation</h4><p>{output.evaluation.samples} samples · {output.evaluation.split} · {output.evaluation.protocol}</p><dl className="data-ai-metrics"><div><dt>Correct predictions</dt><dd>{output.evaluation.correct}<span>of {output.evaluation.samples} synthetic samples</span></dd></div><div><dt>Accuracy</dt><dd>{formatted(output.evaluation.accuracy)}<span>ratio</span></dd></div></dl><p>{output.evaluation.limitations}</p><p className="data-ai-muted">No training occurs during inference. This fixture metric does not establish real-world accuracy.</p></section>}
  </section>;
}

function RecordingDetails({recording}: {recording: DataAiRecording}) {
  const [position, setPosition] = useState(0), run = recording.runs[position];
  return <div><div className="data-ai-notice"><BookOpen size={22} aria-hidden="true"/><p><strong>Replay · Recorded local execution</strong><br/>These are original local observations checked for schema and checksum consistency. They do not certify hosted execution.</p></div>
    <div className="data-ai-field"><label htmlFor="data-ai-case">Recorded case</label><select id="data-ai-case" value={position} onChange={event => setPosition(Number(event.target.value))}><option value="0">1 of 2 · Default inputs</option><option value="1">2 of 2 · Changed inputs</option></select></div>
    <div className="data-ai-actions"><button className="data-ai-button" onClick={() => setPosition(position - 1)} disabled={position === 0}><ArrowLeft size={18} aria-hidden="true"/>Previous case</button><button className="data-ai-button" onClick={() => setPosition(position + 1)} disabled={position === 1}>Next case<ArrowRight size={18} aria-hidden="true"/></button></div>
    <p role="status" aria-live="polite" className="data-ai-case-status">Case {position + 1} of 2 · {position === 0 ? 'Default' : 'Changed'} inputs · original mode LOCAL · measured {run.elapsedMs} ms</p>
    <dl className="data-ai-inputs"><div><dt>Original start time</dt><dd><time dateTime={run.startedAt}>{run.startedAt}</time></dd></div><div><dt>Original fixed synthetic inputs</dt><dd>{Object.entries(run.input).map(([key, value]) => `${key}: ${value}`).join(' · ')}</dd></div></dl>
    <ReturnedOutput output={run.result}/>
    <details className="data-ai-provenance"><summary>Original run identity and checksums</summary><dl>{([['Run ID', run.runId], ['Source SHA-256', run.sourceSha256], ['Data SHA-256', run.dataSha256], ['Model SHA-256', run.modelSha256 || 'Analytics: no model'], ['Evaluation SHA-256', run.evaluationSha256 || 'Analytics: no model evaluation'], ['Input SHA-256', run.inputSha256], ['Result SHA-256', run.resultSha256], ['Recording time', recording.recordedAt]] as const).map(([label, value]) => <div key={label}><dt>{label}</dt><dd><code>{value}</code></dd></div>)}</dl><p>Checksums identify and compare bytes. They do not establish hosted authenticity or model accuracy.</p></details>
    <details className="data-ai-raw"><summary>Actual original result envelope</summary><pre>{JSON.stringify(run, null, 2)}</pre></details>
  </div>;
}

export default function DataAiDashboard() {
  const [index, setIndex] = useState<DataAiIndex | null>(null), [indexLoading, setIndexLoading] = useState(true), [indexError, setIndexError] = useState(''), [indexRetry, setIndexRetry] = useState(0);
  const [selected, setSelected] = useState<DataAiId>('revenue-summary'), [view, setView] = useState<View>('source'), [kind, setKind] = useState('all');
  const [recording, setRecording] = useState<DataAiRecording | null>(null), [recordingError, setRecordingError] = useState(''), [recordingRetry, setRecordingRetry] = useState(0);
  const indexAlert = useRef<HTMLDivElement>(null), recordingAlert = useRef<HTMLDivElement>(null);
  const items = index?.items ?? dataAiCatalogue, filtered = items.filter(item => kind === 'all' || item.kind === kind), material = filtered.find(item => item.id === selected) ?? filtered[0];
  const current = recording?.scenarioId === material?.id && recording?.sourceSha256 === index?.sourceSha256 ? recording : null;
  const recordingLoading = view === 'recording' && Boolean(index && material) && !current && !recordingError;
  useEffect(() => {const controller = new AbortController(); let active = true; async function load() {try {const response = await fetch('/data-ai/material-index.json', {cache: 'no-store', signal: AbortSignal.any([controller.signal, AbortSignal.timeout(15000)])}), next = parseDataAiIndex(await readDataAiFile(response, DATA_AI_INDEX_LIMIT)); if (active) {setIndex(next); setIndexError('');}} catch (problem) {if (active) {setIndex(null); setIndexError(failure(problem));}} finally {if (active) setIndexLoading(false);}} void load(); return () => {active = false; controller.abort();};}, [indexRetry]);
  useEffect(() => {if (indexError && indexRetry > 0) indexAlert.current?.focus();}, [indexError, indexRetry]);
  useEffect(() => {const controller = new AbortController(); let active = true; if (view !== 'recording' || !index || !material) return () => controller.abort(); const sourceIndex = index, sourceMaterial = material; async function load() {try {const response = await fetch(sourceMaterial.recordingUrl, {cache: 'no-store', signal: AbortSignal.any([controller.signal, AbortSignal.timeout(15000)])}), next = await parseDataAiRecording(await readDataAiFile(response, DATA_AI_RECORDING_LIMIT), sourceIndex, sourceMaterial); if (active) {setRecording(next); setRecordingError('');}} catch (problem) {if (active) {setRecording(null); setRecordingError(failure(problem));}}} void load(); return () => {active = false; controller.abort();};}, [view, index, material, recordingRetry]);
  useEffect(() => {if (recordingError) recordingAlert.current?.focus();}, [recordingError]);
  function choose(id: DataAiId) {setSelected(id); setView('source'); setRecording(null); setRecordingError('');}
  function show(next: View) {if (next === view) return; setView(next); setRecording(null); setRecordingError('');}
  function retryIndex() {setIndexLoading(true); setIndexError(''); setRecording(null); setRecordingError(''); setIndexRetry(value => value + 1);}
  return <main id="main" className="data-ai-shell">
    <header className="data-ai-header"><div><span className="data-ai-kicker"><BarChart3 size={18} aria-hidden="true"/>Data & AI labs · V5.0</span><h1>Read the source. Inspect the evidence.</h1><p>Two analytics labs and two curated CPU inference labs. Explore measured synthetic tables, charts and evaluation context, then reproduce the results locally.</p></div><Link className="data-ai-button" href="/labs/scenarios"><ArrowLeft size={18} aria-hidden="true"/>Backend scenarios</Link></header>
    <div className="data-ai-boundary"><ShieldCheck size={24} aria-hidden="true"/><div><strong>Source, replay and hosted admission remain separate.</strong><p>This inspector reads recorded local results. Hosted execution requires current provider certification, independent activation flags and admission in the shared lab workbench. Source downloads stay free.</p></div></div>
    <div className="data-ai-overview"><Card><CardContent><span>Curated source labs</span><strong>4</strong><p>2 analytics · 2 CPU inference</p></CardContent></Card><Card><CardContent><span>Build-listed recordings</span><strong>{indexLoading ? '…' : index ? index.items.length : 'Unconfirmed'}</strong><p>{indexLoading ? 'Checking source index' : 'Original local observations'}</p></CardContent></Card><Card><CardContent><span>Hosted runtime</span><strong>Admission required</strong><p>Checked in the shared workbench</p></CardContent></Card></div>
    {indexLoading && <p className="data-ai-notice" role="status">Loading source versions and recording availability…</p>}
    {indexError && <div ref={indexAlert} className="data-ai-notice data-ai-error" role="alert" tabIndex={-1}><div><strong>Source index unavailable or rejected</strong><p>{indexError} Source catalogue and local setup remain available; recording versions are unconfirmed.</p><button className="data-ai-button" disabled={indexLoading} onClick={retryIndex}><RefreshCw size={18} aria-hidden="true"/>Retry source index</button></div></div>}
    <div className="data-ai-grid"><section className="data-ai-catalogue" aria-labelledby="data-ai-catalogue-heading"><h2 id="data-ai-catalogue-heading">Curated source catalogue</h2><div className="data-ai-field"><label htmlFor="data-ai-kind">Lab category</label><select id="data-ai-kind" value={kind} onChange={event => {setKind(event.target.value); setView('source'); setRecording(null); setRecordingError('');}}><option value="all">All four labs</option><option value="DATA_ANALYTICS">Data analytics</option><option value="AI_ML">CPU inference</option></select></div><p className="data-ai-count" role="status" aria-live="polite">{filtered.length} source labs</p><div className="data-ai-cards">{filtered.map(item => <Card key={item.id} className={'data-ai-card' + (material?.id === item.id ? ' selected' : '')}><CardContent><Badge variant="outline">{item.kind === 'DATA_ANALYTICS' ? 'Analytics' : 'CPU inference'}</Badge><h3><button className="data-ai-card-select" aria-pressed={item.id === material?.id} onClick={() => choose(item.id)}>{item.title}<ArrowRight size={18} aria-hidden="true"/></button></h3><p>{item.summary}</p><span className="data-ai-card-status">{item.id === material?.id && recordingError ? 'Recording rejected or unavailable' : index ? 'Recorded local evidence listed' : 'Source only · recording unconfirmed'}</span></CardContent></Card>)}</div></section>
    <section className="data-ai-inspector" aria-labelledby="data-ai-inspector-heading"><Card><CardHeader><span className="data-ai-kicker">Evidence inspector</span><h2 id="data-ai-inspector-heading">{material?.title ?? 'Choose a source lab'}</h2><div className="data-ai-view-controls" aria-label="Evidence view"><button className="data-ai-button" aria-pressed={view === 'source'} onClick={() => show('source')}>Source</button><button className="data-ai-button" aria-pressed={view === 'recording'} onClick={() => show('recording')}>Recorded execution</button><button className="data-ai-button" aria-pressed={view === 'hosted'} onClick={() => show('hosted')}>Hosted runtime</button></div></CardHeader><CardContent>{material && <>
      {view === 'source' && <div className="data-ai-source"><p>{material.summary}</p><h3>Reproduce the source locally</h3><p className="data-ai-setup">{index?.setup || 'Requires Python 3.12+ standard library. Download the free archive and read README.md. Set LAB_RUN_ID to a fresh UUID and LAB_PORT before starting the local server on 127.0.0.1. Follow the fixed execute request examples; no external model or remote code is accepted.'}</p><div className="data-ai-actions"><a className="data-ai-button data-ai-primary" href="/data-ai/source.tar.gz" download><ArrowDownToLine size={18} aria-hidden="true"/>Download free source & setup</a></div><p className="data-ai-muted">The archive includes README, separate code/data/model MIT notices, the fixed fixtures/models and reproduction instructions. Execution uses your local Python environment.</p><h3>Bounded input contract</h3><dl className="data-ai-schema">{material.inputs.map(field => <div key={field.name}><dt>{field.label}</dt><dd>{field.type === 'ENUM' ? field.choices.join(' / ') : field.type === 'INTEGER' ? `Whole number ${field.min}–${field.max}` : `Printable ASCII text, at most ${field.maxLength} bytes`}</dd></div>)}</dl><h3>Separate rights and limitations</h3><dl className="data-ai-schema"><div><dt>Code license</dt><dd>MIT · original source notices in the archive</dd></div><div><dt>Data license</dt><dd>{material.dataLicense} · {material.dataProvenance}</dd></div>{material.kind === 'AI_ML' && <div><dt>Model license and format</dt><dd>{material.modelLicense} · {material.modelFormat} · {material.modelProvenance}</dd></div>}</dl><p>{material.limitations}</p><details className="data-ai-provenance"><summary>Source and artifact checksums</summary><dl><div><dt>Source SHA-256</dt><dd><code>{index?.sourceSha256 || 'Unconfirmed until the source index loads'}</code></dd></div><div><dt>Archive SHA-256</dt><dd><code>{index?.archiveSha256 || 'Unconfirmed until the source index loads'}</code></dd></div>{(['dataSha256', 'modelSha256', 'evaluationSha256'] as const).map(key => <div key={key}><dt>{key.replace('Sha256', ' SHA-256')}</dt><dd><code>{material[key] || 'Not applicable to analytics'}</code></dd></div>)}</dl></details></div>}
      {view === 'recording' && <>{recordingLoading && <p className="data-ai-notice" role="status">Loading and checking original recorded evidence…</p>}{recordingError && <div className="data-ai-notice data-ai-error" role="alert" tabIndex={-1} ref={recordingAlert}><div><strong>Recording unavailable or rejected</strong><p>{recordingError} No prediction or output is shown.</p><button className="data-ai-button" onClick={() => {setRecording(null); setRecordingError(''); setRecordingRetry(value => value + 1);}}><RefreshCw size={18} aria-hidden="true"/>Retry recording</button></div></div>}{current && !recordingError && <RecordingDetails key={current.scenarioId + current.runs[0].runId + current.runs[0].startedAt} recording={current}/>} {!index && <div className="data-ai-empty"><h3>Recording version unconfirmed</h3><p>Load a valid source index to inspect its matching original evidence. The source and local setup remain free.</p><button className="data-ai-button" onClick={() => show('source')}>Open source</button></div>}</>}
      {view === 'hosted' && <div className="data-ai-hosted"><ShieldCheck size={30} aria-hidden="true"/><h3>Hosted runtime · Current admission</h3><p>Check the shared lab workbench for its current certified catalogue, free allowance and any active run. Data/AI manifests appear only when the independent data/AI flag and existing provider/admission gates are satisfied.</p><Link className="data-ai-button data-ai-primary" href="/labs">Check hosted admission<ArrowRight size={18} aria-hidden="true"/></Link><p className="data-ai-muted">Recorded local evidence grants no hosted run. The existing controls retain authentication, quotas, explicit requests, expiry, cleanup and operator authority.</p></div>}
    </>}</CardContent></Card></section></div>
  </main>;
}
