'use client';

import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,BookOpen,Clock3,FlaskConical,RefreshCw,ShieldCheck,Square} from 'lucide-react';
import {Card,CardContent,CardHeader} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {api,ApiError} from '@/lib/api';
import {labApplyEvents,labAttempt,labCanRequest,labCanStop,labEventsPath,labExpired,labExpiryText,labFieldErrors,labSourceUrl,labRunResponse,labStatusLabel,labTerminal,parseLabEvents,type LabAttempt,type LabCatalogue,type LabEvent,type LabInput,type LabManifest,type LabQuota,type LabRun,type LabRunBody} from '@/lib/labs';
import './labs.css';

const labApi=(path:string,init:RequestInit={})=>api(path,{...init,signal:init.signal??AbortSignal.timeout(15000)});
const message=(problem:unknown)=>problem instanceof Error?problem.message:'The service is unavailable. Try the same request again.';
const definitiveDenial=(problem:unknown)=>problem instanceof ApiError&&([400,401,403,429].includes(problem.status)||problem.code==='LAB_DISABLED');
const emptyInputs=(fields:LabInput[])=>Object.fromEntries(fields.map(field=>[field.name,field.type==='BOOLEAN'?'false':'']));

function Inputs({fields,values,errors,disabled,prefix,onChange}:{fields:LabInput[];values:Record<string,string>;errors:Record<string,string>;disabled:boolean;prefix:string;onChange:(name:string,value:string)=>void}){
 return <div className="lab-fields">{fields.map(field=>{const id=prefix+'-'+field.name,hint=id+'-hint',error=id+'-error',props={id,name:field.name,value:values[field.name]??'',disabled,required:field.required,'aria-invalid':errors[field.name]?'true' as const:undefined,'aria-describedby':hint+(errors[field.name]?' '+error:'')};return <div className="lab-field" key={field.name}><label htmlFor={id}>{field.label}{!field.required&&<span> (optional)</span>}</label>{field.type==='ENUM'||field.type==='BOOLEAN'?<select {...props} onChange={event=>onChange(field.name,event.target.value)}>{field.type==='BOOLEAN'?<><option value="false">No</option><option value="true">Yes</option></>:<><option value="">Choose a value</option>{field.choices.map(choice=><option key={choice} value={choice}>{choice}</option>)}</>}</select>:<input {...props} type="text" inputMode={field.type==='INTEGER'?'numeric':undefined} maxLength={Math.min(field.maxLength||1024,4096)} onChange={event=>onChange(field.name,event.target.value)}/>}<span className="lab-hint" id={hint}>{field.type==='INTEGER'?'Whole number: '+field.min+'–'+field.max:field.type==='BOOLEAN'?'A certified yes or no input.':field.type==='ENUM'?'Choose one of the certified values.':'Maximum '+Math.min(field.maxLength||1024,4096)+' characters.'}</span>{errors[field.name]&&<span className="lab-field-error" id={error}>{errors[field.name]}</span>}</div>;})}</div>;
}

export default function LabWorkbench(){
 const [catalogue,setCatalogue]=useState<LabCatalogue|null>(null),[quota,setQuota]=useState<LabQuota|null>(null),[selected,setSelected]=useState(''),[scenarioId,setScenarioId]=useState(''),[inputs,setInputs]=useState<Record<string,string>>({});
 const [run,setRun]=useState<LabRun|null>(null),[events,setEvents]=useState<LabEvent[]>([]),[requestValues,setRequestValues]=useState<Record<string,string>>({}),[operationId,setOperationId]=useState(''),[response,setResponse]=useState<string|null>(null);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[quotaError,setQuotaError]=useState(''),[authenticated,setAuthenticated]=useState(false),[notice,setNotice]=useState(''),[fieldErrors,setFieldErrors]=useState<Record<string,string>>({}),[requestErrors,setRequestErrors]=useState<Record<string,string>>({}),[now,setNow]=useState(Date.now());
 const [attempt,setAttempt]=useState<LabAttempt<LabRunBody>|null>(null),[requestAttempt,setRequestAttempt]=useState<LabAttempt<{operationId:string;inputs:Record<string,string>}>|null>(null);
 const initializedRun=useRef(''),alive=useRef(true),epoch=useRef(0),eventAbort=useRef<AbortController|null>(null),eventCursor=useRef(0),summary=useRef<HTMLParagraphElement>(null);
 const manifest=catalogue?.items.find(item=>item.id===selected),scenario=manifest?.scenarios.find(item=>item.id===scenarioId),runManifest=catalogue?.items.find(item=>item.id===run?.manifestId),runScenario=runManifest?.scenarios.find(item=>item.id===run?.scenarioId);
 const privateReset=()=>{setAuthenticated(false);setQuota(null);setRun(null);setEvents([]);setResponse(null);eventCursor.current=0;eventAbort.current?.abort();};
 useEffect(()=>{if(error)summary.current?.focus();},[error]);
 useEffect(()=>{alive.current=true;void load();const clock=window.setInterval(()=>setNow(Date.now()),10000);return()=>{alive.current=false;epoch.current++;eventAbort.current?.abort();window.clearInterval(clock);};},[]);
 useEffect(()=>{if(run&&labTerminal(run.status))eventAbort.current?.abort();},[run?.status]);
 useEffect(()=>{if(!run||!runScenario||initializedRun.current===run.id)return;initializedRun.current=run.id;setOperationId(runScenario.operations[0]?.id||'');setRequestValues(previous=>Object.keys(previous).length?previous:emptyInputs(runScenario.inputs));},[run?.id,runScenario]);
 async function load(){
  const token=++epoch.current;setLoading(true);setError('');setQuotaError('');
  const [catalogueResult,quotaResult]=await Promise.allSettled([labApi('/lab-manifests'),labApi('/lab-quota')]);
  if(!alive.current||token!==epoch.current)return;
  if(catalogueResult.status==='fulfilled'){
   const next=catalogueResult.value as LabCatalogue;setCatalogue(next);
   if(!selected&&next.items.length){const first=next.items[0],step=first.scenarios[0];setSelected(first.id);setScenarioId(step?.id||'');setInputs(emptyInputs(step?.inputs||[]));}
  }else{setCatalogue(null);setError(message(catalogueResult.reason));}
  if(quotaResult.status==='fulfilled'){
   const next=quotaResult.value as LabQuota;setQuota(next);setAuthenticated(true);
   if(next.activeRunId&&!run)try{const active=labRunResponse(await labApi('/lab-runs/'+encodeURIComponent(next.activeRunId)));if(alive.current&&token===epoch.current)setRun(active);}catch(problem){if(alive.current&&token===epoch.current){if(problem instanceof ApiError&&[401,403].includes(problem.status))privateReset();setQuotaError(message(problem));}}
  }else{setQuota(null);setAuthenticated(false);if(quotaResult.reason instanceof ApiError&&[401,403].includes(quotaResult.reason.status))privateReset();if(quotaResult.reason instanceof ApiError&&quotaResult.reason.status===401)setQuotaError('Sign in to check your free run allowance.');else setQuotaError(message(quotaResult.reason));}
  if(alive.current&&token===epoch.current)setLoading(false);
 }
 function chooseManifest(id:string){const item=catalogue?.items.find(value=>value.id===id),step=item?.scenarios[0];setSelected(id);setScenarioId(step?.id||'');setInputs(emptyInputs(step?.inputs||[]));setFieldErrors({});setError('');}
 function chooseScenario(id:string){const step=manifest?.scenarios.find(value=>value.id===id);setScenarioId(id);setInputs(emptyInputs(step?.inputs||[]));setFieldErrors({});setError('');}
 async function activity(current:LabRun){
  eventAbort.current?.abort();const controller=new AbortController();eventAbort.current=controller;
  const timeout=window.setTimeout(()=>controller.abort(),15000);
  try{
   const reply=await fetch(labEventsPath(current.id),{credentials:'same-origin',headers:{Accept:'text/event-stream','X-Requested-With':'getlancer','Last-Event-ID':String(eventCursor.current)},signal:controller.signal});
   if(!reply.ok){const body=await reply.json().catch(()=>({}));throw new ApiError(body.error?.message||'Activity is unavailable.',body.error?.code||'REQUEST_FAILED',reply.status,body.error?.requestId);}
   if(!reply.headers.get('Content-Type')?.toLowerCase().includes('text/event-stream'))throw Error('Activity returned an unsupported response.');
   const reader=reply.body?.getReader();if(!reader)throw Error('Activity could not be read.');const decoder=new TextDecoder();let text='',bytes=0;
   try{while(true){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.byteLength;if(bytes>65536)throw Error('The activity response exceeded its limit.');text+=decoder.decode(chunk.value,{stream:true});}text+=decoder.decode();}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}
   if(!alive.current||controller.signal.aborted)return;
   const fresh=parseLabEvents(text,current.id,eventCursor.current);
   if(fresh.length){eventCursor.current=fresh[fresh.length-1].sequence;setEvents(previous=>[...previous,...fresh].slice(-100));setRun(previous=>previous?.id===current.id?labApplyEvents(previous,fresh):previous);}
  }finally{window.clearTimeout(timeout);}
 }
 async function refresh(){if(!run)return;setBusy(true);setError('');setNotice('');const token=epoch.current;
  try{const current=labRunResponse(await labApi('/lab-runs/'+encodeURIComponent(run.id)));if(!alive.current||token!==epoch.current)return;setRun(previous=>previous&&labTerminal(previous.status)&&!labTerminal(current.status)?previous:current);if(!labTerminal(current.status)&&!labExpired(current))await activity(current);else eventAbort.current?.abort();setNotice('Current run status checked.');}
  catch(problem){if(alive.current&&token===epoch.current){if(problem instanceof ApiError&&[401,403].includes(problem.status))privateReset();else if(problem instanceof ApiError&&[404,410].includes(problem.status)){setRun(null);setEvents([]);eventAbort.current?.abort();}setError(message(problem));}}
  finally{if(alive.current&&token===epoch.current)setBusy(false);}
 }
 async function start(event:React.FormEvent){event.preventDefault();if(!manifest||!scenario)return;const errors=labFieldErrors(scenario.inputs,inputs);setFieldErrors(errors);setError('');setNotice('');if(Object.keys(errors).length){setError('Check the labelled inputs before running.');return;}
  const token=epoch.current;let pending:LabAttempt<LabRunBody>;try{pending=labAttempt({manifestId:manifest.id,scenarioId:scenario.id,inputs},attempt);}catch(problem){setError(message(problem));return;}setAttempt(pending);setBusy(true);
  try{const current=labRunResponse(await labApi('/lab-runs',{method:'POST',headers:{'Idempotency-Key':pending.key},body:JSON.stringify(pending.body)}));if(!alive.current||token!==epoch.current)return;setRun(current);setAttempt(null);setEvents([]);setResponse(null);setRequestAttempt(null);eventCursor.current=0;setRequestValues({...inputs});setOperationId(scenario.operations[0]?.id||'');setNotice('Run accepted. Execution is verified only after the isolated worker becomes healthy.');try{await activity(current);}catch(problem){setError('The run was accepted; '+message(problem)+' Refresh this run to verify its state.');}void reloadQuota();}
  catch(problem){if(alive.current&&token===epoch.current){const denied=definitiveDenial(problem)&&!attempt;if(denied)setAttempt(null);if(problem instanceof ApiError&&[401,403].includes(problem.status))privateReset();if(problem instanceof ApiError)setFieldErrors(problem.fieldErrors);setError(message(problem)+(denied?' Your inputs have been kept.':' The result is uncertain. Retry the same request to recover its original run; its identity and inputs are retained.'));}}
  finally{if(alive.current&&token===epoch.current)setBusy(false);}
 }
 async function reloadQuota(){const token=epoch.current;try{const next=await labApi('/lab-quota') as LabQuota;if(alive.current&&token===epoch.current)setQuota(next);}catch(problem){if(alive.current&&token===epoch.current){setQuota(null);setQuotaError(message(problem));if(problem instanceof ApiError&&[401,403].includes(problem.status))privateReset();}}}
 async function stop(){if(!run||!labCanStop(run))return;const token=epoch.current;setBusy(true);setError('');setNotice('');eventAbort.current?.abort();
  try{const current=labRunResponse(await labApi('/lab-runs/'+encodeURIComponent(run.id)+'/stop',{method:'POST',body:'{}'}));if(!alive.current||token!==epoch.current)return;setRun(current);setNotice(labTerminal(current.status)?'The current run is stopped.':'Stop requested. Cleanup has not yet been confirmed.');void reloadQuota();}
  catch(problem){if(alive.current&&token===epoch.current){if(problem instanceof ApiError&&[401,403,404,410].includes(problem.status)){setRun(null);setEvents([]);}setError(message(problem)+' Refresh this same run to confirm its stop status.');}}
  finally{if(alive.current&&token===epoch.current)setBusy(false);}
 }
 async function send(event:React.FormEvent){event.preventDefault();if(!authenticated||!run||!runScenario||!labCanRequest(run)||!operationId)return;const errors=labFieldErrors(runScenario.inputs,requestValues);setRequestErrors(errors);setError('');setNotice('');if(Object.keys(errors).length){setError('Check the operation inputs.');return;}
  const token=epoch.current;let pending:LabAttempt<{operationId:string;inputs:Record<string,string>}>;try{pending=labAttempt({operationId,inputs:requestValues},requestAttempt);}catch(problem){setError(message(problem));return;}setRequestAttempt(pending);setBusy(true);
  try{const result=await labApi('/lab-runs/'+encodeURIComponent(run.id)+'/requests',{method:'POST',headers:{'Idempotency-Key':pending.key},body:JSON.stringify(pending.body)});if(!alive.current||token!==epoch.current)return;setRequestAttempt(null);setResponse(JSON.stringify(result,null,2).slice(0,65536));setNotice('Certified operation response received.');}
  catch(problem){if(alive.current&&token===epoch.current){const denied=problem instanceof ApiError&&[400,429].includes(problem.status)&&!requestAttempt;if(denied)setRequestAttempt(null);if(problem instanceof ApiError&&([401,403,404,410].includes(problem.status)||problem.code==='LAB_ISOLATION_LOST')){setRun(null);setEvents([]);setResponse(null);eventAbort.current?.abort();}if(problem instanceof ApiError)setRequestErrors(problem.fieldErrors);setError(message(problem)+(denied?' Operation inputs have been kept.':' Retry the same operation to recover its response.'));}}
  finally{if(alive.current&&token===epoch.current)setBusy(false);}
 }
 const source=labSourceUrl(manifest?.sourceUrl),runtime=catalogue?.runtime,canStart=!!manifest&&!!scenario&&authenticated&&(!!attempt||!!quota&&runtime?.enabled&&quota.runtime.enabled&&quota.remaining>0&&!quota.activeRunId&&(!run||labTerminal(run.status)));
 const unavailable=!!run&&(!runManifest||!runScenario),requestAllowed=authenticated&&!unavailable&&labCanRequest(run,now);
 return <main id="main" className="lab-shell">
  <header className="lab-page-head"><div><span className="lab-kicker"><FlaskConical size={16} aria-hidden="true"/>Lab workbench</span><h1>Run it. Inspect it. Keep the source.</h1><p>Reviewed source and setup stay free. Isolated execution opens only when its operator admission checks are complete.</p></div><div className="lab-actions"><Link className="button" href="/labs/data-ai"><FlaskConical size={17} aria-hidden="true"/>Explore data & AI</Link><Link className="button" href="/labs/scenarios"><FlaskConical size={17} aria-hidden="true"/>Explore backend scenarios</Link><Link className="button" href="/components"><BookOpen size={17} aria-hidden="true"/>Browse free components</Link></div></header>
  {error&&<p ref={summary} className="lab-notice lab-error" role="alert" tabIndex={-1}>{error}</p>}{notice&&<p className="lab-notice" role="status">{notice}</p>}{loading&&<p className="lab-notice" role="status">Loading current lab availability…</p>}
  {!loading&&(!runtime?.enabled||!catalogue)&&<div className="lab-notice"><ShieldCheck size={20} aria-hidden="true"/><div><strong>Live execution is unavailable</strong><p>{runtime?.reason||'The lab service could not be reached. No execution has started.'} Free source and setup remain available through the component library.</p></div></div>}
  <div className="lab-layout"><Card className="lab-catalogue"><CardHeader><h2>Certified labs</h2><p className="lab-muted">Only current operator-certified manifests appear here.</p></CardHeader><CardContent>{catalogue?.items.length?<nav aria-label="Certified labs">{catalogue.items.map(item=><button key={item.id} aria-current={selected===item.id?'true':undefined} disabled={busy||!!attempt} onClick={()=>chooseManifest(item.id)}><strong>{item.title}</strong><span>{item.language} · {item.framework}</span><span>{item.summary}</span></button>)}</nav>:<div className="lab-empty"><FlaskConical size={28} aria-hidden="true"/><h3>{loading?'Checking catalogue':'No certified labs yet'}</h3><p>No runtime scenarios are published. Explore free reviewed components while lab admission is prepared.</p><Link className="button" href="/components">Open component library<ArrowUpRight size={16} aria-hidden="true"/></Link></div>}<button className="button lab-retry" disabled={busy||loading} onClick={()=>void load()}><RefreshCw size={16} aria-hidden="true"/>Refresh availability</button></CardContent></Card>
   <div className="lab-main"><Card><CardHeader><div className="lab-heading"><div><h2>{manifest?.title||'A deliberate, bounded run'}</h2><p className="lab-muted">{manifest?.summary||'Choose a certified lab when one is available. Opening this page never reserves a run.'}</p></div>{manifest&&<Badge variant="outline">{manifest.executionMode}</Badge>}</div></CardHeader><CardContent><div className="lab-allowance"><Clock3 size={18} aria-hidden="true"/><div>{quota?<><strong>{quota.remaining} of {quota.dailyLimit} free runs remain today</strong><p>Resets {new Date(quota.resetAt).toLocaleString('en-GB')} · One active run per account.</p>{quota.activeRunId&&<p>An account run already holds a reservation. Check or stop that run below.</p>}</>:<><strong>{authenticated?'Allowance unavailable':'Account allowance'}</strong><p>{quotaError||'Checking current account allowance…'}</p>{!authenticated&&<Link href="/login">Sign in to check allowance</Link>}</>}</div></div>
    {manifest&&scenario?<form className="lab-form" onSubmit={start} noValidate><div className="lab-field"><label htmlFor="lab-scenario">Scenario</label><select id="lab-scenario" value={scenarioId} disabled={busy||!!attempt} onChange={event=>chooseScenario(event.target.value)}>{manifest.scenarios.map(step=><option value={step.id} key={step.id}>{step.title}</option>)}</select><p className="lab-hint">{scenario.description}</p></div><Inputs fields={scenario.inputs} values={inputs} errors={fieldErrors} disabled={busy||!!attempt} prefix="lab-start" onChange={(name,value)=>setInputs(previous=>({...previous,[name]:value}))}/>{attempt&&<p className="lab-hint">The previous response is uncertain. These exact inputs and the same request identity are kept until you recover that run.</p>}<div className="lab-actions"><button className="button primary" type="submit" disabled={busy||loading||!canStart}>{busy?'Checking request…':attempt?'Retry same run request':'Run isolated lab'}</button>{source&&<a className="button" href={source} target={source.startsWith('https:')?'_blank':undefined} rel={source.startsWith('https:')?'noopener noreferrer':undefined}>Free source & setup<ArrowUpRight size={16} aria-hidden="true"/></a>}</div><p className="lab-hint">Five-minute maximum lifetime. Idle cleanup starts after 90 seconds. Publishing slots and payments are separate from lab runs.</p></form>:<div className="lab-empty lab-empty-inline"><h3>Source is useful without a runtime</h3><p>Read and download reviewed frontend components, inspect their setup, and run them in your own environment.</p><div className="lab-actions"><Link className="button" href="/components">Browse free source</Link><Link className="button" href="/templates">Explore source templates</Link></div></div>}
   </CardContent></Card>
   {manifest&&<Card><CardHeader><h2>Setup before execution</h2></CardHeader><CardContent><pre className="lab-setup">{manifest.setup}</pre>{!source&&<p className="lab-hint">The source link could not be verified. Use the component library for available reviewed source.</p>}</CardContent></Card>}
   <Card><CardHeader><div className="lab-heading"><h2>Current run</h2>{run&&<Badge variant="outline">{labStatusLabel(run.status)}</Badge>}</div></CardHeader><CardContent>{run?<><div className="lab-run-summary"><strong>{run.verified?'Isolated execution verified':'Execution not yet verified'}</strong><p>{run.reason||'No additional worker status has been reported.'}</p><p className="lab-hint">{labExpiryText(run,now)}</p>{unavailable&&<p className="lab-field-error">This source or scenario is no longer in the eligible catalogue. Operations are unavailable.</p>}<code>Run {run.id}</code></div><div className="lab-actions"><button className="button" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16} aria-hidden="true"/>Refresh status & activity</button>{labCanStop(run)&&<button className="button" disabled={busy} onClick={()=>void stop()}><Square size={15} aria-hidden="true"/>Stop current run</button>}</div>
    {runScenario&&<form className="lab-form lab-operation" onSubmit={send} noValidate><h3>Certified operation</h3><div className="lab-field"><label htmlFor="lab-operation">Operation</label><select id="lab-operation" value={operationId||runScenario.operations[0]?.id||''} disabled={busy||!requestAllowed||!!requestAttempt} onChange={event=>setOperationId(event.target.value)}>{runScenario.operations.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></div><Inputs fields={runScenario.inputs} values={requestValues} errors={requestErrors} disabled={busy||!requestAllowed||!!requestAttempt} prefix="lab-operation" onChange={(name,value)=>setRequestValues(previous=>({...previous,[name]:value}))}/><button className="button primary" type="submit" disabled={busy||loading||!requestAllowed}>{requestAttempt?'Retry same operation':'Send certified request'}</button>{!requestAllowed&&<p className="lab-hint">Requests require a currently verified Running run before its expiry. Terminal and unavailable runs cannot receive operations.</p>}</form>}{response&&<div className="lab-response"><h3>Operation response</h3><pre>{response}</pre></div>}
    <div className="lab-activity"><h3>Recorded activity</h3>{events.length?<ol>{events.map(item=><li key={item.sequence}><span>{item.sequence} · {new Date(item.recordedAt).toLocaleTimeString('en-GB')}</span><strong>{item.type.replaceAll('_',' ').toLowerCase()}</strong><p>{item.data.reason||item.data.status&&labStatusLabel(item.data.status)||'Recorded control-plane event.'}</p></li>)}</ol>:<p className="lab-muted">No activity has been retrieved. Refresh checks your current access before replaying recorded events.</p>}</div></>:<div className="lab-empty lab-empty-inline"><h3>No run has been started here</h3><p>Queued and Starting runs can be cancelled. Terminal runs never become Running again. A lost response is recovered with its original identity.</p>{Object.keys(requestValues).length>0&&<div className="lab-fields lab-retained"><h3>Retained operation inputs</h3><p className="lab-hint">Your entered values remain available to copy. No request can be sent without a current authorized run.</p>{Object.entries(requestValues).map(([name,value])=><div className="lab-field" key={name}><label htmlFor={'lab-retained-'+name}>Retained {name}</label><input id={'lab-retained-'+name} readOnly value={value}/></div>)}</div>}</div>}</CardContent></Card>
   </div></div>
 </main>;
}
