package com.getlancer.commerce;

import static org.junit.jupiter.api.Assertions.*;
import com.getlancer.shared.ApiError;
import java.io.*;
import java.nio.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.*;
import org.junit.jupiter.api.Test;

class SourceArchiveTest {
  public static byte[] zip(Map<String,byte[]> files) throws IOException {var out=new ByteArrayOutputStream();try(var z=new ZipOutputStream(out)) {for(var entry:files.entrySet()) {z.putNextEntry(new ZipEntry(entry.getKey()));z.write(entry.getValue());z.closeEntry();}}return out.toByteArray();}
  public static Map<String,byte[]> valid() {var files=new LinkedHashMap<String,byte[]>();files.put("README.md","Build this application with npm install and npm run build. Includes the complete source.".getBytes(StandardCharsets.UTF_8));files.put("LICENSE","One commercial end product. Do not redistribute source as a competing template. Includes third-party MIT notice.".getBytes(StandardCharsets.UTF_8));files.put("package.json","{\"name\":\"source-package\",\"scripts\":{\"build\":\"vite build\"}}".getBytes(StandardCharsets.UTF_8));files.put("src/index.ts","export const application = 'complete source';".getBytes(StandardCharsets.UTF_8));return files;}
  @Test void safeSourceIsInspectedWithoutExecutingBuildCommands() throws Exception {var files=valid();files.put("package.json","{\"scripts\":{\"build\":\"touch /tmp/this-must-never-run\"}}".getBytes());var bytes=zip(files);var result=SourceArchive.inspect(bytes);assertEquals(4,result.entryCount());assertEquals(bytes.length,result.sizeBytes());assertEquals(64,result.sha256().length());assertEquals(List.of("package.json"),result.manifestFiles());assertFalse(java.nio.file.Files.exists(java.nio.file.Path.of("/tmp/this-must-never-run")));}
  @Test void missingReadmeLicenseAndManifestFailSeparately() throws Exception {for(String path:List.of("README.md","LICENSE","package.json")) {var files=valid();files.remove(path);assertThrows(ApiError.class,()->SourceArchive.inspect(zip(files)));}}
  @Test void traversalAbsoluteBackslashRepeatedSegmentsAndDrivePathsFail() throws Exception {for(String path:List.of("../escape.ts","/absolute.ts","dir/../../x.ts","C:/x.ts","dir\\x.ts","dir//x.ts","dir//")) {var files=valid();files.put(path,"source".getBytes());assertThrows(ApiError.class,()->SourceArchive.inspect(zip(files)),path);}}
  @Test void dependencyFoldersCredentialsAndPrivateKeysAreRejected() throws Exception {for(String path:List.of(".env",".env.production",".git/config","node_modules/a.ts","id_rsa","private-key.pem","credentials.json","app.exe","file.zip")) {var files=valid();files.put(path,"source data".getBytes());assertThrows(ApiError.class,()->SourceArchive.inspect(zip(files)),path);}}
  @Test void highConfidenceSecretsAreRejectedAndPlaceholderEnvironmentFileIsAllowed() throws Exception {for(String value:List.of("-----BEGIN PRIVATE KEY-----\nsecret","const token = 'ghp_abcdefghijklmnopqrstuvwxyz1234';","AWS = AKIA1234567890ABCDEF","KEY = rzp_live_abcdefgh12345678","API_SECRET=supersecret1234567890123456","export const keySecret = 'actualhardcodedsecret123456';","\"apiKey\": \"hardcodedcredential123456\"")) {var files=valid();files.put("config.ts",value.getBytes());assertThrows(ApiError.class,()->SourceArchive.inspect(zip(files)),value);}var files=valid();files.put(".env.example","API_SECRET=your_secret_placeholder".getBytes());assertDoesNotThrow(()->SourceArchive.inspect(zip(files)));}
  @Test void expandedBombAndEntryCountBoundsAreEnforced() throws Exception {var huge=valid();huge.put("bomb.txt",new byte[6*1024*1024]);assertThrows(ApiError.class,()->SourceArchive.inspect(zip(huge)));var many=valid();for(int n=0;n<500;n++) many.put("src/f"+n+".ts","source".getBytes());assertThrows(ApiError.class,()->SourceArchive.inspect(zip(many)));var expanded=valid();for(int n=0;n<6;n++) expanded.put("large"+n+".txt",new byte[5*1024*1024]);assertThrows(ApiError.class,()->SourceArchive.inspect(zip(expanded)));}
  @Test void compressedBoundAndInvalidZipFail() {assertThrows(ApiError.class,()->SourceArchive.inspect(new byte[SourceArchive.MAX_COMPRESSED+1]));assertThrows(ApiError.class,()->SourceArchive.inspect("not a zip archive".getBytes()));}
  @Test void unixSymlinksAndEncryptedEntriesAreRejected() throws Exception {for(boolean link:List.of(true,false)) {byte[] bytes=zip(valid());ByteBuffer buffer=ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN);for(int p=0;p<bytes.length-46;p++) if(buffer.getInt(p)==0x02014b50) {if(link) {buffer.putShort(p+4,(short)(3*256+20));buffer.putInt(p+38,0120777<<16);} else buffer.putShort(p+8,(short)(buffer.getShort(p+8)|1));break;}assertThrows(ApiError.class,()->SourceArchive.inspect(bytes));}}
  @Test void caseFoldDuplicatesInvalidUtf8AndBinaryMagicAreRejected() throws Exception {var duplicate=valid();duplicate.put("readme.md","a duplicate readme with enough content".getBytes());assertThrows(ApiError.class,()->SourceArchive.inspect(zip(duplicate)));var binary=valid();binary.put("malware.dat",new byte[]{127,'E','L','F',1,2,3});assertThrows(ApiError.class,()->SourceArchive.inspect(zip(binary)));var utf=valid();utf.put("source.ts",new byte[]{(byte)0xff,(byte)0xfe});assertThrows(ApiError.class,()->SourceArchive.inspect(zip(utf)));}
  @Test void mismatchedCrcLocalNamesAndTruncatedDirectoryFail() throws Exception {byte[] good=zip(valid());byte[] crc=good.clone();ByteBuffer b=ByteBuffer.wrap(crc).order(ByteOrder.LITTLE_ENDIAN);for(int p=0;p<crc.length-46;p++) if(b.getInt(p)==0x02014b50) {b.putInt(p+16,12345);break;}assertThrows(ApiError.class,()->SourceArchive.inspect(crc));byte[] name=good.clone();name[30]='X';assertThrows(ApiError.class,()->SourceArchive.inspect(name));assertThrows(ApiError.class,()->SourceArchive.inspect(Arrays.copyOf(good,good.length-1)));}
}
