package com.getlancer.commerce;

import com.getlancer.shared.ApiError;
import com.getlancer.shared.Pages;
import jakarta.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class CommerceRepository {
  private final JdbcTemplate db;
  public CommerceRepository(JdbcTemplate db) {this.db=db;}
  private static final String ELIGIBLE="u.account_status='ACTIVE' AND u.email_verified_at IS NOT NULL AND d.approval_status='APPROVED' AND EXISTS(SELECT 1 FROM user_roles r WHERE r.user_id=u.id AND r.role='DEVELOPER')";
  private static final String SELECT="SELECT t.id,t.slug,t.title,t.summary,t.description,p.category,p.technology,t.price_minor AS \"priceMinor\",t.currency,t.product_id AS \"productId\",p.slug AS \"productSlug\",t.seller_id AS \"sellerId\",d.display_name AS \"sellerName\",v.id AS \"versionId\",v.version,v.release_notes AS \"releaseNotes\",v.license_terms AS \"licenseTerms\",t.status,t.created_at AS \"createdAt\" FROM source_templates t JOIN products p ON p.id=t.product_id JOIN users u ON u.id=t.seller_id JOIN developer_profiles d ON d.user_id=u.id LEFT JOIN LATERAL(SELECT id,version,release_notes,license_terms FROM source_versions sv WHERE sv.template_id=t.id AND sv.status='APPROVED' ORDER BY sv.reviewed_at DESC,sv.created_at DESC LIMIT 1) v ON true ";
  private static final String PUBLIC="t.status='ACTIVE' AND v.id IS NOT NULL AND "+ELIGIBLE+" AND p.approval_status='APPROVED' AND p.lifecycle_status='ACTIVE' AND p.visibility='PUBLIC' AND EXISTS(SELECT 1 FROM repository_verifications rv WHERE rv.product_id=p.id AND rv.status='VERIFIED' AND rv.repository_url=p.repository_url)";
  private static final String PUBLIC_VERSIONS="SELECT id,version,release_notes AS \"releaseNotes\",license_terms AS \"licenseTerms\",status,created_at AS \"createdAt\" FROM source_versions WHERE template_id=? AND status='APPROVED' ORDER BY created_at DESC,id";
  private static final String PRIVATE_VERSIONS="SELECT id,version,release_notes AS \"releaseNotes\",license_terms AS \"licenseTerms\",status,created_at AS \"createdAt\",review_reason AS \"reviewReason\",sha256,size_bytes AS \"sizeBytes\",entry_count AS \"entryCount\",manifest_files AS \"manifestFiles\",submitted_at AS \"submittedAt\",reviewed_at AS \"reviewedAt\" FROM source_versions WHERE template_id=? ORDER BY created_at DESC,id";
  public Map<String,Object> catalog(HttpServletRequest r,String q,String category,String technology) {
    if(q.length()>100 || category.length()>100 || technology.length()>100) throw new ApiError(400,"VALIDATION_ERROR","Search values are too long.");
    return Pages.query(db,r,SELECT+"WHERE "+PUBLIC+" AND (?='' OR t.title ILIKE '%'||?||'%' OR t.summary ILIKE '%'||?||'%') AND (?='' OR p.category=?) AND (?='' OR p.technology ILIKE '%'||?||'%') ORDER BY t.created_at DESC,t.id",q,q,q,category,category,technology,technology);
  }
  public Map<String,Object> publicDetail(String slug) {
    var rows=db.queryForList(SELECT+"WHERE "+PUBLIC+" AND t.slug=?",slug);if(rows.isEmpty()) throw missing();var row=rows.get(0);row.put("versions",versions((UUID)row.get("id"),false));return row;
  }
  public Map<String,Object> ownerPage(UUID seller,HttpServletRequest r) {
    var result=Pages.query(db,r,SELECT+"WHERE t.seller_id=? ORDER BY t.created_at DESC,t.id",seller);
    for(var row:Pages.items(result)) privateDetail(row);return result;
  }
  public Map<String,Object> adminPage(HttpServletRequest r) {
    var result=Pages.query(db,r,SELECT+"ORDER BY t.created_at DESC,t.id");for(var row:Pages.items(result)) privateDetail(row);return result;
  }
  public Map<String,Object> ownerDetail(UUID id,UUID seller) {
    var rows=db.queryForList(SELECT+"WHERE t.id=? AND t.seller_id=?",id,seller);if(rows.isEmpty()) throw missing();return privateDetail(rows.get(0));
  }
  public Map<String,Object> detail(UUID id) {var rows=db.queryForList(SELECT+"WHERE t.id=?",id);if(rows.isEmpty()) throw missing();return privateDetail(rows.get(0));}
  private Map<String,Object> privateDetail(Map<String,Object> row) {
    var versions=versions((UUID)row.get("id"),true);row.put("versions",versions);
    if(row.get("versionId")==null && !versions.isEmpty()) {var v=versions.get(0);row.put("versionId",v.get("id"));row.put("version",v.get("version"));row.put("releaseNotes",v.get("releaseNotes"));row.put("licenseTerms",v.get("licenseTerms"));}
    if(row.get("licenseTerms")==null) row.put("licenseTerms",template((UUID)row.get("id"),false).get("license_terms"));return row;
  }
  public List<Map<String,Object>> versions(UUID id,boolean privateFields) {
    var rows=privateFields?db.queryForList(PRIVATE_VERSIONS,id):db.queryForList(PUBLIC_VERSIONS,id);
    if(privateFields) for(var row:rows) row.put("manifestFiles",List.of(Objects.toString(row.get("manifestFiles"),"").split("\\n")));return rows;
  }
  public Map<String,Object> template(UUID id,boolean lock) {var rows=db.queryForList("SELECT id,seller_id,product_id,slug,title,summary,description,price_minor,currency,license_terms,status,created_at,updated_at FROM source_templates WHERE id=?"+(lock?" FOR UPDATE":""),id);if(rows.isEmpty()) throw missing();return rows.get(0);}
  public Map<String,Object> version(UUID template,UUID version,boolean lock) {var rows=db.queryForList("SELECT id,template_id,version,release_notes,storage_key,sha256,size_bytes,entry_count,license_terms,manifest_files,rights_consented_at,status,review_reason,submitted_at,reviewed_at,reviewed_by,created_at FROM source_versions WHERE id=? AND template_id=?"+(lock?" FOR UPDATE":""),version,template);if(rows.isEmpty()) throw missing();return rows.get(0);}
  public void sellerEligible(UUID seller,UUID product,boolean ownershipRequired) {
    var rows=db.queryForList("SELECT p.id FROM products p JOIN users u ON u.id=p.owner_user_id JOIN developer_profiles d ON d.user_id=u.id JOIN user_roles r ON r.user_id=u.id AND r.role='DEVELOPER'"+(ownershipRequired?" JOIN repository_verifications rv ON rv.product_id=p.id AND rv.status='VERIFIED' AND rv.repository_url=p.repository_url":"")+" WHERE u.id=? AND p.id=? AND "+ELIGIBLE+" AND p.approval_status='APPROVED' AND p.lifecycle_status='ACTIVE' AND p.visibility='PUBLIC' FOR SHARE OF u,p,d,r"+(ownershipRequired?",rv":""),seller,product);
    if(rows.isEmpty()) throw new ApiError(409,"SELLER_NOT_ELIGIBLE","An approved public proof product and current verified repository ownership are required.");
  }
  public void create(UUID id,UUID seller,UUID product,String slug,String title,String summary,String description,long price,String terms) {db.update("INSERT INTO source_templates(id,seller_id,product_id,slug,title,summary,description,price_minor,license_terms) VALUES(?,?,?,?,?,?,?,?,?)",id,seller,product,slug,title,summary,description,price,terms);}
  public void addVersion(UUID id,UUID template,String version,String notes,String storage,SourceArchive.Inspection inspection,String terms) {db.update("INSERT INTO source_versions(id,template_id,version,release_notes,storage_key,sha256,size_bytes,entry_count,license_terms,manifest_files,rights_consented_at) VALUES(?,?,?,?,?,?,?,?,?,?,now())",id,template,version,notes,storage,inspection.sha256(),inspection.sizeBytes(),inspection.entryCount(),terms,String.join("\n",inspection.manifestFiles()));}
  public void submit(UUID version) {db.update("UPDATE source_versions SET status='PENDING',submitted_at=now(),review_reason=null WHERE id=?",version);}
  public void review(UUID version,String state,String reason,UUID actor) {db.update("UPDATE source_versions SET status=?,review_reason=?,reviewed_at=now(),reviewed_by=? WHERE id=?",state,reason,actor,version);}
  public void templateStatus(UUID id,String state) {db.update("UPDATE source_templates SET status=?,updated_at=now() WHERE id=?",state,id);}
  public void audit(UUID template,UUID purchase,UUID actor,String kind,String detail) {db.update("INSERT INTO commerce_audit(id,template_id,purchase_id,actor_id,kind,detail) VALUES(?,?,?,?,?,?)",UUID.randomUUID(),template,purchase,actor,kind,detail);}
  public void lock(String key) {db.queryForObject("SELECT pg_advisory_xact_lock(hashtextextended(?,0))",Object.class,"commerce:"+key);}
  public String payee(UUID seller,String mode) {var rows=db.queryForList("SELECT account_id FROM payment_accounts WHERE builder_user_id=? AND mode=? AND provider_status='created' AND activation_confirmed FOR SHARE",seller,mode);if(rows.isEmpty()) throw new ApiError(409,"PAYEE_NOT_CONFIGURED","The seller needs an operator-verified Razorpay linked account.");return Objects.toString(rows.get(0).get("account_id"));}
  public Map<String,Object> purchase(UUID id,boolean lock) {var rows=db.queryForList("SELECT id,template_id,version_id,buyer_id,seller_id,idempotency_key,title,version,license_terms,sha256,amount_minor,currency,account_id,mode,status,order_id,payment_id,refunded_minor,transfer_status,entitlement_revoked,attention_reason,license_consented_at,created_at,updated_at FROM template_purchases WHERE id=?"+(lock?" FOR UPDATE":""),id);if(rows.isEmpty()) throw missing();return rows.get(0);}
  public Map<String,Object> byKey(UUID buyer,UUID key) {var rows=db.queryForList("SELECT id,template_id,version_id,buyer_id,seller_id,idempotency_key,title,version,license_terms,sha256,amount_minor,currency,account_id,mode,status,order_id,payment_id,refunded_minor,transfer_status,entitlement_revoked,attention_reason,license_consented_at,created_at,updated_at FROM template_purchases WHERE buyer_id=? AND idempotency_key=?",buyer,key);return rows.isEmpty()?null:rows.get(0);}
  public Map<String,Object> current(UUID buyer,UUID version,String mode) {var rows=db.queryForList("SELECT id,template_id,version_id,buyer_id,seller_id,idempotency_key,title,version,license_terms,sha256,amount_minor,currency,account_id,mode,status,order_id,payment_id,refunded_minor,transfer_status,entitlement_revoked,attention_reason,license_consented_at,created_at,updated_at FROM template_purchases WHERE buyer_id=? AND version_id=? AND mode=? AND status<>'REJECTED'",buyer,version,mode);return rows.isEmpty()?null:rows.get(0);}
  public Map<String,Object> byOrder(String order) {var rows=db.queryForList("SELECT id,template_id,version_id,buyer_id,seller_id,idempotency_key,title,version,license_terms,sha256,amount_minor,currency,account_id,mode,status,order_id,payment_id,refunded_minor,transfer_status,entitlement_revoked,attention_reason,license_consented_at,created_at,updated_at FROM template_purchases WHERE order_id=?",order);return rows.isEmpty()?null:rows.get(0);}
  public void reserve(UUID id,UUID buyer,UUID key,Map<String,Object> template,Map<String,Object> version,String account,String mode) {db.update("INSERT INTO template_purchases(id,template_id,version_id,buyer_id,seller_id,idempotency_key,title,version,license_terms,sha256,amount_minor,currency,account_id,mode,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,'INR',?,?,'CREATING')",id,template.get("id"),version.get("id"),buyer,template.get("seller_id"),key,template.get("title"),version.get("version"),version.get("license_terms"),version.get("sha256"),template.get("price_minor"),account,mode);}
  public void failed(UUID id,boolean rejected) {db.update("UPDATE template_purchases SET status=?,attention_reason=?,updated_at=now() WHERE id=? AND status='CREATING'",rejected?"REJECTED":"UNKNOWN",rejected?"Provider rejected order creation.":"Uncertain order creation. Operator must bind the matching reserved receipt.",id);}
  public void bind(UUID id,String order,String transfer) {db.update("UPDATE template_purchases SET order_id=?,status='ORDER_CREATED',transfer_status=?,attention_reason=null,updated_at=now() WHERE id=?",order,transfer,id);}
  public void capture(UUID id,String payment,long refunded,String transfer) {db.update("UPDATE template_purchases SET payment_id=?,refunded_minor=?,status=CASE WHEN ?=amount_minor THEN 'REFUNDED' WHEN ?>0 THEN 'PARTIALLY_REFUNDED' ELSE 'CAPTURED' END,transfer_status=?,attention_reason=CASE WHEN ?='UNKNOWN' THEN 'Captured payment requires transfer verification.' ELSE null END,updated_at=now() WHERE id=?",payment,refunded,refunded,refunded,transfer,transfer,id);refreshDisputes(id);}
  public void ledger(UUID purchase,String key,String kind,long amount) {db.update("INSERT INTO commerce_ledger(id,purchase_id,entry_key,kind,amount_minor,currency) VALUES(?,?,?,?,?,'INR') ON CONFLICT(purchase_id,entry_key) DO NOTHING",UUID.randomUUID(),purchase,key,kind,amount);}
  public List<String> providerDisputes(UUID id) {return db.queryForList("SELECT id FROM commerce_provider_disputes WHERE purchase_id=? ORDER BY updated_at LIMIT 100",String.class,id);}
  public boolean providerHeld(UUID id) {return db.queryForObject("SELECT count(*) FROM commerce_provider_disputes WHERE purchase_id=? AND (status<>'won' OR deducted_minor>0)",Integer.class,id)>0;}
  public void providerDispute(UUID purchase,String id,String state,long deducted) {int changed=db.update("INSERT INTO commerce_provider_disputes(id,purchase_id,status,deducted_minor) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,deducted_minor=excluded.deducted_minor,updated_at=now() WHERE commerce_provider_disputes.purchase_id=excluded.purchase_id",id,purchase,state,deducted);if(changed!=1) throw new ApiError(409,"PROVIDER_MISMATCH","This provider dispute belongs to a different purchase.");refreshDisputes(purchase);}
  private void refreshDisputes(UUID id) {db.update("UPDATE template_purchases p SET status=CASE WHEN EXISTS(SELECT 1 FROM commerce_provider_disputes d WHERE d.purchase_id=p.id AND (d.status<>'won' OR d.deducted_minor>0)) OR EXISTS(SELECT 1 FROM commerce_disputes d WHERE d.purchase_id=p.id AND d.status='OPEN') THEN 'DISPUTED' ELSE CASE WHEN p.refunded_minor=p.amount_minor THEN 'REFUNDED' WHEN p.refunded_minor>0 THEN 'PARTIALLY_REFUNDED' WHEN p.payment_id IS NOT NULL THEN 'CAPTURED' ELSE p.status END END WHERE p.id=?",id);}
  public void dispute(UUID id,UUID buyer,String reason) {db.update("INSERT INTO commerce_disputes(id,purchase_id,buyer_id,reason) VALUES(?,?,?,?)",UUID.randomUUID(),id,buyer,reason);refreshDisputes(id);}
  public void resolve(UUID id,UUID actor,String resolution,String reason) {db.update("UPDATE commerce_disputes SET status=?,resolution_reason=?,resolved_by=?,resolved_at=now() WHERE purchase_id=?",resolution.equals("RESUME")?"RESUMED":"REVOKED",reason,actor,id);db.update("UPDATE template_purchases SET entitlement_revoked=?,updated_at=now() WHERE id=?",resolution.equals("REVOKE"),id);refreshDisputes(id);}
  public Map<String,Object> dispute(UUID id) {var rows=db.queryForList("SELECT status,reason,resolution_reason AS \"resolutionReason\",created_at AS \"createdAt\" FROM commerce_disputes WHERE purchase_id=?",id);return rows.isEmpty()?null:rows.get(0);}
  public void lockEntitlementParties(UUID id) {db.queryForList("SELECT x.id FROM template_purchases x JOIN users b ON b.id=x.buyer_id JOIN users u ON u.id=x.seller_id JOIN developer_profiles d ON d.user_id=u.id JOIN user_roles r ON r.user_id=u.id AND r.role='DEVELOPER' JOIN source_templates t ON t.id=x.template_id JOIN products p ON p.id=t.product_id JOIN repository_verifications rv ON rv.product_id=p.id WHERE x.id=? FOR SHARE OF b,u,d,p,r,rv",id);}
  public boolean entitled(UUID id,UUID buyer) {return db.queryForObject("SELECT count(*) FROM template_purchases x JOIN users b ON b.id=x.buyer_id JOIN source_versions sv ON sv.id=x.version_id JOIN source_templates t ON t.id=x.template_id JOIN users u ON u.id=x.seller_id JOIN developer_profiles d ON d.user_id=u.id JOIN products p ON p.id=t.product_id WHERE x.id=? AND x.buyer_id=? AND b.account_status='ACTIVE' AND x.mode='live' AND x.status='CAPTURED' AND x.refunded_minor=0 AND NOT x.entitlement_revoked AND x.transfer_status IN ('CREATED','PENDING','PROCESSED') AND sv.status='APPROVED' AND t.status<>'SUSPENDED' AND "+ELIGIBLE+" AND p.approval_status='APPROVED' AND p.lifecycle_status<>'SUSPENDED' AND p.visibility='PUBLIC' AND EXISTS(SELECT 1 FROM repository_verifications rv WHERE rv.product_id=p.id AND rv.status='VERIFIED' AND rv.repository_url=p.repository_url) AND NOT EXISTS(SELECT 1 FROM commerce_disputes cd WHERE cd.purchase_id=x.id AND cd.status IN ('OPEN','REVOKED')) AND NOT EXISTS(SELECT 1 FROM commerce_provider_disputes pd WHERE pd.purchase_id=x.id AND (pd.status<>'won' OR pd.deducted_minor>0))",Integer.class,id,buyer)>0;}
  public Map<String,Object> summaries(UUID buyer,HttpServletRequest r) {var page=Pages.query(db,r,"SELECT id FROM template_purchases WHERE buyer_id=? ORDER BY created_at DESC,id",buyer);List<Map<String,Object>> rows=new ArrayList<>();for(var item:Pages.items(page)) rows.add(summary(purchase((UUID)item.get("id"),false)));page.put("items",rows);return page;}
  public Map<String,Object> attention(HttpServletRequest r) {var page=Pages.query(db,r,"SELECT id FROM template_purchases WHERE status IN ('UNKNOWN','CREATING','DISPUTED') OR attention_reason IS NOT NULL OR entitlement_revoked ORDER BY created_at,id");List<Map<String,Object>> rows=new ArrayList<>();for(var item:Pages.items(page)) {var p=purchase((UUID)item.get("id"),false);var row=summary(p);row.put("accountId",p.get("account_id"));row.put("buyerId",p.get("buyer_id"));row.put("sellerId",p.get("seller_id"));rows.add(row);}page.put("items",rows);return page;}
  public Map<String,Object> summary(Map<String,Object> p) {var out=new LinkedHashMap<String,Object>();for(String key:List.of("id","title","version","currency","mode","status","sha256")) out.put(key,p.get(key));out.put("templateId",p.get("template_id"));out.put("versionId",p.get("version_id"));out.put("licenseTerms",p.get("license_terms"));out.put("amountMinor",p.get("amount_minor"));out.put("orderId",p.get("order_id"));out.put("paymentId",p.get("payment_id"));out.put("refundedMinor",p.get("refunded_minor"));out.put("transferStatus",p.get("transfer_status"));out.put("attentionReason",p.get("attention_reason"));out.put("createdAt",p.get("created_at"));out.put("downloadAvailable",entitled((UUID)p.get("id"),(UUID)p.get("buyer_id")));out.put("dispute",dispute((UUID)p.get("id")));return out;}
  public String eventHash(String event) {var rows=db.queryForList("SELECT payload_hash FROM commerce_webhook_events WHERE event_id=?",String.class,event);return rows.isEmpty()?null:rows.get(0);}
  public void event(String id,String hash,String kind) {db.update("INSERT INTO commerce_webhook_events(event_id,payload_hash,event_kind) VALUES(?,?,?)",id,hash,kind);}
  public static long number(Map<String,Object> row,String key) {return ((Number)row.get(key)).longValue();}
  private static ApiError missing() {return new ApiError(404,"NOT_FOUND","Template or purchase not found.");}
}
