/** Real local HTTP jobs, independent numeric oracle, hostile denials and clean source reproduction. */
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFile,mkdir,writeFile,mkdtemp,rm,access} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';
import {createServer} from 'node:net';
import {request} from 'node:http';
import {tmpdir} from 'node:os';
import {dirname,join,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {base,root,sha,parseStrictJson,sourceFiles,archiveFor,unpackArchive} from './build-data-ai-material.mjs';
export {sha,parseStrictJson};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const SHA=/^[0-9a-f]{64}$/;
const round6=value=>Math.round(value*1e6)/1e6;
export function canonical(value){if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}';assert(typeof value!=='number'||Number.isFinite(value),'Non-finite output');return JSON.stringify(typeof value==='number'?round6(value):value);}
export const digest=value=>sha(canonical(value));
function exact(value,keys){assert(value&&typeof value==='object'&&!Array.isArray(value),'Expected bounded object');assert.deepEqual(Object.keys(value).sort(),keys.slice().sort(),'Unknown or missing evidence fields');}
function finite(value,low,high){assert(typeof value==='number'&&Number.isFinite(value)&&value>=low&&value<=high,'Value exceeds contextual bounds');}
function timestamp(value){assert(typeof value==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(value)&&Number.isFinite(Date.parse(value))&&Date.parse(value)<=Date.now()+2000,'Invalid/future timestamp');}
export function validateInput(input,item){
 exact(input,item.inputs.map(i=>i.name));
 for(const spec of item.inputs){const value=input[spec.name];assert(typeof value==='string'&&Buffer.byteLength(value)<=spec.maxLength,'Unsafe input type/length');if(spec.type==='ENUM')assert(spec.choices.includes(value),'Unknown enum input');else if(spec.type==='INTEGER')assert(/^(?:0|-?[1-9][0-9]{0,2})$/.test(value)&&Number(value)>=spec.min&&Number(value)<=spec.max,'Unsafe integer input');else assert(/^[\x20-\x7e]{1,160}$/.test(value)&&/[A-Za-z]/.test(value),'Unsafe text input');}return input;
}
export function validateResult(result,item,contract){
 exact(result,['tables','metrics','prediction','evaluation']);assert.equal(result.tables.length,contract.tables.length);assert(result.tables.length<=2);assert.equal(result.metrics.length,contract.metrics.length);assert(result.metrics.length<=20);
 for(const [i,table] of result.tables.entries()){
  exact(table,['id','title','columns','rows']);assert.equal(table.id,contract.tables[i].id);assert.equal(table.title,contract.tables[i].title);assert.deepEqual(table.columns,contract.tables[i].columns);assert(table.columns.length<=8&&Array.isArray(table.rows)&&table.rows.length>0&&table.rows.length<=32);
  for(const row of table.rows){exact(row,table.columns.map(c=>c.key));for(const column of table.columns){const value=row[column.key];if(column.type==='number')finite(value,0,2000000);else assert(typeof value==='string'&&/^[\x20-\x7e]{1,80}$/.test(value),'Unsafe table string');}}
 }
 for(const [i,metric] of result.metrics.entries()){exact(metric,['key','label','value','unit']);for(const key of ['key','label','unit'])assert.equal(metric[key],contract.metrics[i][key]);finite(metric.value,0,2000000);}
 const rows=result.tables[0].rows,values=result.metrics.map(m=>m.value);
 if(item.id==='revenue-summary'){
  assert.equal(result.prediction,null);assert.equal(result.evaluation,null);assert.deepEqual(rows.map(r=>r.month),['Jan','Feb','Mar']);assert(rows.every(r=>Number.isSafeInteger(r.revenue)&&Number.isSafeInteger(r.orders)&&r.orders>=1&&r.orders<=2));assert.equal(values[0],rows.reduce((s,r)=>s+r.revenue,0));assert.equal(values[1],rows.reduce((s,r)=>s+r.orders,0));assert.equal(values[2],Math.round(values[0]/values[1]));
 }else if(item.id==='sensor-quality'){
  assert.equal(result.prediction,null);assert.equal(result.evaluation,null);assert(rows.length<=2&&new Set(rows.map(r=>r.channel)).size===rows.length);assert(rows.every(r=>['temperature','vibration'].includes(r.channel)&&[r.accepted,r.rejected,r.total].every(Number.isSafeInteger)&&r.total===4&&r.accepted+r.rejected===r.total));assert.equal(values[0],rows.reduce((s,r)=>s+r.accepted,0));assert.equal(values[1],rows.reduce((s,r)=>s+r.rejected,0));assert.equal(values[2],round6(100*values[0]/(values[0]+values[1])));
 }else{
  exact(result.prediction,['label','probability']);assert.equal(rows.length,2);assert.deepEqual(rows.map(r=>r.class),contract.classes);rows.forEach(r=>finite(r.probability,0,1));assert(Math.abs(rows[0].probability+rows[1].probability-1)<0.000002);const best=rows[1].probability>rows[0].probability?rows[1]:rows[0];assert.equal(result.prediction.label,best.class);assert.equal(result.prediction.probability,best.probability);assert.equal(values[0],best.probability);
  const evaluation=result.evaluation;exact(evaluation,['split','protocol','samples','correct','accuracy','limitations']);assert.equal(evaluation.split,item.evaluationSplit);assert.equal(evaluation.protocol,item.evaluationProtocol);assert.equal(evaluation.limitations,item.limitations);assert.equal(evaluation.samples,8);assert(Number.isSafeInteger(evaluation.correct)&&evaluation.correct>=0&&evaluation.correct<=8);assert.equal(evaluation.accuracy,round6(evaluation.correct/evaluation.samples));assert.equal(values[1],evaluation.accuracy);
 }
 return result;
}
export function validateEnvelope(envelope,item,sourceSha256,contract){
 exact(envelope,['schemaVersion','mode','runId','scenarioId','sourceSha256','dataSha256','modelSha256','evaluationSha256','input','inputSha256','result','resultSha256','startedAt','elapsedMs']);assert.equal(envelope.schemaVersion,'getlancer-data-ai-result-v1');assert.equal(envelope.mode,'LOCAL');assert(UUID.test(envelope.runId));assert.equal(envelope.scenarioId,item.id);assert.equal(envelope.sourceSha256,sourceSha256);
 for(const key of ['dataSha256','modelSha256','evaluationSha256'])assert.equal(envelope[key],item[key],'Stale asset '+key);for(const key of ['sourceSha256','dataSha256','inputSha256','resultSha256'])assert(SHA.test(envelope[key]));for(const key of ['modelSha256','evaluationSha256'])assert(envelope[key]===null||SHA.test(envelope[key]));validateInput(envelope.input,item);assert.equal(envelope.inputSha256,digest(envelope.input),'Forged input hash');assert.equal(envelope.resultSha256,digest(envelope.result),'Forged result hash');timestamp(envelope.startedAt);assert(Number.isSafeInteger(envelope.elapsedMs)&&envelope.elapsedMs>=0&&envelope.elapsedMs<=1000,'Unsafe duration');validateResult(envelope.result,item,contract);assert(Buffer.byteLength(canonical(envelope))<=4096,'Envelope exceeds byte budget');return envelope;
}
export function validateRecording(recording,item,sourceSha256,contract){
 exact(recording,['schemaVersion','mode','scenarioId','sourceSha256','dataSha256','modelSha256','evaluationSha256','recordedAt','runs']);assert.equal(recording.schemaVersion,'getlancer-data-ai-recording-v1');assert.equal(recording.mode,'REPLAY');assert.equal(recording.scenarioId,item.id);assert.equal(recording.sourceSha256,sourceSha256);for(const key of ['dataSha256','modelSha256','evaluationSha256'])assert.equal(recording[key],item[key]);timestamp(recording.recordedAt);assert.equal(recording.runs.length,2);
 for(const [i,envelope] of recording.runs.entries()){validateEnvelope(envelope,item,sourceSha256,contract);assert.deepEqual(envelope.input,i?item.changedInputs:item.defaultInputs);if(i){assert.equal(envelope.runId,recording.runs[0].runId);assert(Date.parse(envelope.startedAt)>=Date.parse(recording.runs[0].startedAt),'Reversed run observations');}assert(Date.parse(recording.recordedAt)+2>=Date.parse(envelope.startedAt)+envelope.elapsedMs,'Recording predates execution');}
 assert.notEqual(recording.runs[0].inputSha256,recording.runs[1].inputSha256);assert.notEqual(recording.runs[0].resultSha256,recording.runs[1].resultSha256,'Changed input has no measured effect');assert(Buffer.byteLength(canonical(recording))<=16384);return recording;
}
export async function freePort(){const server=createServer();await new Promise((r,j)=>server.once('error',j).listen(0,'127.0.0.1',r));const port=server.address().port;await new Promise(r=>server.close(r));return port;}
export async function startRuntime(options={}){
 const port=options.port??await freePort(),runId=options.runId??randomUUID();let stderr='';
 const child=spawn(options.python??'python3',['-I',options.source??join(base,'runtime.py')],{cwd:root,env:{...process.env,LAB_RUN_ID:runId,LAB_PORT:String(port),...options.env},stdio:['ignore','pipe','pipe']});child.stdout.on('data',()=>{});child.stderr.on('data',chunk=>{stderr+=chunk;if(stderr.length>4096)child.kill();});
 await new Promise((ready,reject)=>{const timer=setTimeout(()=>{child.kill();reject(Error('Runtime readiness timed out'));},5000);child.once('error',error=>{clearTimeout(timer);reject(error);});child.once('exit',code=>{clearTimeout(timer);reject(Error('Runtime rejected startup: '+code+' '+stderr));});const onData=()=>{if(stderr.includes('"status": "READY"')){clearTimeout(timer);child.stderr.off('data',onData);ready();}};child.stderr.on('data',onData);});
 return {port,runId,child,get stderr(){return stderr;},async close(){if(child.exitCode===null&&!child.killed){child.kill('SIGTERM');await new Promise(resolve=>child.once('exit',resolve));}}};
}
export function send(runtime,fields,options={}){
 const body=Buffer.isBuffer(fields)?fields:Buffer.from(new URLSearchParams(Object.entries(fields).map(([key,value])=>[key,String(value)])).toString());
 return new Promise((done,reject)=>{const req=request({host:'127.0.0.1',port:runtime.port,path:options.path??'/request',method:options.method??'POST',headers:{Host:'127.0.0.1:'+runtime.port,'Content-Type':'application/x-www-form-urlencoded','Content-Length':body.length,...options.headers},timeout:2500},response=>{let bytes=Buffer.alloc(0);response.on('data',chunk=>{bytes=Buffer.concat([bytes,chunk]);if(bytes.length>4096){req.destroy();reject(Error('Unbounded output'));}});response.on('end',()=>{try{done({status:response.statusCode,headers:response.headers,bytes:bytes.length,value:parseStrictJson(bytes.toString('utf8'))});}catch(error){reject(error);}});});req.on('error',reject);req.on('timeout',()=>req.destroy(Error('Request deadline exceeded')));req.end(body);});
}
function prediction(model,input){
 const score=model.bias+(model.id==='sentiment-inference'?(input.text.toLowerCase().match(/[a-z]+/g)??[]).reduce((sum,token)=>sum+(model.weights[token]??0),0):Object.entries(model.weights).reduce((sum,[key,weight])=>sum+weight*Number(input[key]),0));const p=round6(1/(1+Math.exp(-Math.max(-30,Math.min(30,score))))),probabilities=[round6(1-p),p],index=p>0.5?1:0;return {prediction:{label:model.classes[index],probability:probabilities[index]},probabilities};
}
/** Independent JS oracle loads pinned actual bytes and recomputes the entire expected result. */
export async function expectedResult(item,contract,assets,input){
 const bytes=await readFile(join(base,assets.dataPath));assert.equal(sha(bytes),item.dataSha256);const data=parseStrictJson(bytes.toString('utf8'));let rows,values,predicted=null,evaluation=null;
 if(item.id==='revenue-summary'){
  const orders=data.filter(row=>input.region==='all'||row.region===input.region),adjusted=amount=>Math.round(amount*(100+Number(input.upliftPercent))/100),total=adjusted(orders.reduce((sum,row)=>sum+row.revenue,0));rows=['Jan','Feb','Mar'].map(month=>({month,revenue:adjusted(orders.filter(row=>row.month===month).reduce((sum,row)=>sum+row.revenue,0)),orders:orders.filter(row=>row.month===month).length}));values=[total,orders.length,Math.round(total/orders.length)];
 }else if(item.id==='sensor-quality'){
  const samples=data.filter(row=>input.channel==='all'||row.channel===input.channel),accepted=samples.filter(row=>Math.abs(row.deviation)<=Number(input.tolerance)),channels=input.channel==='all'?['temperature','vibration']:[input.channel];rows=channels.map(channel=>{const total=samples.filter(row=>row.channel===channel).length,pass=accepted.filter(row=>row.channel===channel).length;return {channel,accepted:pass,rejected:total-pass,total};});values=[accepted.length,samples.length-accepted.length,round6(100*accepted.length/samples.length)];
 }else{
  const modelBytes=await readFile(join(base,assets.modelPath)),evaluationBytes=await readFile(join(base,assets.evaluationPath));assert.equal(sha(modelBytes),item.modelSha256);assert.equal(sha(evaluationBytes),item.evaluationSha256);const model=parseStrictJson(modelBytes.toString('utf8')),samples=parseStrictJson(evaluationBytes.toString('utf8')),actual=prediction(model,input),correct=samples.filter(row=>prediction(model,row).prediction.label===row.label).length;predicted=actual.prediction;rows=model.classes.map((label,i)=>({class:label,probability:actual.probabilities[i]}));evaluation={split:item.evaluationSplit,protocol:item.evaluationProtocol,samples:samples.length,correct,accuracy:round6(correct/samples.length),limitations:item.limitations};values=[predicted.probability,evaluation.accuracy];
 }
 return {tables:[{...contract.tables[0],rows}],metrics:contract.metrics.map((metric,i)=>({...metric,value:values[i]})),prediction:predicted,evaluation};
}
export async function validateRecordedResults(recording,item,contract,assets){for(const run of recording.runs)assert.deepEqual(run.result,await expectedResult(item,contract,assets,run.input),'Recorded output differs from pinned source oracle');return recording;}
async function exists(path){try{await access(path);return true;}catch(error){if(error.code==='ENOENT')return false;throw error;}}
export async function verifyRuntime(options={}){
 const {catalogue,files}=await sourceFiles(),sourceSha256=sha(files.find(([name])=>name==='runtime.py')[1]),archive=archiveFor(files),runtime=await startRuntime(),recordings=[];let maxResponseBytes=0;
 try{
  for(const item of catalogue.items){const contract=catalogue.contracts[item.id],assets=catalogue.assets[item.id],runs=[];
   for(const input of [item.defaultInputs,item.changedInputs]){const fields={runId:runtime.runId,scenarioId:item.id,operationId:'execute',...input},reply=await send(runtime,fields);assert.equal(reply.status,200);validateEnvelope(reply.value,item,sourceSha256,contract);assert.deepEqual(reply.value.result,await expectedResult(item,contract,assets,input));const repeated=await send(runtime,fields);assert.equal(repeated.status,200);assert.equal(repeated.value.resultSha256,reply.value.resultSha256,'Identical inputs drifted');maxResponseBytes=Math.max(maxResponseBytes,reply.bytes);runs.push(reply.value);}
   const recording={schemaVersion:'getlancer-data-ai-recording-v1',mode:'REPLAY',scenarioId:item.id,sourceSha256,dataSha256:item.dataSha256,modelSha256:item.modelSha256,evaluationSha256:item.evaluationSha256,recordedAt:new Date().toISOString(),runs};validateRecording(recording,item,sourceSha256,contract);recordings.push({item,recording});
   const path=join(base,'recordings',item.id+'.json');if(options.requireRecordings||(options.validateStored!==false&&await exists(path))){const published=validateRecording(parseStrictJson(await readFile(path,'utf8')),item,sourceSha256,contract);await validateRecordedResults(published,item,contract,assets);published.runs.forEach((run,i)=>assert.equal(run.resultSha256,runs[i].resultSha256,'Published replay differs from measured source'));}
  }
  const sample={runId:runtime.runId,scenarioId:'revenue-summary',operationId:'execute',region:'all',upliftPercent:'0'};
  for(const [fields,extra,status] of [[{...sample,runId:randomUUID()},{},403],[{...sample,url:'https://example.invalid/model'},{},400],[Buffer.from('runId=%ff'),{},400],[Buffer.from(new URLSearchParams(sample)+'&region=north'),{},400],[sample,{path:'/request?url=x'},400],[sample,{path:'//request'},400],[sample,{headers:{Origin:''}},403],[sample,{headers:{'Content-Type':'application/json'}},415],[Buffer.alloc(8193,65),{},413]]){const reply=await send(runtime,fields,extra);assert.equal(reply.status,status);exact(reply.value,['error','message']);assert(!Object.keys(reply.headers).some(key=>key.startsWith('access-control-')));}
  const item=catalogue.items.find(i=>i.id==='sentiment-inference'),input={text:'terrible '.repeat(7)},tiny=await send(runtime,{runId:runtime.runId,scenarioId:item.id,operationId:'execute',...input});assert.equal(tiny.status,200);validateEnvelope(tiny.value,item,sourceSha256,catalogue.contracts[item.id]);assert.deepEqual(tiny.value.result,await expectedResult(item,catalogue.contracts[item.id],catalogue.assets[item.id],input));assert(!runtime.stderr.includes('excellent')&&!runtime.stderr.includes('terrible'),'Inputs leaked to logs');
 }finally{await runtime.close();}
 assert(archive.equals(archiveFor(files)),'Archive is not deterministic');const clean=await mkdtemp(join(tmpdir(),'getlancer-data-ai-reproduction-'));
 try{for(const [name,bytes] of unpackArchive(archive,files)){await mkdir(dirname(join(clean,name)),{recursive:true});await writeFile(join(clean,name),bytes);}const extracted=await startRuntime({source:join(clean,'runtime.py')});try{for(const {item,recording} of recordings){for(const [i,input] of [item.defaultInputs,item.changedInputs].entries()){const reply=await send(extracted,{runId:extracted.runId,scenarioId:item.id,operationId:'execute',...input});assert.equal(reply.status,200);validateEnvelope(reply.value,item,sourceSha256,catalogue.contracts[item.id]);assert.equal(reply.value.resultSha256,recording.runs[i].resultSha256,'Clean extraction changed result');}}}finally{await extracted.close();}}finally{await rm(clean,{recursive:true,force:true});}
 const source=join(base,'runtime.py'),measurement=spawnSync('python3',['-I','-c',`import importlib.util,json,time,uuid\ns=importlib.util.spec_from_file_location('r',${JSON.stringify(source)});m=importlib.util.module_from_spec(s);s.loader.exec_module(m);limited=m.apply_limits();r=m.Runtime(str(uuid.uuid4()));started=time.monotonic();maximum=0\nfor i in range(500):\n for ident,item in r.items.items():\n  value=r.execute({'runId':r.run_id,'scenarioId':ident,'operationId':'execute',**item['defaultInputs']});maximum=max(maximum,len(m.canonical(value)))\nelapsed=round((time.monotonic()-started)*1000,2)\ntry:\n import resource\n usage=resource.getrusage(resource.RUSAGE_SELF);rss=usage.ru_maxrss;cpu=round(usage.ru_utime+usage.ru_stime,4);memory=resource.getrlimit(resource.RLIMIT_AS)[0];seconds=resource.getrlimit(resource.RLIMIT_CPU)[0]\nexcept ImportError:\n rss=cpu=memory=seconds=None\nr.cleanup();print(json.dumps({'executions':2000,'elapsedMs':elapsed,'maxRssKiB':rss,'cpuSeconds':cpu,'maxEnvelopeBytes':maximum,'osLimits':limited,'memoryLimitBytes':memory,'cpuLimitSeconds':seconds,'cleanupEmpty':not any([r.items,r.assets,r.contracts,r.data,r.models,r.evaluations])}))`],{encoding:'utf8',timeout:15000,maxBuffer:4096});assert.equal(measurement.status,0,'Resource measurement rejected: '+measurement.stderr);const measurements=parseStrictJson(measurement.stdout);assert(measurements.cleanupEmpty&&measurements.maxEnvelopeBytes<=4096&&measurements.elapsedMs<10000);if(measurements.osLimits)assert(measurements.memoryLimitBytes<=256*1024*1024&&measurements.cpuLimitSeconds<=10&&measurements.maxRssKiB<256*1024);
 return {sourceSha256,archiveSha256:sha(archive),archiveBytes:archive.length,recordings,measurements:{scenarios:4,changedInputs:4,cleanExecutions:8,maxResponseBytes,...measurements}};
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 try{assert(process.argv.slice(2).every(value=>value==='--verify'),'Use no argument or --verify');const result=await verifyRuntime({requireRecordings:process.argv.includes('--verify')});console.log('DATA_AI_VERIFY_OK '+JSON.stringify({sourceSha256:result.sourceSha256,archiveSha256:result.archiveSha256,archiveBytes:result.archiveBytes,...result.measurements}));}catch(error){console.error('DATA_AI_VERIFY_REJECTED '+error.message);process.exitCode=1;}
}
