package com.getlancer;
import java.util.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;
import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.dao.DataIntegrityViolationException;
public final class Support{
 public static UUID id(){return UUID.randomUUID();}public static String text(Map<String,Object>b,String k,int min,int max){String v=Objects.toString(b.get(k),"").trim();if(v.length()<min||v.length()>max)throw new ApiError(400,"VALIDATION_ERROR","Check the "+k+" field.",Map.of(k,"Use between "+min+" and "+max+" characters."));return v;}
 public static String email(Map<String,Object>b,String k){String e=text(b,k,3,254).toLowerCase(Locale.ROOT);if(!e.matches("[^\\s@]+@[^\\s@]+\\.[^\\s@]+"))throw new ApiError(400,"VALIDATION_ERROR","Enter a valid email address.");return e;}
 public static UUID uuid(Object v){try{return UUID.fromString(v.toString());}catch(Exception e){throw new ApiError(400,"VALIDATION_ERROR","Invalid identifier.");}}
 public static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 public static String randomToken(){byte[] b=new byte[32];new SecureRandom().nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
 public static boolean totp(String secret,String code){if(secret==null||code==null||!code.matches("[0-9]{6}"))return false;try{String a="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";int bits=0,value=0;java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();for(char c:secret.toUpperCase().replace("=","").toCharArray()){int x=a.indexOf(c);if(x<0)return false;value=(value<<5)|x;bits+=5;if(bits>=8){out.write((value>>(bits-8))&255);bits-=8;}}long now=Instant.now().getEpochSecond()/30;for(long n=now-1;n<=now+1;n++){byte[] counter=java.nio.ByteBuffer.allocate(8).putLong(n).array();Mac mac=Mac.getInstance("HmacSHA1");mac.init(new SecretKeySpec(out.toByteArray(),"HmacSHA1"));byte[] h=mac.doFinal(counter);int p=h[h.length-1]&15;int number=((h[p]&127)<<24)|((h[p+1]&255)<<16)|((h[p+2]&255)<<8)|(h[p+3]&255);String expected=String.format("%06d",number%1000000);if(MessageDigest.isEqual(code.getBytes(StandardCharsets.UTF_8),expected.getBytes(StandardCharsets.UTF_8)))return true;}return false;}catch(Exception e){return false;}}
}
class ApiError extends RuntimeException{final int status;final String code;final Map<String,String> fieldErrors;ApiError(int status,String code,String message){this(status,code,message,Map.of());}ApiError(int status,String code,String message,Map<String,String> fields){super(message);this.status=status;this.code=code;this.fieldErrors=fields;}}
@RestControllerAdvice class Errors{
 @ExceptionHandler(ApiError.class) ResponseEntity<?> api(ApiError e){return ResponseEntity.status(e.status).body(Map.of("error",Map.of("code",e.code,"message",e.getMessage(),"requestId",Support.id().toString(),"fieldErrors",e.fieldErrors)));}
 @ExceptionHandler(IllegalArgumentException.class) ResponseEntity<?> invalid(IllegalArgumentException e){String code=Set.of("UNSAFE_EXTERNAL_URL","INVALID_STATE_TRANSITION").contains(e.getMessage())?e.getMessage():"VALIDATION_ERROR";return api(new ApiError(code.equals("INVALID_STATE_TRANSITION")?409:400,code,code.equals("UNSAFE_EXTERNAL_URL")?"Use an HTTPS URL on a public domain.":"This action or field is not valid."));}
 @ExceptionHandler(DataIntegrityViolationException.class) ResponseEntity<?> conflict(){return api(new ApiError(409,"CONFLICT","This record already exists or cannot be changed."));}
 @ExceptionHandler({org.springframework.web.multipart.support.MissingServletRequestPartException.class,org.springframework.http.converter.HttpMessageNotReadableException.class,org.springframework.web.bind.MissingRequestHeaderException.class,org.springframework.web.method.annotation.MethodArgumentTypeMismatchException.class}) ResponseEntity<?> malformed(Exception e){return api(new ApiError(400,"VALIDATION_ERROR","Check the request fields and try again."));}
 @ExceptionHandler(org.springframework.web.multipart.MaxUploadSizeExceededException.class) ResponseEntity<?> oversized(){return api(new ApiError(413,"PAYLOAD_TOO_LARGE","Choose an image smaller than 5 MB."));}
 @ExceptionHandler(Exception.class) ResponseEntity<?> unexpected(Exception e){String ref=Support.id().toString();org.slf4j.LoggerFactory.getLogger(Errors.class).error("request_failed ref={} type={}",ref,e.getClass().getSimpleName());return ResponseEntity.status(500).body(Map.of("error",Map.of("code","INTERNAL_ERROR","message","We could not complete this request.","requestId",ref)));}
}
