package com.getlancer.hosting;

import static org.junit.jupiter.api.Assertions.*;
import com.getlancer.shared.ApiError;
import java.time.Instant;
import java.util.UUID;
import org.junit.jupiter.api.*;

class DemoPublisherClientTest {
  HostingPublisherFixture fixture;DemoPublisherClient client;StaticArchive.Inspection archive;UUID id;Instant expiry;
  @BeforeEach void setup(){fixture=new HostingPublisherFixture();client=new DemoPublisherClient(configuration(true,fixture.url(),HostingPublisherFixture.TEMPLATE,HostingPublisherFixture.SECRET,HostingPublisherFixture.GATEWAY));archive=StaticArchive.inspect(HostingTestArchives.built());id=UUID.randomUUID();expiry=Instant.now().plusSeconds(86400).truncatedTo(java.time.temporal.ChronoUnit.MILLIS);}
  @AfterEach void close(){fixture.close();}
  private static HostingConfiguration configuration(boolean enabled,String url,String template,String secret,String gateway){return new HostingConfiguration(enabled,url,secret,template,gateway,7,1000,"http://localhost:3000");}
  @Test void actualHttpBytesAndExactMetadataRecoverAndDeleteIdempotently(){var result=client.publish(id,archive,expiry);assertEquals("READY",result.state());assertEquals(HostingPublisherFixture.TEMPLATE.replace("{id}",id.toString()),result.url());assertEquals(result,client.get(id,archive.archiveSha256(),archive.manifestSha256(),expiry));assertEquals(result,client.publish(id,archive,expiry));assertEquals("DELETED",client.delete(id,archive.archiveSha256(),archive.manifestSha256(),expiry).state());assertEquals("DELETED",client.delete(id,archive.archiveSha256(),archive.manifestSha256(),expiry).state());assertEquals("DELETED",client.get(id,archive.archiveSha256(),archive.manifestSha256(),expiry).state());assertThrows(ApiError.class,()->client.publish(id,archive,expiry));}
  @Test void unknownDeleteAcceptsOnlyExactOwnIdAndCreatesPermanentTombstone(){assertEquals("DELETED",client.delete(id,archive.archiveSha256(),archive.manifestSha256(),expiry).state());fixture.wrongId=true;assertEquals("PUBLISHER_MISMATCH",assertThrows(ApiError.class,()->client.delete(id,archive.archiveSha256(),archive.manifestSha256(),expiry)).code);}
  @Test void hashesUrlsAndIdsCannotBeBoundByUntrustedResponse(){client.publish(id,archive,expiry);fixture.mismatch=true;assertEquals("PUBLISHER_MISMATCH",assertThrows(ApiError.class,()->client.get(id,archive.archiveSha256(),archive.manifestSha256(),expiry)).code);fixture.mismatch=false;fixture.wrongUrl=true;assertThrows(ApiError.class,()->client.get(id,archive.archiveSha256(),archive.manifestSha256(),expiry));fixture.wrongUrl=false;fixture.wrongId=true;assertThrows(ApiError.class,()->client.get(id,archive.archiveSha256(),archive.manifestSha256(),expiry));}
  @Test void redirectsOversizedAndSlowBodiesFailClosedWithinFixedBound(){fixture.redirect=true;assertEquals("PUBLISHER_UNCONFIRMED",assertThrows(ApiError.class,()->client.publish(id,archive,expiry)).code);fixture.redirect=false;fixture.oversized=true;assertThrows(ApiError.class,()->client.publish(id,archive,expiry));fixture.oversized=false;fixture.blockPut=true;long start=System.nanoTime();assertThrows(ApiError.class,()->client.publish(id,archive,expiry));assertTrue((System.nanoTime()-start)/1_000_000<2500);fixture.release.countDown();}
  @Test void productionPublicOriginsCannotShareParentCookiesOrUseDevelopmentHttp(){
    assertFalse(new HostingConfiguration(true,"https://publisher.internal",HostingPublisherFixture.SECRET,"https://{id}.demo.getlancer.com",HostingPublisherFixture.GATEWAY,7,1000,"https://www.getlancer.com").configured);
    assertTrue(new HostingConfiguration(true,"https://publisher.internal",HostingPublisherFixture.SECRET,"https://{id}.demos.example.net",HostingPublisherFixture.GATEWAY,7,1000,"https://www.getlancer.com").configured);
    assertFalse(new HostingConfiguration(true,"https://publisher.internal",HostingPublisherFixture.SECRET,HostingPublisherFixture.TEMPLATE,HostingPublisherFixture.GATEWAY,7,1000,"https://www.getlancer.com").configured);
  }
  @Test void fixedConfigRejectsInvalidUrlsWeakOrSharedSecretsAndExcessExpiry(){assertFalse(configuration(true,"https://provider.example/path",HostingPublisherFixture.TEMPLATE,HostingPublisherFixture.SECRET,HostingPublisherFixture.GATEWAY).configured);assertFalse(configuration(true,fixture.url(),"https://{id}.localhost/evil",HostingPublisherFixture.SECRET,HostingPublisherFixture.GATEWAY).configured);assertFalse(configuration(true,fixture.url(),"http://{id}.example.com",HostingPublisherFixture.SECRET,HostingPublisherFixture.GATEWAY).configured);assertFalse(configuration(true,fixture.url(),HostingPublisherFixture.TEMPLATE,"short",HostingPublisherFixture.GATEWAY).configured);assertFalse(configuration(true,fixture.url(),HostingPublisherFixture.TEMPLATE,HostingPublisherFixture.SECRET,HostingPublisherFixture.SECRET).configured);assertFalse(new HostingConfiguration(true,fixture.url(),HostingPublisherFixture.SECRET,HostingPublisherFixture.TEMPLATE,HostingPublisherFixture.GATEWAY,31,1000,"http://localhost:3000").configured);assertFalse(configuration(false,fixture.url(),HostingPublisherFixture.TEMPLATE,HostingPublisherFixture.SECRET,HostingPublisherFixture.GATEWAY).gateway(HostingPublisherFixture.GATEWAY));}
}
