package com.getlancer.hosting;

import static org.junit.jupiter.api.Assertions.*;
import com.getlancer.shared.ApiError;
import java.nio.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.junit.jupiter.api.Test;

class StaticArchiveTest {
  private static byte[] text(String value){return value.getBytes(StandardCharsets.UTF_8);}
  private static void unsafe(byte[] bytes){assertEquals("UNSAFE_STATIC_ARCHIVE",assertThrows(ApiError.class,()->StaticArchive.inspect(bytes)).code);}
  @Test void actualBuiltFilesHaveExactDeterministicSortedByteManifest(){byte[] bytes=HostingTestArchives.built();var inspected=StaticArchive.inspect(bytes);assertEquals(5,inspected.files().size());assertEquals(StaticArchive.sha(bytes),inspected.archiveSha256());assertEquals(inspected.files().stream().map(StaticArchive.File::path).sorted().toList(),inspected.files().stream().map(StaticArchive.File::path).toList());var manifest=new StringBuilder();for(var f:inspected.files()){assertEquals(f.sha256(),StaticArchive.sha(f.content()));manifest.append(f.path()).append('\0').append(f.sha256()).append('\0').append(f.sizeBytes()).append('\n');}assertEquals(StaticArchive.sha(text(manifest.toString())),inspected.manifestSha256());assertFalse(inspected.manifest().get(0).containsKey("contentBase64"));byte[] copy=inspected.files().get(0).content();copy[0]=0;assertNotEquals(0,inspected.files().get(0).content()[0]);}
  @Test void rootIndexAndUsefulNoticesAreEnforcedWithoutBuildSources(){unsafe(HostingTestArchives.zip(Map.of("assets/index.html",text("<html>demo</html>"))));unsafe(HostingTestArchives.zip(Map.of("index.html",new byte[0])));unsafe(HostingTestArchives.zip(Map.of("index.html",text("<html>demo</html>"),"README.md",text("todo"))));unsafe(HostingTestArchives.zip(Map.of("index.html",text("demo"),"package.json",text("{}"))));assertEquals(1,StaticArchive.inspect(HostingTestArchives.zip(Map.of("index.html",text("<html>demo</html>")))).files().size());}
  @Test void traversalCaseCollisionHiddenPrivateSourcesAndNestedArchivesAreRejected(){for(String name:List.of("../index.html","/index.html",".env","a/../index.html","a//file.js","a/.git/info.txt","secret-key.json","src/main.ts","bundle.js.map","backend.java","nested.zip","app.exe","with space.js","private.js","tokens.css","assets/design-tokens.css","assets/passwords.txt","api_key.json")){unsafe(HostingTestArchives.zip(Map.of("index.html",text("valid"),name,text("bad"))));}unsafe(HostingTestArchives.zip(Map.of("index.html",text("valid"),"INDEX.HTML",text("bad"))));unsafe(HostingTestArchives.zip(Map.of("index.html",text("valid"),"Assets/a.js",text("one"),"assets/b.js",text("two"))));unsafe(HostingTestArchives.zip(Map.of("index.html",text("valid"),"x.js",text("file"),"x.js/other.js",text("invalid"))));unsafe(HostingTestArchives.zip(Map.of("index.html",text("valid"),"logo.png",new byte[]{'P','K',3,4,0,0})));unsafe(HostingTestArchives.zip(Map.of("index.html",text("valid"),"app.js",text("const API_KEY = 'abcdefghijklmnopqrstuvwx12345678';"))));unsafe(HostingTestArchives.zip(Map.of("index.html",text("-----BEGIN PRIVATE KEY-----"))));}
  @Test void publisherPathAndBoundedCredentialPoliciesAgreeBeforeUpload(){for(String name:List.of("tokens.css","private.js","assets/passwords.txt","assets/api-keys.json"))unsafe(HostingTestArchives.zip(Map.of("index.html",text("valid"),name,text("asset"))));for(String key:List.of("apiKey","API_KEY","accessToken","ACCESS_TOKEN","privateKey","PRIVATE_KEY"))unsafe(HostingTestArchives.zip(Map.of("index.html",text("valid"),"app.js",text("const "+key+" = 'abcdefghijklmnopqrstuvwx12345678';"))));assertEquals(3,StaticArchive.inspect(HostingTestArchives.zip(Map.of("index.html",text("valid"),"docs/LICENCE.md",text("MIT licensed assets; preserve third-party notices."),"docs/README.md",text("This is the built static frontend sample package.")))).files().size());}
  @Test void largeMinifiedAssetCannotCauseQuadraticCredentialInspection(){org.junit.jupiter.api.Assertions.assertTimeout(java.time.Duration.ofSeconds(4),()->{byte[] bytes=HostingTestArchives.zip(Map.of("index.html",text("valid"),"large.js",text("a".repeat(StaticArchive.MAX_COMPRESSED))));assertEquals(2,StaticArchive.inspect(bytes).files().size());});}
  @Test void fileCountExpansionAndCompressedBoundsAreIndependent(){var tooMany=new LinkedHashMap<String,byte[]>();tooMany.put("index.html",text("valid"));for(int i=0;i<256;i++)tooMany.put("a"+i+".js",text("a"));unsafe(HostingTestArchives.zip(tooMany));unsafe(HostingTestArchives.zip(Map.of("index.html",new byte[StaticArchive.MAX_COMPRESSED+1])));unsafe(HostingTestArchives.zip(Map.of("index.html",new byte[StaticArchive.MAX_COMPRESSED],"a.js",new byte[StaticArchive.MAX_COMPRESSED],"b.js",text("overflow"))));unsafe(new byte[StaticArchive.MAX_COMPRESSED+1]);}
  @Test void centralLocalIntegrityEncryptionZip64SymlinkAndCrcTamperingFail(){byte[] original=HostingTestArchives.built();for(String mutation:List.of("encrypted","zip64","symlink","local-name","crc","extra-tag")){byte[] bytes=original.clone();var b=ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN);int central=-1;for(int i=0;i<bytes.length-4;i++)if(b.getInt(i)==0x02014b50){central=i;break;}assertTrue(central>=0);int local=b.getInt(central+42);switch(mutation){case "encrypted"->b.putShort(central+8,(short)(b.getShort(central+8)|1));case "zip64"->b.putInt(central+24,-1);case "symlink"->b.putInt(central+38,0120777<<16);case "local-name"->bytes[local+30]='X';case "crc"->b.putInt(central+16,b.getInt(central+16)+1);case "extra-tag"->b.putShort(central+6,(short)45);}unsafe(bytes);}}
  @Test void storedBinaryMagicDoesNotBecomeAnAllowedImage(){for(byte[] signature:List.of(new byte[]{'M','Z',0,0},new byte[]{127,'E','L','F'}))unsafe(HostingTestArchives.zip(Map.of("index.html",text("valid"),"image.png",signature)));}
}
